import type { CodingLesson } from '../languages'

export const c: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to C',
    summary: 'Headers, the main function, and printf',
    explanation: [
      'C is a foundational systems language — fast, low-level, and the ancestor of many modern languages. Programs start by including headers like #include <stdio.h>.',
      'Execution starts at int main() { ... }. printf("...") prints text, and \\n starts a new line.',
      'Each statement ends with a semicolon ;, and main typically ends with return 0;.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  printf("Hello, world!\\n");\n  printf("%d\\n", 2 + 3 * 4);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  printf("Hello, world!\\n");\n  printf("%d\\n", 7 * 6);\n  return 0;\n}',
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Declaring typed variables and format specifiers',
    explanation: [
      'C is statically typed — you state the type when declaring: int age = 12; double price = 4.5; char grade = \'A\';.',
      'printf uses format specifiers to print values: %d for int, %f for double, %c for char, %s for strings (char arrays).',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  char name[] = "Aria";\n  int age = 12;\n  printf("%s is %d years old\\n", name, age);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  char city[] = "Pokhara";\n  int temperature = 24;\n  printf("%s is %d degrees\\n", city, temperature);\n  return 0;\n}',
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Branching with if / else if / else',
    explanation: [
      'if checks a condition in parentheses; else if checks another; else runs otherwise. Blocks are wrapped in { }.',
      'Comparison operators ==, !=, >, < produce 0 (false) or non-zero (true) values that conditionals use.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  int score = 82;\n  if (score >= 90) {\n    printf("Grade: A\\n");\n  } else if (score >= 75) {\n    printf("Grade: B\\n");\n  } else {\n    printf("Keep practising!\\n");\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int temperature = 30;\n  if (temperature > 25) {\n    printf("It is warm\\n");\n  } else {\n    printf("It is cool\\n");\n  }\n  return 0;\n}',
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating with for and while',
    explanation: [
      'A for loop has three parts: for (int i = 1; i <= 5; i++) { ... } — start, condition, and update.',
      'A while loop repeats while its condition stays true (non-zero).',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  for (int i = 1; i <= 5; i++) {\n    printf("Step %d\\n", i);\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  for (int i = 1; i <= 3; i++) {\n    printf("Count: %d\\n", i);\n  }\n  return 0;\n}',
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Reusable blocks of logic',
    explanation: [
      'A function is declared with a return type, name, and parameters: int square(int n) { return n * n; }.',
      'Functions must be declared (or defined) before they are used in main, or given a prototype above main.',
    ],
    example: '#include <stdio.h>\n\nint square(int n) {\n  return n * n;\n}\n\nint main() {\n  printf("%d\\n", square(6));\n  printf("%d\\n", square(9));\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint doubleIt(int n) {\n  return n * 2;\n}\n\nint main() {\n  printf("%d\\n", doubleIt(21));\n  return 0;\n}',
  },
  {
    slug: 'arrays',
    title: 'Arrays',
    summary: 'Storing ordered collections of values',
    explanation: [
      'An array holds a fixed-size collection of one type: int scores[] = {70, 85, 92, 60};.',
      'Access elements with scores[0], and find the length with sizeof(scores) / sizeof(scores[0]).',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  int scores[] = {70, 85, 92, 60};\n  int total = 0;\n  int len = sizeof(scores) / sizeof(scores[0]);\n  for (int i = 0; i < len; i++) {\n    total += scores[i];\n  }\n  printf("Total: %d\\n", total);\n  printf("Average: %d\\n", total / len);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int nums[] = {3, 6, 9};\n  for (int i = 0; i < 3; i++) {\n    printf("%d\\n", nums[i] * nums[i]);\n  }\n  return 0;\n}',
  },
  {
    slug: 'pointers',
    title: 'Pointers',
    summary: 'Storing addresses with & and dereferencing with *',
    explanation: [
      'A pointer holds the address of another variable: int x = 5; int *p = &x; — & takes an address, * declares a pointer or dereferences one.',
      '*p reads or writes the value at the address p points to, so *p = 10; changes x itself.',
      'Passing a pointer to a function lets that function modify the caller\'s variable directly — this is "passing by reference".',
    ],
    example: '#include <stdio.h>\n\nvoid increment(int *p) {\n  *p = *p + 1;\n}\n\nint main() {\n  int x = 5;\n  int *ptr = &x;\n  printf("Before: %d\\n", x);\n  printf("Address holds: %d\\n", *ptr);\n  increment(&x);\n  printf("After: %d\\n", x);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nvoid doubleValue(int *p) {\n  *p = *p * 2;\n}\n\nint main() {\n  int n = 21;\n  doubleValue(&n);\n  printf("%d\\n", n);\n  return 0;\n}',
  },
  {
    slug: 'strings',
    title: 'Strings in C',
    summary: 'Char arrays and the <string.h> helper functions',
    explanation: [
      'A C string is just a char array ending in a hidden \'\\0\' byte: char name[] = "Aria"; printf("%s\\n", name); prints it.',
      '#include <string.h> gives helpers like strlen (length), strcpy (copy), and strcmp (compare, returns 0 when equal).',
    ],
    example: '#include <stdio.h>\n#include <string.h>\n\nint main() {\n  char greeting[20] = "Hello";\n  char name[] = "Aria";\n  printf("Length: %d\\n", (int)strlen(name));\n  strcat(greeting, ", ");\n  strcat(greeting, name);\n  printf("%s\\n", greeting);\n  if (strcmp(name, "Aria") == 0) {\n    printf("Names match\\n");\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n#include <string.h>\n\nint main() {\n  char word[20];\n  strcpy(word, "code");\n  printf("%s has %d letters\\n", word, (int)strlen(word));\n  return 0;\n}',
  },
  {
    slug: 'structs',
    title: 'Structs',
    summary: 'Grouping related fields into a custom type',
    explanation: [
      'struct lets you bundle several fields into one type: struct Point { int x; int y; };.',
      'Create and initialize an instance with struct Point p = {3, 4}; and access fields with the dot operator: p.x.',
    ],
    example: '#include <stdio.h>\n\nstruct Point {\n  int x;\n  int y;\n};\n\nint main() {\n  struct Point a = {3, 4};\n  struct Point b = {0, 0};\n  printf("a = (%d, %d)\\n", a.x, a.y);\n  printf("b = (%d, %d)\\n", b.x, b.y);\n  a.x = a.x + 1;\n  printf("a.x is now %d\\n", a.x);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nstruct Book {\n  char title[20];\n  int pages;\n};\n\nint main() {\n  struct Book b = {"C Basics", 120};\n  printf("%s has %d pages\\n", b.title, b.pages);\n  return 0;\n}',
  },
  {
    slug: 'recursion',
    title: 'Recursion',
    summary: 'Functions that call themselves to solve smaller problems',
    explanation: [
      'A recursive function calls itself with a smaller input, eventually reaching a base case that stops the recursion.',
      'factorial(n) = n * factorial(n - 1), with the base case factorial(0) = 1 — without a base case the recursion never ends.',
    ],
    example: '#include <stdio.h>\n\nint factorial(int n) {\n  if (n <= 1) {\n    return 1;\n  }\n  return n * factorial(n - 1);\n}\n\nint main() {\n  for (int i = 1; i <= 5; i++) {\n    printf("%d! = %d\\n", i, factorial(i));\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint fibonacci(int n) {\n  if (n <= 1) {\n    return n;\n  }\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}\n\nint main() {\n  printf("%d\\n", fibonacci(7));\n  return 0;\n}',
  },
  {
    slug: '2d-arrays',
    title: '2D Arrays',
    summary: 'Grids of values addressed with two indices',
    explanation: [
      'A 2D array is declared with two sizes: int grid[2][3] = {{1, 2, 3}, {4, 5, 6}}; — rows then columns.',
      'Visit every cell with nested loops: the outer loop walks rows, the inner loop walks columns, and grid[r][c] accesses one cell.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  int grid[2][3] = {{1, 2, 3}, {4, 5, 6}};\n  int total = 0;\n  for (int r = 0; r < 2; r++) {\n    for (int c = 0; c < 3; c++) {\n      printf("%d ", grid[r][c]);\n      total += grid[r][c];\n    }\n    printf("\\n");\n  }\n  printf("Total: %d\\n", total);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int board[2][2] = {{1, 0}, {0, 1}};\n  for (int r = 0; r < 2; r++) {\n    for (int c = 0; c < 2; c++) {\n      printf("%d", board[r][c]);\n    }\n    printf("\\n");\n  }\n  return 0;\n}',
  },
  {
    slug: 'command-line-basics',
    title: 'Constants & Utility Programs',
    summary: 'Defining constants and combining concepts into a small program',
    explanation: [
      'Constants can be defined with #define MAX_SCORE 100 (a text substitution) or const int maxScore = 100; (a typed, immutable variable).',
      'Real programs combine arrays, loops, and functions — for example computing the minimum, maximum, and average of a list of values.',
    ],
    example: '#include <stdio.h>\n\n#define COUNT 5\n\nint main() {\n  int values[COUNT] = {12, 45, 7, 23, 39};\n  int min = values[0];\n  int max = values[0];\n  int total = 0;\n  for (int i = 0; i < COUNT; i++) {\n    if (values[i] < min) min = values[i];\n    if (values[i] > max) max = values[i];\n    total += values[i];\n  }\n  printf("Min: %d\\n", min);\n  printf("Max: %d\\n", max);\n  printf("Average: %d\\n", total / COUNT);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nconst int LIMIT = 3;\n\nint main() {\n  int nums[LIMIT] = {4, 8, 15};\n  int total = 0;\n  for (int i = 0; i < LIMIT; i++) {\n    total += nums[i];\n  }\n  printf("Sum: %d\\n", total);\n  return 0;\n}',
  },
  {
    slug: 'dynamic-memory',
    title: 'Dynamic Memory with malloc & free',
    summary: 'Allocating arrays at runtime and cleaning them up',
    explanation: [
      '#include <stdlib.h> gives you malloc, which reserves a block of memory while the program is running: int *nums = malloc(n * sizeof(int));. Unlike a regular array, the size n can be decided at runtime instead of being fixed when you write the code.',
      'malloc can fail and return NULL if memory runs out, so it is good practice to check the pointer before using it. Once you have a valid pointer, you read and write through it just like an array: nums[i] = i * i;.',
      'When you are done with the memory, call free(nums); to release it back to the system. Forgetting to free memory you allocated is called a memory leak — every malloc should be paired with exactly one free.',
    ],
    example: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n  int n = 5;\n  int *nums = malloc(n * sizeof(int));\n  if (nums == NULL) {\n    printf("Allocation failed\\n");\n    return 1;\n  }\n  for (int i = 0; i < n; i++) {\n    nums[i] = i * i;\n  }\n  for (int i = 0; i < n; i++) {\n    printf("%d\\n", nums[i]);\n  }\n  free(nums);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n  int count = 3;\n  int *values = malloc(count * sizeof(int));\n  if (values == NULL) {\n    return 1;\n  }\n  values[0] = 10;\n  values[1] = 20;\n  values[2] = 30;\n  int total = 0;\n  for (int i = 0; i < count; i++) {\n    total += values[i];\n  }\n  printf("Total: %d\\n", total);\n  free(values);\n  return 0;\n}',
  },
  {
    slug: 'enums-and-typedef',
    title: 'Enums & typedef',
    summary: 'Naming sets of constants and giving types shorter aliases',
    explanation: [
      'enum lets you name a set of related integer constants instead of using plain numbers: enum Level { BEGINNER, INTERMEDIATE, ADVANCED };. By default BEGINNER is 0, INTERMEDIATE is 1, and ADVANCED is 2, counting up automatically.',
      'Enums work great with switch statements, which jump to the matching case and run its code until a break; — without break, execution would "fall through" into the next case.',
      'typedef gives an existing type a new, shorter name. struct Point { int x; int y; }; normally requires writing struct Point every time, but typedef struct { int x; int y; } Point; lets you just write Point — this is exactly like the structs lesson, except you drop the struct keyword everywhere afterward.',
    ],
    example: '#include <stdio.h>\n\nenum Level { BEGINNER, INTERMEDIATE, ADVANCED };\n\ntypedef struct {\n  int x;\n  int y;\n} Point;\n\nint main() {\n  enum Level current = INTERMEDIATE;\n  switch (current) {\n    case BEGINNER:\n      printf("Just starting out\\n");\n      break;\n    case INTERMEDIATE:\n      printf("Making good progress\\n");\n      break;\n    case ADVANCED:\n      printf("Nearly an expert\\n");\n      break;\n  }\n  Point p = {3, 4};\n  printf("Point: (%d, %d)\\n", p.x, p.y);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nenum Color { RED, GREEN, BLUE };\n\ntypedef struct {\n  char name[10];\n  int age;\n} Person;\n\nint main() {\n  enum Color favorite = GREEN;\n  switch (favorite) {\n    case RED:\n      printf("Red\\n");\n      break;\n    case GREEN:\n      printf("Green\\n");\n      break;\n    case BLUE:\n      printf("Blue\\n");\n      break;\n  }\n  Person p = {"Sam", 11};\n  printf("%s is %d\\n", p.name, p.age);\n  return 0;\n}',
  },
  {
    slug: 'pointer-arithmetic',
    title: 'Pointer Arithmetic',
    summary: 'Walking an array by moving a pointer instead of an index',
    explanation: [
      'When you add 1 to a pointer, it moves forward by one element of its type, not one byte — so int *p = arr; p + 1; points to the next int, not the next byte.',
      'arr[i] is actually shorthand for *(arr + i) — the compiler treats array indexing and pointer arithmetic as the same operation underneath.',
      'You can walk an entire array using only a pointer and ++, without ever writing square brackets.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  int arr[] = {10, 20, 30, 40};\n  int *p = arr;\n  for (int i = 0; i < 4; i++) {\n    printf("arr[%d] = %d, *(arr + %d) = %d\\n", i, arr[i], i, *(arr + i));\n  }\n  for (int i = 0; i < 4; i++) {\n    printf("via pointer: %d\\n", *p);\n    p++;\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int nums[] = {5, 6, 7};\n  int *p = nums;\n  for (int i = 0; i < 3; i++) {\n    printf("%d\\n", *(p + i));\n  }\n  return 0;\n}',
  },
  {
    slug: 'function-pointers',
    title: 'Function Pointers',
    summary: 'Storing a function in a variable and calling it indirectly',
    explanation: [
      'A function pointer holds the address of a function: int (*op)(int, int) = add; lets you call op(2, 3) just like calling add(2, 3).',
      'This is useful when you want to choose which function to run at runtime, like picking an operation based on user input.',
    ],
    example: '#include <stdio.h>\n\nint add(int a, int b) {\n  return a + b;\n}\n\nint multiply(int a, int b) {\n  return a * b;\n}\n\nint main() {\n  int (*op)(int, int) = add;\n  printf("add: %d\\n", op(3, 4));\n  op = multiply;\n  printf("multiply: %d\\n", op(3, 4));\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint square(int n) {\n  return n * n;\n}\n\nint cube(int n) {\n  return n * n * n;\n}\n\nint main() {\n  int (*fn)(int) = square;\n  printf("%d\\n", fn(4));\n  fn = cube;\n  printf("%d\\n", fn(4));\n  return 0;\n}',
  },
  {
    slug: 'arrays-of-strings',
    title: 'Arrays of Strings',
    summary: 'Holding a list of strings using an array of char pointers',
    explanation: [
      'An array of strings can be declared as char *names[] = {"Aria", "Sam", "Lee"}; — each element is a pointer to a char array.',
      'Loop over it just like any other array, printing each string with %s.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  char *names[] = {"Aria", "Sam", "Lee"};\n  int count = 3;\n  for (int i = 0; i < count; i++) {\n    printf("Name %d: %s\\n", i, names[i]);\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  char *colors[] = {"red", "green", "blue"};\n  for (int i = 0; i < 3; i++) {\n    printf("%s\\n", colors[i]);\n  }\n  return 0;\n}',
  },
  {
    slug: 'unions',
    title: 'Unions',
    summary: 'A type where all members share the same memory',
    explanation: [
      'A union declares several members that all overlap in the same block of memory, so a union only ever holds one of them at a time — unlike a struct, where each field gets its own separate space.',
      'Writing to one member of a union can change what you read from another, because they share the same bytes — this saves memory when you only need one value at a time.',
    ],
    example: '#include <stdio.h>\n\nunion Value {\n  int asInt;\n  float asFloat;\n};\n\nstruct Pair {\n  int a;\n  int b;\n};\n\nint main() {\n  union Value v;\n  v.asInt = 65;\n  printf("As int: %d\\n", v.asInt);\n  v.asFloat = 3.14f;\n  printf("As float: %.2f\\n", v.asFloat);\n  printf("Size of union: %d\\n", (int)sizeof(union Value));\n\n  struct Pair p = {1, 2};\n  printf("Size of struct: %d\\n", (int)sizeof(struct Pair));\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nunion Data {\n  int i;\n  char c;\n};\n\nint main() {\n  union Data d;\n  d.i = 100;\n  printf("%d\\n", d.i);\n  d.c = \'A\';\n  printf("%c\\n", d.c);\n  return 0;\n}',
  },
  {
    slug: 'bitwise-operators',
    title: 'Bitwise Operators',
    summary: 'Manipulating individual bits with &, |, ^, ~, <<, >>',
    explanation: [
      '& (AND), | (OR), ^ (XOR), and ~ (NOT) work on the individual bits of a number, while << and >> shift bits left or right.',
      'A common use is flags: a single int can store many true/false switches as separate bits, set with | and checked with &.',
    ],
    example: '#include <stdio.h>\n\n#define FLAG_READ  1\n#define FLAG_WRITE 2\n#define FLAG_EXEC  4\n\nint main() {\n  int permissions = 0;\n  permissions = permissions | FLAG_READ;\n  permissions = permissions | FLAG_WRITE;\n  printf("Permissions: %d\\n", permissions);\n\n  if (permissions & FLAG_READ) {\n    printf("Can read\\n");\n  }\n  if (permissions & FLAG_EXEC) {\n    printf("Can execute\\n");\n  } else {\n    printf("Cannot execute\\n");\n  }\n\n  printf("1 << 3 = %d\\n", 1 << 3);\n  printf("8 >> 2 = %d\\n", 8 >> 2);\n  printf("5 ^ 3 = %d\\n", 5 ^ 3);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int a = 6;\n  int b = 3;\n  printf("a & b = %d\\n", a & b);\n  printf("a | b = %d\\n", a | b);\n  printf("a << 1 = %d\\n", a << 1);\n  return 0;\n}',
  },
  {
    slug: 'preprocessor-macros',
    title: 'Preprocessor Macros',
    summary: '#define constants, parameterized macros, and #ifdef',
    explanation: [
      '#define performs simple text substitution before the code is compiled: #define PI 3.14 replaces every PI with 3.14 in the source.',
      'Macros can also take parameters, like #define SQUARE(x) ((x) * (x)) — the extra parentheses keep the substitution safe.',
      '#ifdef NAME ... #endif includes code only if NAME has been #defined, which is handy for turning debug output on or off.',
    ],
    example: '#include <stdio.h>\n\n#define PI 3.14\n#define SQUARE(x) ((x) * (x))\n#define DEBUG\n\nint main() {\n  printf("PI = %.2f\\n", PI);\n  printf("SQUARE(5) = %d\\n", SQUARE(5));\n\n#ifdef DEBUG\n  printf("Debug mode is on\\n");\n#endif\n\n#ifndef RELEASE\n  printf("This is not a release build\\n");\n#endif\n\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\n#define MAX(a, b) ((a) > (b) ? (a) : (b))\n\nint main() {\n  printf("%d\\n", MAX(4, 9));\n  printf("%d\\n", MAX(20, 7));\n  return 0;\n}',
  },
  {
    slug: 'multi-file-concept',
    title: 'Header Files (Concept)',
    summary: 'How real C projects split code across .h and .c files',
    explanation: [
      'Real C projects usually split code into a header file (like math_utils.h) that declares function prototypes and a source file (like math_utils.c) that defines them — other .c files then #include the header to use those functions, and a compiler links all the .c files together into one program.',
      'This sandbox can only run a single file at a time, so we cannot truly split files here. Instead, this example simulates the same idea: a function prototype is declared near the top (standing in for the header), and the real definition appears later (standing in for the source file) — main can call it either way because the prototype already told the compiler what to expect.',
    ],
    example: '#include <stdio.h>\n\n/* In a real project, this prototype would live in "math_utils.h" */\nint add(int a, int b);\nint square(int n);\n\nint main() {\n  printf("add(2, 3) = %d\\n", add(2, 3));\n  printf("square(5) = %d\\n", square(5));\n  return 0;\n}\n\n/* In a real project, these definitions would live in "math_utils.c" */\nint add(int a, int b) {\n  return a + b;\n}\n\nint square(int n) {\n  return n * n;\n}',
    starterCode: '#include <stdio.h>\n\nint triple(int n);\n\nint main() {\n  printf("%d\\n", triple(7));\n  return 0;\n}\n\nint triple(int n) {\n  return n * 3;\n}',
  },
  {
    slug: 'static-variables-in-c',
    title: 'Static Variables in C',
    summary: 'A local variable that remembers its value between calls',
    explanation: [
      'Normally, a local variable is created fresh each time a function runs and forgotten when it returns. A static local variable is initialized only once and keeps its value across calls.',
      'This makes static variables handy for things like counting how many times a function has been called.',
    ],
    example: '#include <stdio.h>\n\nvoid countCalls() {\n  static int calls = 0;\n  calls++;\n  printf("This function has been called %d time(s)\\n", calls);\n}\n\nint main() {\n  countCalls();\n  countCalls();\n  countCalls();\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint nextId() {\n  static int id = 0;\n  id++;\n  return id;\n}\n\nint main() {\n  printf("%d\\n", nextId());\n  printf("%d\\n", nextId());\n  printf("%d\\n", nextId());\n  return 0;\n}',
  },
  {
    slug: 'const-and-pointers',
    title: 'const & Pointers',
    summary: 'const int *p vs int *const p — what each one locks down',
    explanation: [
      'const int *p means the value p points to cannot be changed through p, but p itself can be reassigned to point somewhere else.',
      'int *const p means p itself cannot be reassigned once set, but the value it points to can still be modified.',
      'Using const correctly documents intent and lets the compiler catch accidental modifications — a function that takes const int *p promises it will not change the data it points to.',
    ],
    example: '#include <stdio.h>\n\nvoid printValue(const int *p) {\n  printf("Value: %d\\n", *p);\n}\n\nint main() {\n  int a = 10;\n  int b = 20;\n\n  const int *ptrToConstValue = &a;\n  printf("Before: %d\\n", *ptrToConstValue);\n  ptrToConstValue = &b;\n  printf("After reassigning pointer: %d\\n", *ptrToConstValue);\n\n  int *const constPtr = &a;\n  *constPtr = 99;\n  printf("a is now: %d\\n", a);\n\n  printValue(&b);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nvoid show(const int *p) {\n  printf("%d\\n", *p);\n}\n\nint main() {\n  int x = 42;\n  show(&x);\n  int *const fixed = &x;\n  *fixed = 100;\n  printf("%d\\n", x);\n  return 0;\n}',
  },
  {
    slug: 'struct-pointers-and-arrow',
    title: 'Struct Pointers & ->',
    summary: 'Accessing struct fields through a pointer with the -> operator',
    explanation: [
      'When you have a pointer to a struct, you could write (*p).field, but the arrow operator p->field does the same thing more cleanly.',
      'Passing a pointer to a struct into a function lets that function modify the original struct\'s fields directly, instead of working on a copy.',
    ],
    example: '#include <stdio.h>\n\nstruct Point {\n  int x;\n  int y;\n};\n\nvoid movePoint(struct Point *p, int dx, int dy) {\n  p->x = p->x + dx;\n  p->y = p->y + dy;\n}\n\nint main() {\n  struct Point a = {1, 1};\n  printf("Before: (%d, %d)\\n", a.x, a.y);\n  movePoint(&a, 3, 4);\n  printf("After: (%d, %d)\\n", a.x, a.y);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nstruct Counter {\n  int value;\n};\n\nvoid increment(struct Counter *c) {\n  c->value = c->value + 1;\n}\n\nint main() {\n  struct Counter counter = {0};\n  increment(&counter);\n  increment(&counter);\n  printf("%d\\n", counter.value);\n  return 0;\n}',
  },
  {
    slug: 'linked-lists-basics',
    title: 'Linked Lists Basics',
    summary: 'Nodes connected by pointers instead of sitting in one array',
    explanation: [
      'A linked list is built from nodes, where each node holds a value and a pointer to the next node: struct Node { int value; struct Node *next; };.',
      'Unlike an array, a linked list does not need contiguous memory — you traverse it by following next pointers until you reach NULL, which marks the end.',
    ],
    example: '#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node {\n  int value;\n  struct Node *next;\n};\n\nint main() {\n  struct Node *third = malloc(sizeof(struct Node));\n  third->value = 30;\n  third->next = NULL;\n\n  struct Node *second = malloc(sizeof(struct Node));\n  second->value = 20;\n  second->next = third;\n\n  struct Node *first = malloc(sizeof(struct Node));\n  first->value = 10;\n  first->next = second;\n\n  struct Node *current = first;\n  while (current != NULL) {\n    printf("%d\\n", current->value);\n    current = current->next;\n  }\n\n  free(first);\n  free(second);\n  free(third);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node {\n  int value;\n  struct Node *next;\n};\n\nint main() {\n  struct Node *second = malloc(sizeof(struct Node));\n  second->value = 2;\n  second->next = NULL;\n\n  struct Node *first = malloc(sizeof(struct Node));\n  first->value = 1;\n  first->next = second;\n\n  struct Node *current = first;\n  while (current != NULL) {\n    printf("%d\\n", current->value);\n    current = current->next;\n  }\n\n  free(first);\n  free(second);\n  return 0;\n}',
  },
  {
    slug: 'bubble-sort',
    title: 'Bubble Sort',
    summary: 'Sorting an array by repeatedly swapping neighbors',
    explanation: [
      'Bubble sort repeatedly walks through the array, swapping any two neighboring elements that are out of order, until the whole array is sorted.',
      'Each full pass "bubbles" the largest remaining value to its correct position at the end, so after n passes the array is sorted.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  int arr[] = {5, 2, 9, 1, 5, 6};\n  int n = 6;\n\n  for (int i = 0; i < n - 1; i++) {\n    for (int j = 0; j < n - 1 - i; j++) {\n      if (arr[j] > arr[j + 1]) {\n        int temp = arr[j];\n        arr[j] = arr[j + 1];\n        arr[j + 1] = temp;\n      }\n    }\n  }\n\n  printf("Sorted: ");\n  for (int i = 0; i < n; i++) {\n    printf("%d ", arr[i]);\n  }\n  printf("\\n");\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  int arr[] = {4, 2, 7, 1};\n  int n = 4;\n  for (int i = 0; i < n - 1; i++) {\n    for (int j = 0; j < n - 1 - i; j++) {\n      if (arr[j] > arr[j + 1]) {\n        int temp = arr[j];\n        arr[j] = arr[j + 1];\n        arr[j + 1] = temp;\n      }\n    }\n  }\n  for (int i = 0; i < n; i++) {\n    printf("%d\\n", arr[i]);\n  }\n  return 0;\n}',
  },
  {
    slug: 'binary-search',
    title: 'Binary Search',
    summary: 'Finding a value quickly in a sorted array by halving the range',
    explanation: [
      'Binary search only works on a sorted array. It checks the middle element, and if the target is smaller it searches the left half, if larger it searches the right half — repeating until found.',
      'Because the search range halves every step, binary search is much faster than checking every element one by one, especially for large arrays.',
    ],
    example: '#include <stdio.h>\n\nint binarySearch(int arr[], int n, int target) {\n  int low = 0;\n  int high = n - 1;\n  while (low <= high) {\n    int mid = (low + high) / 2;\n    if (arr[mid] == target) {\n      return mid;\n    } else if (arr[mid] < target) {\n      low = mid + 1;\n    } else {\n      high = mid - 1;\n    }\n  }\n  return -1;\n}\n\nint main() {\n  int arr[] = {1, 3, 5, 7, 9, 11, 13};\n  int n = 7;\n  int target = 9;\n  int result = binarySearch(arr, n, target);\n  if (result != -1) {\n    printf("Found %d at index %d\\n", target, result);\n  } else {\n    printf("%d not found\\n", target);\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint binarySearch(int arr[], int n, int target) {\n  int low = 0;\n  int high = n - 1;\n  while (low <= high) {\n    int mid = (low + high) / 2;\n    if (arr[mid] == target) {\n      return mid;\n    } else if (arr[mid] < target) {\n      low = mid + 1;\n    } else {\n      high = mid - 1;\n    }\n  }\n  return -1;\n}\n\nint main() {\n  int nums[] = {2, 4, 6, 8, 10};\n  printf("%d\\n", binarySearch(nums, 5, 6));\n  return 0;\n}',
  },
  {
    slug: 'variadic-functions',
    title: 'Variadic Functions',
    summary: 'Writing functions that accept a varying number of arguments',
    explanation: [
      '#include <stdarg.h> lets you write functions like printf that accept a different number of arguments each time they are called.',
      'va_list holds the extra arguments, va_start begins reading them, va_arg reads one at a time (you must say what type to expect), and va_end finishes up.',
    ],
    example: '#include <stdio.h>\n#include <stdarg.h>\n\nint sum(int count, ...) {\n  va_list args;\n  va_start(args, count);\n  int total = 0;\n  for (int i = 0; i < count; i++) {\n    total += va_arg(args, int);\n  }\n  va_end(args);\n  return total;\n}\n\nint main() {\n  printf("%d\\n", sum(3, 10, 20, 30));\n  printf("%d\\n", sum(5, 1, 2, 3, 4, 5));\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n#include <stdarg.h>\n\nint maxOf(int count, ...) {\n  va_list args;\n  va_start(args, count);\n  int best = va_arg(args, int);\n  for (int i = 1; i < count; i++) {\n    int next = va_arg(args, int);\n    if (next > best) {\n      best = next;\n    }\n  }\n  va_end(args);\n  return best;\n}\n\nint main() {\n  printf("%d\\n", maxOf(4, 3, 9, 2, 7));\n  return 0;\n}',
  },
  {
    slug: 'file-io-in-c',
    title: 'File I/O in C',
    summary: 'Writing to a file with fprintf and reading it back with fscanf',
    explanation: [
      '#include <stdio.h> also gives you file functions: fopen("name.txt", "w") opens a file for writing, fprintf writes formatted text to it, and fclose closes it when done.',
      'To read a file back, open it again with "r" mode, then fscanf reads values out of it the same way scanf reads from the keyboard.',
      'Always check that fopen did not return NULL before using the file, and always fclose every file you open.',
    ],
    example: '#include <stdio.h>\n\nint main() {\n  FILE *out = fopen("scores.txt", "w");\n  if (out == NULL) {\n    printf("Could not open file for writing\\n");\n    return 1;\n  }\n  fprintf(out, "%d %d %d\\n", 10, 20, 30);\n  fclose(out);\n\n  FILE *in = fopen("scores.txt", "r");\n  if (in == NULL) {\n    printf("Could not open file for reading\\n");\n    return 1;\n  }\n  int a, b, c;\n  fscanf(in, "%d %d %d", &a, &b, &c);\n  fclose(in);\n\n  printf("Read back: %d %d %d\\n", a, b, c);\n  printf("Sum: %d\\n", a + b + c);\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main() {\n  FILE *out = fopen("note.txt", "w");\n  if (out == NULL) {\n    return 1;\n  }\n  fprintf(out, "%d\\n", 99);\n  fclose(out);\n\n  FILE *in = fopen("note.txt", "r");\n  if (in == NULL) {\n    return 1;\n  }\n  int value;\n  fscanf(in, "%d", &value);\n  fclose(in);\n\n  printf("Read: %d\\n", value);\n  return 0;\n}',
  },
  {
    slug: 'command-line-arguments',
    title: 'Command-Line Arguments',
    summary: 'Receiving arguments through argc and argv in main',
    explanation: [
      'main can be declared as int main(int argc, char *argv[]) to receive command-line arguments: argc is how many there are, and argv is an array of strings holding them, starting with the program name at argv[0].',
      'This sandbox always runs the program with no extra arguments, so argc will be 1 and argv[0] will be the only entry — but the pattern below is exactly how you would read real arguments in any C program.',
    ],
    example: '#include <stdio.h>\n\nint main(int argc, char *argv[]) {\n  printf("argc = %d\\n", argc);\n  for (int i = 0; i < argc; i++) {\n    printf("argv[%d] = %s\\n", i, argv[i]);\n  }\n  return 0;\n}',
    starterCode: '#include <stdio.h>\n\nint main(int argc, char *argv[]) {\n  printf("Number of arguments: %d\\n", argc);\n  printf("Program name: %s\\n", argv[0]);\n  return 0;\n}',
  },
]
