import type { CodingLesson } from '../languages'

export const cpp: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to C++',
    summary: 'Headers, the main function, and cout',
    explanation: [
      'C++ extends C with object-oriented features while staying close to the hardware. Programs include headers like #include <iostream> and use the std namespace.',
      'Execution starts at int main() { ... }. std::cout << ... << std::endl; prints output, with << chaining values together.',
      'Each statement ends with a semicolon ;, and main typically ends with return 0;.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nint main() {\n  cout << "Hello, world!" << endl;\n  cout << (2 + 3 * 4) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  cout << "Hello, world!" << endl;\n  cout << (7 * 6) << endl;\n  return 0;\n}',
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Declaring typed variables',
    explanation: [
      'C++ is statically typed — you state the type when declaring: int age = 12; double price = 4.5; string name = "Aria"; (requires #include <string>).',
      'Common types include int, double, bool, char, and string. Combine values in cout with <<.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n  string name = "Aria";\n  int age = 12;\n  cout << name << " is " << age << " years old" << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n  string city = "Pokhara";\n  int temperature = 24;\n  cout << city << " is " << temperature << " degrees" << endl;\n  return 0;\n}',
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Branching with if / else if / else',
    explanation: [
      'if checks a condition in parentheses; else if checks another; else runs otherwise. Blocks are wrapped in { }.',
      'Comparison operators ==, !=, >, < produce bool values (true or false) that conditionals use.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nint main() {\n  int score = 82;\n  if (score >= 90) {\n    cout << "Grade: A" << endl;\n  } else if (score >= 75) {\n    cout << "Grade: B" << endl;\n  } else {\n    cout << "Keep practising!" << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  int temperature = 30;\n  if (temperature > 25) {\n    cout << "It is warm" << endl;\n  } else {\n    cout << "It is cool" << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating with for and while',
    explanation: [
      'A for loop has three parts: for (int i = 1; i <= 5; i++) { ... } — start, condition, and update.',
      'A while loop repeats while its condition stays true.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nint main() {\n  for (int i = 1; i <= 5; i++) {\n    cout << "Step " << i << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  for (int i = 1; i <= 3; i++) {\n    cout << "Count: " << i << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Reusable blocks of logic',
    explanation: [
      'A function is declared with a return type, name, and parameters: int square(int n) { return n * n; }.',
      'Functions defined above main can be called directly from it.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nint square(int n) {\n  return n * n;\n}\n\nint main() {\n  cout << square(6) << endl;\n  cout << square(9) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint doubleIt(int n) {\n  return n * 2;\n}\n\nint main() {\n  cout << doubleIt(21) << endl;\n  return 0;\n}',
  },
  {
    slug: 'vectors',
    title: 'Arrays & Vectors',
    summary: 'Storing ordered collections of values',
    explanation: [
      'A fixed-size array holds one type: int nums[] = {1, 2, 3};. A vector (#include <vector>) is a resizable array: vector<int> scores = {70, 85, 92, 60};.',
      'Access elements with scores[0], get the size with scores.size(), and loop with a for or range-based for loop.',
    ],
    example: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  vector<int> scores = {70, 85, 92, 60};\n  int total = 0;\n  for (int s : scores) {\n    total += s;\n  }\n  cout << "Total: " << total << endl;\n  cout << "Average: " << (total / (int)scores.size()) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  vector<int> nums = {3, 6, 9};\n  for (int n : nums) {\n    cout << (n * n) << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'classes-and-objects',
    title: 'Classes & Objects',
    summary: 'Bundling data and behaviour with classes',
    explanation: [
      'A class groups data (fields) and behaviour (methods) into one type: private fields are hidden, while public methods form the interface.',
      'A constructor runs when an object is created — Dog d("Rex", 3); — and methods like d.bark() act on that object\'s own fields.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Dog {\n  private:\n    string name;\n    int age;\n  public:\n    Dog(string n, int a) {\n      name = n;\n      age = a;\n    }\n    void describe() {\n      cout << name << " is " << age << " years old" << endl;\n    }\n};\n\nint main() {\n  Dog rex("Rex", 3);\n  Dog luna("Luna", 5);\n  rex.describe();\n  luna.describe();\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Counter {\n  private:\n    int count;\n  public:\n    Counter() {\n      count = 0;\n    }\n    void increment() {\n      count = count + 1;\n    }\n    int value() {\n      return count;\n    }\n};\n\nint main() {\n  Counter c;\n  c.increment();\n  c.increment();\n  c.increment();\n  cout << c.value() << endl;\n  return 0;\n}',
  },
  {
    slug: 'inheritance',
    title: 'Inheritance',
    summary: 'Building new classes from existing ones',
    explanation: [
      'A derived class reuses a base class with `: public Base`, inheriting its fields and methods while adding or changing its own.',
      'Marking a base method `virtual` lets a derived class override it with its own version, and calling it through a base pointer or reference picks the derived behaviour.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Animal {\n  public:\n    string name;\n    Animal(string n) {\n      name = n;\n    }\n    virtual void speak() {\n      cout << name << " makes a sound" << endl;\n    }\n};\n\nclass Cat : public Animal {\n  public:\n    Cat(string n) : Animal(n) {}\n    void speak() override {\n      cout << name << " says Meow" << endl;\n    }\n};\n\nint main() {\n  Animal generic("Creature");\n  Cat whiskers("Whiskers");\n  generic.speak();\n  whiskers.speak();\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Shape {\n  public:\n    virtual void describe() {\n      cout << "A shape" << endl;\n    }\n};\n\nclass Square : public Shape {\n  public:\n    void describe() override {\n      cout << "A square has 4 equal sides" << endl;\n    }\n};\n\nint main() {\n  Square s;\n  s.describe();\n  return 0;\n}',
  },
  {
    slug: 'references-and-pointers',
    title: 'References & Pointers',
    summary: 'Aliasing variables and working with addresses',
    explanation: [
      'A reference is an alias for an existing variable: int &ref = x; — changes through ref change x directly, with no special syntax needed.',
      'A pointer stores an address: int *p = &x; and *p accesses the value there. Passing a reference parameter (void f(int &n)) lets a function modify the caller\'s variable, unlike passing by value which copies it.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nvoid addOneByValue(int n) {\n  n = n + 1;\n}\n\nvoid addOneByReference(int &n) {\n  n = n + 1;\n}\n\nint main() {\n  int x = 10;\n  addOneByValue(x);\n  cout << "After by-value: " << x << endl;\n  addOneByReference(x);\n  cout << "After by-reference: " << x << endl;\n  int *p = &x;\n  cout << "Pointer reads: " << *p << endl;\n  *p = 100;\n  cout << "After *p = 100: " << x << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nvoid doubleIt(int &n) {\n  n = n * 2;\n}\n\nint main() {\n  int value = 21;\n  doubleIt(value);\n  cout << value << endl;\n  return 0;\n}',
  },
  {
    slug: 'stl-maps-and-sets',
    title: 'Maps & Sets',
    summary: 'Key-value lookups and unique collections from the STL',
    explanation: [
      'A map<KeyType, ValueType> (#include <map>) stores key-value pairs and looks values up by key: ages["Aria"] = 12;.',
      'A set<Type> (#include <set>) stores unique values in sorted order — inserting a duplicate has no effect, and count() checks membership.',
    ],
    example: '#include <iostream>\n#include <map>\n#include <set>\n#include <string>\nusing namespace std;\n\nint main() {\n  map<string, int> ages;\n  ages["Aria"] = 12;\n  ages["Bodhi"] = 9;\n  ages["Aria"] = 13;\n  for (auto const &entry : ages) {\n    cout << entry.first << " is " << entry.second << endl;\n  }\n\n  set<int> uniqueNums;\n  uniqueNums.insert(4);\n  uniqueNums.insert(2);\n  uniqueNums.insert(4);\n  cout << "Set size: " << uniqueNums.size() << endl;\n  if (uniqueNums.count(2) > 0) {\n    cout << "2 is in the set" << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n  map<string, int> scores;\n  scores["Aria"] = 90;\n  scores["Bodhi"] = 75;\n  cout << "Aria scored " << scores["Aria"] << endl;\n  cout << "Bodhi scored " << scores["Bodhi"] << endl;\n  return 0;\n}',
  },
  {
    slug: 'strings',
    title: 'Strings in C++',
    summary: 'Working with std::string methods',
    explanation: [
      'std::string supports +, comparisons (==, <), and methods like length(), substr(start, len), and find(text) which returns the starting index or string::npos if not found.',
      'These methods make text processing far more convenient than raw C char arrays.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n  string first = "Hello";\n  string second = "world";\n  string greeting = first + ", " + second + "!";\n  cout << greeting << endl;\n  cout << "Length: " << greeting.length() << endl;\n  cout << "Substring: " << greeting.substr(7, 5) << endl;\n  size_t pos = greeting.find("world");\n  if (pos != string::npos) {\n    cout << "Found world at index " << pos << endl;\n  }\n  if (first == "Hello") {\n    cout << "first equals Hello" << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n  string word = "programming";\n  cout << "Length: " << word.length() << endl;\n  cout << "First 4: " << word.substr(0, 4) << endl;\n  return 0;\n}',
  },
  {
    slug: 'exceptions',
    title: 'Exceptions',
    summary: 'Handling errors with try, throw, and catch',
    explanation: [
      'A try block runs code that might fail; throw raises an exception, and a matching catch block handles it instead of crashing the program.',
      'std::exception is the standard base type for exceptions, and you can derive your own custom exception classes from it by overriding what().',
    ],
    example: '#include <iostream>\n#include <stdexcept>\n#include <string>\nusing namespace std;\n\nclass NegativeValueError : public exception {\n  public:\n    const char *what() const throw() {\n      return "value must not be negative";\n    }\n};\n\ndouble safeSqrt(double x) {\n  if (x < 0) {\n    throw NegativeValueError();\n  }\n  return x * x;\n}\n\nint main() {\n  try {\n    cout << safeSqrt(4) << endl;\n    cout << safeSqrt(-9) << endl;\n  } catch (const NegativeValueError &e) {\n    cout << "Caught error: " << e.what() << endl;\n  }\n\n  try {\n    throw runtime_error("something went wrong");\n  } catch (const exception &e) {\n    cout << "Caught: " << e.what() << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <stdexcept>\nusing namespace std;\n\nint divide(int a, int b) {\n  if (b == 0) {\n    throw runtime_error("division by zero");\n  }\n  return a / b;\n}\n\nint main() {\n  try {\n    cout << divide(10, 2) << endl;\n    cout << divide(5, 0) << endl;\n  } catch (const exception &e) {\n    cout << "Error: " << e.what() << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'templates',
    title: 'Function Templates',
    summary: 'Writing one function that works across types',
    explanation: [
      'A function template lets you write the logic once and have it work for multiple types: template <typename T> T maxOf(T a, T b) { ... } declares T as a placeholder type, filled in when the function is actually called.',
      'When you call maxOf(3, 7), the compiler sees two ints and generates an int version of the function behind the scenes. Call maxOf(2.5, 1.1) instead, and it generates a separate double version — same source code, different specialized machine code for each type used.',
      'This avoids writing maxOfInt, maxOfDouble, and so on by hand, while still keeping the type safety of a normal typed function.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nT maxOf(T a, T b) {\n  return (a > b) ? a : b;\n}\n\nint main() {\n  cout << maxOf(3, 7) << endl;\n  cout << maxOf(2.5, 1.1) << endl;\n  cout << maxOf(-4, -10) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nT minOf(T a, T b) {\n  return (a < b) ? a : b;\n}\n\nint main() {\n  cout << minOf(8, 3) << endl;\n  cout << minOf(1.5, 4.2) << endl;\n  return 0;\n}',
  },
  {
    slug: 'enums-and-switch',
    title: 'Enums & Switch Statements',
    summary: 'Naming a fixed set of options and branching on them',
    explanation: [
      'An enum gives a set of named integer constants a type of their own. enum class Direction { Up, Down, Left, Right }; defines exactly four possible values, written as Direction::Up, Direction::Down, and so on — far clearer than using plain numbers.',
      'A switch statement branches on one value across several case labels: switch (move) { case Direction::Up: ...; break; ... }. Each case runs its block until break, which stops it from falling through into the next case.',
      'For a handful of exact-match options like a direction or a menu choice, a switch reads more cleanly than a long chain of if / else if checks, even though either approach can solve the same problem.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nenum class Direction { Up, Down, Left, Right };\n\nint main() {\n  Direction move = Direction::Left;\n  switch (move) {\n    case Direction::Up:\n      cout << "Moving up" << endl;\n      break;\n    case Direction::Down:\n      cout << "Moving down" << endl;\n      break;\n    case Direction::Left:\n      cout << "Moving left" << endl;\n      break;\n    case Direction::Right:\n      cout << "Moving right" << endl;\n      break;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nenum class Day { Mon, Tue, Wed };\n\nint main() {\n  Day today = Day::Tue;\n  switch (today) {\n    case Day::Mon:\n      cout << "Start of the week" << endl;\n      break;\n    case Day::Tue:\n      cout << "Second day" << endl;\n      break;\n    case Day::Wed:\n      cout << "Midweek" << endl;\n      break;\n  }\n  return 0;\n}',
  },
  {
    slug: 'operator-overloading',
    title: 'Operator Overloading',
    summary: 'Making + and << work with your own types',
    explanation: [
      'C++ lets you redefine what an operator does for your own class. Writing Point operator+(const Point &other) lets you write a + b for two Point objects instead of a clumsy add() method.',
      'Overloading operator<< (taking an ostream& and your type) lets cout << myPoint print it directly, just like it does for built-in types.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Point {\n  public:\n    int x, y;\n    Point(int xVal, int yVal) {\n      x = xVal;\n      y = yVal;\n    }\n    Point operator+(const Point &other) {\n      return Point(x + other.x, y + other.y);\n    }\n};\n\nostream& operator<<(ostream &out, const Point &p) {\n  out << "(" << p.x << ", " << p.y << ")";\n  return out;\n}\n\nint main() {\n  Point a(1, 2);\n  Point b(3, 4);\n  Point c = a + b;\n  cout << "a = " << a << endl;\n  cout << "b = " << b << endl;\n  cout << "a + b = " << c << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Vector2D {\n  public:\n    double x, y;\n    Vector2D(double xVal, double yVal) {\n      x = xVal;\n      y = yVal;\n    }\n    Vector2D operator+(const Vector2D &other) {\n      return Vector2D(x + other.x, y + other.y);\n    }\n};\n\nostream& operator<<(ostream &out, const Vector2D &v) {\n  out << "(" << v.x << ", " << v.y << ")";\n  return out;\n}\n\nint main() {\n  Vector2D a(1.5, 2.0);\n  Vector2D b(0.5, 3.0);\n  cout << (a + b) << endl;\n  return 0;\n}',
  },
  {
    slug: 'constructors-and-destructors',
    title: 'Constructors & Destructors',
    summary: 'Object setup and teardown',
    explanation: [
      'A constructor runs automatically when an object is created. A class can offer several, like a default constructor with no arguments and a parameterized one that fills in fields right away.',
      'A destructor (~ClassName()) runs automatically when an object goes out of scope, useful for cleanup. A copy constructor (ClassName(const ClassName &other)) controls what happens when one object is used to initialize another.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Resource {\n  public:\n    string name;\n    Resource() {\n      name = "unnamed";\n      cout << "Default constructor for " << name << endl;\n    }\n    Resource(string n) {\n      name = n;\n      cout << "Created " << name << endl;\n    }\n    Resource(const Resource &other) {\n      name = other.name + " (copy)";\n      cout << "Copy constructor for " << name << endl;\n    }\n    ~Resource() {\n      cout << "Destroying " << name << endl;\n    }\n};\n\nint main() {\n  Resource a("Alpha");\n  Resource b = a;\n  Resource c;\n  cout << "End of main" << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Greeter {\n  public:\n    string name;\n    Greeter(string n) {\n      name = n;\n      cout << "Hello from " << name << endl;\n    }\n    ~Greeter() {\n      cout << "Goodbye from " << name << endl;\n    }\n};\n\nint main() {\n  Greeter g("Aria");\n  cout << "Inside main" << endl;\n  return 0;\n}',
  },
  {
    slug: 'virtual-functions-and-polymorphism',
    title: 'Virtual Functions & Polymorphism',
    summary: 'One pointer, many behaviours',
    explanation: [
      'When a base class method is marked virtual, calling it through a base class pointer or reference runs the derived class\'s version instead — this is called runtime polymorphism.',
      'This lets you write code that works with a base class type (like Animal*) while actually operating on different derived objects (Cat, Dog), each responding in its own way.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Animal {\n  public:\n    string name;\n    Animal(string n) {\n      name = n;\n    }\n    virtual void speak() {\n      cout << name << " makes a sound" << endl;\n    }\n};\n\nclass Dog : public Animal {\n  public:\n    Dog(string n) : Animal(n) {}\n    void speak() override {\n      cout << name << " says Woof" << endl;\n    }\n};\n\nclass Cat : public Animal {\n  public:\n    Cat(string n) : Animal(n) {}\n    void speak() override {\n      cout << name << " says Meow" << endl;\n    }\n};\n\nint main() {\n  Dog rex("Rex");\n  Cat whiskers("Whiskers");\n  Animal *animals[2] = { &rex, &whiskers };\n  for (int i = 0; i < 2; i++) {\n    animals[i]->speak();\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Shape {\n  public:\n    virtual void describe() {\n      cout << "Some shape" << endl;\n    }\n};\n\nclass Circle : public Shape {\n  public:\n    void describe() override {\n      cout << "A round circle" << endl;\n    }\n};\n\nint main() {\n  Circle c;\n  Shape &ref = c;\n  ref.describe();\n  return 0;\n}',
  },
  {
    slug: 'abstract-classes-and-pure-virtual',
    title: 'Abstract Classes & Pure Virtual Functions',
    summary: 'Defining a contract without an implementation',
    explanation: [
      'A pure virtual function, written virtual double area() = 0;, has no body in the base class — it just declares that every subclass must provide one.',
      'A class with at least one pure virtual function becomes abstract: you cannot create an object of that class directly, only of concrete subclasses that implement all its pure virtual functions.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Shape {\n  public:\n    virtual double area() = 0;\n    virtual ~Shape() {}\n};\n\nclass Rectangle : public Shape {\n  public:\n    double width, height;\n    Rectangle(double w, double h) {\n      width = w;\n      height = h;\n    }\n    double area() override {\n      return width * height;\n    }\n};\n\nclass Circle : public Shape {\n  public:\n    double radius;\n    Circle(double r) {\n      radius = r;\n    }\n    double area() override {\n      return 3.14159 * radius * radius;\n    }\n};\n\nint main() {\n  Rectangle rect(4, 5);\n  Circle circ(3);\n  Shape *shapes[2] = { &rect, &circ };\n  for (int i = 0; i < 2; i++) {\n    cout << "Area: " << shapes[i]->area() << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Animal {\n  public:\n    virtual void makeSound() = 0;\n};\n\nclass Cow : public Animal {\n  public:\n    void makeSound() override {\n      cout << "Moo" << endl;\n    }\n};\n\nint main() {\n  Cow c;\n  c.makeSound();\n  return 0;\n}',
  },
  {
    slug: 'function-overloading',
    title: 'Function Overloading',
    summary: 'Same name, different parameters',
    explanation: [
      'C++ allows several functions to share the same name as long as their parameter types or counts differ — the compiler picks the right one based on the arguments you pass.',
      'This is handy for things like add(int, int) and add(double, double), letting callers write add(...) without worrying about which version runs.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nint add(int a, int b) {\n  return a + b;\n}\n\ndouble add(double a, double b) {\n  return a + b;\n}\n\nint add(int a, int b, int c) {\n  return a + b + c;\n}\n\nint main() {\n  cout << add(2, 3) << endl;\n  cout << add(2.5, 1.5) << endl;\n  cout << add(1, 2, 3) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nvoid printValue(int n) {\n  cout << "int: " << n << endl;\n}\n\nvoid printValue(string s) {\n  cout << "string: " << s << endl;\n}\n\nint main() {\n  printValue(42);\n  printValue(string("hello"));\n  return 0;\n}',
  },
  {
    slug: 'lambda-expressions-cpp',
    title: 'Lambda Expressions',
    summary: 'Small, inline, anonymous functions',
    explanation: [
      'A lambda is a quick way to write a function inline without giving it a name: [](int a, int b) { return a + b; } captures the logic right where you need it.',
      'Lambdas are often used as arguments, like a custom comparator for std::sort, so related logic stays close to where it is used instead of needing a separate named function.',
    ],
    example: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n  auto add = [](int a, int b) {\n    return a + b;\n  };\n  cout << "3 + 4 = " << add(3, 4) << endl;\n\n  vector<int> nums = {5, 2, 8, 1, 9};\n  sort(nums.begin(), nums.end(), [](int a, int b) {\n    return a > b;\n  });\n  cout << "Sorted descending: ";\n  for (int n : nums) {\n    cout << n << " ";\n  }\n  cout << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n  auto square = [](int n) {\n    return n * n;\n  };\n  cout << square(6) << endl;\n\n  vector<int> nums = {4, 1, 3};\n  sort(nums.begin(), nums.end());\n  for (int n : nums) {\n    cout << n << " ";\n  }\n  cout << endl;\n  return 0;\n}',
  },
  {
    slug: 'stl-algorithms',
    title: 'STL Algorithms',
    summary: 'Ready-made operations from <algorithm>',
    explanation: [
      '#include <algorithm> brings in many ready-to-use functions that operate on ranges, like sort(begin, end) and find(begin, end, value).',
      'accumulate (from <numeric>) totals up a range, and count_if counts elements matching a condition you provide as a lambda — all without writing your own loops.',
    ],
    example: '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <numeric>\nusing namespace std;\n\nint main() {\n  vector<int> nums = {7, 2, 9, 4, 1, 5};\n  sort(nums.begin(), nums.end());\n  cout << "Sorted: ";\n  for (int n : nums) {\n    cout << n << " ";\n  }\n  cout << endl;\n\n  auto it = find(nums.begin(), nums.end(), 9);\n  if (it != nums.end()) {\n    cout << "Found 9" << endl;\n  }\n\n  int total = accumulate(nums.begin(), nums.end(), 0);\n  cout << "Sum: " << total << endl;\n\n  int evens = count_if(nums.begin(), nums.end(), [](int n) {\n    return n % 2 == 0;\n  });\n  cout << "Even count: " << evens << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n  vector<int> nums = {3, 1, 4, 1, 5};\n  sort(nums.begin(), nums.end());\n  for (int n : nums) {\n    cout << n << " ";\n  }\n  cout << endl;\n  return 0;\n}',
  },
  {
    slug: 'pairs-and-tuples',
    title: 'Pairs & Tuples',
    summary: 'Grouping a few related values quickly',
    explanation: [
      'std::pair<T1, T2> (#include <utility>) bundles two values together, accessed with .first and .second — handy for things like a name and a score without writing a struct.',
      'std::tuple<...> (#include <tuple>) generalizes this to any number of values, accessed with get<index>(myTuple).',
    ],
    example: '#include <iostream>\n#include <utility>\n#include <tuple>\n#include <string>\nusing namespace std;\n\nint main() {\n  pair<string, int> student("Aria", 92);\n  cout << student.first << " scored " << student.second << endl;\n\n  tuple<string, int, double> record("Bodhi", 9, 1.42);\n  cout << get<0>(record) << " is " << get<1>(record) << " years old and " << get<2>(record) << "m tall" << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <utility>\nusing namespace std;\n\nint main() {\n  pair<string, int> item("apples", 5);\n  cout << item.first << ": " << item.second << endl;\n  return 0;\n}',
  },
  {
    slug: 'smart-pointers',
    title: 'Smart Pointers',
    summary: 'Automatic memory management',
    explanation: [
      'Raw pointers from new must be matched with a manual delete, and forgetting it leaks memory. Smart pointers from #include <memory> clean up automatically when they go out of scope.',
      'std::unique_ptr<T> owns an object exclusively, while std::shared_ptr<T> allows multiple owners and frees the object once the last one disappears.',
    ],
    example: '#include <iostream>\n#include <memory>\n#include <string>\nusing namespace std;\n\nclass Greeter {\n  public:\n    string name;\n    Greeter(string n) {\n      name = n;\n      cout << "Created " << name << endl;\n    }\n    ~Greeter() {\n      cout << "Destroyed " << name << endl;\n    }\n};\n\nint main() {\n  unique_ptr<Greeter> u = make_unique<Greeter>("Unique");\n  cout << u->name << " is here" << endl;\n\n  shared_ptr<Greeter> s1 = make_shared<Greeter>("Shared");\n  {\n    shared_ptr<Greeter> s2 = s1;\n    cout << "Shared use count: " << s1.use_count() << endl;\n  }\n  cout << "After inner scope, use count: " << s1.use_count() << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n  unique_ptr<int> p = make_unique<int>(42);\n  cout << *p << endl;\n  return 0;\n}',
  },
  {
    slug: 'const-correctness',
    title: 'const Correctness',
    summary: 'Promising not to modify things',
    explanation: [
      'Marking a parameter const, like void printName(const string &name), promises the function will not modify it — the compiler enforces this and catches accidental changes.',
      'Marking a member function const, like void print() const, promises it will not modify the object\'s fields, which lets it be called on const objects too.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Book {\n  private:\n    string title;\n  public:\n    Book(string t) {\n      title = t;\n    }\n    void print() const {\n      cout << "Book: " << title << endl;\n    }\n};\n\nvoid printName(const string &name) {\n  cout << "Name: " << name << endl;\n}\n\nint main() {\n  const Book b("The Hobbit");\n  b.print();\n  string n = "Aria";\n  printName(n);\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nvoid shout(const string &text) {\n  cout << text << "!!!" << endl;\n}\n\nint main() {\n  string message = "hello";\n  shout(message);\n  return 0;\n}',
  },
  {
    slug: 'static-members',
    title: 'Static Members',
    summary: 'Data and functions shared by all instances',
    explanation: [
      'A static data member belongs to the class itself rather than to any one object, so all instances share the same single copy of it — useful for things like counting how many objects exist.',
      'A static member function can be called without any object at all, using ClassName::function(), and can only access other static members.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Counter {\n  public:\n    static int instanceCount;\n    Counter() {\n      instanceCount++;\n    }\n    static int getCount() {\n      return instanceCount;\n    }\n};\n\nint Counter::instanceCount = 0;\n\nint main() {\n  Counter a;\n  Counter b;\n  Counter c;\n  cout << "Instances created: " << Counter::getCount() << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass IdGenerator {\n  public:\n    static int nextId;\n    static int getNext() {\n      return nextId++;\n    }\n};\n\nint IdGenerator::nextId = 1;\n\nint main() {\n  cout << IdGenerator::getNext() << endl;\n  cout << IdGenerator::getNext() << endl;\n  return 0;\n}',
  },
  {
    slug: 'namespaces',
    title: 'Namespaces',
    summary: 'Avoiding name collisions',
    explanation: [
      'A namespace groups related names together so they do not clash with identically named things elsewhere: namespace Game { int score; void reset() { ... } }.',
      'You access members from outside with the :: operator, like Game::reset(), or bring a whole namespace into scope with using namespace Game; (which is exactly what using namespace std; does for the standard library).',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nnamespace Geometry {\n  double pi = 3.14159;\n  double circleArea(double radius) {\n    return pi * radius * radius;\n  }\n}\n\nnamespace Physics {\n  double pi = 3.0;\n}\n\nint main() {\n  cout << "Geometry pi: " << Geometry::pi << endl;\n  cout << "Physics pi: " << Physics::pi << endl;\n  cout << "Circle area: " << Geometry::circleArea(2.0) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nnamespace Shop {\n  double price = 9.99;\n}\n\nint main() {\n  cout << "Price: " << Shop::price << endl;\n  return 0;\n}',
  },
  {
    slug: 'multidimensional-vectors',
    title: 'Multidimensional Vectors',
    summary: 'A dynamic 2D grid with vector<vector<int>>',
    explanation: [
      'A vector<vector<int>> is a vector where each element is itself a vector, giving you a resizable 2D grid: vector<vector<int>> grid(3, vector<int>(4, 0)); makes 3 rows of 4 zeros each.',
      'Access a cell with grid[row][col], and loop over rows and columns with nested for loops, just like a regular 2D array but resizable.',
    ],
    example: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  vector<vector<int>> grid(3, vector<int>(4, 0));\n  for (int r = 0; r < 3; r++) {\n    for (int c = 0; c < 4; c++) {\n      grid[r][c] = r * 4 + c;\n    }\n  }\n  for (int r = 0; r < 3; r++) {\n    for (int c = 0; c < 4; c++) {\n      cout << grid[r][c] << " ";\n    }\n    cout << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  vector<vector<int>> grid = {{1, 2}, {3, 4}};\n  for (auto &row : grid) {\n    for (int val : row) {\n      cout << val << " ";\n    }\n    cout << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'structs-vs-classes',
    title: 'Structs vs Classes',
    summary: 'The one real difference between struct and class',
    explanation: [
      'In C++, struct and class can both have fields, methods, and constructors — the one technical difference is default visibility: struct members are public by default, while class members are private by default.',
      'By convention, programmers reach for struct for simple data bundles with little or no behaviour (like a Point with just x and y), and class for types with invariants, private state, and rich behaviour.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nstruct Point {\n  int x;\n  int y;\n};\n\nclass BankAccount {\n  private:\n    double balance;\n  public:\n    BankAccount(double initial) {\n      balance = initial;\n    }\n    void deposit(double amount) {\n      balance += amount;\n    }\n    double getBalance() const {\n      return balance;\n    }\n};\n\nint main() {\n  Point p;\n  p.x = 3;\n  p.y = 4;\n  cout << "Point: (" << p.x << ", " << p.y << ")" << endl;\n\n  BankAccount account(100.0);\n  account.deposit(50.0);\n  cout << "Balance: " << account.getBalance() << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nstruct Size {\n  int width;\n  int height;\n};\n\nint main() {\n  Size s;\n  s.width = 10;\n  s.height = 20;\n  cout << "Area: " << (s.width * s.height) << endl;\n  return 0;\n}',
  },
  {
    slug: 'range-based-for-and-auto',
    title: 'Range-Based For & auto',
    summary: 'Cleaner loops and inferred types',
    explanation: [
      'A range-based for loop, for (auto &x : container), visits every element in a container without needing an index variable or calling .size() yourself.',
      'The auto keyword tells the compiler to figure out a variable\'s type from its initializer, which is especially handy with long type names like map iterators, and using auto& avoids copying each element.',
    ],
    example: '#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nint main() {\n  vector<string> fruits = {"apple", "banana", "cherry"};\n  for (auto &fruit : fruits) {\n    fruit += "!";\n  }\n  for (const auto &fruit : fruits) {\n    cout << fruit << endl;\n  }\n\n  auto total = 0;\n  vector<int> nums = {1, 2, 3, 4};\n  for (auto n : nums) {\n    total += n;\n  }\n  cout << "Total: " << total << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  vector<int> nums = {10, 20, 30};\n  for (auto n : nums) {\n    cout << n << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'reading-input-with-cin',
    title: 'Reading Input with cin',
    summary: 'The cin pattern for reading user input',
    explanation: [
      'In a normal C++ program, cin >> variable; reads a value typed by the user from standard input, the same way cout << prints output — cin >> name >> age; can even read several values in a row.',
      'This playground has no real keyboard input to type into, so the example below simulates what cin would receive by assigning the values directly, then processes them exactly as if they had been typed at a prompt.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n  string name;\n  int age;\n\n  // In a real terminal you would write:\n  //   cin >> name >> age;\n  // Here we simulate the same input since this sandbox has no live stdin:\n  name = "Aria";\n  age = 12;\n\n  cout << "Hello, " << name << "! You are " << age << " years old." << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  int a;\n  int b;\n  // Simulated cin >> a >> b; since this playground has no real stdin\n  a = 7;\n  b = 5;\n  cout << "Sum: " << (a + b) << endl;\n  return 0;\n}',
  },
  {
    slug: 'move-semantics-and-rvalue-refs',
    title: 'Move Semantics & Rvalue References',
    summary: 'Transferring resources instead of copying them',
    explanation: [
      'An rvalue reference, written Type&&, binds to a temporary value. std::move(x) (#include <utility>) does not move anything by itself — it casts x to an rvalue reference, telling the compiler "you may steal this object\'s resources".',
      'A class can define a move constructor, ClassName(ClassName &&other), which takes ownership of another object\'s internal data (like a pointer) instead of copying it, then leaves the source in an empty, valid state.',
      'This avoids expensive deep copies when a temporary object is no longer needed, which is exactly what happens when returning large objects or inserting them into containers.',
    ],
    example: '#include <iostream>\n#include <utility>\n#include <string>\nusing namespace std;\n\nclass Buffer {\n  public:\n    string label;\n    Buffer(string l) {\n      label = l;\n      cout << "Constructed " << label << endl;\n    }\n    Buffer(Buffer &&other) {\n      label = other.label;\n      other.label = "empty";\n      cout << "Moved into " << label << endl;\n    }\n};\n\nint main() {\n  Buffer a("Original");\n  Buffer b(std::move(a));\n  cout << "a.label is now: " << a.label << endl;\n  cout << "b.label is now: " << b.label << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <utility>\n#include <string>\nusing namespace std;\n\nint main() {\n  string a = "hello";\n  string b = std::move(a);\n  cout << "b: " << b << endl;\n  return 0;\n}',
  },
  {
    slug: 'copy-constructor-and-assignment',
    title: 'Copy Constructor & Assignment',
    summary: 'Controlling how objects get duplicated',
    explanation: [
      'A copy constructor, ClassName(const ClassName &other), runs when a new object is initialized from an existing one, like ClassName b = a; or passing by value.',
      'A copy assignment operator, ClassName& operator=(const ClassName &other), runs instead when an already-existing object is assigned a new value, like b = a; after both are constructed.',
      'Writing both explicitly matters when a class manages a resource (like raw memory) so each copy gets its own independent data instead of accidentally sharing it.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Tag {\n  public:\n    string label;\n    Tag(string l) {\n      label = l;\n      cout << "Constructed " << label << endl;\n    }\n    Tag(const Tag &other) {\n      label = other.label + " (copy)";\n      cout << "Copy constructed " << label << endl;\n    }\n    Tag& operator=(const Tag &other) {\n      label = other.label + " (assigned)";\n      cout << "Copy assigned " << label << endl;\n      return *this;\n    }\n};\n\nint main() {\n  Tag a("Original");\n  Tag b = a;\n  Tag c("Placeholder");\n  c = a;\n  cout << "a: " << a.label << ", b: " << b.label << ", c: " << c.label << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Box {\n  public:\n    int value;\n    Box(int v) {\n      value = v;\n    }\n    Box(const Box &other) {\n      value = other.value;\n      cout << "Copied box with value " << value << endl;\n    }\n};\n\nint main() {\n  Box a(10);\n  Box b = a;\n  cout << b.value << endl;\n  return 0;\n}',
  },
  {
    slug: 'friend-functions',
    title: 'Friend Functions',
    summary: 'Granting outside access to private members',
    explanation: [
      'A class\'s private members are normally hidden from everything outside it, including ordinary standalone functions. Declaring friend void show(const Box &b); inside the class grants that one function access to its private fields.',
      'Friendship is not mutual and not inherited — declaring a function (or another class) as a friend gives it access, but the favor is not automatically returned, and subclasses do not inherit it.',
      'It is used sparingly, often for operators or closely related helper functions that need direct access without exposing a public getter for everything.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Box {\n  private:\n    int width;\n  public:\n    Box(int w) {\n      width = w;\n    }\n    friend void printWidth(const Box &b);\n};\n\nvoid printWidth(const Box &b) {\n  cout << "Width is " << b.width << endl;\n}\n\nint main() {\n  Box b(42);\n  printWidth(b);\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Account {\n  private:\n    double balance;\n  public:\n    Account(double b) {\n      balance = b;\n    }\n    friend void printBalance(const Account &a);\n};\n\nvoid printBalance(const Account &a) {\n  cout << "Balance: " << a.balance << endl;\n}\n\nint main() {\n  Account acc(99.5);\n  printBalance(acc);\n  return 0;\n}',
  },
  {
    slug: 'initializer-lists-cpp',
    title: 'Constructor Initializer Lists',
    summary: 'Initializing members directly, before the body runs',
    explanation: [
      'A member initializer list, written after the constructor\'s parameters as : field1(value1), field2(value2), initializes fields directly as the object is built, rather than assigning to them inside the constructor body.',
      'This is required for const members and references, which must be given a value at construction and can never be reassigned afterward, and it is generally more efficient for class-type members since it avoids a default-construct-then-assign step.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Point {\n  public:\n    const int x;\n    const int y;\n    Point(int xVal, int yVal) : x(xVal), y(yVal) {\n      cout << "Point built at (" << x << ", " << y << ")" << endl;\n    }\n};\n\nclass Person {\n  public:\n    string name;\n    int age;\n    Person(string n, int a) : name(n), age(a) {}\n};\n\nint main() {\n  Point p(3, 4);\n  Person person("Aria", 12);\n  cout << person.name << " is " << person.age << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Circle {\n  public:\n    const double radius;\n    Circle(double r) : radius(r) {}\n    double area() const {\n      return 3.14159 * radius * radius;\n    }\n};\n\nint main() {\n  Circle c(2.0);\n  cout << c.area() << endl;\n  return 0;\n}',
  },
  {
    slug: 'unordered-map-and-set',
    title: 'unordered_map & unordered_set',
    summary: 'Hash-based lookups for average O(1) access',
    explanation: [
      'unordered_map<KeyType, ValueType> (#include <unordered_map>) stores key-value pairs using a hash table, giving average constant-time lookup, insertion, and removal — unlike map, it does not keep keys in sorted order.',
      'unordered_set<Type> (#include <unordered_set>) works the same way for unique values: insert(), count(), and erase() all run in average constant time.',
      'Choose the unordered versions when you only care about fast lookups, and the ordered map/set when you need to iterate in sorted key order.',
    ],
    example: '#include <iostream>\n#include <unordered_map>\n#include <unordered_set>\n#include <string>\nusing namespace std;\n\nint main() {\n  unordered_map<string, int> inventory;\n  inventory["apples"] = 10;\n  inventory["bananas"] = 5;\n  cout << "Apples: " << inventory["apples"] << endl;\n\n  unordered_set<string> seen;\n  seen.insert("a");\n  seen.insert("b");\n  seen.insert("a");\n  cout << "Unique count: " << seen.size() << endl;\n  if (seen.count("b") > 0) {\n    cout << "b was seen" << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <unordered_map>\n#include <string>\nusing namespace std;\n\nint main() {\n  unordered_map<string, int> ages;\n  ages["Aria"] = 12;\n  ages["Bodhi"] = 9;\n  cout << ages["Aria"] << endl;\n  cout << ages["Bodhi"] << endl;\n  return 0;\n}',
  },
  {
    slug: 'stl-stack-and-queue',
    title: 'Stack & Queue',
    summary: 'Last-in-first-out and first-in-first-out containers',
    explanation: [
      'std::stack<T> (#include <stack>) is last-in-first-out: push() adds to the top, top() reads it, and pop() removes it — useful for things like undo history or matching brackets.',
      'std::queue<T> (#include <queue>) is first-in-first-out: push() adds to the back, front() reads the oldest element, and pop() removes it — useful for things like task scheduling.',
      'Both are container adapters built on top of other containers, offering a focused interface rather than full random access.',
    ],
    example: '#include <iostream>\n#include <stack>\n#include <queue>\nusing namespace std;\n\nint main() {\n  stack<int> s;\n  s.push(1);\n  s.push(2);\n  s.push(3);\n  cout << "Stack top: " << s.top() << endl;\n  s.pop();\n  cout << "After pop, top: " << s.top() << endl;\n\n  queue<int> q;\n  q.push(1);\n  q.push(2);\n  q.push(3);\n  cout << "Queue front: " << q.front() << endl;\n  q.pop();\n  cout << "After pop, front: " << q.front() << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <stack>\nusing namespace std;\n\nint main() {\n  stack<int> s;\n  s.push(10);\n  s.push(20);\n  cout << s.top() << endl;\n  s.pop();\n  cout << s.top() << endl;\n  return 0;\n}',
  },
  {
    slug: 'sorting-with-comparators-cpp',
    title: 'Sorting with Comparators',
    summary: 'Custom orderings with std::sort',
    explanation: [
      'std::sort(begin, end) sorts in ascending order by default, but passing a third argument — a comparator — lets you define any ordering you like.',
      'A comparator is a function or lambda that takes two elements and returns true if the first should come before the second: sort(v.begin(), v.end(), [](int a, int b) { return a > b; }) sorts descending.',
      'This is especially useful for sorting structs or pairs by a specific field, like sorting people by age instead of by name.',
    ],
    example: '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nstruct Person {\n  string name;\n  int age;\n};\n\nint main() {\n  vector<Person> people = {{"Aria", 12}, {"Bodhi", 9}, {"Caleb", 15}};\n  sort(people.begin(), people.end(), [](const Person &a, const Person &b) {\n    return a.age < b.age;\n  });\n  for (const auto &p : people) {\n    cout << p.name << ": " << p.age << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n  vector<int> nums = {5, 1, 4, 2, 3};\n  sort(nums.begin(), nums.end(), [](int a, int b) {\n    return a > b;\n  });\n  for (int n : nums) {\n    cout << n << " ";\n  }\n  cout << endl;\n  return 0;\n}',
  },
  {
    slug: 'string-stream',
    title: 'String Streams',
    summary: 'Parsing and building strings with stringstream',
    explanation: [
      'std::stringstream (#include <sstream>) lets you treat a string like an input/output stream, using << to build text and >> to parse values out of it, just like cout and cin.',
      'A common pattern is feeding a whole line into a stringstream, then using >> repeatedly to split it into individual typed values, such as breaking "12 7 9" into three separate ints.',
      'str() retrieves the stream\'s current contents as a regular string once you are done building it.',
    ],
    example: '#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;\n\nint main() {\n  stringstream out;\n  out << "Score: " << 42 << ", Level: " << 3;\n  cout << out.str() << endl;\n\n  stringstream in("12 7 9");\n  int a, b, c;\n  in >> a >> b >> c;\n  cout << "Sum: " << (a + b + c) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <sstream>\nusing namespace std;\n\nint main() {\n  stringstream ss("3 4");\n  int x, y;\n  ss >> x >> y;\n  cout << (x + y) << endl;\n  return 0;\n}',
  },
  {
    slug: 'exception-hierarchies-cpp',
    title: 'Exception Hierarchies',
    summary: 'Building your own family of exception types',
    explanation: [
      'Custom exceptions can form a hierarchy just like any other classes: a base AppError can derive from std::exception, and more specific errors like NotFoundError can derive from AppError.',
      'A catch (const AppError &e) block catches AppError and anything derived from it, thanks to polymorphism, so you can handle a whole family of related errors with one catch clause, or get more specific by catching the derived type first.',
      'Catch blocks are checked in order, so more specific exception types should be listed before more general ones.',
    ],
    example: '#include <iostream>\n#include <exception>\n#include <string>\nusing namespace std;\n\nclass AppError : public exception {\n  protected:\n    string message;\n  public:\n    AppError(string m) {\n      message = m;\n    }\n    const char *what() const throw() {\n      return message.c_str();\n    }\n};\n\nclass NotFoundError : public AppError {\n  public:\n    NotFoundError(string m) : AppError(m) {}\n};\n\nvoid lookup(bool found) {\n  if (!found) {\n    throw NotFoundError("item not found");\n  }\n}\n\nint main() {\n  try {\n    lookup(false);\n  } catch (const NotFoundError &e) {\n    cout << "Not found: " << e.what() << endl;\n  } catch (const AppError &e) {\n    cout << "App error: " << e.what() << endl;\n  }\n  return 0;\n}',
    starterCode: '#include <iostream>\n#include <exception>\n#include <string>\nusing namespace std;\n\nclass MyError : public exception {\n  public:\n    const char *what() const throw() {\n      return "custom error occurred";\n    }\n};\n\nint main() {\n  try {\n    throw MyError();\n  } catch (const exception &e) {\n    cout << "Caught: " << e.what() << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'multiple-inheritance-cpp',
    title: 'Multiple Inheritance',
    summary: 'Deriving a class from more than one base',
    explanation: [
      'C++ allows a class to inherit from more than one base class at once: class Duck : public Swimmer, public Flyer combines the fields and methods of both.',
      'If two bases each declare a method with the same name, calling it through the derived class is ambiguous unless you qualify it, like Swimmer::move() or Flyer::move(), to say which one you mean.',
      'Multiple inheritance is powerful but can get complicated quickly, so many designs prefer composition or interfaces (abstract classes with only pure virtual functions) where possible.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Swimmer {\n  public:\n    void swim() {\n      cout << "Swimming" << endl;\n    }\n};\n\nclass Flyer {\n  public:\n    void fly() {\n      cout << "Flying" << endl;\n    }\n};\n\nclass Duck : public Swimmer, public Flyer {\n  public:\n    void describe() {\n      cout << "A duck can do both:" << endl;\n      swim();\n      fly();\n    }\n};\n\nint main() {\n  Duck d;\n  d.describe();\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Walker {\n  public:\n    void walk() {\n      cout << "Walking" << endl;\n    }\n};\n\nclass Talker {\n  public:\n    void talk() {\n      cout << "Talking" << endl;\n    }\n};\n\nclass Robot : public Walker, public Talker {};\n\nint main() {\n  Robot r;\n  r.walk();\n  r.talk();\n  return 0;\n}',
  },
  {
    slug: 'virtual-destructors',
    title: 'Virtual Destructors',
    summary: 'Making sure cleanup runs correctly through base pointers',
    explanation: [
      'When you delete a derived object through a base class pointer, the base destructor runs unless it is marked virtual — without virtual, the derived class\'s destructor is skipped, potentially leaking its resources.',
      'Any class meant to be used polymorphically (with virtual functions and deleted through a base pointer) should declare virtual ~ClassName() {}, even if the body is empty, so the full chain of destructors runs in the right order.',
      'This is a common rule of thumb: if a class has any virtual function, it should almost always have a virtual destructor too.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nclass Base {\n  public:\n    virtual ~Base() {\n      cout << "Base destructor" << endl;\n    }\n};\n\nclass Derived : public Base {\n  public:\n    ~Derived() {\n      cout << "Derived destructor" << endl;\n    }\n};\n\nint main() {\n  Base *b = new Derived();\n  delete b;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nclass Animal {\n  public:\n    virtual ~Animal() {\n      cout << "Animal cleanup" << endl;\n    }\n};\n\nclass Dog : public Animal {\n  public:\n    ~Dog() {\n      cout << "Dog cleanup" << endl;\n    }\n};\n\nint main() {\n  Animal *a = new Dog();\n  delete a;\n  return 0;\n}',
  },
  {
    slug: 'templates-with-multiple-params',
    title: 'Templates with Multiple Parameters',
    summary: 'Generic code over more than one type at a time',
    explanation: [
      'A template can take several type parameters at once: template <typename K, typename V> declares two independent placeholder types, useful for things like a generic key-value pair.',
      'Class templates work the same way as function templates — template <typename A, typename B> class Pair { ... } lets you write Pair<string, int> or Pair<int, double> from one definition.',
      'The compiler generates a separate specialized version for each distinct combination of types actually used in the program.',
    ],
    example: '#include <iostream>\n#include <string>\nusing namespace std;\n\ntemplate <typename K, typename V>\nclass Entry {\n  public:\n    K key;\n    V value;\n    Entry(K k, V v) {\n      key = k;\n      value = v;\n    }\n    void print() {\n      cout << key << " -> " << value << endl;\n    }\n};\n\ntemplate <typename A, typename B>\nA pickFirst(A a, B b) {\n  cout << "Ignoring " << b << endl;\n  return a;\n}\n\nint main() {\n  Entry<string, int> e("age", 12);\n  e.print();\n  cout << pickFirst(5, "hello") << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\ntemplate <typename A, typename B>\nclass Pair2 {\n  public:\n    A first;\n    B second;\n    Pair2(A a, B b) {\n      first = a;\n      second = b;\n    }\n};\n\nint main() {\n  Pair2<string, int> p("score", 90);\n  cout << p.first << ": " << p.second << endl;\n  return 0;\n}',
  },
  {
    slug: 'auto-and-decltype',
    title: 'auto & decltype',
    summary: 'Letting the compiler work out types for you',
    explanation: [
      'auto infers a variable\'s type from its initializer at the point of declaration: auto x = 5; makes x an int, auto y = 3.14; makes y a double.',
      'decltype(expression) instead works out the type of an expression without evaluating it, which is useful for declaring a variable whose type should exactly match another expression\'s type, even before that expression has run.',
      'Both reduce repetition and avoid mistakes from writing out long or subtly wrong type names by hand, especially with templates and iterators.',
    ],
    example: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n  auto x = 5;\n  auto y = 3.14;\n  auto name = string("Aria");\n  cout << x << " " << y << " " << name << endl;\n\n  int a = 10;\n  decltype(a) b = 20;\n  cout << "b: " << b << endl;\n\n  vector<int> nums = {1, 2, 3};\n  for (auto it = nums.begin(); it != nums.end(); ++it) {\n    cout << *it << " ";\n  }\n  cout << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  auto a = 42;\n  auto b = 3.5;\n  decltype(a) c = 100;\n  cout << a << " " << b << " " << c << endl;\n  return 0;\n}',
  },
  {
    slug: 'nullptr-and-pointer-safety',
    title: 'nullptr & Pointer Safety',
    summary: 'Representing "points to nothing" safely',
    explanation: [
      'nullptr is a type-safe constant representing a pointer that points to nothing, replacing the older C-style NULL macro (which was really just an int 0 in disguise).',
      'A pointer should be checked against nullptr before being dereferenced — if (p != nullptr) { ... } — since dereferencing a null pointer is undefined behaviour and typically crashes a real program.',
      'Initializing every pointer to nullptr when declared, rather than leaving it uninitialized, avoids accidentally reading garbage memory through a pointer that was never set.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nvoid printValue(int *p) {\n  if (p != nullptr) {\n    cout << "Value: " << *p << endl;\n  } else {\n    cout << "Pointer is null" << endl;\n  }\n}\n\nint main() {\n  int x = 42;\n  int *a = &x;\n  int *b = nullptr;\n  printValue(a);\n  printValue(b);\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n  int *p = nullptr;\n  if (p == nullptr) {\n    cout << "p is null" << endl;\n  }\n  int x = 7;\n  p = &x;\n  if (p != nullptr) {\n    cout << "p now points to " << *p << endl;\n  }\n  return 0;\n}',
  },
  {
    slug: 'enum-class',
    title: 'enum class vs Plain enum',
    summary: 'Scoped enums that avoid silent conversions',
    explanation: [
      'A plain enum (enum Color { Red, Green, Blue };) puts its values directly into the surrounding scope and implicitly converts to int, which can let unrelated enums or raw numbers mix together by accident.',
      'enum class Color { Red, Green, Blue }; scopes its values under Color:: (Color::Red) and does not implicitly convert to int or to other enums, catching mistakes like comparing two unrelated enum types at compile time.',
      'Because of this extra safety, enum class is generally preferred over plain enum in modern C++ unless you specifically need implicit int conversion or unscoped names.',
    ],
    example: '#include <iostream>\nusing namespace std;\n\nenum class TrafficLight { Red, Yellow, Green };\n\nstring describe(TrafficLight light) {\n  switch (light) {\n    case TrafficLight::Red:\n      return "Stop";\n    case TrafficLight::Yellow:\n      return "Caution";\n    case TrafficLight::Green:\n      return "Go";\n  }\n  return "Unknown";\n}\n\nint main() {\n  TrafficLight current = TrafficLight::Yellow;\n  cout << describe(current) << endl;\n  cout << static_cast<int>(current) << endl;\n  return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nenum class Status { Active, Inactive };\n\nint main() {\n  Status s = Status::Active;\n  if (s == Status::Active) {\n    cout << "Status is active" << endl;\n  }\n  return 0;\n}',
  },
]
