import type { CodingLesson } from '../languages'

export const csharp: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to C#',
    summary: 'Classes, the Main method, and Console.WriteLine',
    explanation: [
      'C# is Microsoft\'s flagship language, used for everything from desktop apps to games (Unity) to web servers. Code lives inside classes.',
      'Execution starts at static void Main(string[] args). Console.WriteLine(...) prints a line of output.',
      'Each statement ends with a semicolon ;.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    Console.WriteLine("Hello, world!");\n    Console.WriteLine(2 + 3 * 4);\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    Console.WriteLine("Hello, world!");\n    Console.WriteLine(7 * 6);\n  }\n}',
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Declaring typed variables',
    explanation: [
      'C# is statically typed — you state the type when declaring: int age = 12; string name = "Aria"; double price = 4.5;.',
      'Common types include int, double, bool, char, and string. Use $"..." (string interpolation) to embed variables in text.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    string name = "Aria";\n    int age = 12;\n    Console.WriteLine($"{name} is {age} years old");\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    string city = "Pokhara";\n    int temperature = 24;\n    Console.WriteLine($"{city} is {temperature} degrees");\n  }\n}',
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Branching with if / else if / else',
    explanation: [
      'if checks a condition in parentheses; else if checks another; else runs otherwise. Blocks are wrapped in { }.',
      'Comparison operators ==, !=, >, < produce bool values that conditionals use.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int score = 82;\n    if (score >= 90) {\n      Console.WriteLine("Grade: A");\n    } else if (score >= 75) {\n      Console.WriteLine("Grade: B");\n    } else {\n      Console.WriteLine("Keep practising!");\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int temperature = 30;\n    if (temperature > 25) {\n      Console.WriteLine("It is warm");\n    } else {\n      Console.WriteLine("It is cool");\n    }\n  }\n}',
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating with for and while',
    explanation: [
      'A for loop has three parts: for (int i = 1; i <= 5; i++) { ... } — start, condition, and update.',
      'A while loop repeats while its condition stays true.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    for (int i = 1; i <= 5; i++) {\n      Console.WriteLine($"Step {i}");\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    for (int i = 1; i <= 3; i++) {\n      Console.WriteLine($"Count: {i}");\n    }\n  }\n}',
  },
  {
    slug: 'methods',
    title: 'Methods',
    summary: 'Reusable blocks of logic',
    explanation: [
      'A method is declared with a return type, name, and parameters: static int Square(int n) { return n * n; }.',
      'Static methods belong to the class itself and can be called directly from Main.',
    ],
    example: 'using System;\n\nclass Program {\n  static int Square(int n) {\n    return n * n;\n  }\n  static void Main(string[] args) {\n    Console.WriteLine(Square(6));\n    Console.WriteLine(Square(9));\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static int DoubleIt(int n) {\n    return n * 2;\n  }\n  static void Main(string[] args) {\n    Console.WriteLine(DoubleIt(21));\n  }\n}',
  },
  {
    slug: 'arrays',
    title: 'Arrays',
    summary: 'Storing ordered collections of values',
    explanation: [
      'An array holds a fixed-size collection of one type: int[] scores = {70, 85, 92, 60};.',
      'Access elements with scores[0], get the length with scores.Length, and loop with a for or foreach loop.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int[] scores = {70, 85, 92, 60};\n    int total = 0;\n    foreach (int s in scores) {\n      total += s;\n    }\n    Console.WriteLine($"Total: {total}");\n    Console.WriteLine($"Average: {total / scores.Length}");\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int[] nums = {3, 6, 9};\n    foreach (int n in nums) {\n      Console.WriteLine(n * n);\n    }\n  }\n}',
  },
  {
    slug: 'classes-and-objects',
    title: 'Classes & Objects',
    summary: 'Defining a class with fields and a constructor',
    explanation: [
      'A class is a blueprint with fields (data) and methods (behaviour). A constructor runs when you create a new instance with new.',
      'Use dot notation like dog.Bark() to call methods on an object and access its fields.',
    ],
    example: 'using System;\n\nclass Dog {\n  public string Name;\n  public int Age;\n\n  public Dog(string name, int age) {\n    Name = name;\n    Age = age;\n  }\n\n  public void Bark() {\n    Console.WriteLine($"{Name} says Woof!");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Dog rex = new Dog("Rex", 3);\n    Dog luna = new Dog("Luna", 5);\n    rex.Bark();\n    luna.Bark();\n    Console.WriteLine($"{rex.Name} is {rex.Age} years old");\n  }\n}',
    starterCode: 'using System;\n\nclass Book {\n  public string Title;\n\n  public Book(string title) {\n    Title = title;\n  }\n\n  public void Describe() {\n    Console.WriteLine($"Book: {Title}");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Book b = new Book("C# Basics");\n    b.Describe();\n  }\n}',
  },
  {
    slug: 'inheritance',
    title: 'Inheritance',
    summary: 'Sharing behaviour with base classes and override',
    explanation: [
      'A class can inherit from another with a colon, e.g. class Cat : Animal, reusing its fields and methods.',
      'Mark a parent method virtual and a child method override to customise behaviour, and use base(...) to call the parent constructor or methods.',
    ],
    example: 'using System;\n\nclass Animal {\n  public string Name;\n\n  public Animal(string name) {\n    Name = name;\n  }\n\n  public virtual void Speak() {\n    Console.WriteLine($"{Name} makes a sound");\n  }\n}\n\nclass Cat : Animal {\n  public Cat(string name) : base(name) { }\n\n  public override void Speak() {\n    Console.WriteLine($"{Name} says Meow");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Animal generic = new Animal("Creature");\n    Animal cat = new Cat("Whiskers");\n    generic.Speak();\n    cat.Speak();\n  }\n}',
    starterCode: 'using System;\n\nclass Vehicle {\n  public virtual void Drive() {\n    Console.WriteLine("The vehicle moves");\n  }\n}\n\nclass Car : Vehicle {\n  public override void Drive() {\n    Console.WriteLine("The car zooms down the road");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Vehicle v = new Car();\n    v.Drive();\n  }\n}',
  },
  {
    slug: 'interfaces',
    title: 'Interfaces',
    summary: 'Declaring contracts with interface and implementing them',
    explanation: [
      'An interface declares method signatures without bodies; a class agrees to the contract by listing it after a colon and providing implementations.',
      'Code written against the interface type can work with any implementing class, giving you polymorphism.',
    ],
    example: 'using System;\n\ninterface IShape {\n  double Area();\n}\n\nclass Circle : IShape {\n  public double Radius;\n\n  public Circle(double radius) {\n    Radius = radius;\n  }\n\n  public double Area() {\n    return Math.PI * Radius * Radius;\n  }\n}\n\nclass Square : IShape {\n  public double Side;\n\n  public Square(double side) {\n    Side = side;\n  }\n\n  public double Area() {\n    return Side * Side;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    IShape[] shapes = { new Circle(2), new Square(3) };\n    foreach (IShape s in shapes) {\n      Console.WriteLine($"Area: {s.Area()}");\n    }\n  }\n}',
    starterCode: 'using System;\n\ninterface IGreeter {\n  string Greet(string name);\n}\n\nclass Friendly : IGreeter {\n  public string Greet(string name) {\n    return $"Hello, {name}!";\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    IGreeter g = new Friendly();\n    Console.WriteLine(g.Greet("Aria"));\n  }\n}',
  },
  {
    slug: 'collections',
    title: 'Collections',
    summary: 'Storing growable lists with List<T>',
    explanation: [
      'List<T> from System.Collections.Generic is a resizable list — import the namespace and create one with new List<T>().',
      'Use Add(value) to append, indexing like list[0] to read, Count for the size, and foreach to visit every element.',
    ],
    example: 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n  static void Main(string[] args) {\n    List<string> fruits = new List<string>();\n    fruits.Add("apple");\n    fruits.Add("banana");\n    fruits.Add("cherry");\n\n    Console.WriteLine($"Count: {fruits.Count}");\n    Console.WriteLine($"First: {fruits[0]}");\n    foreach (string fruit in fruits) {\n      Console.WriteLine($"- {fruit}");\n    }\n  }\n}',
    starterCode: 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n  static void Main(string[] args) {\n    List<int> numbers = new List<int>();\n    numbers.Add(10);\n    numbers.Add(20);\n    numbers.Add(30);\n    foreach (int n in numbers) {\n      Console.WriteLine(n);\n    }\n  }\n}',
  },
  {
    slug: 'linq',
    title: 'LINQ',
    summary: 'Querying collections with Where, Select, and OrderBy',
    explanation: [
      'LINQ (System.Linq) lets you query lists in a declarative style: Where filters, Select transforms, and OrderBy sorts.',
      'These methods return sequences you can loop over with foreach, often chained together and finished with ToList().',
    ],
    example: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n  static void Main(string[] args) {\n    List<int> numbers = new List<int> { 5, 1, 9, 3, 8, 2 };\n\n    var evens = numbers.Where(n => n % 2 == 0);\n    Console.WriteLine("Evens:");\n    foreach (int n in evens) {\n      Console.WriteLine(n);\n    }\n\n    var doubled = numbers.Select(n => n * 2).ToList();\n    Console.WriteLine($"First doubled: {doubled[0]}");\n\n    var sorted = numbers.OrderBy(n => n).ToList();\n    Console.WriteLine("Sorted:");\n    foreach (int n in sorted) {\n      Console.WriteLine(n);\n    }\n  }\n}',
    starterCode: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n  static void Main(string[] args) {\n    List<string> names = new List<string> { "Mira", "Eli", "Aria", "Sam" };\n    var shortNames = names.Where(n => n.Length <= 3).ToList();\n    foreach (string n in shortNames) {\n      Console.WriteLine(n);\n    }\n  }\n}',
  },
  {
    slug: 'exception-handling',
    title: 'Exception Handling',
    summary: 'Handling errors with try, catch, finally, and throw',
    explanation: [
      'Risky code goes in a try block; a matching catch block handles the exception, and finally always runs afterwards.',
      'You can throw your own exceptions, including custom ones defined by extending Exception.',
    ],
    example: 'using System;\n\nclass InvalidAgeException : Exception {\n  public InvalidAgeException(string message) : base(message) { }\n}\n\nclass Program {\n  static void CheckAge(int age) {\n    if (age < 0) {\n      throw new InvalidAgeException("Age cannot be negative");\n    }\n    Console.WriteLine($"Age {age} is valid");\n  }\n\n  static void Main(string[] args) {\n    try {\n      int a = 10;\n      int b = 0;\n      Console.WriteLine(a / b);\n    } catch (DivideByZeroException e) {\n      Console.WriteLine($"Caught: {e.Message}");\n    } finally {\n      Console.WriteLine("Division attempt finished");\n    }\n\n    try {\n      CheckAge(-5);\n    } catch (InvalidAgeException e) {\n      Console.WriteLine($"Caught: {e.Message}");\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    try {\n      int[] nums = { 1, 2, 3 };\n      Console.WriteLine(nums[5]);\n    } catch (IndexOutOfRangeException e) {\n      Console.WriteLine($"Caught an error: {e.Message}");\n    } finally {\n      Console.WriteLine("Done checking the array");\n    }\n  }\n}',
  },
  {
    slug: 'properties-and-enums',
    title: 'Properties & Enums',
    summary: 'Auto-properties and named constants with enum',
    explanation: [
      'A plain public field works, but a property like public string Name { get; set; } is the more idiomatic choice — it looks just as simple to use but lets you add validation or read-only logic later without breaking any code that already uses Name.',
      'An enum defines a small, named set of values, e.g. enum Level { Beginner, Intermediate, Advanced };. Using a Level variable instead of a raw string or number makes invalid values impossible and makes your code read like plain English.',
    ],
    example: 'using System;\n\nenum Level { Beginner, Intermediate, Advanced }\n\nclass Player {\n  public string Name { get; set; }\n  public int Score { get; set; }\n  public Level Rank { get; set; }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Player p = new Player();\n    p.Name = "Aria";\n    p.Score = 95;\n    p.Rank = Level.Advanced;\n    Console.WriteLine($"{p.Name} scored {p.Score} and is ranked {p.Rank}");\n  }\n}',
    starterCode: 'using System;\n\nenum Level { Beginner, Intermediate, Advanced }\n\nclass Student {\n  public string Name { get; set; }\n  public Level CurrentLevel { get; set; }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Student s = new Student();\n    s.Name = "Eli";\n    s.CurrentLevel = Level.Beginner;\n    Console.WriteLine($"{s.Name} is at the {s.CurrentLevel} level");\n  }\n}',
  },
  {
    slug: 'generics',
    title: 'Generics',
    summary: 'Writing one class or method that works with any type',
    explanation: [
      'Without generics, storing different types safely would mean writing a separate class for each one, or giving up type safety entirely. Generics let you write a single class or method with a placeholder type, written in angle brackets like <T>, that the compiler fills in for you each time you use it.',
      'class Box<T> { public T Value; } defines a box that can hold any type — Box<int> for a number, Box<string> for text — while still catching type mistakes at compile time. The List<T> you used in the collections lesson is built exactly this way; now you know how to write your own.',
    ],
    example: 'using System;\n\nclass Box<T> {\n  public T Value;\n\n  public Box(T value) {\n    Value = value;\n  }\n\n  public void Print() {\n    Console.WriteLine($"Box contains: {Value}");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Box<string> nameBox = new Box<string>("Aria");\n    Box<int> numberBox = new Box<int>(42);\n    nameBox.Print();\n    numberBox.Print();\n  }\n}',
    starterCode: 'using System;\n\nclass Box<T> {\n  public T Value;\n\n  public Box(T value) {\n    Value = value;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Box<int> ageBox = new Box<int>(12);\n    Box<string> cityBox = new Box<string>("Pokhara");\n    Console.WriteLine(ageBox.Value);\n    Console.WriteLine(cityBox.Value);\n  }\n}',
  },
  {
    slug: 'static-and-readonly',
    title: 'Static & Readonly',
    summary: 'Members shared by the class, and fields set only once',
    explanation: [
      'A static field or method belongs to the class itself rather than to any one object, so every instance shares the same value — useful for counters or constants.',
      'A readonly field can only be assigned when it is declared or inside the constructor; after that it is locked, which protects values that should never change.',
    ],
    example: 'using System;\n\nclass Counter {\n  public static int InstanceCount = 0;\n  public readonly string Id;\n\n  public Counter() {\n    InstanceCount++;\n    Id = $"counter-{InstanceCount}";\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Counter a = new Counter();\n    Counter b = new Counter();\n    Counter c = new Counter();\n    Console.WriteLine($"Created: {Counter.InstanceCount}");\n    Console.WriteLine(a.Id);\n    Console.WriteLine(b.Id);\n    Console.WriteLine(c.Id);\n  }\n}',
    starterCode: 'using System;\n\nclass Config {\n  public static string AppName = "LearnHub";\n  public readonly int CreatedYear;\n\n  public Config(int year) {\n    CreatedYear = year;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Config cfg = new Config(2024);\n    Console.WriteLine(Config.AppName);\n    Console.WriteLine(cfg.CreatedYear);\n  }\n}',
  },
  {
    slug: 'polymorphism-and-virtual-override',
    title: 'Polymorphism: virtual & override',
    summary: 'Calling overridden methods through a base-type reference',
    explanation: [
      'When a base class marks a method virtual and a subclass marks its version override, calling that method through a base-type variable still runs the subclass\'s version — this is polymorphism.',
      'It lets you write code that works with a list of base-type references while still getting each object\'s own specialised behaviour at runtime.',
    ],
    example: 'using System;\nusing System.Collections.Generic;\n\nclass Shape {\n  public virtual string Describe() {\n    return "A generic shape";\n  }\n}\n\nclass Circle : Shape {\n  public override string Describe() {\n    return "A round circle";\n  }\n}\n\nclass Square : Shape {\n  public override string Describe() {\n    return "A four-sided square";\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    List<Shape> shapes = new List<Shape> { new Shape(), new Circle(), new Square() };\n    foreach (Shape s in shapes) {\n      Console.WriteLine(s.Describe());\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass Employee {\n  public virtual double GetPay() {\n    return 1000;\n  }\n}\n\nclass Manager : Employee {\n  public override double GetPay() {\n    return 2000;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Employee e = new Manager();\n    Console.WriteLine(e.GetPay());\n  }\n}',
  },
  {
    slug: 'abstract-classes',
    title: 'Abstract Classes',
    summary: 'A base class that forces subclasses to fill in behaviour',
    explanation: [
      'An abstract class cannot be instantiated directly with new — it exists only to be inherited from, and may mix abstract methods (no body) with regular ones.',
      'A subclass must provide an override for every abstract method, which guarantees that behaviour exists while still letting the base class share common code, unlike an interface which cannot hold implementation for fields or method bodies the same way.',
    ],
    example: 'using System;\n\nabstract class Shape {\n  public abstract double Area();\n\n  public void PrintArea() {\n    Console.WriteLine($"Area: {Area()}");\n  }\n}\n\nclass Rectangle : Shape {\n  public double Width;\n  public double Height;\n\n  public Rectangle(double width, double height) {\n    Width = width;\n    Height = height;\n  }\n\n  public override double Area() {\n    return Width * Height;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Rectangle r = new Rectangle(4, 5);\n    r.PrintArea();\n  }\n}',
    starterCode: 'using System;\n\nabstract class Instrument {\n  public abstract void Play();\n}\n\nclass Drum : Instrument {\n  public override void Play() {\n    Console.WriteLine("Boom boom!");\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Instrument i = new Drum();\n    i.Play();\n  }\n}',
  },
  {
    slug: 'structs-in-csharp',
    title: 'Structs',
    summary: 'Value types versus reference type classes',
    explanation: [
      'A struct looks similar to a class but is a value type — when you assign or pass it, C# copies the whole value rather than sharing a reference.',
      'A class is a reference type, so copying a variable just copies the reference and both variables point at the same object; changing one through the reference is visible through the other.',
    ],
    example: 'using System;\n\nstruct PointStruct {\n  public int X;\n  public int Y;\n}\n\nclass PointClass {\n  public int X;\n  public int Y;\n}\n\nclass Program {\n  static void Main(string[] args) {\n    PointStruct s1 = new PointStruct { X = 1, Y = 1 };\n    PointStruct s2 = s1;\n    s2.X = 99;\n    Console.WriteLine($"struct s1.X = {s1.X}, s2.X = {s2.X}");\n\n    PointClass c1 = new PointClass { X = 1, Y = 1 };\n    PointClass c2 = c1;\n    c2.X = 99;\n    Console.WriteLine($"class c1.X = {c1.X}, c2.X = {c2.X}");\n  }\n}',
    starterCode: 'using System;\n\nstruct Coordinate {\n  public int X;\n  public int Y;\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Coordinate a = new Coordinate { X = 5, Y = 10 };\n    Coordinate b = a;\n    b.X = 50;\n    Console.WriteLine($"a.X = {a.X}, b.X = {b.X}");\n  }\n}',
  },
  {
    slug: 'nullable-types',
    title: 'Nullable Types',
    summary: 'int? and friends for values that might be missing',
    explanation: [
      'A value type like int normally always holds a value, but writing int? (short for Nullable<int>) lets it also hold null to represent "no value".',
      'Check .HasValue before reading .Value, or use the null-conditional operator ?. to safely call members on something that might be null.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int? maybeAge = null;\n    Console.WriteLine($"HasValue: {maybeAge.HasValue}");\n\n    maybeAge = 12;\n    if (maybeAge.HasValue) {\n      Console.WriteLine($"Age is {maybeAge.Value}");\n    }\n\n    string name = null;\n    Console.WriteLine($"Length: {name?.Length}");\n\n    int total = maybeAge ?? 0;\n    Console.WriteLine($"Total: {total}");\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int? score = null;\n    Console.WriteLine(score.HasValue);\n    score = 88;\n    Console.WriteLine(score.Value);\n  }\n}',
  },
  {
    slug: 'switch-expressions',
    title: 'Switch Expressions',
    summary: 'The modern value switch { ... } syntax',
    explanation: [
      'A traditional switch statement uses case labels and break, but a switch expression is more compact: result = value switch { 1 => "one", 2 => "two", _ => "other" };.',
      'Each arrow => maps a pattern to a value, and the underscore _ acts as the default catch-all, with the whole expression producing a single value you can assign or return.',
    ],
    example: 'using System;\n\nclass Program {\n  static string DayName(int day) {\n    string traditional;\n    switch (day) {\n      case 1:\n        traditional = "Monday";\n        break;\n      default:\n        traditional = "Unknown";\n        break;\n    }\n    Console.WriteLine($"Traditional switch: {traditional}");\n\n    string name = day switch {\n      1 => "Monday",\n      2 => "Tuesday",\n      3 => "Wednesday",\n      _ => "Unknown",\n    };\n    return name;\n  }\n\n  static void Main(string[] args) {\n    Console.WriteLine(DayName(1));\n    Console.WriteLine(DayName(3));\n    Console.WriteLine(DayName(9));\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    int grade = 2;\n    string label = grade switch {\n      1 => "Excellent",\n      2 => "Good",\n      3 => "Fair",\n      _ => "Unknown",\n    };\n    Console.WriteLine(label);\n  }\n}',
  },
  {
    slug: 'tuples-in-csharp',
    title: 'Tuples',
    summary: 'Bundling a few values together with named tuples',
    explanation: [
      'A tuple groups several values into one without needing a whole new class: (string Name, int Age) person = ("Aria", 12);.',
      'Tuples are handy for returning more than one value from a method — just give the return type a tuple shape and access the named parts with dot notation.',
    ],
    example: 'using System;\n\nclass Program {\n  static (string Name, int Age) MakePerson() {\n    return ("Aria", 12);\n  }\n\n  static (int Min, int Max) MinMax(int[] nums) {\n    int min = nums[0];\n    int max = nums[0];\n    foreach (int n in nums) {\n      if (n < min) min = n;\n      if (n > max) max = n;\n    }\n    return (min, max);\n  }\n\n  static void Main(string[] args) {\n    (string Name, int Age) person = MakePerson();\n    Console.WriteLine($"{person.Name} is {person.Age}");\n\n    var range = MinMax(new int[] { 4, 8, 1, 9, 3 });\n    Console.WriteLine($"Min: {range.Min}, Max: {range.Max}");\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static (string City, int Population) GetCity() {\n    return ("Pokhara", 500000);\n  }\n\n  static void Main(string[] args) {\n    var city = GetCity();\n    Console.WriteLine($"{city.City}: {city.Population}");\n  }\n}',
  },
  {
    slug: 'delegates-and-events',
    title: 'Delegates & Events',
    summary: 'A type that points to a method you can call indirectly',
    explanation: [
      'A delegate declares a method signature, e.g. delegate int Operation(int a, int b);, and a variable of that delegate type can hold any method matching that shape.',
      'You assign a matching method to the delegate variable and then invoke the delegate like a method call — this is the simplified idea behind C# events, where multiple methods can be notified when something happens.',
    ],
    example: 'using System;\n\ndelegate int Operation(int a, int b);\n\nclass Program {\n  static int Add(int a, int b) {\n    return a + b;\n  }\n\n  static int Multiply(int a, int b) {\n    return a * b;\n  }\n\n  static void Main(string[] args) {\n    Operation op = Add;\n    Console.WriteLine(op(3, 4));\n\n    op = Multiply;\n    Console.WriteLine(op(3, 4));\n  }\n}',
    starterCode: 'using System;\n\ndelegate void Greeter(string name);\n\nclass Program {\n  static void SayHello(string name) {\n    Console.WriteLine($"Hello, {name}!");\n  }\n\n  static void Main(string[] args) {\n    Greeter greet = SayHello;\n    greet("Aria");\n  }\n}',
  },
  {
    slug: 'lambda-expressions-csharp',
    title: 'Lambda Expressions',
    summary: 'Short, inline functions with the => syntax',
    explanation: [
      'A lambda expression is a compact, unnamed function written as (parameters) => expression, like (a, b) => a + b, and is often stored in a Func<> or Predicate<> variable.',
      'You already used lambdas inside LINQ calls like Where(n => n % 2 == 0) — that arrow function is a lambda passed directly as an argument.',
    ],
    example: 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n  static void Main(string[] args) {\n    Func<int, int, int> add = (a, b) => a + b;\n    Console.WriteLine(add(3, 5));\n\n    Predicate<int> isEven = n => n % 2 == 0;\n    Console.WriteLine(isEven(8));\n\n    List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };\n    var evens = numbers.Where(n => n % 2 == 0).ToList();\n    foreach (int n in evens) {\n      Console.WriteLine(n);\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    Func<int, int> square = n => n * n;\n    Console.WriteLine(square(6));\n    Console.WriteLine(square(9));\n  }\n}',
  },
  {
    slug: 'string-interpolation-and-formatting',
    title: 'String Interpolation & Formatting',
    summary: 'Format specifiers inside interpolated strings',
    explanation: [
      'Inside an interpolated string you can add a format specifier after a colon, like $"{value:F2}", to control how a value is displayed.',
      'F2 rounds a number to two decimal places, C formats currency, and N adds thousands separators — handy for turning raw numbers into readable output.',
    ],
    example: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    double price = 19.5;\n    double pi = Math.PI;\n    int big = 1234567;\n\n    Console.WriteLine($"Price: {price:F2}");\n    Console.WriteLine($"Pi: {pi:F4}");\n    Console.WriteLine($"Currency: {price:C}");\n    Console.WriteLine($"Big number: {big:N0}");\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    double average = 87.6666;\n    Console.WriteLine($"Average: {average:F2}");\n  }\n}',
  },
  {
    slug: 'dictionaries-in-csharp',
    title: 'Dictionaries',
    summary: 'Key-value lookups with Dictionary<TKey, TValue>',
    explanation: [
      'A Dictionary<TKey, TValue> stores pairs of keys and values so you can look up a value quickly by its key, similar to a real dictionary mapping words to definitions.',
      'Use TryGetValue(key, out value) to safely check for a key without risking an exception, and foreach (var kvp in dict) to visit every pair via kvp.Key and kvp.Value.',
    ],
    example: 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n  static void Main(string[] args) {\n    Dictionary<string, int> ages = new Dictionary<string, int>();\n    ages["Aria"] = 12;\n    ages["Eli"] = 9;\n    ages["Mira"] = 14;\n\n    if (ages.TryGetValue("Eli", out int eliAge)) {\n      Console.WriteLine($"Eli is {eliAge}");\n    }\n\n    foreach (var kvp in ages) {\n      Console.WriteLine($"{kvp.Key} -> {kvp.Value}");\n    }\n  }\n}',
    starterCode: 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n  static void Main(string[] args) {\n    Dictionary<string, string> capitals = new Dictionary<string, string>();\n    capitals["Nepal"] = "Kathmandu";\n    capitals["France"] = "Paris";\n    foreach (var kvp in capitals) {\n      Console.WriteLine($"{kvp.Key}: {kvp.Value}");\n    }\n  }\n}',
  },
  {
    slug: 'extension-methods',
    title: 'Extension Methods',
    summary: 'Adding new methods to an existing type',
    explanation: [
      'An extension method lets you "add" a method to a type you don\'t own, like int or string, without modifying its source — declare it as static in a static class.',
      'The first parameter uses the this keyword to mark which type is being extended, e.g. static bool IsEven(this int n), and then you call it as if it were a real instance method: 4.IsEven().',
    ],
    example: 'using System;\n\nstatic class IntExtensions {\n  public static bool IsEven(this int n) {\n    return n % 2 == 0;\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    int a = 4;\n    int b = 7;\n    Console.WriteLine(a.IsEven());\n    Console.WriteLine(b.IsEven());\n  }\n}',
    starterCode: 'using System;\n\nstatic class StringExtensions {\n  public static string Shout(this string s) {\n    return s.ToUpper() + "!";\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    string word = "hello";\n    Console.WriteLine(word.Shout());\n  }\n}',
  },
  {
    slug: 'pattern-matching',
    title: 'Pattern Matching',
    summary: 'Testing and unpacking values with is and switch',
    explanation: [
      'The is keyword can both test a type and bind it to a new variable in one step, like if (shape is Circle c), which only enters the block when shape is actually a Circle and gives you c to use inside.',
      'Switch expressions can use the same kind of pattern as a case, matching on type and even extra conditions, which keeps multi-branch type checks tidy.',
    ],
    example: 'using System;\n\nclass Shape { }\nclass Circle : Shape {\n  public double Radius;\n  public Circle(double radius) { Radius = radius; }\n}\nclass Square : Shape {\n  public double Side;\n  public Square(double side) { Side = side; }\n}\n\nclass Program {\n  static string Describe(Shape shape) {\n    if (shape is Circle c) {\n      return $"Circle with radius {c.Radius}";\n    }\n    return shape switch {\n      Square sq => $"Square with side {sq.Side}",\n      _ => "Unknown shape",\n    };\n  }\n\n  static void Main(string[] args) {\n    Console.WriteLine(Describe(new Circle(3)));\n    Console.WriteLine(Describe(new Square(5)));\n  }\n}',
    starterCode: 'using System;\n\nclass Program {\n  static void Main(string[] args) {\n    object value = 42;\n    if (value is int n) {\n      Console.WriteLine($"It is an int: {n}");\n    } else {\n      Console.WriteLine("Not an int");\n    }\n  }\n}',
  },
  {
    slug: 'operator-overloading-csharp',
    title: 'Operator Overloading',
    summary: 'Teaching + and other operators how to work on your own types',
    explanation: [
      'C# lets you define what an operator like + means for your own type by declaring a static method named operator +, taking two instances and returning a new combined one.',
      'Once overloaded, your custom type can be used with natural-looking expressions like point1 + point2 instead of writing a separate Add method.',
    ],
    example: 'using System;\n\nstruct Point {\n  public int X;\n  public int Y;\n\n  public Point(int x, int y) {\n    X = x;\n    Y = y;\n  }\n\n  public static Point operator +(Point a, Point b) {\n    return new Point(a.X + b.X, a.Y + b.Y);\n  }\n\n  public override string ToString() {\n    return $"({X}, {Y})";\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Point p1 = new Point(1, 2);\n    Point p2 = new Point(3, 4);\n    Point sum = p1 + p2;\n    Console.WriteLine(sum);\n  }\n}',
    starterCode: 'using System;\n\nstruct Money {\n  public int Cents;\n\n  public Money(int cents) {\n    Cents = cents;\n  }\n\n  public static Money operator +(Money a, Money b) {\n    return new Money(a.Cents + b.Cents);\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Money a = new Money(150);\n    Money b = new Money(250);\n    Money total = a + b;\n    Console.WriteLine(total.Cents);\n  }\n}',
  },
  {
    slug: 'namespaces-in-csharp',
    title: 'Namespaces',
    summary: 'Organising code into named groups',
    explanation: [
      'A namespace groups related classes under one name, e.g. namespace MyApp { class Helper { ... } }, which helps avoid naming collisions in larger programs.',
      'To use a class from another namespace you either write its fully qualified name like MyApp.Utilities.Helper, or add a using statement at the top of the file.',
    ],
    example: 'using System;\nusing MyApp.Utilities;\n\nnamespace MyApp.Utilities {\n  class MathHelper {\n    public static int Square(int n) {\n      return n * n;\n    }\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    int result = MathHelper.Square(7);\n    Console.WriteLine(result);\n    Console.WriteLine(MyApp.Utilities.MathHelper.Square(3));\n  }\n}',
    starterCode: 'using System;\n\nnamespace Greetings {\n  class Greeter {\n    public static string Hello(string name) {\n      return $"Hello, {name}!";\n    }\n  }\n}\n\nclass Program {\n  static void Main(string[] args) {\n    Console.WriteLine(Greetings.Greeter.Hello("Aria"));\n  }\n}',
  },
  {
    slug: 'custom-exceptions-and-multiple-catch',
    title: 'Custom Exceptions & Multiple Catch Blocks',
    summary: 'Defining your own exception type and catching several kinds',
    explanation: [
      'A custom exception is just a class that extends Exception, usually passing a message to the base constructor, so you can throw errors that describe your program\'s own rules.',
      'A single try can be followed by several catch blocks for different exception types — list the most specific exceptions first and a general catch (Exception e) last, since C# checks them in order.',
    ],
    example: 'using System;\n\nclass OutOfStockException : Exception {\n  public OutOfStockException(string message) : base(message) { }\n}\n\nclass Program {\n  static void BuyItem(int stock) {\n    if (stock <= 0) {\n      throw new OutOfStockException("This item is out of stock");\n    }\n    Console.WriteLine("Purchase successful");\n  }\n\n  static void Main(string[] args) {\n    try {\n      int stock = 0;\n      BuyItem(stock);\n      int[] nums = { 1, 2 };\n      Console.WriteLine(nums[5]);\n    } catch (OutOfStockException e) {\n      Console.WriteLine($"Stock error: {e.Message}");\n    } catch (IndexOutOfRangeException e) {\n      Console.WriteLine($"Index error: {e.Message}");\n    } catch (Exception e) {\n      Console.WriteLine($"Unexpected error: {e.Message}");\n    }\n  }\n}',
    starterCode: 'using System;\n\nclass NegativeAmountException : Exception {\n  public NegativeAmountException(string message) : base(message) { }\n}\n\nclass Program {\n  static void Withdraw(int amount) {\n    if (amount < 0) {\n      throw new NegativeAmountException("Amount cannot be negative");\n    }\n    Console.WriteLine($"Withdrew {amount}");\n  }\n\n  static void Main(string[] args) {\n    try {\n      Withdraw(-10);\n    } catch (NegativeAmountException e) {\n      Console.WriteLine($"Error: {e.Message}");\n    } catch (Exception e) {\n      Console.WriteLine($"Unexpected: {e.Message}");\n    }\n  }\n}',
  },
]
