import type { CodingLesson } from '../languages'

export const css: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to CSS',
    summary: 'How CSS styles HTML elements',
    explanation: [
      'CSS (Cascading Style Sheets) controls how HTML looks — colours, fonts, spacing, layout, and more.',
      'A CSS rule has a selector (which elements to style) and a declaration block in {} with property: value; pairs.',
      'In this playground your CSS is applied to a small HTML preview so you can see the effect immediately.',
    ],
    example: 'p {\n  color: violet;\n  font-size: 20px;\n}\nh1 {\n  text-align: center;\n}',
    starterCode: 'h1 {\n  color: teal;\n}\np {\n  font-size: 18px;\n}',
  },
  {
    slug: 'selectors',
    title: 'Selectors',
    summary: 'Targeting exactly the elements you want to style',
    explanation: [
      'Element selectors (p, h1) target every element of that type. Class selectors (.card) target elements with class="card". ID selectors (#header) target the single element with that id.',
      'You can combine selectors — e.g. .card p targets paragraphs inside elements with class "card".',
    ],
    example: '.highlight {\n  background: yellow;\n}\n#title {\n  font-weight: bold;\n}\nul li {\n  color: slategray;\n}',
    starterCode: '.highlight {\n  background: lightblue;\n}\n#title {\n  color: crimson;\n}',
  },
  {
    slug: 'box-model',
    title: 'The Box Model',
    summary: 'Margin, border, padding, and content',
    explanation: [
      'Every HTML element is a rectangular box made of four layers, from the inside out: content, padding, border, and margin.',
      'padding adds space inside the border; margin adds space outside it; border draws a line around the padding.',
      'Understanding the box model is the key to controlling spacing and layout.',
    ],
    example: 'div {\n  width: 200px;\n  padding: 16px;\n  border: 2px solid teal;\n  margin: 20px;\n  background: #eef;\n}',
    starterCode: '.box {\n  padding: 12px;\n  border: 3px dashed orange;\n  margin: 16px;\n}',
  },
  {
    slug: 'flexbox',
    title: 'Flexbox Layout',
    summary: 'Arranging items in a row or column with ease',
    explanation: [
      'Setting display: flex on a container turns its children into a flexible row (by default).',
      'justify-content controls horizontal alignment (e.g. center, space-between); align-items controls vertical alignment.',
      'Flexbox is the modern way to build navigation bars, card layouts, and centred content.',
    ],
    example: '.row {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 12px;\n}\n.row div {\n  background: #c4b5fd;\n  padding: 10px;\n  border-radius: 6px;\n}',
    starterCode: '.row {\n  display: flex;\n  gap: 10px;\n  justify-content: center;\n}',
  },
  {
    slug: 'colors-and-units',
    title: 'Colours & Units',
    summary: 'Naming colours and sizing things precisely',
    explanation: [
      'Colours can be named (red), hex (#ff6600), or functions like rgb(255,102,0) and hsl(24,100%,50%).',
      'Sizes can be absolute (px) or relative (%, em, rem, vw, vh) — relative units help your design adapt to different screens.',
    ],
    example: 'h1 {\n  color: #7c3aed;\n  font-size: 2rem;\n}\n.banner {\n  background: linear-gradient(90deg, #8b5cf6, #4f46e5);\n  padding: 2vh 4vw;\n}',
    starterCode: 'h1 {\n  color: rgb(124, 58, 237);\n}\n.banner {\n  background: #e0e7ff;\n  padding: 1rem;\n}',
  },
  {
    slug: 'transitions',
    title: 'Transitions & Hover Effects',
    summary: 'Adding smooth, interactive animations',
    explanation: [
      'The transition property smoothly animates a CSS change over time, e.g. transition: all 0.3s ease.',
      'Combine it with the :hover pseudo-class to make elements respond when the user moves their mouse over them.',
    ],
    example: 'button {\n  background: #4f46e5;\n  color: white;\n  padding: 10px 20px;\n  border: none;\n  border-radius: 8px;\n  transition: transform 0.2s ease, background 0.2s ease;\n}\nbutton:hover {\n  background: #7c3aed;\n  transform: scale(1.08);\n}',
    starterCode: 'button {\n  background: teal;\n  color: white;\n  padding: 10px 18px;\n  border: none;\n  border-radius: 6px;\n  transition: background 0.2s;\n}\nbutton:hover {\n  background: darkcyan;\n}',
  },
  {
    slug: 'typography',
    title: 'Typography',
    summary: 'Controlling how text looks and reads on the page',
    explanation: [
      'font-family chooses the typeface, font-weight controls boldness (e.g. normal, bold, or a number like 600), and line-height sets the vertical spacing between lines of text.',
      'text-align positions text within its box (left, center, right, justify), while letter-spacing adds or removes space between characters for a tighter or more open feel.',
      'Good typography makes long passages of text comfortable to read — small tweaks to these properties can transform a page.',
    ],
    example: 'h1 {\n  font-family: Georgia, serif;\n  font-weight: 700;\n  letter-spacing: 1px;\n  text-align: center;\n}\np {\n  font-family: Arial, sans-serif;\n  line-height: 1.6;\n  text-align: justify;\n}',
    starterCode: 'h1 {\n  font-family: Verdana, sans-serif;\n  font-weight: 600;\n  text-align: center;\n}\np {\n  line-height: 1.5;\n  letter-spacing: 0.5px;\n}',
  },
  {
    slug: 'css-grid',
    title: 'CSS Grid',
    summary: 'Laying elements out in rows and columns at once',
    explanation: [
      'Setting display: grid on a container turns it into a two-dimensional layout where you control rows and columns together.',
      'grid-template-columns defines how many columns there are and how wide each one is (e.g. "1fr 1fr 1fr" makes three equal columns), and gap adds space between cells.',
      'Named grid-template-areas let you lay out a page like a map, assigning each child element to a named region with grid-area.',
    ],
    example: '.layout {\n  display: grid;\n  grid-template-columns: 1fr 2fr;\n  grid-template-areas:\n    "sidebar header"\n    "sidebar main";\n  gap: 10px;\n}\n.sidebar { grid-area: sidebar; background: #c4b5fd; }\n.header { grid-area: header; background: #ddd6fe; }\n.main { grid-area: main; background: #ede9fe; }',
    starterCode: '.row {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}\n.row div {\n  background: #c4b5fd;\n  padding: 16px;\n  text-align: center;\n  border-radius: 6px;\n}',
  },
  {
    slug: 'positioning',
    title: 'Positioning',
    summary: 'Controlling where elements sit using the position property',
    explanation: [
      'position: static is the default — elements simply flow in document order. position: relative shifts an element from its normal spot using top/left/right/bottom, while leaving a gap behind it.',
      'position: absolute removes an element from the flow and places it relative to its nearest positioned ancestor; position: fixed pins it to the browser window even while scrolling.',
      'position: sticky behaves like relative until the page scrolls past it, then "sticks" in place; z-index controls which overlapping element appears on top.',
    ],
    example: '.card {\n  position: relative;\n  background: #ede9fe;\n  padding: 24px;\n}\n.badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n  background: crimson;\n  color: white;\n  padding: 2px 8px;\n  border-radius: 999px;\n  z-index: 2;\n}',
    starterCode: '.box {\n  position: relative;\n  background: #eef;\n  padding: 20px;\n}\n.tag {\n  position: absolute;\n  top: 6px;\n  left: 6px;\n  background: teal;\n  color: white;\n  padding: 2px 6px;\n  border-radius: 4px;\n}',
  },
  {
    slug: 'pseudo-classes-and-elements',
    title: 'Pseudo-classes & Pseudo-elements',
    summary: 'Styling based on state, position, and generated content',
    explanation: [
      'Pseudo-classes like :hover, :first-child, and :nth-child(2) select elements based on a state or their position among siblings, without needing extra classes in your HTML.',
      'Pseudo-elements like ::before and ::after let you insert generated content immediately before or after an element\'s real content, styled with the content property.',
      'These are written with one colon for pseudo-classes (:hover) and two colons for pseudo-elements (::before), and combine well with transitions for interactive effects.',
    ],
    example: 'li:first-child {\n  font-weight: bold;\n}\nli:nth-child(2) {\n  color: crimson;\n}\nbutton:hover {\n  background: darkcyan;\n}\nh1::before {\n  content: "✦ ";\n  color: gold;\n}',
    starterCode: 'li:nth-child(odd) {\n  background: #eef;\n}\nli:hover {\n  color: teal;\n}\np::after {\n  content: " 🌟";\n}',
  },
  {
    slug: 'responsive-design',
    title: 'Responsive Design',
    summary: 'Adapting layouts to different screen sizes with media queries',
    explanation: [
      'A media query like @media (max-width: 600px) { ... } applies a block of CSS only when the browser window matches that condition — here, when it is 600px wide or narrower.',
      '"Mobile-first" design means writing your base styles for small screens first, then adding @media (min-width: ...) rules to enhance the layout as the screen gets bigger.',
      'Responsive design lets one set of HTML look great on phones, tablets, and desktops alike.',
    ],
    example: '.row {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}\n@media (min-width: 600px) {\n  .row {\n    flex-direction: row;\n    justify-content: space-between;\n  }\n}\n.card {\n  background: #ede9fe;\n  padding: 12px;\n}',
    starterCode: 'h1 {\n  font-size: 1.5rem;\n  text-align: center;\n}\n@media (min-width: 500px) {\n  h1 {\n    font-size: 2.5rem;\n    text-align: left;\n  }\n}',
  },
  {
    slug: 'css-variables',
    title: 'CSS Variables',
    summary: 'Reusing values with custom properties and theming',
    explanation: [
      'A custom property is declared with two leading dashes, like --main-color: teal;, usually on :root so it is available everywhere on the page.',
      'You read a custom property anywhere with var(--main-color) — change the single declaration and every place that uses it updates together.',
      'This makes theming easy: redefine the same variable names inside a different selector (like .dark-theme) to swap an entire colour palette at once.',
    ],
    example: ':root {\n  --main-color: #7c3aed;\n  --gap: 12px;\n}\nh1 {\n  color: var(--main-color);\n}\n.card {\n  border: 2px solid var(--main-color);\n  padding: var(--gap);\n  margin-bottom: var(--gap);\n}',
    starterCode: ':root {\n  --brand: teal;\n}\nh1 {\n  color: var(--brand);\n}\nbutton {\n  background: var(--brand);\n  color: white;\n  border: none;\n  padding: 8px 16px;\n  border-radius: 6px;\n}',
  },
  {
    slug: 'animations',
    title: 'Animations',
    summary: 'Bringing elements to life with @keyframes',
    explanation: [
      '@keyframes defines a named sequence of styles at different points (0%, 50%, 100%, or "from"/"to") that an element should move through over time.',
      'The animation property plays a keyframe sequence on an element — animation: bounce 1s ease-in-out infinite runs the "bounce" animation repeatedly.',
      'Animating transform (like scale or translateY) instead of properties such as width or top is smoother, since the browser does not have to recompute the page layout.',
    ],
    example: '@keyframes bounce {\n  0%, 100% { transform: translateY(0); }\n  50% { transform: translateY(-16px); }\n}\n#title {\n  display: inline-block;\n  animation: bounce 1.2s ease-in-out infinite;\n}',
    starterCode: '@keyframes pulse {\n  0% { transform: scale(1); }\n  50% { transform: scale(1.15); }\n  100% { transform: scale(1); }\n}\n#btn {\n  animation: pulse 1.5s ease-in-out infinite;\n}',
  },
]
