import type { CodingLesson } from '../languages'

export const css: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to CSS',
    summary: 'How CSS styles HTML elements',
    explanation: [
      'CSS (Cascading Style Sheets) controls how HTML looks — colours, fonts, spacing, layout, and more.',
      'A CSS rule has a selector (which elements to style) and a declaration block in {} with property: value; pairs.',
      'In this playground your CSS is applied to a small HTML preview so you can see the effect immediately.',
    ],
    example: 'p {\n  color: violet;\n  font-size: 20px;\n}\nh1 {\n  text-align: center;\n}',
    starterCode: 'h1 {\n  color: teal;\n}\np {\n  font-size: 18px;\n}',
  },
  {
    slug: 'selectors',
    title: 'Selectors',
    summary: 'Targeting exactly the elements you want to style',
    explanation: [
      'Element selectors (p, h1) target every element of that type. Class selectors (.card) target elements with class="card". ID selectors (#header) target the single element with that id.',
      'You can combine selectors — e.g. .card p targets paragraphs inside elements with class "card".',
    ],
    example: '.highlight {\n  background: yellow;\n}\n#title {\n  font-weight: bold;\n}\nul li {\n  color: slategray;\n}',
    starterCode: '.highlight {\n  background: lightblue;\n}\n#title {\n  color: crimson;\n}',
  },
  {
    slug: 'box-model',
    title: 'The Box Model',
    summary: 'Margin, border, padding, and content',
    explanation: [
      'Every HTML element is a rectangular box made of four layers, from the inside out: content, padding, border, and margin.',
      'padding adds space inside the border; margin adds space outside it; border draws a line around the padding.',
      'Understanding the box model is the key to controlling spacing and layout.',
    ],
    example: 'div {\n  width: 200px;\n  padding: 16px;\n  border: 2px solid teal;\n  margin: 20px;\n  background: #eef;\n}',
    starterCode: '.box {\n  padding: 12px;\n  border: 3px dashed orange;\n  margin: 16px;\n}',
  },
  {
    slug: 'flexbox',
    title: 'Flexbox Layout',
    summary: 'Arranging items in a row or column with ease',
    explanation: [
      'Setting display: flex on a container turns its children into a flexible row (by default).',
      'justify-content controls horizontal alignment (e.g. center, space-between); align-items controls vertical alignment.',
      'Flexbox is the modern way to build navigation bars, card layouts, and centred content.',
    ],
    example: '.row {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 12px;\n}\n.row div {\n  background: #c4b5fd;\n  padding: 10px;\n  border-radius: 6px;\n}',
    starterCode: '.row {\n  display: flex;\n  gap: 10px;\n  justify-content: center;\n}',
  },
  {
    slug: 'colors-and-units',
    title: 'Colours & Units',
    summary: 'Naming colours and sizing things precisely',
    explanation: [
      'Colours can be named (red), hex (#ff6600), or functions like rgb(255,102,0) and hsl(24,100%,50%).',
      'Sizes can be absolute (px) or relative (%, em, rem, vw, vh) — relative units help your design adapt to different screens.',
    ],
    example: 'h1 {\n  color: #7c3aed;\n  font-size: 2rem;\n}\n.banner {\n  background: linear-gradient(90deg, #8b5cf6, #4f46e5);\n  padding: 2vh 4vw;\n}',
    starterCode: 'h1 {\n  color: rgb(124, 58, 237);\n}\n.banner {\n  background: #e0e7ff;\n  padding: 1rem;\n}',
  },
  {
    slug: 'transitions',
    title: 'Transitions & Hover Effects',
    summary: 'Adding smooth, interactive animations',
    explanation: [
      'The transition property smoothly animates a CSS change over time, e.g. transition: all 0.3s ease.',
      'Combine it with the :hover pseudo-class to make elements respond when the user moves their mouse over them.',
    ],
    example: 'button {\n  background: #4f46e5;\n  color: white;\n  padding: 10px 20px;\n  border: none;\n  border-radius: 8px;\n  transition: transform 0.2s ease, background 0.2s ease;\n}\nbutton:hover {\n  background: #7c3aed;\n  transform: scale(1.08);\n}',
    starterCode: 'button {\n  background: teal;\n  color: white;\n  padding: 10px 18px;\n  border: none;\n  border-radius: 6px;\n  transition: background 0.2s;\n}\nbutton:hover {\n  background: darkcyan;\n}',
  },
  {
    slug: 'typography',
    title: 'Typography',
    summary: 'Controlling how text looks and reads on the page',
    explanation: [
      'font-family chooses the typeface, font-weight controls boldness (e.g. normal, bold, or a number like 600), and line-height sets the vertical spacing between lines of text.',
      'text-align positions text within its box (left, center, right, justify), while letter-spacing adds or removes space between characters for a tighter or more open feel.',
      'Good typography makes long passages of text comfortable to read — small tweaks to these properties can transform a page.',
    ],
    example: 'h1 {\n  font-family: Georgia, serif;\n  font-weight: 700;\n  letter-spacing: 1px;\n  text-align: center;\n}\np {\n  font-family: Arial, sans-serif;\n  line-height: 1.6;\n  text-align: justify;\n}',
    starterCode: 'h1 {\n  font-family: Verdana, sans-serif;\n  font-weight: 600;\n  text-align: center;\n}\np {\n  line-height: 1.5;\n  letter-spacing: 0.5px;\n}',
  },
  {
    slug: 'css-grid',
    title: 'CSS Grid',
    summary: 'Laying elements out in rows and columns at once',
    explanation: [
      'Setting display: grid on a container turns it into a two-dimensional layout where you control rows and columns together.',
      'grid-template-columns defines how many columns there are and how wide each one is (e.g. "1fr 1fr 1fr" makes three equal columns), and gap adds space between cells.',
      'Named grid-template-areas let you lay out a page like a map, assigning each child element to a named region with grid-area.',
    ],
    example: '.layout {\n  display: grid;\n  grid-template-columns: 1fr 2fr;\n  grid-template-areas:\n    "sidebar header"\n    "sidebar main";\n  gap: 10px;\n}\n.sidebar { grid-area: sidebar; background: #c4b5fd; }\n.header { grid-area: header; background: #ddd6fe; }\n.main { grid-area: main; background: #ede9fe; }',
    starterCode: '.row {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}\n.row div {\n  background: #c4b5fd;\n  padding: 16px;\n  text-align: center;\n  border-radius: 6px;\n}',
  },
  {
    slug: 'positioning',
    title: 'Positioning',
    summary: 'Controlling where elements sit using the position property',
    explanation: [
      'position: static is the default — elements simply flow in document order. position: relative shifts an element from its normal spot using top/left/right/bottom, while leaving a gap behind it.',
      'position: absolute removes an element from the flow and places it relative to its nearest positioned ancestor; position: fixed pins it to the browser window even while scrolling.',
      'position: sticky behaves like relative until the page scrolls past it, then "sticks" in place; z-index controls which overlapping element appears on top.',
    ],
    example: '.card {\n  position: relative;\n  background: #ede9fe;\n  padding: 24px;\n}\n.badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n  background: crimson;\n  color: white;\n  padding: 2px 8px;\n  border-radius: 999px;\n  z-index: 2;\n}',
    starterCode: '.box {\n  position: relative;\n  background: #eef;\n  padding: 20px;\n}\n.tag {\n  position: absolute;\n  top: 6px;\n  left: 6px;\n  background: teal;\n  color: white;\n  padding: 2px 6px;\n  border-radius: 4px;\n}',
  },
  {
    slug: 'pseudo-classes-and-elements',
    title: 'Pseudo-classes & Pseudo-elements',
    summary: 'Styling based on state, position, and generated content',
    explanation: [
      'Pseudo-classes like :hover, :first-child, and :nth-child(2) select elements based on a state or their position among siblings, without needing extra classes in your HTML.',
      'Pseudo-elements like ::before and ::after let you insert generated content immediately before or after an element\'s real content, styled with the content property.',
      'These are written with one colon for pseudo-classes (:hover) and two colons for pseudo-elements (::before), and combine well with transitions for interactive effects.',
    ],
    example: 'li:first-child {\n  font-weight: bold;\n}\nli:nth-child(2) {\n  color: crimson;\n}\nbutton:hover {\n  background: darkcyan;\n}\nh1::before {\n  content: "✦ ";\n  color: gold;\n}',
    starterCode: 'li:nth-child(odd) {\n  background: #eef;\n}\nli:hover {\n  color: teal;\n}\np::after {\n  content: " 🌟";\n}',
  },
  {
    slug: 'responsive-design',
    title: 'Responsive Design',
    summary: 'Adapting layouts to different screen sizes with media queries',
    explanation: [
      'A media query like @media (max-width: 600px) { ... } applies a block of CSS only when the browser window matches that condition — here, when it is 600px wide or narrower.',
      '"Mobile-first" design means writing your base styles for small screens first, then adding @media (min-width: ...) rules to enhance the layout as the screen gets bigger.',
      'Responsive design lets one set of HTML look great on phones, tablets, and desktops alike.',
    ],
    example: '.row {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}\n@media (min-width: 600px) {\n  .row {\n    flex-direction: row;\n    justify-content: space-between;\n  }\n}\n.card {\n  background: #ede9fe;\n  padding: 12px;\n}',
    starterCode: 'h1 {\n  font-size: 1.5rem;\n  text-align: center;\n}\n@media (min-width: 500px) {\n  h1 {\n    font-size: 2.5rem;\n    text-align: left;\n  }\n}',
  },
  {
    slug: 'css-variables',
    title: 'CSS Variables',
    summary: 'Reusing values with custom properties and theming',
    explanation: [
      'A custom property is declared with two leading dashes, like --main-color: teal;, usually on :root so it is available everywhere on the page.',
      'You read a custom property anywhere with var(--main-color) — change the single declaration and every place that uses it updates together.',
      'This makes theming easy: redefine the same variable names inside a different selector (like .dark-theme) to swap an entire colour palette at once.',
    ],
    example: ':root {\n  --main-color: #7c3aed;\n  --gap: 12px;\n}\nh1 {\n  color: var(--main-color);\n}\n.card {\n  border: 2px solid var(--main-color);\n  padding: var(--gap);\n  margin-bottom: var(--gap);\n}',
    starterCode: ':root {\n  --brand: teal;\n}\nh1 {\n  color: var(--brand);\n}\nbutton {\n  background: var(--brand);\n  color: white;\n  border: none;\n  padding: 8px 16px;\n  border-radius: 6px;\n}',
  },
  {
    slug: 'animations',
    title: 'Animations',
    summary: 'Bringing elements to life with @keyframes',
    explanation: [
      '@keyframes defines a named sequence of styles at different points (0%, 50%, 100%, or "from"/"to") that an element should move through over time.',
      'The animation property plays a keyframe sequence on an element — animation: bounce 1s ease-in-out infinite runs the "bounce" animation repeatedly.',
      'Animating transform (like scale or translateY) instead of properties such as width or top is smoother, since the browser does not have to recompute the page layout.',
    ],
    example: '@keyframes bounce {\n  0%, 100% { transform: translateY(0); }\n  50% { transform: translateY(-16px); }\n}\n#title {\n  display: inline-block;\n  animation: bounce 1.2s ease-in-out infinite;\n}',
    starterCode: '@keyframes pulse {\n  0% { transform: scale(1); }\n  50% { transform: scale(1.15); }\n  100% { transform: scale(1); }\n}\n#btn {\n  animation: pulse 1.5s ease-in-out infinite;\n}',
  },
  {
    slug: 'specificity-and-cascade',
    title: 'Specificity & the Cascade',
    summary: 'How the browser decides which rule wins when several apply',
    explanation: [
      'When more than one rule targets the same element, the browser has to pick a winner. It does this in two stages: first by specificity (how precise a selector is), and if that ties, by the cascade (later rules in the stylesheet beat earlier ones).',
      'Specificity is roughly a points system — ID selectors (#title) score highest, class and attribute selectors (.highlight) score in the middle, and plain element selectors (p, h1) score lowest. A single #title will always beat a single .highlight, no matter which one is written last.',
      'The !important keyword overrides normal specificity entirely, but it should be used sparingly — once several rules fight with !important, there is no clean way to tell which one wins, and debugging styles becomes painful.',
    ],
    example: 'p {\n  color: slategray;\n}\n.highlight {\n  color: darkorange;\n}\n#title {\n  color: crimson;\n}',
    starterCode: 'h1 {\n  color: teal;\n}\n#title {\n  color: crimson;\n}',
  },
  {
    slug: 'display-property',
    title: 'The display Property',
    summary: 'Controlling how an element takes up space on the page',
    explanation: [
      'Every element has a default display type: block elements (like li) stack on their own line and fill the available width, while inline elements (like a button by default... actually buttons are inline-block) sit alongside text.',
      'display: inline-block lets an element sit in a line like inline content, but still accept a width, height, and padding like a block.',
      'display: none removes an element entirely from the page — it takes up no space at all, as if it were never there.',
    ],
    example: 'li {\n  display: inline-block;\n  background: #ede9fe;\n  padding: 6px 12px;\n  margin-right: 6px;\n}\n#btn {\n  display: block;\n  width: 100%;\n}',
    starterCode: 'li {\n  display: inline;\n  margin-right: 8px;\n}\np {\n  display: none;\n}',
  },
  {
    slug: 'overflow-and-scrolling',
    title: 'Overflow & Scrolling',
    summary: 'Deciding what happens when content is bigger than its box',
    explanation: [
      'When a box has a fixed size but its content is too big to fit, the overflow property decides what happens: visible (default, content spills out), hidden (extra content is clipped away), scroll (always show scrollbars), or auto (scrollbars only when needed).',
      'Giving a container a fixed height and overflow: auto is a common way to create a scrollable panel without letting it grow the whole page.',
    ],
    example: 'div {\n  height: 90px;\n  overflow: auto;\n  border: 2px solid teal;\n  padding: 8px;\n}',
    starterCode: 'div {\n  height: 70px;\n  overflow: hidden;\n  border: 1px solid gray;\n}',
  },
  {
    slug: 'float-and-clear',
    title: 'Float & Clear (Legacy Layout)',
    summary: 'How web pages were laid out before flexbox and grid',
    explanation: [
      'Before flexbox and grid existed, float: left or float: right was used to pull an element to one side and let other content (like text) wrap around it.',
      'Floats caused problems — parent containers could not tell how tall their floated children were, which is why the clear property and various "clearfix" hacks were invented to fix the layout.',
      'Today float is mostly only used for its original purpose, wrapping text around an image, while flexbox and grid handle real layout far more predictably.',
    ],
    example: '#btn {\n  float: left;\n  margin-right: 12px;\n}\np {\n  clear: left;\n}',
    starterCode: '#title {\n  float: left;\n}\np {\n  clear: both;\n}',
  },
  {
    slug: 'backgrounds-in-depth',
    title: 'Backgrounds In Depth',
    summary: 'Gradients, sizing, positioning, and layering backgrounds',
    explanation: [
      'background-image accepts not just image URLs but also CSS gradients like linear-gradient() or radial-gradient(), generated entirely by the browser.',
      'background-size (e.g. cover, contain) controls how the image fills the box, while background-position and background-repeat control where it sits and whether it tiles.',
      'You can even layer several backgrounds on one element by separating them with commas — the first one listed sits on top.',
    ],
    example: 'div {\n  background-image: linear-gradient(135deg, #7c3aed, #06b6d4);\n  background-size: cover;\n  background-position: center;\n  padding: 20px;\n}',
    starterCode: 'div {\n  background-image: radial-gradient(circle, #fbbf24, #ef4444);\n  background-repeat: no-repeat;\n  padding: 16px;\n}',
  },
  {
    slug: 'shadows',
    title: 'Box & Text Shadows',
    summary: 'Adding depth with box-shadow and text-shadow',
    explanation: [
      'box-shadow: offsetX offsetY blurRadius color draws a shadow around an element\'s box — positive offsets push the shadow right and down.',
      'text-shadow uses the same offsetX offsetY blur color pattern but draws the shadow behind the text characters themselves.',
      'Larger blur values create a softer, more spread-out shadow, while a blur of 0 gives a sharp, hard-edged copy.',
    ],
    example: '#btn {\n  box-shadow: 0 4px 10px rgba(0,0,0,0.35);\n}\n#title {\n  text-shadow: 2px 2px 4px rgba(124,58,237,0.6);\n}',
    starterCode: 'button {\n  box-shadow: 2px 2px 6px gray;\n}\nh1 {\n  text-shadow: 1px 1px 2px black;\n}',
  },
  {
    slug: 'border-radius-and-border-image',
    title: 'Border Radius & Border Styles',
    summary: 'Rounding corners and styling borders',
    explanation: [
      'border-radius rounds the corners of a box — a single value rounds all four corners equally, while four values (or per-corner properties) let each corner differ.',
      'Setting border-radius to 50% on a square-ish box turns it into a circle or ellipse, since each corner curves all the way to the centre of its side.',
      'border-style controls the line pattern itself — solid, dashed, dotted, and double are common choices, each giving a very different feel.',
    ],
    example: 'button {\n  border-radius: 20px 4px;\n  border: 3px dashed #7c3aed;\n}\nul {\n  border-radius: 50% / 10%;\n  border: 2px dotted teal;\n}',
    starterCode: 'button {\n  border-radius: 50%;\n  border: 4px double crimson;\n  width: 60px;\n  height: 60px;\n}',
  },
  {
    slug: 'css-functions-calc-clamp-min-max',
    title: 'calc(), clamp(), min() & max()',
    summary: 'Computing sizes on the fly with CSS math functions',
    explanation: [
      'calc() lets you mix units in one calculation, like calc(100% - 40px), so a box can be "full width minus a fixed margin".',
      'clamp(min, preferred, max) picks the preferred value but never lets it go below min or above max — great for font sizes that scale with the viewport but stay readable.',
      'min() and max() pick the smallest or largest of a list of values, which is handy for capping or guaranteeing a minimum size.',
    ],
    example: '#title {\n  font-size: clamp(1.2rem, 4vw, 2.5rem);\n}\np {\n  width: calc(100% - 32px);\n  max-width: min(500px, 90%);\n}',
    starterCode: 'h1 {\n  font-size: clamp(1rem, 5vw, 3rem);\n}\ndiv {\n  width: calc(100% - 20px);\n}',
  },
  {
    slug: 'attribute-selectors',
    title: 'Attribute Selectors',
    summary: 'Targeting elements based on their HTML attributes',
    explanation: [
      'Attribute selectors match elements that have a given attribute, written in square brackets — [id] matches any element with an id attribute, regardless of its value.',
      '[id="title"] matches an exact attribute value, while ^= matches the start of a value, $= matches the end, and *= matches anywhere inside it.',
      'These are handy when you cannot (or do not want to) add a class, but the element already carries a useful attribute like id, type, or href.',
    ],
    example: '[id="title"] {\n  color: #7c3aed;\n}\n[id^="bt"] {\n  background: gold;\n}',
    starterCode: '[id$="tle"] {\n  text-decoration: underline;\n}\n[id*="bt"] {\n  border: 2px solid teal;\n}',
  },
  {
    slug: 'combinators',
    title: 'Combinators',
    summary: 'Connecting selectors to describe relationships between elements',
    explanation: [
      'A space between selectors (ul li) means "any li anywhere inside a ul" — a descendant combinator that matches no matter how deeply nested.',
      'A greater-than sign (ul > li) is the child combinator — it only matches direct children, not grandchildren.',
      'A plus sign (h1 + p) matches an element immediately after another sibling, while a tilde (h1 ~ p) matches any later sibling, not just the very next one.',
    ],
    example: 'div > p {\n  font-style: italic;\n}\nul li {\n  color: slategray;\n}\nh1 + p {\n  font-weight: bold;\n}',
    starterCode: 'div > h1 {\n  color: crimson;\n}\nh1 ~ p {\n  color: teal;\n}',
  },
  {
    slug: 'filters-and-blend-modes',
    title: 'Filters & Blend Modes',
    summary: 'Applying photo-style effects and blending elements together',
    explanation: [
      'The filter property applies visual effects like blur(), brightness(), contrast(), and grayscale() directly to an element, similar to a photo-editing filter.',
      'You can combine several filters in one declaration, e.g. filter: brightness(1.1) blur(1px), and they apply in order.',
      'mix-blend-mode controls how an element\'s colours blend with whatever is behind it, using modes like multiply, screen, or difference — the same concepts used in image editors.',
    ],
    example: '#title {\n  filter: brightness(1.3) contrast(1.1);\n}\nbutton {\n  filter: grayscale(0.8);\n}',
    starterCode: 'h1 {\n  filter: blur(0.5px) brightness(1.2);\n}\np {\n  mix-blend-mode: multiply;\n}',
  },
  {
    slug: 'transforms-2d-and-3d',
    title: '2D & 3D Transforms',
    summary: 'Rotating, scaling, skewing, and moving elements in space',
    explanation: [
      'The transform property changes an element\'s shape and position without affecting the layout around it — translate() moves it, scale() resizes it, rotate() spins it, and skew() slants it.',
      'You can combine multiple transforms in one declaration, like transform: rotate(10deg) scale(1.1), and they apply left to right.',
      'Adding perspective to a parent and rotateY() / rotateX() to a child creates a believable 3D tilt, since the browser simulates depth.',
    ],
    example: '#btn {\n  transform: rotate(-5deg) scale(1.1);\n}\ndiv {\n  perspective: 400px;\n}\n#title {\n  transform: rotateY(15deg);\n}',
    starterCode: 'button {\n  transform: translateX(10px) skew(5deg);\n}\nh1 {\n  transform: scale(1.2);\n}',
  },
  {
    slug: 'flexbox-advanced',
    title: 'Flexbox In Depth',
    summary: 'Fine-tuning how flex items grow, shrink, and order themselves',
    explanation: [
      'flex-grow controls how much extra space an item takes when there is room to spare; flex-shrink controls how much it gives up when space is tight; flex-basis sets its starting size before growing or shrinking.',
      'flex-wrap: wrap lets items move onto a new line instead of squeezing into one row when they no longer fit.',
      'The order property lets you visually reorder flex items without changing the underlying HTML — lower numbers appear first.',
    ],
    example: 'ul {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 8px;\n}\nli {\n  flex-grow: 1;\n  flex-basis: 100px;\n}\nli:first-child {\n  order: 2;\n}',
    starterCode: 'ul {\n  display: flex;\n  gap: 6px;\n}\nli {\n  flex-shrink: 0;\n  flex-basis: 80px;\n}',
  },
  {
    slug: 'grid-advanced',
    title: 'CSS Grid In Depth',
    summary: 'Building responsive grids without writing a single media query',
    explanation: [
      'grid-template-columns: repeat(auto-fit, minmax(100px, 1fr)) creates as many equal columns as will fit, each at least 100px wide, automatically reflowing as the container resizes.',
      'auto-fit collapses empty leftover columns to take up no space, while auto-fill keeps them as empty tracks — auto-fit is usually what you want for a responsive card grid.',
      'grid-auto-flow: column changes the direction items are placed in, filling columns first instead of rows.',
    ],
    example: 'ul {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(80px, 1fr));\n  gap: 10px;\n}\nli {\n  background: #ede9fe;\n  padding: 10px;\n}',
    starterCode: 'ul {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(60px, 1fr));\n  grid-auto-flow: column;\n  gap: 6px;\n}',
  },
  {
    slug: 'object-fit-and-aspect-ratio',
    title: 'object-fit & aspect-ratio',
    summary: 'Controlling proportions and how content fills its box',
    explanation: [
      'aspect-ratio: 16 / 9 locks the relationship between an element\'s width and height, so it keeps the same shape as the box resizes.',
      'object-fit (most often used on images and video) decides how that content fills its box — cover crops it to fill the space, contain shrinks it to fit entirely inside, and fill stretches it.',
      'Combining a fixed aspect-ratio with object-fit: cover is the standard recipe for consistent, non-distorted media thumbnails.',
    ],
    example: 'div {\n  aspect-ratio: 16 / 9;\n  background: #c4b5fd;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}',
    starterCode: 'button {\n  aspect-ratio: 1 / 1;\n  width: 60px;\n}',
  },
  {
    slug: 'scroll-snap',
    title: 'Scroll Snap',
    summary: 'Making scrolling settle neatly on each item',
    explanation: [
      'scroll-snap-type: x mandatory (set on a scrollable container) forces the browser to stop scrolling exactly on a snap point instead of anywhere in between.',
      'scroll-snap-align: start (set on each child, like the li items in a list) tells the browser which point of that child should align with the snap position.',
      'This combination is how horizontally scrolling image carousels and card lists "click" into place as you swipe or drag.',
    ],
    example: 'ul {\n  display: flex;\n  overflow-x: auto;\n  scroll-snap-type: x mandatory;\n  gap: 12px;\n}\nli {\n  scroll-snap-align: start;\n  min-width: 120px;\n  background: #ede9fe;\n}',
    starterCode: 'ul {\n  display: flex;\n  overflow-x: scroll;\n  scroll-snap-type: x mandatory;\n}\nli {\n  scroll-snap-align: center;\n  min-width: 100px;\n}',
  },
  {
    slug: 'print-and-media-types',
    title: 'Print Styles & Media Types',
    summary: 'Writing CSS that only applies when a page is printed',
    explanation: [
      'Media queries do not just react to screen size — @media print applies rules only when the page is being printed or previewed for printing.',
      'A common pattern is hiding interactive elements (like buttons) that make no sense on paper with @media print { button { display: none; } }.',
      '@media screen does the opposite, applying only on screens, which lets you keep interactive styling away from the printed page entirely.',
    ],
    example: '@media print {\n  #btn {\n    display: none;\n  }\n  #title {\n    color: black;\n  }\n}',
    starterCode: '@media print {\n  button {\n    display: none;\n  }\n}\n@media screen {\n  button {\n    background: teal;\n  }\n}',
  },
  {
    slug: 'css-counters',
    title: 'CSS Counters',
    summary: 'Numbering elements automatically with counter-reset and counter-increment',
    explanation: [
      'counter-reset creates (or resets) a named counter on an element, and counter-increment increases it by one each time a matching element appears — commonly used on a list\'s container and its items.',
      'The counter() function reads the current value inside a ::before or ::after pseudo-element\'s content property, letting you build custom numbering without using the browser\'s default list markers.',
      'Counters can be styled freely, since they are just generated text — you can prefix them, suffix them, or combine several counters together.',
    ],
    example: 'ul {\n  counter-reset: item;\n  list-style: none;\n}\nli {\n  counter-increment: item;\n}\nli::before {\n  content: "Step " counter(item) ": ";\n  font-weight: bold;\n  color: #7c3aed;\n}',
    starterCode: 'ul {\n  counter-reset: item;\n}\nli {\n  counter-increment: item;\n}\nli::before {\n  content: counter(item) ") ";\n}',
  },
  {
    slug: 'multi-column-layout',
    title: 'Multi-column Layout',
    summary: 'Flowing text into newspaper-style columns',
    explanation: [
      'column-count splits an element\'s content into that many columns, automatically reflowing text from one column to the next, much like a newspaper.',
      'column-gap controls the space between columns, and column-rule draws a dividing line between them, using the same shorthand pattern as border.',
      'Instead of a fixed count, column-width lets the browser decide how many columns fit, creating as many as it can at roughly that width.',
    ],
    example: 'p {\n  column-count: 2;\n  column-gap: 24px;\n  column-rule: 1px solid #c4b5fd;\n}',
    starterCode: 'p {\n  column-count: 3;\n  column-gap: 16px;\n}',
  },
  {
    slug: 'css-nesting',
    title: 'Native CSS Nesting',
    summary: 'Writing nested selectors directly in plain CSS',
    explanation: [
      'Modern CSS supports nesting rules inside other rules, similar to Sass — a selector written inside another selector\'s braces is automatically combined with its parent as a descendant.',
      'The & symbol explicitly refers to the parent selector, which is useful for nesting pseudo-classes like &:hover or compound selectors without repeating the parent\'s full selector.',
      'Nesting keeps related styles visually grouped together in the stylesheet, which mirrors the structure of the HTML they target.',
    ],
    example: 'div {\n  padding: 16px;\n  & h1 {\n    color: #7c3aed;\n  }\n  & button {\n    background: teal;\n    &:hover {\n      background: darkcyan;\n    }\n  }\n}',
    starterCode: 'div {\n  border: 1px solid #ccc;\n  & p {\n    color: slategray;\n  }\n  & ul {\n    margin-top: 8px;\n  }\n}',
  },
  {
    slug: 'writing-modes-and-direction',
    title: 'Writing Modes & Direction',
    summary: 'Changing the flow direction of text',
    explanation: [
      'writing-mode: vertical-rl flips text to flow vertically, top to bottom, with new lines stacking right to left — used for some vertical scripts and stylistic headlines.',
      'direction: rtl reverses the horizontal reading order of text, which is essential for languages like Arabic and Hebrew that are written right to left.',
      'These properties affect not just text direction but also how related "logical" properties (like margin-inline) resolve to physical sides.',
    ],
    example: 'p {\n  writing-mode: vertical-rl;\n  text-orientation: mixed;\n}',
    starterCode: 'p {\n  direction: rtl;\n  text-align: right;\n}',
  },
  {
    slug: 'clip-path-basics',
    title: 'clip-path Basics',
    summary: 'Cutting an element into a custom visible shape',
    explanation: [
      'clip-path defines a region to display — anything outside that region is simply not rendered, even though the element\'s box is still the same size underneath.',
      'Basic shape functions like circle(), ellipse(), and polygon() describe the visible region using percentages or lengths, with polygon() taking a list of x/y coordinate pairs to form straight-edged shapes.',
      'Because clipping is purely visual, transitions and hover effects can animate clip-path to reveal or morph shapes smoothly.',
    ],
    example: '#btn {\n  clip-path: polygon(50% 0%, 100% 100%, 0% 100%);\n  padding: 16px 24px;\n}',
    starterCode: 'button {\n  clip-path: circle(45% at 50% 50%);\n  padding: 14px 20px;\n}',
  },
  {
    slug: 'css-gradients-advanced',
    title: 'Advanced Gradients',
    summary: 'Building richer backgrounds with multi-stop and radial gradients',
    explanation: [
      'linear-gradient() accepts an optional angle (or "to" direction) followed by any number of colour stops, each of which can include a position like 30% to control exactly where the colour transition happens.',
      'radial-gradient() radiates colour outward from a center point instead of along a line, and accepts the same kind of multi-stop colour list, plus an optional shape and size like circle or closest-side.',
      'Layering several gradients on the same element (separated by commas in background-image) lets you build complex textures entirely without image files.',
    ],
    example: 'div {\n  background-image: linear-gradient(120deg, #7c3aed 0%, #06b6d4 50%, #fbbf24 100%);\n  padding: 24px;\n}',
    starterCode: 'div {\n  background-image: radial-gradient(circle at top left, #fbbf24, #ef4444 60%, #7c3aed);\n  padding: 20px;\n}',
  },
  {
    slug: 'css-units-viewport-and-container',
    title: 'Viewport & Percentage Units',
    summary: 'Sizing elements relative to the browser window',
    explanation: [
      'vw and vh are relative to the viewport\'s width and height — 1vw is 1% of the browser window\'s width, so font sizes or boxes using vw scale automatically as the window resizes.',
      'Percentage units (%) are relative to a property\'s containing context instead — a width of 50% means half of the parent element\'s width, not the screen.',
      'Mixing viewport units with calc() (like calc(2rem + 1vw)) is a common way to get text that scales with the screen but never shrinks below a comfortable minimum.',
    ],
    example: '#title {\n  font-size: 5vw;\n}\ndiv {\n  width: 90vw;\n  max-width: 600px;\n}',
    starterCode: 'p {\n  width: 80%;\n  font-size: 3vw;\n}',
  },
  {
    slug: 'logical-properties',
    title: 'Logical Properties',
    summary: 'Writing direction-aware spacing with inline and block properties',
    explanation: [
      'Logical properties like margin-inline and padding-block describe spacing relative to the text flow rather than fixed physical sides — "inline" follows the horizontal reading direction, and "block" follows the direction new lines stack in.',
      'In a left-to-right, top-to-bottom language, margin-inline behaves like margin-left and margin-right combined, and padding-block behaves like padding-top and padding-bottom combined.',
      'The advantage appears when direction or writing-mode changes — logical properties automatically adapt, while physical properties like margin-left would point the wrong way.',
    ],
    example: 'div {\n  padding-block: 20px;\n  padding-inline: 16px;\n  border: 1px solid #c4b5fd;\n}',
    starterCode: 'p {\n  margin-block: 12px;\n  margin-inline: 24px;\n}',
  },
  {
    slug: 'css-grid-template-areas',
    title: 'Named Grid Template Areas',
    summary: 'Laying out a page by naming regions instead of counting tracks',
    explanation: [
      'grid-template-areas lets you sketch a layout as a grid of names in quotes, where each row of the declaration is a row of the grid and repeated names span multiple cells.',
      'Each child is then assigned to a named region with grid-area: name, matching one of the names used in grid-template-areas — the browser figures out exactly where that puts it.',
      'This makes a layout\'s structure readable at a glance directly in the CSS, since the area names form a visual map of the page.',
    ],
    example: 'div {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  grid-template-areas:\n    "heading heading"\n    "text list";\n  gap: 10px;\n}\n#title {\n  grid-area: heading;\n}\np {\n  grid-area: text;\n}\nul {\n  grid-area: list;\n}',
    starterCode: 'div {\n  display: grid;\n  grid-template-areas:\n    "head"\n    "body"\n    "foot";\n  gap: 8px;\n}\n#title {\n  grid-area: head;\n}\np {\n  grid-area: body;\n}\nul {\n  grid-area: foot;\n}',
  },
  {
    slug: 'sticky-positioning-patterns',
    title: 'Sticky Positioning Patterns',
    summary: 'Keeping headings in view while the page scrolls',
    explanation: [
      'position: sticky behaves like position: relative until the page scrolls to the point where a threshold (like top: 0) would be crossed, then it "sticks" in place as if it were fixed.',
      'A sticky element only sticks within its containing block — once you scroll past the end of that container, the element scrolls away with it rather than staying glued to the viewport forever.',
      'Sticky headings are a common pattern for keeping a section title visible while its related content scrolls underneath.',
    ],
    example: '#title {\n  position: sticky;\n  top: 0;\n  background: white;\n  padding: 8px 0;\n}',
    starterCode: 'h1 {\n  position: sticky;\n  top: 0;\n  z-index: 1;\n}',
  },
  {
    slug: 'css-timing-functions',
    title: 'Transition Timing Functions',
    summary: 'Shaping how a transition accelerates and decelerates over time',
    explanation: [
      'The timing function in a transition (or animation) controls the rate of change over its duration, not just its start and end values — ease-in starts slow and speeds up, ease-out starts fast and slows down.',
      'cubic-bezier(x1, y1, x2, y2) defines a fully custom easing curve using two control points, letting you create effects like a slight overshoot or a snappy bounce.',
      'Choosing the right timing function is what makes an interface feel "natural" rather than mechanical — linear motion often feels robotic compared to eased motion.',
    ],
    example: '#btn {\n  transition: transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);\n}\n#btn:hover {\n  transform: scale(1.1);\n}',
    starterCode: 'button {\n  transition: background 0.3s ease-in-out;\n}\nbutton:hover {\n  background: darkcyan;\n}',
  },
  {
    slug: 'hover-focus-active-states',
    title: 'Hover, Focus & Active States',
    summary: 'Giving interactive elements clear visual feedback',
    explanation: [
      ':hover applies while the pointer is over an element, :focus applies while it has keyboard or click focus (important for accessibility), and :active applies only during the moment it is being pressed.',
      'Combining all three on an interactive element like a button ensures it gives feedback no matter how a person interacts with it — mouse, keyboard, or touch.',
      'focus-visible (a newer relative of :focus) shows a focus ring only when it is actually useful, such as for keyboard users, avoiding an outline appearing on every mouse click.',
    ],
    example: '#btn {\n  background: #4f46e5;\n  color: white;\n  transition: background 0.2s;\n}\n#btn:hover {\n  background: #7c3aed;\n}\n#btn:focus {\n  outline: 3px solid #fbbf24;\n}\n#btn:active {\n  background: #4338ca;\n}',
    starterCode: 'button:hover {\n  background: teal;\n}\nbutton:focus {\n  outline: 2px solid orange;\n}\nbutton:active {\n  transform: scale(0.96);\n}',
  },
  {
    slug: 'css-cursor-and-pointer-events',
    title: 'Cursor & Pointer Events',
    summary: 'Controlling the mouse cursor and whether elements respond to clicks',
    explanation: [
      'The cursor property changes the icon shown when the mouse hovers over an element — common values include pointer (a hand, used for clickable things), not-allowed, and grab.',
      'pointer-events: none makes an element invisible to mouse and touch interaction entirely — clicks pass straight through it to whatever is behind it, even though it still renders.',
      'These two properties are often paired: cursor signals that something is clickable, while pointer-events can disable that interactivity for elements that are temporarily inactive, like a disabled-looking button.',
    ],
    example: '#btn {\n  cursor: pointer;\n}\np {\n  cursor: help;\n}',
    starterCode: 'button {\n  cursor: not-allowed;\n  pointer-events: none;\n  opacity: 0.6;\n}',
  },
  {
    slug: 'css-z-index-stacking-context',
    title: 'z-index & Stacking Contexts',
    summary: 'Understanding which overlapping element appears on top',
    explanation: [
      'z-index only has an effect on elements with a position value other than static (relative, absolute, fixed, or sticky) — a higher z-index appears in front of a lower one when boxes overlap.',
      'A stacking context is a self-contained group formed by certain properties (like position plus z-index, or opacity less than 1) — z-index values are only compared directly against siblings within the same stacking context.',
      'This is why a child with a very high z-index can still appear behind another element entirely, if its parent\'s stacking context itself is positioned below that element.',
    ],
    example: 'div {\n  position: relative;\n}\n#title {\n  position: absolute;\n  top: 10px;\n  left: 10px;\n  z-index: 2;\n}\nbutton {\n  position: relative;\n  top: -20px;\n  z-index: 1;\n}',
    starterCode: 'h1 {\n  position: relative;\n  z-index: 5;\n}\nbutton {\n  position: relative;\n  z-index: 1;\n}',
  },
  {
    slug: 'css-will-change-and-performance',
    title: 'will-change & Animation Performance',
    summary: 'Hinting to the browser which properties are about to animate',
    explanation: [
      'will-change tells the browser in advance that a property (like transform or opacity) is about to change, so it can prepare optimisations — such as promoting the element to its own rendering layer — before the animation starts.',
      'It should be used sparingly and only on elements that are actually about to animate, since creating extra layers for every element wastes memory and can make performance worse, not better.',
      'Animating transform and opacity is already cheap for the browser because they do not trigger layout recalculation, so will-change matters most for properties that would otherwise be expensive to animate.',
    ],
    example: '#btn {\n  will-change: transform;\n  transition: transform 0.3s ease;\n}\n#btn:hover {\n  transform: translateY(-4px);\n}',
    starterCode: 'button {\n  will-change: transform, opacity;\n  transition: transform 0.2s, opacity 0.2s;\n}',
  },
]
