import type { CodingLesson } from '../languages'

export const html: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to HTML',
    summary: 'What HTML is and how a page is structured',
    explanation: [
      'HTML (HyperText Markup Language) is the skeleton of every web page. It uses "tags" — words wrapped in angle brackets like <p> — to describe the different parts of a document: headings, paragraphs, links, images, and more.',
      'Most tags come in pairs: an opening tag <p> and a closing tag </p>, with content in between. The browser reads these tags and renders them as a structured page.',
      'Try editing the code on the right and press Run to see your page update instantly.',
    ],
    example: '<h1>Hello, world!</h1>\n<p>This is a paragraph of text.</p>',
    starterCode: '<h1>My First Heading</h1>\n<p>My first paragraph.</p>',
  },
  {
    slug: 'elements-and-attributes',
    title: 'Elements & Attributes',
    summary: 'Adding extra information to tags with attributes',
    explanation: [
      'An HTML element is the opening tag, its content, and its closing tag together — e.g. <a href="...">link text</a> is one element.',
      'Attributes live inside the opening tag and give extra information: href tells a link where to go, src tells an image where to load from, and alt provides text for screen readers.',
      'Attributes always appear as name="value" pairs, separated by spaces.',
    ],
    example: '<a href="https://example.com">Visit Example</a>\n<img src="https://placekitten.com/200/120" alt="A cute kitten">',
    starterCode: '<a href="https://example.com">Click me</a>\n<img src="https://placekitten.com/150/100" alt="kitten">',
  },
  {
    slug: 'lists',
    title: 'Lists',
    summary: 'Grouping items with ordered and unordered lists',
    explanation: [
      'Use <ul> for an unordered (bulleted) list and <ol> for an ordered (numbered) list. Each item inside goes in its own <li> (list item) tag.',
      'Lists are everywhere on the web — navigation menus, recipes, to-do apps — anywhere you need to group related items.',
    ],
    example: '<ul>\n  <li>Tea</li>\n  <li>Coffee</li>\n</ul>\n<ol>\n  <li>Wake up</li>\n  <li>Code</li>\n</ol>',
    starterCode: '<h2>My favourite languages</h2>\n<ul>\n  <li>Python</li>\n  <li>JavaScript</li>\n</ul>',
  },
  {
    slug: 'tables',
    title: 'Tables',
    summary: 'Displaying tabular data with rows and columns',
    explanation: [
      'A table is built with <table>, rows with <tr> (table row), and cells with <td> (table data) or <th> (table header).',
      'Tables are great for structured data — schedules, price lists, comparisons — but should not be used just for page layout.',
    ],
    example: '<table border="1">\n  <tr><th>Name</th><th>Score</th></tr>\n  <tr><td>Aria</td><td>95</td></tr>\n  <tr><td>Leo</td><td>88</td></tr>\n</table>',
    starterCode: '<table border="1">\n  <tr><th>Day</th><th>Topic</th></tr>\n  <tr><td>Mon</td><td>HTML</td></tr>\n</table>',
  },
  {
    slug: 'forms',
    title: 'Forms & Inputs',
    summary: 'Collecting input from users',
    explanation: [
      'Forms let users enter information. The <form> element wraps inputs like <input>, <textarea>, and <button>.',
      'The type attribute on <input> changes its behaviour — type="text" for plain text, type="email" for emails, type="checkbox" for a tickbox, and so on.',
      'Every input should have a matching <label> so users (and screen readers) know what it is for.',
    ],
    example: '<form>\n  <label>Name: <input type="text" name="name"></label><br>\n  <label>I agree <input type="checkbox"></label><br>\n  <button type="button" onclick="alert(\'Submitted!\')">Submit</button>\n</form>',
    starterCode: '<form>\n  <label>Your name: <input type="text"></label><br>\n  <button type="button" onclick="alert(\'Hi!\')">Say hi</button>\n</form>',
  },
  {
    slug: 'semantic-html',
    title: 'Semantic HTML',
    summary: 'Writing HTML that describes meaning, not just looks',
    explanation: [
      'Semantic tags describe the role of their content: <header>, <nav>, <main>, <article>, <section>, and <footer> instead of generic <div> soup.',
      'Semantic markup helps browsers, search engines, and assistive technology understand your page — and makes your code far easier to read.',
    ],
    example: '<header><h1>My Site</h1></header>\n<nav><a href="#">Home</a> | <a href="#">About</a></nav>\n<main>\n  <article>\n    <h2>My First Post</h2>\n    <p>Semantic HTML rocks!</p>\n  </article>\n</main>\n<footer><p>&copy; 2026 My Site</p></footer>',
    starterCode: '<header><h1>My Page</h1></header>\n<main>\n  <article>\n    <h2>Hello</h2>\n    <p>This is semantic HTML.</p>\n  </article>\n</main>',
  },
  {
    slug: 'images-and-media',
    title: 'Images & Media',
    summary: 'Embedding pictures, video, and audio in a page',
    explanation: [
      'The <img> tag embeds a picture using its src attribute, and should always include alt text describing the image for screen readers and broken-image fallbacks.',
      'Wrap an image in <figure> and add a <figcaption> when you want to show a caption alongside it — the two are linked semantically as one unit.',
      '<video> and <audio> embed media players directly in the page; add the controls attribute so the user can play, pause, and adjust volume.',
    ],
    example: '<figure>\n  <img src="https://placekitten.com/220/140" alt="A sleepy kitten curled up on a blanket">\n  <figcaption>Our office cat, napping on the job.</figcaption>\n</figure>\n<video controls width="240">\n  <source src="https://example.com/clip.mp4" type="video/mp4">\n  Your browser does not support video.\n</video>',
    starterCode: '<figure>\n  <img src="https://placekitten.com/180/120" alt="A small kitten">\n  <figcaption>Caption goes here.</figcaption>\n</figure>\n<audio controls>\n  <source src="https://example.com/sound.mp3" type="audio/mpeg">\n</audio>',
  },
  {
    slug: 'links-and-navigation',
    title: 'Links & Navigation',
    summary: 'Connecting pages with anchor tags and URLs',
    explanation: [
      'The <a> tag creates a hyperlink; its href attribute points to the destination — a full "absolute" URL like https://example.com, or a "relative" path like /about that stays on the same site.',
      'The target="_blank" attribute opens a link in a new browser tab — pair it with rel="noopener" for security.',
      'A group of links wrapped in a <nav> element forms a navigation menu, often built as a list of links with <ul> and <li>.',
    ],
    example: '<nav>\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/about">About</a></li>\n    <li><a href="https://example.com" target="_blank" rel="noopener">External Site</a></li>\n  </ul>\n</nav>\n<p>Jump to the <a href="#bottom">bottom</a> of this page.</p>',
    starterCode: '<nav>\n  <a href="/">Home</a> |\n  <a href="/blog">Blog</a> |\n  <a href="https://example.com" target="_blank">Visit Example</a>\n</nav>',
  },
  {
    slug: 'div-and-span',
    title: 'Div & Span',
    summary: 'Generic containers for grouping and styling content',
    explanation: [
      '<div> is a generic block-level container — it starts on its own line and stretches to fill its parent — used to group larger chunks of content for layout or styling.',
      '<span> is a generic inline container — it sits in the flow of text without breaking the line — used to style or target a small piece of text.',
      'Reach for a semantic tag like <article> or <nav> first; use <div> and <span> when no more meaningful element fits.',
    ],
    example: '<div style="border: 2px solid #7c3aed; padding: 10px;">\n  <p>This whole block is wrapped in a <span style="color: crimson; font-weight: bold;">div</span>, and this word is wrapped in a <span style="color: teal;">span</span>.</p>\n</div>',
    starterCode: '<div style="background: #eef; padding: 12px;">\n  <p>Some text with a <span style="color: purple;">highlighted word</span> inside.</p>\n</div>',
  },
  {
    slug: 'input-types',
    title: 'Input Types',
    summary: 'Different kinds of fields for collecting different data',
    explanation: [
      'The type attribute on <input> changes both how it looks and how it behaves: type="email" validates an email shape, type="number" only accepts digits, and type="date" shows a date picker.',
      'type="radio" lets the user choose one option from a group sharing the same name; type="range" shows a slider; type="checkbox" is an on/off toggle.',
      'Choosing the right input type gives users better keyboards on mobile and built-in validation for free.',
    ],
    example: '<form>\n  <label>Email: <input type="email" placeholder="you@example.com"></label><br>\n  <label>Age: <input type="number" min="0" max="120"></label><br>\n  <label>Birthday: <input type="date"></label><br>\n  <label>Volume: <input type="range" min="0" max="100"></label><br>\n  <label><input type="radio" name="plan" value="free"> Free</label>\n  <label><input type="radio" name="plan" value="pro"> Pro</label>\n</form>',
    starterCode: '<form>\n  <label>Name: <input type="text"></label><br>\n  <label>Score: <input type="number" min="0" max="10"></label><br>\n  <label>Pick a colour:\n    <input type="radio" name="colour" value="red"> Red\n    <input type="radio" name="colour" value="blue"> Blue\n  </label>\n</form>',
  },
  {
    slug: 'comments-and-document-structure',
    title: 'Comments & Document Structure',
    summary: 'How a full HTML document is put together',
    explanation: [
      'A real HTML page starts with <!DOCTYPE html> to tell the browser which version of HTML to use, then wraps everything in an <html> element containing <head> and <body>.',
      'The <head> holds metadata (like the page <title>) that is not shown directly on the page; the <body> holds everything the visitor actually sees.',
      'You can leave notes for yourself or other developers using <!-- comments like this --> — the browser ignores anything between the markers.',
    ],
    example: '<!DOCTYPE html>\n<html>\n  <head>\n    <title>My Page</title>\n  </head>\n  <body>\n    <!-- This is the visible content -->\n    <h1>Welcome!</h1>\n    <p>This paragraph is shown to visitors.</p>\n    <!-- TODO: add a footer here -->\n  </body>\n</html>',
    starterCode: '<!DOCTYPE html>\n<html>\n  <head>\n    <title>Practice Page</title>\n  </head>\n  <body>\n    <!-- Try adding more elements below -->\n    <h1>Hello!</h1>\n  </body>\n</html>',
  },
  {
    slug: 'accessibility-basics',
    title: 'Accessibility Basics',
    summary: 'Writing markup that works for everyone',
    explanation: [
      'Always give images meaningful alt text — it is read aloud by screen readers and shown if the image fails to load; decorative images can use alt="".',
      'Connect every form field to a <label> (either by wrapping it or using for/id) so assistive technology announces what the field is for; aria-label can name an element when no visible text is possible.',
      'Use heading tags <h1> through <h6> in order, without skipping levels, so the page has a clear, navigable outline for screen reader users.',
    ],
    example: '<h1>Trip Planner</h1>\n<h2>Destinations</h2>\n<img src="https://placekitten.com/200/120" alt="A scenic mountain lake at sunrise">\n<form>\n  <label for="dest">Where to?</label>\n  <input id="dest" type="text" name="destination">\n  <button aria-label="Search destinations">🔍</button>\n</form>',
    starterCode: '<h1>My Page</h1>\n<img src="https://placekitten.com/180/120" alt="A kitten playing with yarn">\n<label for="name">Your name</label>\n<input id="name" type="text">',
  },
]
