import type { CodingLesson } from '../languages'

export const html: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to HTML',
    summary: 'What HTML is and how a page is structured',
    explanation: [
      'HTML (HyperText Markup Language) is the skeleton of every web page. It uses "tags" — words wrapped in angle brackets like <p> — to describe the different parts of a document: headings, paragraphs, links, images, and more.',
      'Most tags come in pairs: an opening tag <p> and a closing tag </p>, with content in between. The browser reads these tags and renders them as a structured page.',
      'Try editing the code on the right and press Run to see your page update instantly.',
    ],
    example: '<h1>Hello, world!</h1>\n<p>This is a paragraph of text.</p>',
    starterCode: '<h1>My First Heading</h1>\n<p>My first paragraph.</p>',
  },
  {
    slug: 'elements-and-attributes',
    title: 'Elements & Attributes',
    summary: 'Adding extra information to tags with attributes',
    explanation: [
      'An HTML element is the opening tag, its content, and its closing tag together — e.g. <a href="...">link text</a> is one element.',
      'Attributes live inside the opening tag and give extra information: href tells a link where to go, src tells an image where to load from, and alt provides text for screen readers.',
      'Attributes always appear as name="value" pairs, separated by spaces.',
    ],
    example: '<a href="https://example.com">Visit Example</a>\n<img src="https://placekitten.com/200/120" alt="A cute kitten">',
    starterCode: '<a href="https://example.com">Click me</a>\n<img src="https://placekitten.com/150/100" alt="kitten">',
  },
  {
    slug: 'lists',
    title: 'Lists',
    summary: 'Grouping items with ordered and unordered lists',
    explanation: [
      'Use <ul> for an unordered (bulleted) list and <ol> for an ordered (numbered) list. Each item inside goes in its own <li> (list item) tag.',
      'Lists are everywhere on the web — navigation menus, recipes, to-do apps — anywhere you need to group related items.',
    ],
    example: '<ul>\n  <li>Tea</li>\n  <li>Coffee</li>\n</ul>\n<ol>\n  <li>Wake up</li>\n  <li>Code</li>\n</ol>',
    starterCode: '<h2>My favourite languages</h2>\n<ul>\n  <li>Python</li>\n  <li>JavaScript</li>\n</ul>',
  },
  {
    slug: 'tables',
    title: 'Tables',
    summary: 'Displaying tabular data with rows and columns',
    explanation: [
      'A table is built with <table>, rows with <tr> (table row), and cells with <td> (table data) or <th> (table header).',
      'Tables are great for structured data — schedules, price lists, comparisons — but should not be used just for page layout.',
    ],
    example: '<table border="1">\n  <tr><th>Name</th><th>Score</th></tr>\n  <tr><td>Aria</td><td>95</td></tr>\n  <tr><td>Leo</td><td>88</td></tr>\n</table>',
    starterCode: '<table border="1">\n  <tr><th>Day</th><th>Topic</th></tr>\n  <tr><td>Mon</td><td>HTML</td></tr>\n</table>',
  },
  {
    slug: 'forms',
    title: 'Forms & Inputs',
    summary: 'Collecting input from users',
    explanation: [
      'Forms let users enter information. The <form> element wraps inputs like <input>, <textarea>, and <button>.',
      'The type attribute on <input> changes its behaviour — type="text" for plain text, type="email" for emails, type="checkbox" for a tickbox, and so on.',
      'Every input should have a matching <label> so users (and screen readers) know what it is for.',
    ],
    example: '<form>\n  <label>Name: <input type="text" name="name"></label><br>\n  <label>I agree <input type="checkbox"></label><br>\n  <button type="button" onclick="alert(\'Submitted!\')">Submit</button>\n</form>',
    starterCode: '<form>\n  <label>Your name: <input type="text"></label><br>\n  <button type="button" onclick="alert(\'Hi!\')">Say hi</button>\n</form>',
  },
  {
    slug: 'semantic-html',
    title: 'Semantic HTML',
    summary: 'Writing HTML that describes meaning, not just looks',
    explanation: [
      'Semantic tags describe the role of their content: <header>, <nav>, <main>, <article>, <section>, and <footer> instead of generic <div> soup.',
      'Semantic markup helps browsers, search engines, and assistive technology understand your page — and makes your code far easier to read.',
    ],
    example: '<header><h1>My Site</h1></header>\n<nav><a href="#">Home</a> | <a href="#">About</a></nav>\n<main>\n  <article>\n    <h2>My First Post</h2>\n    <p>Semantic HTML rocks!</p>\n  </article>\n</main>\n<footer><p>&copy; 2026 My Site</p></footer>',
    starterCode: '<header><h1>My Page</h1></header>\n<main>\n  <article>\n    <h2>Hello</h2>\n    <p>This is semantic HTML.</p>\n  </article>\n</main>',
  },
  {
    slug: 'images-and-media',
    title: 'Images & Media',
    summary: 'Embedding pictures, video, and audio in a page',
    explanation: [
      'The <img> tag embeds a picture using its src attribute, and should always include alt text describing the image for screen readers and broken-image fallbacks.',
      'Wrap an image in <figure> and add a <figcaption> when you want to show a caption alongside it — the two are linked semantically as one unit.',
      '<video> and <audio> embed media players directly in the page; add the controls attribute so the user can play, pause, and adjust volume.',
    ],
    example: '<figure>\n  <img src="https://placekitten.com/220/140" alt="A sleepy kitten curled up on a blanket">\n  <figcaption>Our office cat, napping on the job.</figcaption>\n</figure>\n<video controls width="240">\n  <source src="https://example.com/clip.mp4" type="video/mp4">\n  Your browser does not support video.\n</video>',
    starterCode: '<figure>\n  <img src="https://placekitten.com/180/120" alt="A small kitten">\n  <figcaption>Caption goes here.</figcaption>\n</figure>\n<audio controls>\n  <source src="https://example.com/sound.mp3" type="audio/mpeg">\n</audio>',
  },
  {
    slug: 'links-and-navigation',
    title: 'Links & Navigation',
    summary: 'Connecting pages with anchor tags and URLs',
    explanation: [
      'The <a> tag creates a hyperlink; its href attribute points to the destination — a full "absolute" URL like https://example.com, or a "relative" path like /about that stays on the same site.',
      'The target="_blank" attribute opens a link in a new browser tab — pair it with rel="noopener" for security.',
      'A group of links wrapped in a <nav> element forms a navigation menu, often built as a list of links with <ul> and <li>.',
    ],
    example: '<nav>\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/about">About</a></li>\n    <li><a href="https://example.com" target="_blank" rel="noopener">External Site</a></li>\n  </ul>\n</nav>\n<p>Jump to the <a href="#bottom">bottom</a> of this page.</p>',
    starterCode: '<nav>\n  <a href="/">Home</a> |\n  <a href="/blog">Blog</a> |\n  <a href="https://example.com" target="_blank">Visit Example</a>\n</nav>',
  },
  {
    slug: 'div-and-span',
    title: 'Div & Span',
    summary: 'Generic containers for grouping and styling content',
    explanation: [
      '<div> is a generic block-level container — it starts on its own line and stretches to fill its parent — used to group larger chunks of content for layout or styling.',
      '<span> is a generic inline container — it sits in the flow of text without breaking the line — used to style or target a small piece of text.',
      'Reach for a semantic tag like <article> or <nav> first; use <div> and <span> when no more meaningful element fits.',
    ],
    example: '<div style="border: 2px solid #7c3aed; padding: 10px;">\n  <p>This whole block is wrapped in a <span style="color: crimson; font-weight: bold;">div</span>, and this word is wrapped in a <span style="color: teal;">span</span>.</p>\n</div>',
    starterCode: '<div style="background: #eef; padding: 12px;">\n  <p>Some text with a <span style="color: purple;">highlighted word</span> inside.</p>\n</div>',
  },
  {
    slug: 'input-types',
    title: 'Input Types',
    summary: 'Different kinds of fields for collecting different data',
    explanation: [
      'The type attribute on <input> changes both how it looks and how it behaves: type="email" validates an email shape, type="number" only accepts digits, and type="date" shows a date picker.',
      'type="radio" lets the user choose one option from a group sharing the same name; type="range" shows a slider; type="checkbox" is an on/off toggle.',
      'Choosing the right input type gives users better keyboards on mobile and built-in validation for free.',
    ],
    example: '<form>\n  <label>Email: <input type="email" placeholder="you@example.com"></label><br>\n  <label>Age: <input type="number" min="0" max="120"></label><br>\n  <label>Birthday: <input type="date"></label><br>\n  <label>Volume: <input type="range" min="0" max="100"></label><br>\n  <label><input type="radio" name="plan" value="free"> Free</label>\n  <label><input type="radio" name="plan" value="pro"> Pro</label>\n</form>',
    starterCode: '<form>\n  <label>Name: <input type="text"></label><br>\n  <label>Score: <input type="number" min="0" max="10"></label><br>\n  <label>Pick a colour:\n    <input type="radio" name="colour" value="red"> Red\n    <input type="radio" name="colour" value="blue"> Blue\n  </label>\n</form>',
  },
  {
    slug: 'comments-and-document-structure',
    title: 'Comments & Document Structure',
    summary: 'How a full HTML document is put together',
    explanation: [
      'A real HTML page starts with <!DOCTYPE html> to tell the browser which version of HTML to use, then wraps everything in an <html> element containing <head> and <body>.',
      'The <head> holds metadata (like the page <title>) that is not shown directly on the page; the <body> holds everything the visitor actually sees.',
      'You can leave notes for yourself or other developers using <!-- comments like this --> — the browser ignores anything between the markers.',
    ],
    example: '<!DOCTYPE html>\n<html>\n  <head>\n    <title>My Page</title>\n  </head>\n  <body>\n    <!-- This is the visible content -->\n    <h1>Welcome!</h1>\n    <p>This paragraph is shown to visitors.</p>\n    <!-- TODO: add a footer here -->\n  </body>\n</html>',
    starterCode: '<!DOCTYPE html>\n<html>\n  <head>\n    <title>Practice Page</title>\n  </head>\n  <body>\n    <!-- Try adding more elements below -->\n    <h1>Hello!</h1>\n  </body>\n</html>',
  },
  {
    slug: 'accessibility-basics',
    title: 'Accessibility Basics',
    summary: 'Writing markup that works for everyone',
    explanation: [
      'Always give images meaningful alt text — it is read aloud by screen readers and shown if the image fails to load; decorative images can use alt="".',
      'Connect every form field to a <label> (either by wrapping it or using for/id) so assistive technology announces what the field is for; aria-label can name an element when no visible text is possible.',
      'Use heading tags <h1> through <h6> in order, without skipping levels, so the page has a clear, navigable outline for screen reader users.',
    ],
    example: '<h1>Trip Planner</h1>\n<h2>Destinations</h2>\n<img src="https://placekitten.com/200/120" alt="A scenic mountain lake at sunrise">\n<form>\n  <label for="dest">Where to?</label>\n  <input id="dest" type="text" name="destination">\n  <button aria-label="Search destinations">🔍</button>\n</form>',
    starterCode: '<h1>My Page</h1>\n<img src="https://placekitten.com/180/120" alt="A kitten playing with yarn">\n<label for="name">Your name</label>\n<input id="name" type="text">',
  },
  {
    slug: 'form-validation',
    title: 'Form Validation',
    summary: 'Letting the browser check input before it is submitted',
    explanation: [
      'HTML can validate form fields for you, with no JavaScript required. Add the required attribute to make a field mandatory, and the browser will block submission and show a hint if it is left empty.',
      'The pattern attribute checks a text field against a regular expression — handy for things like a postcode or product code — while minlength/maxlength limit how many characters can be typed, and min/max limit the allowed range on a number input.',
      'By default the browser shows a generic message when a field is invalid. Add a title attribute with a short description of what is expected, and the browser uses it as a custom hint in that validation popup.',
    ],
    example: '<form>\n  <label>Username (required): <input type="text" name="username" required></label><br>\n  <label>Product code: <input type="text" name="code" pattern="[A-Z]{3}-[0-9]{4}" title="Format: ABC-1234"></label><br>\n  <label>Age: <input type="number" name="age" min="18" max="99"></label><br>\n  <button type="submit">Submit</button>\n</form>',
    starterCode: '<form>\n  <label>Email (required): <input type="email" name="email" required></label><br>\n  <label>Zip code: <input type="text" pattern="[0-9]{5}" title="Five digits, e.g. 90210"></label><br>\n  <button type="submit">Submit</button>\n</form>',
  },
  {
    slug: 'details-and-meta',
    title: 'Details, Summary & Meta Tags',
    summary: 'A built-in collapsible widget, plus useful tags hidden in <head>',
    explanation: [
      'The <details> element is a disclosure widget that shows or hides extra content — and it works without a single line of JavaScript. Its first child should be a <summary> element, which acts as the always-visible label the user clicks to expand or collapse the rest.',
      'Add the open attribute to <details> to have it start out expanded instead of collapsed.',
      'Back in the comments-and-document-structure lesson, you saw that <head> holds metadata rather than visible content. Three common meta tags live there: <meta charset="UTF-8"> tells the browser which character encoding the page uses, <meta name="viewport" content="width=device-width, initial-scale=1"> makes a page render sensibly on mobile screens, and <meta name="description" content="..."> gives search engines a short summary to show in results.',
    ],
    example: '<!-- A real page would also have this in its <head>: -->\n<!-- <meta charset="UTF-8"> -->\n<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->\n<!-- <meta name="description" content="A friendly guide to HTML basics"> -->\n\n<h2>FAQ</h2>\n<details>\n  <summary>What is HTML?</summary>\n  <p>HTML is the markup language used to structure content on the web.</p>\n</details>\n<details open>\n  <summary>Do I need JavaScript for this widget?</summary>\n  <p>Nope — the browser handles the expand and collapse for you.</p>\n</details>',
    starterCode: '<details>\n  <summary>Click to reveal</summary>\n  <p>Surprise! This content was hidden until you clicked.</p>\n</details>',
  },
  {
    slug: 'text-formatting-tags',
    title: 'Text Formatting Tags',
    summary: 'Adding emphasis, highlights, and small touches to text',
    explanation: [
      '<strong> marks text as important (shown bold) and <em> marks text as emphasised (shown italic) — both carry meaning, unlike plain styling.',
      '<mark> highlights text like a highlighter pen, <small> shrinks text for fine print, and <sub>/<sup> drop text below or above the line for things like footnotes and exponents.',
      '<br> inserts a single line break and <hr> draws a horizontal rule to separate content — neither one wraps any text.',
    ],
    example: '<p><strong>Warning:</strong> this recipe is <em>extremely</em> spicy.</p>\n<p>Don\'t forget to <mark>bring snacks</mark>.</p>\n<p><small>Terms and conditions apply.</small></p>\n<p>Water is H<sub>2</sub>O and E = mc<sup>2</sup>.</p>\n<p>First line<br>Second line</p>\n<hr>\n<p>Content after the rule.</p>',
    starterCode: '<p><strong>Bold</strong> and <em>italic</em> text.</p>\n<p><mark>Highlighted</mark> and <small>small</small> text.</p>\n<hr>\n<p>x<sup>2</sup> + y<sub>1</sub></p>',
  },
  {
    slug: 'block-and-inline-elements',
    title: 'Block & Inline Elements',
    summary: 'Why some elements stack and others sit side by side',
    explanation: [
      'Block-level elements like <div>, <p>, and <h1> always start on a new line and stretch to fill the available width, stacking on top of each other.',
      'Inline elements like <span> and <a> flow within a line of text, only taking up as much width as their content needs, and sit next to other inline content.',
      'Knowing the difference helps you predict your page layout before you even add any CSS.',
    ],
    example: '<div style="background: #fee2e2; padding: 8px;">I am a div (block) — I take the full width.</div>\n<div style="background: #dbeafe; padding: 8px;">I am another div — I start on a new line below the first.</div>\n<p>Some text with <span style="background: #fef08a;">a span (inline)</span> sitting right in the middle of the sentence, not breaking the line.</p>',
    starterCode: '<div style="background: #e0f2fe; padding: 6px;">Block element 1</div>\n<div style="background: #fce7f3; padding: 6px;">Block element 2</div>\n<p>Inline: <span style="color: red;">red span</span> and <span style="color: green;">green span</span> on the same line.</p>',
  },
  {
    slug: 'inline-svg-basics',
    title: 'Inline SVG Basics',
    summary: 'Drawing vector shapes directly in your HTML',
    explanation: [
      'SVG (Scalable Vector Graphics) can be written directly inside HTML using the <svg> tag — no separate image file needed, and shapes stay crisp at any size.',
      'Basic shapes include <circle> (cx, cy, r), <rect> (x, y, width, height), and <line> (x1, y1, x2, y2) — each takes attributes describing its position and size.',
      'The fill attribute sets the inside colour and stroke sets the outline colour of a shape.',
    ],
    example: '<svg width="220" height="120">\n  <circle cx="50" cy="60" r="40" fill="dodgerblue" />\n  <rect x="110" y="20" width="80" height="80" fill="orange" stroke="black" stroke-width="2" />\n  <line x1="0" y1="0" x2="220" y2="120" stroke="gray" stroke-width="2" />\n</svg>',
    starterCode: '<svg width="160" height="100">\n  <circle cx="40" cy="50" r="30" fill="seagreen" />\n  <rect x="90" y="20" width="60" height="60" fill="crimson" />\n</svg>',
  },
  {
    slug: 'canvas-basics',
    title: 'Canvas Basics',
    summary: 'Drawing pixels with JavaScript on a blank canvas',
    explanation: [
      'The <canvas> element is a blank rectangle that JavaScript can draw on pixel by pixel — unlike SVG, what you draw is not made of individual tags you can inspect afterwards.',
      'Grab a "drawing context" with canvas.getContext(\'2d\'), then use methods like fillRect, arc, and fillStyle to draw shapes.',
      'Canvas is great for games, charts, and anything that needs to redraw quickly.',
    ],
    example: '<canvas id="myCanvas" width="220" height="120" style="border: 1px solid #999;"></canvas>\n<script>\n  var ctx = document.getElementById(\'myCanvas\').getContext(\'2d\');\n  ctx.fillStyle = \'tomato\';\n  ctx.fillRect(10, 10, 80, 60);\n  ctx.beginPath();\n  ctx.arc(160, 60, 40, 0, Math.PI * 2);\n  ctx.fillStyle = \'royalblue\';\n  ctx.fill();\n</script>',
    starterCode: '<canvas id="c" width="160" height="100" style="border: 1px solid #999;"></canvas>\n<script>\n  var ctx = document.getElementById(\'c\').getContext(\'2d\');\n  ctx.fillStyle = \'purple\';\n  ctx.fillRect(20, 20, 100, 60);\n</script>',
  },
  {
    slug: 'select-and-textarea',
    title: 'Select & Textarea',
    summary: 'Dropdown menus and multi-line text boxes',
    explanation: [
      'The <select> element creates a dropdown menu, with each choice defined by an <option> — the value attribute is what gets submitted, while the text between the tags is what the user sees.',
      'Group related options together with <optgroup label="...">  to organise a long dropdown into labeled sections.',
      '<textarea> is like a multi-line <input> for longer text such as comments or messages; its rows and cols attributes control the visible size.',
    ],
    example: '<label>Favourite fruit:\n  <select>\n    <optgroup label="Citrus">\n      <option value="orange">Orange</option>\n      <option value="lemon">Lemon</option>\n    </optgroup>\n    <optgroup label="Tropical">\n      <option value="mango">Mango</option>\n      <option value="pineapple">Pineapple</option>\n    </optgroup>\n  </select>\n</label>\n<br><br>\n<label>Comments:<br>\n  <textarea rows="4" cols="30" placeholder="Type your thoughts..."></textarea>\n</label>',
    starterCode: '<label>Choose a pet:\n  <select>\n    <option value="dog">Dog</option>\n    <option value="cat">Cat</option>\n    <option value="fish">Fish</option>\n  </select>\n</label>\n<br><br>\n<textarea rows="3" cols="25" placeholder="Write something..."></textarea>',
  },
  {
    slug: 'fieldset-and-legend',
    title: 'Fieldset & Legend',
    summary: 'Grouping related form fields together',
    explanation: [
      '<fieldset> draws a box around a group of related form controls, visually showing they belong together — like all the fields in a "Shipping Address" section.',
      'The first child of a <fieldset> should be a <legend>, which provides a caption describing what the group is for, both visually and for screen readers.',
      'Grouping fields this way makes long forms much easier to scan and understand.',
    ],
    example: '<form>\n  <fieldset>\n    <legend>Contact Details</legend>\n    <label>Name: <input type="text"></label><br>\n    <label>Email: <input type="email"></label>\n  </fieldset>\n  <fieldset>\n    <legend>Preferences</legend>\n    <label><input type="checkbox"> Subscribe to newsletter</label>\n  </fieldset>\n</form>',
    starterCode: '<form>\n  <fieldset>\n    <legend>Pizza Order</legend>\n    <label>Size: <input type="text"></label><br>\n    <label>Toppings: <input type="text"></label>\n  </fieldset>\n</form>',
  },
  {
    slug: 'html-entities',
    title: 'HTML Entities',
    summary: 'Typing special characters that HTML would otherwise misread',
    explanation: [
      'Because < and > are used to write tags, you cannot type them directly as text — instead use the entities &lt; and &gt;, which the browser turns back into < and >.',
      '&amp; stands in for an ampersand (&), since a raw & can sometimes be misread as the start of another entity.',
      '&copy; produces the © symbol, and &nbsp; inserts a "non-breaking space" — a space that won\'t collapse or let the browser wrap a line at that point.',
    ],
    example: '<p>To write a paragraph tag, type &lt;p&gt;text&lt;/p&gt;.</p>\n<p>Tom &amp; Jerry is a classic cartoon.</p>\n<p>&copy; 2026 My Company. All rights reserved.</p>\n<p>10&nbsp;km is about 6&nbsp;miles (the&nbsp;nbsp; keeps each pair together on one line).</p>',
    starterCode: '<p>Use &lt;strong&gt; for bold text.</p>\n<p>Salt &amp; pepper.</p>\n<p>&copy; My Site 2026</p>',
  },
  {
    slug: 'global-attributes',
    title: 'Global Attributes',
    summary: 'Attributes that work on almost any HTML element',
    explanation: [
      'Global attributes can be added to nearly any tag: id gives an element a unique name, and class lets you group multiple elements to style or select together.',
      'title shows a small tooltip on hover, and tabindex controls the order elements are focused when a user presses Tab on their keyboard.',
      'hidden hides an element completely, while contenteditable="true" lets the user click in and edit that element\'s text right in the page.',
    ],
    example: '<p id="intro" title="This is the intro paragraph">Hover over me to see a tooltip.</p>\n<p class="note">I have a class for styling.</p>\n<p hidden>You will not see this paragraph.</p>\n<p contenteditable="true" style="border: 1px dashed #999; padding: 6px;">Click here and try editing this text!</p>\n<button tabindex="1">First tab stop</button>\n<button tabindex="2">Second tab stop</button>',
    starterCode: '<p id="greeting" title="Hello tooltip">Hover for a tooltip.</p>\n<p contenteditable="true" style="border: 1px dashed #999;">Edit me!</p>\n<p hidden>You cannot see this.</p>',
  },
  {
    slug: 'data-attributes',
    title: 'Data Attributes',
    summary: 'Storing custom data right inside your HTML',
    explanation: [
      'Any attribute starting with data- is a custom "data attribute" — a safe way to attach your own information to an element, like data-user-id="42" or data-role="admin".',
      'JavaScript can read these values through the element\'s dataset property: an attribute named data-user-id becomes element.dataset.userId (notice it becomes camelCase).',
      'Data attributes are handy for storing information a script needs without it being visible as page text.',
    ],
    example: '<button id="card" data-user-id="42" data-role="admin">View Profile</button>\n<script>\n  var card = document.getElementById(\'card\');\n  card.addEventListener(\'click\', function () {\n    alert(\'User ID: \' + card.dataset.userId + \', Role: \' + card.dataset.role);\n  });\n</script>',
    starterCode: '<button id="item" data-price="25" data-name="Widget">Buy</button>\n<script>\n  var item = document.getElementById(\'item\');\n  item.addEventListener(\'click\', function () {\n    alert(item.dataset.name + \' costs $\' + item.dataset.price);\n  });\n</script>',
  },
  {
    slug: 'picture-and-responsive-images',
    title: 'Picture & Responsive Images',
    summary: 'Serving the right image for each screen size',
    explanation: [
      'The <picture> element lets you offer several <source> options, and the browser picks whichever one matches its rules (like screen width) — falling back to a regular <img> if none match.',
      'On a single <img>, the srcset attribute lists multiple image files at different sizes, and sizes tells the browser how wide the image will be displayed, so it can pick the most efficient file.',
      'This avoids forcing phones to download huge desktop-sized images.',
    ],
    example: '<picture>\n  <source media="(min-width: 600px)" srcset="https://placekitten.com/400/200">\n  <source media="(max-width: 599px)" srcset="https://placekitten.com/200/100">\n  <img src="https://placekitten.com/300/150" alt="A kitten, sized for your screen">\n</picture>\n<p>Below: srcset with a sizes hint</p>\n<img src="https://placekitten.com/300/150" srcset="https://placekitten.com/150/75 150w, https://placekitten.com/300/150 300w, https://placekitten.com/600/300 600w" sizes="(max-width: 500px) 150px, 300px" alt="A responsive kitten">',
    starterCode: '<picture>\n  <source media="(min-width: 600px)" srcset="https://placekitten.com/300/150">\n  <img src="https://placekitten.com/150/75" alt="A kitten">\n</picture>',
  },
  {
    slug: 'video-and-audio-advanced',
    title: 'Video & Audio In Depth',
    summary: 'Posters, autoplay caveats, and fallback sources',
    explanation: [
      'The poster attribute on <video> sets an image shown before the video plays — handy so the player isn\'t a blank black box.',
      'Browsers block autoplay with sound for almost all videos; autoplay typically only works when combined with muted (and often loop), so silent looping background videos are the common pattern.',
      'You can list several <source> tags with different file formats inside one <video> or <audio> — the browser uses the first format it supports and ignores the rest.',
    ],
    example: '<video controls width="240" poster="https://placekitten.com/240/135" autoplay muted loop>\n  <source src="https://example.com/clip.webm" type="video/webm">\n  <source src="https://example.com/clip.mp4" type="video/mp4">\n  Your browser does not support video.\n</video>\n<audio controls>\n  <source src="https://example.com/sound.ogg" type="audio/ogg">\n  <source src="https://example.com/sound.mp3" type="audio/mpeg">\n  Your browser does not support audio.\n</audio>',
    starterCode: '<video controls width="200" poster="https://placekitten.com/200/120">\n  <source src="https://example.com/clip.mp4" type="video/mp4">\n  Your browser does not support video.\n</video>',
  },
  {
    slug: 'iframes',
    title: 'Iframes',
    summary: 'Embedding another document inside your page',
    explanation: [
      'An <iframe> embeds a whole separate HTML document inside a rectangle on your page — commonly used for maps, videos, or embedded widgets from other sites.',
      'Instead of pointing to an external URL with src, the srcdoc attribute lets you write the embedded page\'s HTML directly inline, which is great for self-contained demos.',
      'Always set width and height (or style them) so the embedded frame has a sensible size on the page.',
    ],
    example: '<p>Here is an iframe with its own inline document:</p>\n<iframe srcdoc="<h2 style=&quot;color: teal;&quot;>Hello from inside!</h2><p>This whole page is embedded using srcdoc.</p>" width="300" height="120" style="border: 2px solid #999;"></iframe>',
    starterCode: '<iframe srcdoc="<p>I am a tiny embedded page.</p>" width="250" height="100" style="border: 1px solid #999;"></iframe>',
  },
  {
    slug: 'character-encoding-and-language',
    title: 'Character Encoding & Language',
    summary: 'Telling browsers what characters and language your page uses',
    explanation: [
      'The lang attribute on <html lang="en"> tells browsers, search engines, and screen readers which language the page is written in, which affects pronunciation, spell-checking, and translation tools.',
      'You can also set lang on a smaller element, like a <span lang="fr">, to mark just one phrase as being in a different language.',
      'Character encoding (set with <meta charset="UTF-8"> in the head) tells the browser how to translate the page\'s raw bytes into text. UTF-8 supports virtually every character and emoji from every language, which is why it is the standard choice today.',
    ],
    example: '<!-- A real page would set this on the root tag: <html lang="en"> -->\n<p lang="en">Hello, how are you?</p>\n<p lang="fr">Bonjour, comment &ccedil;a va?</p>\n<p lang="ja">こんにちは</p>\n<p>UTF-8 encoding means emoji work fine too: 🎉🚀✨</p>',
    starterCode: '<p lang="en">Good morning!</p>\n<p lang="es">&iexcl;Buenos d&iacute;as!</p>',
  },
  {
    slug: 'favicon-and-theme-color',
    title: 'Favicon & Theme Color',
    summary: 'Branding the browser tab and mobile UI',
    explanation: [
      'A favicon is the small icon shown in a browser tab, bookmarks list, and history — set it in the <head> with <link rel="icon" type="image/png" href="/favicon.png">.',
      'The <meta name="theme-color" content="#7c3aed"> tag suggests a colour for the browser\'s UI chrome (like the address bar on mobile) to match your brand.',
      'Both of these tags live in <head> and have no visible effect inside the page body itself — they affect the browser\'s own interface.',
    ],
    example: '<!-- These would normally live in <head>: -->\n<!-- <link rel="icon" type="image/png" href="/favicon.png"> -->\n<!-- <meta name="theme-color" content="#7c3aed"> -->\n\n<div style="background: #7c3aed; color: white; padding: 12px; border-radius: 6px;">\n  <p>Imagine this purple matches the browser\'s address bar on mobile, thanks to theme-color.</p>\n</div>',
    starterCode: '<!-- <link rel="icon" href="/favicon.png"> would go in <head> -->\n<p>This page would show a custom tab icon and a themed address bar.</p>',
  },
  {
    slug: 'web-components-intro',
    title: 'Web Components (Intro)',
    summary: 'A first look at building your own reusable HTML tags',
    explanation: [
      'Web Components let developers define brand-new, reusable tags (like <my-widget>) with their own behaviour, bundled up as a single self-contained piece.',
      'Until that custom tag is "defined" with JavaScript (using customElements.define), the browser treats it as an unknown element — it still renders any plain content placed inside it, just without any special behaviour yet.',
      'This is the foundation for sharing components across projects and frameworks without relying on any single library.',
    ],
    example: '<p>Below is an undefined custom tag. The browser does not know what &lt;my-widget&gt; means, but it still renders its inner content as plain HTML:</p>\n<my-widget>\n  <strong>I am the light-DOM content</strong> inside a custom element.\n</my-widget>\n<p>Once defined with JavaScript via customElements.define(\'my-widget\', ...), this tag could have its own styles and behaviour.</p>',
    starterCode: '<my-greeting>\n  <p>Hello from inside a custom tag!</p>\n</my-greeting>',
  },
  {
    slug: 'aria-roles-and-landmarks',
    title: 'ARIA Roles & Landmarks',
    summary: 'Telling assistive technology what a generic element actually does',
    explanation: [
      'ARIA roles describe what an element behaves like when no native semantic tag fits — for example role="button" tells a screen reader to treat a <div> as a clickable button.',
      'Landmark roles like role="navigation", role="main", and role="banner" mark out major regions of a page so screen reader users can jump straight between them, similar to how <nav> and <main> already do this automatically.',
      'Prefer the real semantic element first (as covered in semantic-html and accessibility-basics) — only add an ARIA role when you must repurpose a generic element like <div> or <span>.',
    ],
    example: '<div role="banner" style="background: #f1f5f9; padding: 8px;">Site Header</div>\n<div role="navigation" style="padding: 8px;">\n  <span role="button" tabindex="0" style="cursor: pointer; text-decoration: underline;">Home</span> |\n  <span role="button" tabindex="0" style="cursor: pointer; text-decoration: underline;">About</span>\n</div>\n<div role="main" style="padding: 8px;">\n  <p>This div is announced as the main content region.</p>\n</div>',
    starterCode: '<div role="navigation">\n  <span role="button" tabindex="0">Menu</span>\n</div>\n<div role="main">\n  <p>Main page content goes here.</p>\n</div>',
  },
  {
    slug: 'definition-lists',
    title: 'Definition Lists',
    summary: 'Pairing terms with their descriptions using dl, dt, and dd',
    explanation: [
      'A definition list uses <dl> to wrap a series of terms and descriptions: each term goes in a <dt> (definition term) and its explanation goes in a <dd> (definition description).',
      'A single <dt> can be followed by multiple <dd> elements if a term has more than one description — perfect for glossaries, FAQs, or metadata like name/value pairs.',
    ],
    example: '<dl>\n  <dt>HTML</dt>\n  <dd>The markup language used to structure web pages.</dd>\n  <dt>CSS</dt>\n  <dd>The language used to style web pages.</dd>\n  <dd>Stands for Cascading Style Sheets.</dd>\n</dl>',
    starterCode: '<dl>\n  <dt>Apple</dt>\n  <dd>A crisp, round fruit.</dd>\n  <dt>Banana</dt>\n  <dd>A long, yellow fruit.</dd>\n</dl>',
  },
  {
    slug: 'tables-spanning-cells',
    title: 'Tables: Spanning Cells',
    summary: 'Merging table cells with colspan and rowspan',
    explanation: [
      'The colspan attribute on a <td> or <th> makes that cell stretch across multiple columns — handy for a heading that spans several columns below it.',
      'The rowspan attribute makes a cell stretch down across multiple rows instead, so a single value can apply to several rows at once.',
    ],
    example: '<table border="1">\n  <tr><th colspan="2">Contact Info</th></tr>\n  <tr><td>Email</td><td>aria@example.com</td></tr>\n  <tr><td rowspan="2">Phone</td><td>555-0100 (home)</td></tr>\n  <tr><td>555-0199 (mobile)</td></tr>\n</table>',
    starterCode: '<table border="1">\n  <tr><th colspan="2">Order Summary</th></tr>\n  <tr><td>Item</td><td>Widget</td></tr>\n  <tr><td>Qty</td><td>3</td></tr>\n</table>',
  },
  {
    slug: 'progress-and-meter',
    title: 'Progress & Meter',
    summary: 'Built-in bars for showing completion and measurements',
    explanation: [
      'The <progress> element shows how far a task has gotten toward completion — set value and max, e.g. <progress value="30" max="100">, to show 30%.',
      'The <meter> element shows a measurement within a known range, like disk usage or a rating — it uses value, min, max, and can even shift colour using low/high/optimum thresholds.',
    ],
    example: '<label>Download progress: <progress value="70" max="100"></progress></label><br><br>\n<label>Disk usage: <meter value="0.8" min="0" max="1"></meter></label><br><br>\n<label>Battery: <meter value="20" min="0" max="100" low="30" high="70" optimum="100"></meter></label>',
    starterCode: '<label>Upload: <progress value="45" max="100"></progress></label><br><br>\n<label>Score: <meter value="6" min="0" max="10"></meter></label>',
  },
  {
    slug: 'abbr-cite-and-time',
    title: 'Abbr, Cite & Time',
    summary: 'Giving meaning to abbreviations, citations, and dates',
    explanation: [
      '<abbr title="..."> marks up an abbreviation or acronym, with the title attribute giving the full expansion shown as a tooltip on hover — e.g. <abbr title="HyperText Markup Language">HTML</abbr>.',
      '<cite> marks the title of a creative work being referenced (a book, film, or article), while <time datetime="..."> marks a human-readable date or time and pairs it with a machine-readable value in the datetime attribute.',
    ],
    example: '<p>I am learning <abbr title="HyperText Markup Language">HTML</abbr> today.</p>\n<p><cite>The Innovators</cite> is a great read about computing history.</p>\n<p>The article was published on <time datetime="2026-03-15">March 15, 2026</time>.</p>',
    starterCode: '<p><abbr title="As Soon As Possible">ASAP</abbr> means right away.</p>\n<p>Published <time datetime="2026-01-01">January 1, 2026</time>.</p>',
  },
  {
    slug: 'blockquote-and-quotations',
    title: 'Blockquote & Quotations',
    summary: 'Marking up longer and shorter quoted text',
    explanation: [
      '<blockquote> wraps a longer, block-level quotation from another source — browsers typically indent it — and the optional cite attribute can hold the source URL.',
      '<q> wraps a short, inline quotation within a sentence; browsers automatically add quotation marks around it, so you should not type your own.',
    ],
    example: '<blockquote cite="https://example.com/quotes">\n  <p>The only way to do great work is to love what you do.</p>\n</blockquote>\n<p>As she put it, <q>this changes everything</q>, and she was right.</p>',
    starterCode: '<blockquote>\n  <p>Code is read more often than it is written.</p>\n</blockquote>\n<p>He said <q>practice makes perfect</q> during the lesson.</p>',
  },
  {
    slug: 'contenteditable-basics',
    title: 'Contenteditable Basics',
    summary: 'Turning any element into an editable text area',
    explanation: [
      'Adding contenteditable="true" to almost any element lets the user click into it and edit its text directly in the page, no <input> or <textarea> required.',
      'This is the building block behind rich-text editors — combined with JavaScript, you can read the edited content back out using element.innerHTML or element.textContent.',
    ],
    example: '<div contenteditable="true" style="border: 1px solid #999; padding: 10px; min-height: 60px;">\n  Click here and start typing — this whole box is editable!\n</div>\n<p contenteditable="true" style="border: 1px dashed #999; padding: 6px;">You can edit this single paragraph too.</p>',
    starterCode: '<div contenteditable="true" style="border: 1px solid #999; padding: 10px;">\n  Edit this text right in the page.\n</div>',
  },
  {
    slug: 'html-templates-element',
    title: 'The Template Element',
    summary: 'Holding inert markup that only becomes real when cloned',
    explanation: [
      'Content inside a <template> is parsed by the browser but not rendered and not run — scripts inside it do not execute, images inside it do not load — until JavaScript pulls it out.',
      'A common pattern is to grab template.content, clone it with cloneNode(true), and append the clone to the page, letting you stamp out the same markup repeatedly without writing it from scratch each time.',
    ],
    example: '<template id="card-template">\n  <div style="border: 1px solid #999; padding: 8px; margin: 4px 0;">A reusable card</div>\n</template>\n<div id="output"></div>\n<script>\n  var tpl = document.getElementById(\'card-template\');\n  for (var i = 0; i < 3; i++) {\n    var clone = tpl.content.cloneNode(true);\n    document.getElementById(\'output\').appendChild(clone);\n  }\n</script>',
    starterCode: '<template id="item-template">\n  <p>Templated item</p>\n</template>\n<div id="list"></div>\n<script>\n  var tpl = document.getElementById(\'item-template\');\n  document.getElementById(\'list\').appendChild(tpl.content.cloneNode(true));\n</script>',
  },
  {
    slug: 'noscript-fallbacks',
    title: 'Noscript Fallbacks',
    summary: 'Showing alternative content when JavaScript is unavailable',
    explanation: [
      'Anything inside <noscript> is only shown if the browser has JavaScript disabled or does not support it — the rest of the time it is completely ignored.',
      'It is commonly used to display a friendly message explaining that a feature, like an interactive widget, needs JavaScript turned on to work.',
    ],
    example: '<p id="js-message">This message was inserted by JavaScript.</p>\n<noscript>\n  <p>JavaScript is disabled in your browser, so the interactive parts of this page will not work.</p>\n</noscript>\n<script>\n  document.getElementById(\'js-message\').textContent = \'JavaScript is running just fine!\';\n</script>',
    starterCode: '<noscript>\n  <p>Please enable JavaScript to use this app.</p>\n</noscript>\n<p>If JavaScript is enabled, you will not see the message above.</p>',
  },
  {
    slug: 'drag-and-drop-basics',
    title: 'Drag & Drop Basics',
    summary: 'Making elements draggable and droppable',
    explanation: [
      'Setting draggable="true" on an element lets the user pick it up and drag it; the dragstart event fires on that element when the drag begins.',
      'A container becomes a valid drop target by listening for dragover (calling event.preventDefault() to allow dropping) and drop, where you can move the dragged element into place.',
    ],
    example: '<div id="item" draggable="true" style="width: 100px; padding: 8px; background: #fde68a; cursor: grab;">Drag me</div>\n<div id="box" style="width: 200px; height: 80px; border: 2px dashed #999; margin-top: 10px;">Drop here</div>\n<script>\n  var item = document.getElementById(\'item\');\n  var box = document.getElementById(\'box\');\n  item.addEventListener(\'dragstart\', function (e) {\n    e.dataTransfer.setData(\'text/plain\', \'item\');\n  });\n  box.addEventListener(\'dragover\', function (e) { e.preventDefault(); });\n  box.addEventListener(\'drop\', function (e) {\n    e.preventDefault();\n    box.appendChild(item);\n  });\n</script>',
    starterCode: '<div id="card" draggable="true" style="width: 80px; padding: 6px; background: #bfdbfe;">Drag</div>\n<div id="target" style="width: 160px; height: 60px; border: 2px dashed #999;">Target</div>\n<script>\n  var card = document.getElementById(\'card\');\n  var target = document.getElementById(\'target\');\n  target.addEventListener(\'dragover\', function (e) { e.preventDefault(); });\n  target.addEventListener(\'drop\', function (e) { target.appendChild(card); });\n</script>',
  },
  {
    slug: 'meta-tags-and-seo',
    title: 'Meta Tags & SEO',
    summary: 'Describing your page to search engines and social previews',
    explanation: [
      '<meta charset="UTF-8"> should be the first tag in <head>, and <meta name="description" content="..."> gives search engines a short summary often shown directly in search results.',
      '<meta name="keywords" content="..."> lists topics related to the page (mostly ignored by modern search engines now), while Open Graph tags like <meta property="og:title" content="..."> control how a link looks when shared on social media.',
    ],
    example: '<!-- These would normally live in <head>: -->\n<!-- <meta charset="UTF-8"> -->\n<!-- <meta name="description" content="Learn HTML for free with interactive lessons"> -->\n<!-- <meta name="keywords" content="html, learn, coding"> -->\n<!-- <meta property="og:title" content="Learn HTML"> -->\n\n<p>A real page would have description and Open Graph meta tags in its &lt;head&gt; so it previews nicely when shared.</p>',
    starterCode: '<!-- <meta name="description" content="My personal blog about cooking"> -->\n<p>Imagine this page has SEO meta tags in its head.</p>',
  },
  {
    slug: 'input-validation-attributes',
    title: 'Input Validation Attributes',
    summary: 'Constraining numbers and patterns with pattern, min, max, and step',
    explanation: [
      'On number-like inputs, min and max set the allowed range, while step controls the increment the up/down arrows (and scroll wheel) move by — e.g. step="5" only allows multiples of 5 from min.',
      'The pattern attribute (seen earlier with text inputs) works alongside these on other input types too, and the browser blocks form submission until every constraint is satisfied.',
    ],
    example: '<form>\n  <label>Quantity (1-10, step 1): <input type="number" min="1" max="10" step="1" value="1"></label><br>\n  <label>Price (step 0.25): <input type="number" min="0" step="0.25" value="0"></label><br>\n  <label>Rating (0-100, step 10): <input type="range" min="0" max="100" step="10"></label>\n</form>',
    starterCode: '<form>\n  <label>Age: <input type="number" min="0" max="120" step="1"></label><br>\n  <label>Tip %: <input type="range" min="0" max="30" step="5"></label>\n</form>',
  },
  {
    slug: 'datalist-autocomplete',
    title: 'Datalist Autocomplete',
    summary: 'Offering suggestions while still allowing free text',
    explanation: [
      'A <datalist> holds a set of <option> suggestions; linking it to an <input> via its list attribute (matching the datalist\'s id) shows those suggestions as the user types.',
      'Unlike <select>, the user can still type any value they like — the datalist only offers suggestions, it does not restrict input to that list.',
    ],
    example: '<label>Favourite browser:\n  <input type="text" list="browsers">\n  <datalist id="browsers">\n    <option value="Chrome"></option>\n    <option value="Firefox"></option>\n    <option value="Safari"></option>\n    <option value="Edge"></option>\n  </datalist>\n</label>',
    starterCode: '<label>City:\n  <input type="text" list="cities">\n  <datalist id="cities">\n    <option value="London"></option>\n    <option value="Tokyo"></option>\n    <option value="Nairobi"></option>\n  </datalist>\n</label>',
  },
  {
    slug: 'responsive-viewport-meta',
    title: 'Responsive Viewport Meta',
    summary: 'Making a page render sensibly on mobile screens',
    explanation: [
      'Without <meta name="viewport" content="width=device-width, initial-scale=1"> in the head, mobile browsers render pages at a zoomed-out desktop width, forcing users to pinch-zoom to read anything.',
      'width=device-width matches the page\'s width to the device\'s actual screen width, and initial-scale=1 sets the starting zoom level to 100%, which together is the foundation of any responsive design.',
    ],
    example: '<!-- This would normally live in <head>: -->\n<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->\n\n<div style="background: #ecfccb; padding: 12px;">\n  <p>With the viewport meta tag set, this page would scale to fit a phone screen instead of rendering zoomed out.</p>\n</div>',
    starterCode: '<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> would go in <head> -->\n<p>This page is set up to be mobile-friendly.</p>',
  },
  {
    slug: 'microdata-basics',
    title: 'Microdata Basics',
    summary: 'Embedding structured data search engines can understand',
    explanation: [
      'itemscope marks an element as describing one "item" (like a person or product), and itemtype points to a vocabulary (commonly from schema.org) that defines what properties that item can have.',
      'itemprop="name" inside that scope labels a piece of content as a specific property of the item — search engines can read this structured data to build rich results, like star ratings shown directly in search.',
    ],
    example: '<div itemscope itemtype="https://schema.org/Person">\n  <span itemprop="name">Ada Lovelace</span>\n  <span itemprop="jobTitle">Mathematician</span>\n  <a itemprop="url" href="https://example.com/ada">Profile</a>\n</div>',
    starterCode: '<div itemscope itemtype="https://schema.org/Product">\n  <span itemprop="name">Widget Pro</span>\n  <span itemprop="price">29.99</span>\n</div>',
  },
  {
    slug: 'html-forms-method-and-action',
    title: 'Forms: Method & Action',
    summary: 'Telling a form where and how to send its data',
    explanation: [
      'The action attribute on <form> sets the URL the data is sent to, and method sets how it is sent: method="get" appends the data to the URL as a query string (visible, bookmarkable, good for searches), while method="post" sends it in the request body (hidden from the URL, used for things like logins or anything that changes data).',
      'If action is left out, the form submits to the current page\'s own URL; this lesson only inspects the attributes, since there is no real server here to submit to.',
    ],
    example: '<form action="/search" method="get">\n  <label>Search: <input type="text" name="q"></label>\n  <button type="submit">Go (GET — visible in URL)</button>\n</form>\n<form action="/login" method="post">\n  <label>Password: <input type="password" name="pw"></label>\n  <button type="submit">Log in (POST — hidden from URL)</button>\n</form>',
    starterCode: '<form action="/submit" method="post">\n  <label>Comment: <input type="text" name="comment"></label>\n  <button type="submit">Send</button>\n</form>',
  },
]
