import type { CodingLesson } from '../languages'

export const javascript: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to JavaScript',
    summary: 'Making web pages interactive — and printing your first output',
    explanation: [
      'JavaScript is the programming language of the web. It runs in the browser and can react to clicks, update content, fetch data, and much more.',
      'console.log(...) prints a value to the console — perfect for checking what your code is doing. In this playground, anything you log appears in the Output panel.',
      'Statements usually end with a semicolon ; (optional, but good practice).',
    ],
    example: "console.log('Hello, world!');\nconsole.log(2 + 3 * 4);",
    starterCode: "console.log('Hello, world!');\nconsole.log(10 - 4);",
  },
  {
    slug: 'variables',
    title: 'Variables & Data Types',
    summary: 'Storing values with let and const',
    explanation: [
      'Variables store values so you can use them later. Use let for values that may change, and const for values that should not be reassigned.',
      'JavaScript has several basic types: numbers (42), strings ("hello"), booleans (true/false), arrays ([1,2,3]), and objects ({name: "Aria"}).',
      'Template strings — backticks with ${...} — let you mix variables into text easily.',
    ],
    example: "const name = 'Aria';\nlet age = 12;\nage = age + 1;\nconsole.log(`${name} is now ${age} years old`);",
    starterCode: "const city = 'Kathmandu';\nlet temperature = 22;\nconsole.log(`${city} is ${temperature}°C today`);",
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Making decisions with if, else if, and else',
    explanation: [
      'if statements run code only when a condition is true. else if checks another condition, and else runs when nothing else matched.',
      'Comparison operators like ===, !==, >, and < produce true or false, which conditionals use to decide what to do.',
    ],
    example: "const score = 82;\nif (score >= 90) {\n  console.log('Grade: A');\n} else if (score >= 75) {\n  console.log('Grade: B');\n} else {\n  console.log('Keep practising!');\n}",
    starterCode: "const temperature = 30;\nif (temperature > 25) {\n  console.log('It is warm');\n} else {\n  console.log('It is cool');\n}",
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating actions with for and while',
    explanation: [
      'A for loop repeats code a set number of times: for (let i = 0; i < 5; i++) { ... }.',
      'A while loop repeats as long as a condition stays true — useful when you do not know in advance how many times you need to repeat.',
      'Arrays also have handy loop-like methods such as .forEach(item => ...) and .map(item => ...).',
    ],
    example: "for (let i = 1; i <= 5; i++) {\n  console.log(`Step ${i}`);\n}\n\nconst fruits = ['apple', 'banana', 'mango'];\nfruits.forEach(f => console.log(f.toUpperCase()));",
    starterCode: "for (let i = 1; i <= 3; i++) {\n  console.log(`Count: ${i}`);\n}",
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Packaging reusable blocks of logic',
    explanation: [
      'A function is a reusable block of code. Define one with function name(params) { ... } or as an arrow function const name = (params) => { ... }.',
      'Functions can take inputs (parameters) and give back an output with return.',
    ],
    example: "function double(n) {\n  return n * 2;\n}\n\nconst greet = (name) => `Hello, ${name}!`;\n\nconsole.log(double(21));\nconsole.log(greet('World'));",
    starterCode: "function square(n) {\n  return n * n;\n}\nconsole.log(square(6));",
  },
  {
    slug: 'arrays-and-objects',
    title: 'Arrays & Objects',
    summary: 'Working with collections and structured data',
    explanation: [
      'Arrays hold ordered lists of values: const nums = [1, 2, 3]. Access items with nums[0], get the length with nums.length.',
      'Objects hold named properties: const dog = { name: "Rex", age: 3 }. Access them with dog.name or dog["name"].',
      'Methods like .map(), .filter(), and .reduce() transform arrays without writing manual loops.',
    ],
    example: "const numbers = [1, 2, 3, 4, 5];\nconst doubled = numbers.map(n => n * 2);\nconst evens = numbers.filter(n => n % 2 === 0);\nconsole.log(doubled);\nconsole.log(evens);\n\nconst student = { name: 'Aria', grade: 7 };\nconsole.log(`${student.name} is in grade ${student.grade}`);",
    starterCode: "const scores = [70, 85, 92, 60];\nconst passing = scores.filter(s => s >= 70);\nconsole.log(passing);",
  },
  {
    slug: 'dom-basics',
    title: 'DOM Basics',
    summary: 'Creating and inspecting page elements with the DOM',
    explanation: [
      'The DOM (Document Object Model) is how JavaScript sees and changes a web page — every tag becomes an object you can read and modify.',
      'document.createElement(tag) makes a new element, .textContent sets its text, and parent.appendChild(child) attaches it to the page.',
      'document.querySelector(selector) finds the first matching element, and .classList lets you add, remove, or toggle CSS classes on it.',
    ],
    example: "const card = document.createElement('div');\ncard.textContent = 'Hello DOM!';\ncard.classList.add('card', 'highlight');\n\nconst container = document.createElement('section');\ncontainer.appendChild(card);\n\nconsole.log(container.children.length);\nconsole.log(card.textContent);\nconsole.log(card.classList.contains('highlight'));",
    starterCode: "const item = document.createElement('li');\nitem.textContent = 'Learn the DOM';\nitem.classList.add('todo-item');\n\nconsole.log(item.textContent);\nconsole.log(item.classList.contains('todo-item'));",
  },
  {
    slug: 'events',
    title: 'Events & Callbacks',
    summary: 'Reacting to things happening with addEventListener and callbacks',
    explanation: [
      'In the browser, element.addEventListener("click", callback) runs your callback function whenever that event happens — buttons get clicked, forms get submitted, keys get pressed.',
      'A callback is just a function passed as a value to be called later. Array methods like .forEach(item => ...) use the same idea: they call your function once for each item.',
      'This "tell me when it happens" pattern is everywhere in JavaScript, from button clicks to network responses.',
    ],
    example: "// Simulating how addEventListener works: store a callback, call it later\nfunction onClick(callback) {\n  console.log('Button was clicked!');\n  callback('click');\n}\n\nonClick((eventType) => console.log(`Handled event: ${eventType}`));\n\n// The same callback pattern powers array iteration\nconst names = ['Aria', 'Kiran', 'Maya'];\nnames.forEach((name, index) => {\n  console.log(`${index}: Hello, ${name}`);\n});",
    starterCode: "function onHover(callback) {\n  callback('mouseover');\n}\n\nonHover((eventType) => console.log(`Triggered: ${eventType}`));\n\n['red', 'green', 'blue'].forEach(color => console.log(`Color: ${color}`));",
  },
  {
    slug: 'destructuring-and-spread',
    title: 'Destructuring & Spread',
    summary: 'Unpacking values and combining collections with concise syntax',
    explanation: [
      'Destructuring unpacks values from arrays or objects into variables in one step: const [a, b] = [1, 2] or const { name } = person.',
      'The spread operator ... expands an array or object into individual elements — handy for copying, merging, or passing many arguments at once.',
      'Together they make working with collections shorter and easier to read than manual indexing.',
    ],
    example: "const point = [10, 20];\nconst [x, y] = point;\nconsole.log(`x=${x}, y=${y}`);\n\nconst person = { name: 'Aria', age: 12, city: 'Kathmandu' };\nconst { name, ...rest } = person;\nconsole.log(name);\nconsole.log(rest);\n\nconst nums = [1, 2, 3];\nconst moreNums = [...nums, 4, 5];\nconsole.log(moreNums);\n\nconst defaults = { theme: 'light', size: 'medium' };\nconst settings = { ...defaults, size: 'large' };\nconsole.log(settings);",
    starterCode: "const colors = ['red', 'green', 'blue'];\nconst [first, ...others] = colors;\nconsole.log(first);\nconsole.log(others);\n\nconst base = { a: 1, b: 2 };\nconst extended = { ...base, c: 3 };\nconsole.log(extended);",
  },
  {
    slug: 'higher-order-functions',
    title: 'Higher-Order Functions',
    summary: 'Functions that take or return other functions',
    explanation: [
      'A higher-order function either accepts a function as an argument or returns a new function — JavaScript treats functions as ordinary values that can be passed around.',
      '.map() transforms each item, .filter() keeps items that pass a test, and .reduce() combines all items into a single result; chaining them lets you express complex transformations clearly.',
      'Functions can also build and return other functions, which is useful for creating customized, reusable behavior.',
    ],
    example: "const numbers = [1, 2, 3, 4, 5, 6];\n\nconst total = numbers\n  .filter(n => n % 2 === 0)\n  .map(n => n * 10)\n  .reduce((sum, n) => sum + n, 0);\n\nconsole.log(total);\n\nfunction makeMultiplier(factor) {\n  return (n) => n * factor;\n}\n\nconst triple = makeMultiplier(3);\nconsole.log(triple(7));\nconsole.log(numbers.map(triple));",
    starterCode: "const prices = [5, 12, 8, 20];\nconst withTax = prices.map(p => p * 1.1);\nconst total = withTax.reduce((sum, p) => sum + p, 0);\nconsole.log(withTax);\nconsole.log(total);",
  },
  {
    slug: 'promises-and-async',
    title: 'Promises & Async/Await',
    summary: 'Handling work that finishes later, in order',
    explanation: [
      'A Promise represents a value that will be available later — it starts "pending" and then resolves (success) or rejects (failure).',
      'async functions let you write asynchronous code that reads top-to-bottom: await pauses the function until a Promise resolves, without blocking the rest of the program.',
      'Code after setTimeout or other async calls runs later, which is why the console.log order can look surprising at first — async/await makes that order easier to follow.',
    ],
    example: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function run() {\n  console.log('start');\n  const first = await wait(10, 'first result');\n  console.log(first);\n  const second = await wait(10, 'second result');\n  console.log(second);\n  console.log('done');\n}\n\nrun();\nconsole.log('this logs before the async work finishes');",
    starterCode: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function run() {\n  const message = await wait(10, 'Loaded!');\n  console.log(message);\n}\n\nrun();\nconsole.log('Loading...');",
  },
  {
    slug: 'classes',
    title: 'Classes',
    summary: 'Blueprints for creating objects with shared behavior',
    explanation: [
      'A class is a blueprint for objects: class Dog { constructor(name) { this.name = name } } defines what every dog instance will have.',
      'The constructor runs when you create a new instance with new, and methods defined inside the class become functions every instance can call.',
      'Classes group related data and behavior together, making it easier to create many similar objects.',
    ],
    example: "class Animal {\n  constructor(name, sound) {\n    this.name = name;\n    this.sound = sound;\n  }\n\n  speak() {\n    return `${this.name} says ${this.sound}`;\n  }\n}\n\nclass Dog extends Animal {\n  constructor(name) {\n    super(name, 'Woof');\n  }\n\n  fetch() {\n    return `${this.name} fetches the ball!`;\n  }\n}\n\nconst rex = new Dog('Rex');\nconsole.log(rex.speak());\nconsole.log(rex.fetch());\nconsole.log(rex instanceof Animal);",
    starterCode: "class Counter {\n  constructor() {\n    this.count = 0;\n  }\n\n  increment() {\n    this.count += 1;\n    return this.count;\n  }\n}\n\nconst counter = new Counter();\nconsole.log(counter.increment());\nconsole.log(counter.increment());\nconsole.log(counter.count);",
  },
  {
    slug: 'error-handling',
    title: 'Error Handling',
    summary: 'Dealing gracefully with things that go wrong',
    explanation: [
      'try { ... } catch (error) { ... } lets you run risky code and handle any error it throws instead of crashing the program.',
      'You can throw your own errors with throw new Error("message") to signal that something went wrong in a way callers can catch.',
      'finally { ... } runs no matter what — whether the code succeeded, failed, or threw — which is useful for cleanup.',
    ],
    example: "function parsePositiveNumber(value) {\n  const n = Number(value);\n  if (Number.isNaN(n)) {\n    throw new Error(`\"${value}\" is not a number`);\n  }\n  if (n <= 0) {\n    throw new Error(`${n} is not positive`);\n  }\n  return n;\n}\n\nfor (const input of ['12', 'abc', '-5']) {\n  try {\n    const n = parsePositiveNumber(input);\n    console.log(`Parsed: ${n}`);\n  } catch (error) {\n    console.log(`Error: ${error.message}`);\n  } finally {\n    console.log(`Finished checking \"${input}\"`);\n  }\n}",
    starterCode: "function divide(a, b) {\n  if (b === 0) {\n    throw new Error('Cannot divide by zero');\n  }\n  return a / b;\n}\n\ntry {\n  console.log(divide(10, 2));\n  console.log(divide(10, 0));\n} catch (error) {\n  console.log(`Caught: ${error.message}`);\n}",
  },
]
