import type { CodingLesson } from '../languages'

export const java: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to Java',
    summary: 'Classes, the main method, and printing output',
    explanation: [
      'Java is a popular, strongly-typed language used for everything from Android apps to enterprise servers. Every program lives inside a class.',
      'Execution starts at public static void main(String[] args). System.out.println(...) prints a line of output.',
      'Each statement ends with a semicolon ;.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, world!");\n    System.out.println(2 + 3 * 4);\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, world!");\n    System.out.println(7 * 6);\n  }\n}',
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Declaring typed variables',
    explanation: [
      'Java is statically typed — you state the type when declaring a variable: int age = 12; String name = "Aria";.',
      'Common types include int (whole numbers), double (decimals), boolean (true/false), and String (text).',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    String name = "Aria";\n    int age = 12;\n    System.out.println(name + " is " + age + " years old");\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    String city = "Pokhara";\n    int temperature = 24;\n    System.out.println(city + " is " + temperature + " degrees");\n  }\n}',
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Branching with if / else if / else',
    explanation: [
      'if checks a condition in parentheses; else if checks another; else runs otherwise. Blocks are wrapped in { }.',
      'Comparison operators ==, !=, >, < produce boolean values that conditionals use.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    int score = 82;\n    if (score >= 90) {\n      System.out.println("Grade: A");\n    } else if (score >= 75) {\n      System.out.println("Grade: B");\n    } else {\n      System.out.println("Keep practising!");\n    }\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    int temperature = 30;\n    if (temperature > 25) {\n      System.out.println("It is warm");\n    } else {\n      System.out.println("It is cool");\n    }\n  }\n}',
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating with for and while',
    explanation: [
      'A for loop has three parts: for (int i = 0; i < 5; i++) { ... } — start, condition, and update.',
      'A while loop repeats while its condition stays true.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= 5; i++) {\n      System.out.println("Step " + i);\n    }\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= 3; i++) {\n      System.out.println("Count: " + i);\n    }\n  }\n}',
  },
  {
    slug: 'methods',
    title: 'Methods',
    summary: 'Reusable blocks of logic',
    explanation: [
      'A method is declared with a return type, name, and parameters: static int square(int n) { return n * n; }.',
      'Use static methods when you do not need an object instance — they can be called directly from main.',
    ],
    example: 'public class Main {\n  static int square(int n) {\n    return n * n;\n  }\n  public static void main(String[] args) {\n    System.out.println(square(6));\n    System.out.println(square(9));\n  }\n}',
    starterCode: 'public class Main {\n  static int doubleIt(int n) {\n    return n * 2;\n  }\n  public static void main(String[] args) {\n    System.out.println(doubleIt(21));\n  }\n}',
  },
  {
    slug: 'arrays',
    title: 'Arrays',
    summary: 'Storing ordered collections of values',
    explanation: [
      'An array holds a fixed-size collection of one type: int[] nums = {1, 2, 3, 4, 5};.',
      'Access elements with nums[0], get the length with nums.length, and loop with a for or for-each loop.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    int[] scores = {70, 85, 92, 60};\n    int total = 0;\n    for (int s : scores) {\n      total += s;\n    }\n    System.out.println("Total: " + total);\n    System.out.println("Average: " + (total / scores.length));\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    int[] nums = {3, 6, 9};\n    for (int n : nums) {\n      System.out.println(n * n);\n    }\n  }\n}',
  },
  {
    slug: 'classes-and-objects',
    title: 'Classes & Objects',
    summary: 'Defining a class with fields and a constructor',
    explanation: [
      'A class is a blueprint with fields (data) and methods (behaviour). A constructor sets up a new object\'s initial state.',
      'Use the new keyword to create an instance, and dot notation like dog.bark() to call its methods.',
    ],
    example: 'class Dog {\n  String name;\n  int age;\n\n  Dog(String name, int age) {\n    this.name = name;\n    this.age = age;\n  }\n\n  void bark() {\n    System.out.println(name + " says Woof!");\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Dog rex = new Dog("Rex", 3);\n    Dog luna = new Dog("Luna", 5);\n    rex.bark();\n    luna.bark();\n    System.out.println(rex.name + " is " + rex.age + " years old");\n  }\n}',
    starterCode: 'class Book {\n  String title;\n\n  Book(String title) {\n    this.title = title;\n  }\n\n  void describe() {\n    System.out.println("Book: " + title);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Book b = new Book("Java Basics");\n    b.describe();\n  }\n}',
  },
  {
    slug: 'inheritance',
    title: 'Inheritance',
    summary: 'Sharing behaviour with extends and super',
    explanation: [
      'A class can extend another class to reuse its fields and methods, forming a parent-child relationship.',
      'Use super(...) to call the parent constructor, and override a method by redeclaring it with the same signature in the subclass.',
    ],
    example: 'class Animal {\n  String name;\n\n  Animal(String name) {\n    this.name = name;\n  }\n\n  void speak() {\n    System.out.println(name + " makes a sound");\n  }\n}\n\nclass Cat extends Animal {\n  Cat(String name) {\n    super(name);\n  }\n\n  @Override\n  void speak() {\n    System.out.println(name + " says Meow");\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Animal generic = new Animal("Creature");\n    Animal cat = new Cat("Whiskers");\n    generic.speak();\n    cat.speak();\n  }\n}',
    starterCode: 'class Vehicle {\n  void drive() {\n    System.out.println("The vehicle moves");\n  }\n}\n\nclass Car extends Vehicle {\n  @Override\n  void drive() {\n    System.out.println("The car zooms down the road");\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Vehicle v = new Car();\n    v.drive();\n  }\n}',
  },
  {
    slug: 'interfaces',
    title: 'Interfaces',
    summary: 'Declaring contracts with interface and implements',
    explanation: [
      'An interface declares method signatures without bodies; a class agrees to the contract using implements and supplies the implementation.',
      'Different classes can implement the same interface in their own way, so code that uses the interface type works polymorphically with any of them.',
    ],
    example: 'interface Shape {\n  double area();\n}\n\nclass Circle implements Shape {\n  double radius;\n\n  Circle(double radius) {\n    this.radius = radius;\n  }\n\n  public double area() {\n    return Math.PI * radius * radius;\n  }\n}\n\nclass Square implements Shape {\n  double side;\n\n  Square(double side) {\n    this.side = side;\n  }\n\n  public double area() {\n    return side * side;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Shape[] shapes = { new Circle(2), new Square(3) };\n    for (Shape s : shapes) {\n      System.out.println("Area: " + s.area());\n    }\n  }\n}',
    starterCode: 'interface Greeter {\n  String greet(String name);\n}\n\nclass Friendly implements Greeter {\n  public String greet(String name) {\n    return "Hello, " + name + "!";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Greeter g = new Friendly();\n    System.out.println(g.greet("Aria"));\n  }\n}',
  },
  {
    slug: 'collections',
    title: 'Collections',
    summary: 'Storing growable lists with ArrayList',
    explanation: [
      'ArrayList<T> from java.util is a resizable list — import it with import java.util.*; and create one with new ArrayList<>().',
      'Use add(value) to append, get(index) to read, size() for the count, and a for-each loop to visit every element.',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> fruits = new ArrayList<>();\n    fruits.add("apple");\n    fruits.add("banana");\n    fruits.add("cherry");\n\n    System.out.println("Count: " + fruits.size());\n    System.out.println("First: " + fruits.get(0));\n    for (String fruit : fruits) {\n      System.out.println("- " + fruit);\n    }\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<Integer> numbers = new ArrayList<>();\n    numbers.add(10);\n    numbers.add(20);\n    numbers.add(30);\n    for (int n : numbers) {\n      System.out.println(n);\n    }\n  }\n}',
  },
  {
    slug: 'strings',
    title: 'Strings',
    summary: 'Working with text using common String methods',
    explanation: [
      'Strings support handy methods like length(), substring(start, end), toUpperCase(), and split(delimiter).',
      'Combine text with + concatenation, and compare contents with .equals(...) rather than == .',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    String message = "Hello, Java World";\n    System.out.println("Length: " + message.length());\n    System.out.println("Upper: " + message.toUpperCase());\n    System.out.println("Substring: " + message.substring(7, 11));\n\n    String[] words = message.split(" ");\n    for (String word : words) {\n      System.out.println("Word: " + word);\n    }\n\n    String greeting = "Hi" + ", " + "there";\n    System.out.println(greeting.equals("Hi, there"));\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    String name = "aria";\n    System.out.println(name.toUpperCase());\n    System.out.println(name.length());\n    System.out.println(name.equals("aria"));\n  }\n}',
  },
  {
    slug: 'exceptions',
    title: 'Exceptions',
    summary: 'Handling errors with try, catch, finally, and throw',
    explanation: [
      'Code that might fail goes in a try block; a matching catch block handles the resulting exception, and finally always runs afterwards.',
      'You can throw your own exceptions, including custom ones defined by extending Exception.',
    ],
    example: 'class InvalidAgeException extends Exception {\n  InvalidAgeException(String message) {\n    super(message);\n  }\n}\n\npublic class Main {\n  static void checkAge(int age) throws InvalidAgeException {\n    if (age < 0) {\n      throw new InvalidAgeException("Age cannot be negative");\n    }\n    System.out.println("Age " + age + " is valid");\n  }\n\n  public static void main(String[] args) {\n    try {\n      int result = 10 / 0;\n      System.out.println(result);\n    } catch (ArithmeticException e) {\n      System.out.println("Caught: " + e.getMessage());\n    } finally {\n      System.out.println("Division attempt finished");\n    }\n\n    try {\n      checkAge(-5);\n    } catch (InvalidAgeException e) {\n      System.out.println("Caught: " + e.getMessage());\n    }\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    try {\n      int[] nums = {1, 2, 3};\n      System.out.println(nums[5]);\n    } catch (ArrayIndexOutOfBoundsException e) {\n      System.out.println("Caught an error: " + e.getMessage());\n    } finally {\n      System.out.println("Done checking the array");\n    }\n  }\n}',
  },
  {
    slug: 'enums-and-switch',
    title: 'Enums & Switch Statements',
    summary: 'Naming fixed sets of values and branching with switch',
    explanation: [
      'An enum defines a fixed set of named constants, like enum Direction { UP, DOWN, LEFT, RIGHT };. It is a type-safe alternative to using plain numbers or strings to represent a small set of options.',
      'A switch statement branches on a single value: switch (x) { case A: ...; break; default: ...; }. Each case checks for equality with one value, and break stops it from falling through into the next case.',
      'Where if/else if chains re-check a condition each time, switch jumps straight to the matching case, which often reads more cleanly when you are comparing one value against several exact possibilities, such as an enum constant.',
    ],
    example: 'enum Direction {\n  UP, DOWN, LEFT, RIGHT\n}\n\npublic class Main {\n  static String describe(Direction dir) {\n    switch (dir) {\n      case UP:\n        return "Heading north";\n      case DOWN:\n        return "Heading south";\n      case LEFT:\n        return "Heading west";\n      case RIGHT:\n        return "Heading east";\n      default:\n        return "Unknown direction";\n    }\n  }\n\n  public static void main(String[] args) {\n    Direction current = Direction.LEFT;\n    System.out.println(describe(current));\n\n    int day = 3;\n    switch (day) {\n      case 1:\n        System.out.println("Monday");\n        break;\n      case 2:\n        System.out.println("Tuesday");\n        break;\n      case 3:\n        System.out.println("Wednesday");\n        break;\n      default:\n        System.out.println("Some other day");\n        break;\n    }\n  }\n}',
    starterCode: 'enum Season {\n  SPRING, SUMMER, FALL, WINTER\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Season today = Season.SUMMER;\n    switch (today) {\n      case SPRING:\n        System.out.println("Flowers are blooming");\n        break;\n      case SUMMER:\n        System.out.println("Time for the beach");\n        break;\n      case FALL:\n        System.out.println("Leaves are falling");\n        break;\n      case WINTER:\n        System.out.println("Grab a coat");\n        break;\n    }\n  }\n}',
  },
  {
    slug: 'generics-and-abstract-classes',
    title: 'Generics & Abstract Classes',
    summary: 'Writing reusable generic types and partial blueprints',
    explanation: [
      'A generic class works with a placeholder type, written in angle brackets: class Box<T> { private T value; ... }. The same Box class can hold a String, an Integer, or any other type, and the compiler still checks that the types stay consistent.',
      'An abstract class is a blueprint that cannot be instantiated directly. Unlike an interface, it can hold fields and provide fully working methods alongside abstract ones — methods declared without a body that every subclass must implement.',
      'This makes abstract classes useful when related classes share both state and some common behaviour, but still need to fill in a few details themselves, such as how to calculate their own area.',
    ],
    example: 'class Box<T> {\n  private T value;\n\n  Box(T value) {\n    this.value = value;\n  }\n\n  T getValue() {\n    return value;\n  }\n\n  void setValue(T value) {\n    this.value = value;\n  }\n}\n\nabstract class Shape {\n  String name;\n\n  Shape(String name) {\n    this.name = name;\n  }\n\n  abstract double area();\n\n  void describe() {\n    System.out.println(name + " has area " + area());\n  }\n}\n\nclass Rectangle extends Shape {\n  double width;\n  double height;\n\n  Rectangle(double width, double height) {\n    super("Rectangle");\n    this.width = width;\n    this.height = height;\n  }\n\n  @Override\n  double area() {\n    return width * height;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Box<String> nameBox = new Box<>("Aria");\n    Box<Integer> ageBox = new Box<>(12);\n    System.out.println("Box holds: " + nameBox.getValue());\n    System.out.println("Box holds: " + ageBox.getValue());\n\n    Shape rect = new Rectangle(4, 5);\n    rect.describe();\n  }\n}',
    starterCode: 'class Pair<T> {\n  private T first;\n  private T second;\n\n  Pair(T first, T second) {\n    this.first = first;\n    this.second = second;\n  }\n\n  void show() {\n    System.out.println(first + " and " + second);\n  }\n}\n\nabstract class Animal {\n  abstract void makeSound();\n\n  void introduce() {\n    System.out.println("I am an animal");\n    makeSound();\n  }\n}\n\nclass Dog extends Animal {\n  @Override\n  void makeSound() {\n    System.out.println("Woof!");\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Pair<Integer> scores = new Pair<>(10, 20);\n    scores.show();\n\n    Animal pet = new Dog();\n    pet.introduce();\n  }\n}',
  },
  {
    slug: 'static-vs-instance',
    title: 'Static vs Instance Members',
    summary: 'Shared class members vs per-object members',
    explanation: [
      'A static field or method belongs to the class itself, so every object shares the same one — change it through any reference and everyone sees the new value.',
      'An instance field or method belongs to a specific object; each object created with new gets its own independent copy of the instance fields.',
      'Static members are accessed through the class name (Counter.count), while instance members are accessed through an object reference (counter.increment()).',
    ],
    example: 'class Counter {\n  static int totalCreated = 0;\n  int id;\n\n  Counter() {\n    totalCreated++;\n    id = totalCreated;\n  }\n\n  void show() {\n    System.out.println("Counter #" + id);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Counter a = new Counter();\n    Counter b = new Counter();\n    Counter c = new Counter();\n\n    a.show();\n    b.show();\n    c.show();\n    System.out.println("Total created: " + Counter.totalCreated);\n  }\n}',
    starterCode: 'class Robot {\n  static int unitsBuilt = 0;\n  String name;\n\n  Robot(String name) {\n    this.name = name;\n    unitsBuilt++;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Robot r1 = new Robot("Spark");\n    Robot r2 = new Robot("Bolt");\n    System.out.println(r1.name);\n    System.out.println(r2.name);\n    System.out.println("Units built: " + Robot.unitsBuilt);\n  }\n}',
  },
  {
    slug: 'final-keyword',
    title: 'The final Keyword',
    summary: 'Locking variables, methods, and classes',
    explanation: [
      'A final variable can only be assigned once — after that, trying to reassign it is a compile error, which makes it great for constants.',
      'A final method cannot be overridden by a subclass, and a final class cannot be extended at all, which protects the behaviour you have written.',
    ],
    example: 'class MathHelper {\n  static final double TAX_RATE = 0.08;\n\n  final double applyTax(double price) {\n    return price + price * TAX_RATE;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    final int maxAttempts = 3;\n    System.out.println("Max attempts: " + maxAttempts);\n\n    MathHelper helper = new MathHelper();\n    System.out.println("Total: " + helper.applyTax(100));\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    final String appName = "TaskMaster";\n    final int version = 2;\n    System.out.println(appName + " v" + version);\n  }\n}',
  },
  {
    slug: 'polymorphism-and-overriding',
    title: 'Polymorphism & Overriding',
    summary: 'Dynamic dispatch through a base-type reference',
    explanation: [
      'When a subclass overrides a method, calling that method through a base-type reference still runs the subclass version — Java decides which one at runtime, not compile time.',
      'This is called dynamic dispatch, and it lets the same line of code behave differently depending on the actual object underneath.',
      'Overriding toString() is a common example: it lets println print a meaningful description of your object automatically.',
    ],
    example: 'class Shape {\n  double area() {\n    return 0;\n  }\n\n  @Override\n  public String toString() {\n    return "A generic shape with area " + area();\n  }\n}\n\nclass Circle extends Shape {\n  double radius;\n\n  Circle(double radius) {\n    this.radius = radius;\n  }\n\n  @Override\n  double area() {\n    return Math.PI * radius * radius;\n  }\n\n  @Override\n  public String toString() {\n    return "Circle with area " + area();\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Shape[] shapes = { new Shape(), new Circle(3) };\n    for (Shape s : shapes) {\n      System.out.println(s);\n    }\n  }\n}',
    starterCode: 'class Animal {\n  String sound() {\n    return "...";\n  }\n}\n\nclass Dog extends Animal {\n  @Override\n  String sound() {\n    return "Woof";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Animal a = new Dog();\n    System.out.println(a.sound());\n  }\n}',
  },
  {
    slug: 'wrapper-classes-and-autoboxing',
    title: 'Wrapper Classes & Autoboxing',
    summary: 'Wrapping primitives as objects',
    explanation: [
      'Every primitive type has a matching wrapper class — int has Integer, double has Double — which wraps the value inside an object.',
      'Autoboxing automatically converts a primitive into its wrapper (and unboxing converts it back) whenever it is needed, such as when adding numbers to a generic collection like ArrayList<Integer>.',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    Integer boxed = 42;\n    int unboxed = boxed;\n    System.out.println("Boxed: " + boxed + ", unboxed: " + unboxed);\n\n    ArrayList<Integer> numbers = new ArrayList<>();\n    numbers.add(10);\n    numbers.add(20);\n    int sum = 0;\n    for (int n : numbers) {\n      sum += n;\n    }\n    System.out.println("Sum: " + sum);\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    Double price = 19.99;\n    double rawPrice = price;\n    System.out.println("Price: " + rawPrice);\n  }\n}',
  },
  {
    slug: 'stringbuilder',
    title: 'StringBuilder',
    summary: 'Efficiently building up text',
    explanation: [
      'Repeated + concatenation creates a new String each time, which can be slow when building text in a loop.',
      'StringBuilder solves this by growing one mutable buffer — call .append(...) as many times as you like, then .toString() (or just print it) when you are done.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    StringBuilder sb = new StringBuilder();\n    sb.append("Hello");\n    sb.append(", ");\n    sb.append("world");\n    sb.append("!");\n\n    for (int i = 1; i <= 3; i++) {\n      sb.append(" ").append(i);\n    }\n\n    System.out.println(sb.toString());\n    System.out.println("Length: " + sb.length());\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    StringBuilder sb = new StringBuilder();\n    sb.append("Java");\n    sb.append(" is");\n    sb.append(" fun");\n    System.out.println(sb.toString());\n  }\n}',
  },
  {
    slug: 'hashmap-and-hashset',
    title: 'HashMap & HashSet',
    summary: 'Key-value lookups and unique value sets',
    explanation: [
      'HashMap<K, V> from java.util stores key-value pairs — put(key, value) saves an entry, and get(key) retrieves it quickly.',
      'HashSet<T> stores only unique values with no particular order; adding the same value twice has no effect, which makes it great for membership checks with contains(...).',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> ages = new HashMap<>();\n    ages.put("Aria", 12);\n    ages.put("Sam", 15);\n    System.out.println("Aria is " + ages.get("Aria"));\n\n    for (String name : ages.keySet()) {\n      System.out.println(name + " -> " + ages.get(name));\n    }\n\n    HashSet<String> visited = new HashSet<>();\n    visited.add("Paris");\n    visited.add("Tokyo");\n    visited.add("Paris");\n    System.out.println("Unique cities: " + visited.size());\n    System.out.println("Visited Tokyo? " + visited.contains("Tokyo"));\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> scores = new HashMap<>();\n    scores.put("Alex", 90);\n    scores.put("Bea", 85);\n    System.out.println(scores.get("Alex"));\n\n    HashSet<Integer> uniqueNums = new HashSet<>();\n    uniqueNums.add(1);\n    uniqueNums.add(1);\n    uniqueNums.add(2);\n    System.out.println(uniqueNums.size());\n  }\n}',
  },
  {
    slug: 'comparable-and-comparator',
    title: 'Comparable & Comparator',
    summary: 'Defining natural and custom orderings',
    explanation: [
      'Implementing Comparable<T> and its compareTo(other) method gives a class a single "natural" ordering, which Collections.sort(list) will use automatically.',
      'A Comparator is a separate object you pass to Collections.sort(list, comparator) when you want a different ordering without changing the class itself.',
    ],
    example: 'import java.util.*;\n\nclass Person implements Comparable<Person> {\n  String name;\n  int age;\n\n  Person(String name, int age) {\n    this.name = name;\n    this.age = age;\n  }\n\n  public int compareTo(Person other) {\n    return this.age - other.age;\n  }\n\n  public String toString() {\n    return name + "(" + age + ")";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<Person> people = new ArrayList<>();\n    people.add(new Person("Sam", 30));\n    people.add(new Person("Aria", 12));\n    people.add(new Person("Beck", 21));\n\n    Collections.sort(people);\n    System.out.println("By age: " + people);\n\n    Collections.sort(people, new Comparator<Person>() {\n      public int compare(Person a, Person b) {\n        return a.name.compareTo(b.name);\n      }\n    });\n    System.out.println("By name: " + people);\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<Integer> nums = new ArrayList<>();\n    nums.add(5);\n    nums.add(1);\n    nums.add(3);\n    Collections.sort(nums);\n    System.out.println(nums);\n  }\n}',
  },
  {
    slug: 'nested-and-inner-classes',
    title: 'Nested & Inner Classes',
    summary: 'A class declared inside another class',
    explanation: [
      'A class can be declared inside another class. A static nested class behaves like an independent class that just lives inside another one for organisation, and does not need an outer instance to create.',
      'A non-static inner class is tied to an instance of the outer class, so it can directly access the outer object\'s fields — use this when the inner class genuinely depends on the outer object.',
    ],
    example: 'class Computer {\n  String brand;\n\n  Computer(String brand) {\n    this.brand = brand;\n  }\n\n  class Battery {\n    int percent = 100;\n\n    void describe() {\n      System.out.println(brand + "\'s battery is at " + percent + "%");\n    }\n  }\n\n  static class Specs {\n    int ramGb;\n\n    Specs(int ramGb) {\n      this.ramGb = ramGb;\n    }\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Computer laptop = new Computer("Zenith");\n    Computer.Battery battery = laptop.new Battery();\n    battery.describe();\n\n    Computer.Specs specs = new Computer.Specs(16);\n    System.out.println("RAM: " + specs.ramGb + "GB");\n  }\n}',
    starterCode: 'class Outer {\n  static class Inner {\n    void greet() {\n      System.out.println("Hello from the inner class");\n    }\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Outer.Inner inner = new Outer.Inner();\n    inner.greet();\n  }\n}',
  },
  {
    slug: 'varargs',
    title: 'Varargs',
    summary: 'Methods that accept any number of arguments',
    explanation: [
      'Writing int... numbers as a parameter lets a method accept zero, one, or many int arguments — inside the method, numbers behaves like a normal array.',
      'Varargs must be the last parameter in the method, and it saves you from writing several overloaded versions of the same method for different argument counts.',
    ],
    example: 'public class Main {\n  static int sum(int... numbers) {\n    int total = 0;\n    for (int n : numbers) {\n      total += n;\n    }\n    return total;\n  }\n\n  public static void main(String[] args) {\n    System.out.println(sum());\n    System.out.println(sum(5));\n    System.out.println(sum(1, 2, 3, 4, 5));\n  }\n}',
    starterCode: 'public class Main {\n  static String joinWords(String... words) {\n    StringBuilder sb = new StringBuilder();\n    for (String w : words) {\n      sb.append(w).append(" ");\n    }\n    return sb.toString().trim();\n  }\n\n  public static void main(String[] args) {\n    System.out.println(joinWords("Java", "is", "fun"));\n  }\n}',
  },
  {
    slug: 'try-with-resources',
    title: 'Try-With-Resources',
    summary: 'Automatically closing resources',
    explanation: [
      'A class that implements AutoCloseable defines a close() method describing how to clean itself up, such as closing a file or connection.',
      'Writing try (Resource r = ...) { ... } automatically calls r.close() when the block finishes, even if an exception is thrown, so you never forget to clean up.',
    ],
    example: 'class Connection implements AutoCloseable {\n  String name;\n\n  Connection(String name) {\n    this.name = name;\n    System.out.println("Opening " + name);\n  }\n\n  void query() {\n    System.out.println(name + " is running a query");\n  }\n\n  @Override\n  public void close() {\n    System.out.println("Closing " + name);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    try (Connection conn = new Connection("database")) {\n      conn.query();\n    }\n    System.out.println("Done");\n  }\n}',
    starterCode: 'class Logger implements AutoCloseable {\n  Logger() {\n    System.out.println("Logger opened");\n  }\n\n  void log(String message) {\n    System.out.println("LOG: " + message);\n  }\n\n  @Override\n  public void close() {\n    System.out.println("Logger closed");\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    try (Logger logger = new Logger()) {\n      logger.log("Starting up");\n    }\n  }\n}',
  },
  {
    slug: 'multidimensional-arrays',
    title: 'Multidimensional Arrays',
    summary: 'Grids of values with 2D arrays',
    explanation: [
      'A 2D array like int[][] grid = new int[3][4]; stores rows and columns, accessed with grid[row][col].',
      'You can loop over it with nested for loops — an outer loop for each row and an inner loop for each column within that row.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    int[][] grid = {\n      {1, 2, 3},\n      {4, 5, 6},\n      {7, 8, 9}\n    };\n\n    int total = 0;\n    for (int row = 0; row < grid.length; row++) {\n      for (int col = 0; col < grid[row].length; col++) {\n        System.out.print(grid[row][col] + " ");\n        total += grid[row][col];\n      }\n      System.out.println();\n    }\n    System.out.println("Total: " + total);\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    int[][] board = new int[2][2];\n    board[0][0] = 1;\n    board[0][1] = 2;\n    board[1][0] = 3;\n    board[1][1] = 4;\n\n    for (int[] row : board) {\n      for (int value : row) {\n        System.out.print(value + " ");\n      }\n      System.out.println();\n    }\n  }\n}',
  },
  {
    slug: 'lambda-expressions',
    title: 'Lambda Expressions',
    summary: 'Compact syntax for implementing functional interfaces',
    explanation: [
      'A functional interface has exactly one abstract method, and a lambda like (a, b) -> a + b provides that method\'s body without writing a full class.',
      'Lambdas are most often used where a small interface is expected, such as a Comparator for sorting or a custom interface you define yourself.',
    ],
    example: 'import java.util.*;\n\ninterface Operation {\n  int apply(int a, int b);\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Operation add = (a, b) -> a + b;\n    Operation multiply = (a, b) -> a * b;\n\n    System.out.println("Sum: " + add.apply(3, 4));\n    System.out.println("Product: " + multiply.apply(3, 4));\n\n    ArrayList<String> names = new ArrayList<>();\n    names.add("Charlie");\n    names.add("Alice");\n    names.add("Bob");\n    names.sort((a, b) -> a.compareTo(b));\n    System.out.println(names);\n  }\n}',
    starterCode: 'interface Greeter {\n  String greet(String name);\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Greeter g = name -> "Hello, " + name + "!";\n    System.out.println(g.greet("Aria"));\n  }\n}',
  },
  {
    slug: 'streams-api-basics',
    title: 'Streams API Basics',
    summary: 'Pipelines for filtering, mapping, and collecting',
    explanation: [
      'A stream lets you process a collection as a pipeline: list.stream() starts it, .filter(...) keeps matching elements, and .map(...) transforms each one.',
      'Calling .collect(Collectors.toList()) at the end gathers the results back into a normal List, letting you chain several operations cleanly instead of writing nested loops.',
    ],
    example: 'import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);\n\n    List<Integer> evenSquares = numbers.stream()\n      .filter(n -> n % 2 == 0)\n      .map(n -> n * n)\n      .collect(Collectors.toList());\n\n    System.out.println(evenSquares);\n\n    long count = numbers.stream().filter(n -> n > 5).count();\n    System.out.println("Greater than 5: " + count);\n  }\n}',
    starterCode: 'import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    List<String> names = Arrays.asList("Aria", "Sam", "Beck");\n    List<String> upper = names.stream()\n      .map(n -> n.toUpperCase())\n      .collect(Collectors.toList());\n    System.out.println(upper);\n  }\n}',
  },
  {
    slug: 'optional-class',
    title: 'The Optional Class',
    summary: 'Representing a value that might be absent',
    explanation: [
      'Optional<T> wraps a value that may or may not be present, making it explicit in the type that a result could be missing instead of silently returning null.',
      'Use .isPresent() to check before reading, or simply call .orElse(defaultValue) to get the value or a fallback in one step.',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  static Optional<String> findUser(int id) {\n    if (id == 1) {\n      return Optional.of("Aria");\n    }\n    return Optional.empty();\n  }\n\n  public static void main(String[] args) {\n    Optional<String> found = findUser(1);\n    if (found.isPresent()) {\n      System.out.println("Found: " + found.get());\n    }\n\n    Optional<String> missing = findUser(99);\n    System.out.println("Fallback: " + missing.orElse("Unknown user"));\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    Optional<Integer> maybeNumber = Optional.of(42);\n    System.out.println(maybeNumber.orElse(0));\n\n    Optional<Integer> empty = Optional.empty();\n    System.out.println(empty.orElse(-1));\n  }\n}',
  },
  {
    slug: 'packages-and-access-modifiers',
    title: 'Packages & Access Modifiers',
    summary: 'Organising code and controlling visibility',
    explanation: [
      'Packages group related classes together, similar to folders, and are declared with package com.example.app; at the top of a file.',
      'Java has four access levels: public (visible everywhere), protected (visible to the package and subclasses), default/package-private (visible only within the same package, the level you get when you write no modifier at all), and private (visible only inside the same class).',
    ],
    example: 'class BankAccount {\n  private double balance;\n  protected String owner;\n  String accountType;\n  public String bankName;\n\n  BankAccount(String owner, double balance) {\n    this.owner = owner;\n    this.balance = balance;\n    this.accountType = "Checking";\n    this.bankName = "Aria National Bank";\n  }\n\n  public double getBalance() {\n    return balance;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    BankAccount acct = new BankAccount("Sam", 250.0);\n    System.out.println(acct.owner + " has $" + acct.getBalance());\n    System.out.println("Account type: " + acct.accountType);\n    System.out.println("Bank: " + acct.bankName);\n  }\n}',
    starterCode: 'class Profile {\n  public String username;\n  private int secretPin;\n\n  Profile(String username, int secretPin) {\n    this.username = username;\n    this.secretPin = secretPin;\n  }\n\n  public boolean checkPin(int guess) {\n    return guess == secretPin;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Profile p = new Profile("aria123", 4242);\n    System.out.println(p.username);\n    System.out.println(p.checkPin(4242));\n  }\n}',
  },
  {
    slug: 'enums-with-fields-and-methods',
    title: 'Enums With Fields & Methods',
    summary: 'Enum constants that carry their own data',
    explanation: [
      'An enum is not limited to plain names — each constant can carry its own field values by passing arguments to a constructor, like MERCURY(3.3e23, 2.4e6).',
      'The enum can also define regular methods that every constant shares, letting you compute something different for each constant based on its own stored fields.',
    ],
    example: 'enum Planet {\n  MERCURY(3.303e23, 2.4397e6),\n  EARTH(5.976e24, 6.37814e6);\n\n  final double mass;\n  final double radius;\n\n  Planet(double mass, double radius) {\n    this.mass = mass;\n    this.radius = radius;\n  }\n\n  double surfaceGravity() {\n    final double G = 6.67300E-11;\n    return G * mass / (radius * radius);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    for (Planet p : Planet.values()) {\n      System.out.println(p + " gravity: " + p.surfaceGravity());\n    }\n  }\n}',
    starterCode: 'enum Coin {\n  PENNY(1),\n  NICKEL(5),\n  DIME(10);\n\n  final int cents;\n\n  Coin(int cents) {\n    this.cents = cents;\n  }\n\n  int valueInCents() {\n    return cents;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Coin c = Coin.DIME;\n    System.out.println(c + " is worth " + c.valueInCents() + " cents");\n  }\n}',
  },
  {
    slug: 'functional-interfaces',
    title: 'Functional Interfaces',
    summary: 'Interfaces with a single abstract method',
    explanation: [
      'A functional interface declares exactly one abstract method, which makes it possible to implement with a lambda expression instead of a full class.',
      'The @FunctionalInterface annotation is optional, but it tells the compiler to verify the interface really has just one abstract method, catching mistakes early.',
    ],
    example: '@FunctionalInterface\ninterface Transformer {\n  int transform(int value);\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Transformer square = n -> n * n;\n    Transformer increment = n -> n + 1;\n\n    System.out.println("Square of 5: " + square.transform(5));\n    System.out.println("Increment of 5: " + increment.transform(5));\n  }\n}',
    starterCode: '@FunctionalInterface\ninterface Validator {\n  boolean isValid(int value);\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Validator isPositive = n -> n > 0;\n    System.out.println(isPositive.isValid(10));\n    System.out.println(isPositive.isValid(-3));\n  }\n}',
  },
  {
    slug: 'method-references',
    title: 'Method References',
    summary: 'Pointing to an existing method with ::',
    explanation: [
      'When a lambda would simply call an existing method, you can use a method reference instead, written as ClassName::methodName or instance::methodName.',
      'Method references work anywhere a matching functional interface is expected, such as Consumer<String> or Function<String, Integer>, and often read more clearly than an equivalent lambda.',
    ],
    example: 'import java.util.*;\nimport java.util.function.*;\n\npublic class Main {\n  static void shout(String s) {\n    System.out.println(s.toUpperCase() + "!");\n  }\n\n  public static void main(String[] args) {\n    List<String> names = Arrays.asList("aria", "sam", "beck");\n\n    Consumer<String> printer = System.out::println;\n    printer.accept("Hello from a method reference");\n\n    names.forEach(Main::shout);\n\n    Function<String, Integer> lengthOf = String::length;\n    System.out.println("Length: " + lengthOf.apply("Java"));\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    List<String> words = Arrays.asList("banana", "apple", "cherry");\n    words.sort(String::compareTo);\n    System.out.println(words);\n    words.forEach(System.out::println);\n  }\n}',
  },
  {
    slug: 'stream-collectors',
    title: 'Stream Collectors',
    summary: 'Gathering stream results with Collectors',
    explanation: [
      'Collectors.toList() gathers a stream\'s elements back into a List, while Collectors.groupingBy(...) splits elements into a Map keyed by some property of each element.',
      'Collectors.joining(delimiter) concatenates a stream of strings into a single String, separated by the delimiter you provide.',
    ],
    example: 'import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    List<String> names = Arrays.asList("Aria", "Sam", "Beck", "Ana", "Max");\n\n    List<String> shortNames = names.stream()\n      .filter(n -> n.length() <= 3)\n      .collect(Collectors.toList());\n    System.out.println(shortNames);\n\n    Map<Integer, List<String>> byLength = names.stream()\n      .collect(Collectors.groupingBy(String::length));\n    System.out.println(byLength);\n\n    String joined = names.stream().collect(Collectors.joining(", "));\n    System.out.println(joined);\n  }\n}',
    starterCode: 'import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);\n    Map<Boolean, List<Integer>> grouped = nums.stream()\n      .collect(Collectors.groupingBy(n -> n % 2 == 0));\n    System.out.println(grouped);\n\n    String joined = nums.stream().map(String::valueOf).collect(Collectors.joining("-"));\n    System.out.println(joined);\n  }\n}',
  },
  {
    slug: 'string-formatting-java',
    title: 'String Formatting',
    summary: 'Formatting text with String.format and printf',
    explanation: [
      'String.format(pattern, args...) builds a formatted String using placeholders like %s (string), %d (integer), and %.2f (decimal with 2 places).',
      'System.out.printf(...) works the same way but prints directly instead of returning a String; %n inserts a platform-correct newline.',
    ],
    example: 'public class Main {\n  public static void main(String[] args) {\n    String name = "Aria";\n    int age = 12;\n    double gpa = 3.875;\n\n    String message = String.format("%s is %d years old", name, age);\n    System.out.println(message);\n\n    System.out.printf("GPA: %.2f%n", gpa);\n    System.out.printf("%-10s|%5d%n", name, age);\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) {\n    double price = 19.5;\n    System.out.printf("Price: $%.2f%n", price);\n    String label = String.format("Item #%03d", 7);\n    System.out.println(label);\n  }\n}',
  },
  {
    slug: 'record-classes',
    title: 'Record Classes',
    summary: 'Compact, immutable data carriers',
    explanation: [
      'Since Java 16, "record Point(int x, int y) {}" declares an immutable data class in one line, auto-generating a constructor, accessors like x()/y(), equals(), hashCode(), and toString().',
      'Because this sandbox compiles against an older Java release where records are not yet available, the example below hand-writes the equivalent class so you can see exactly what a record generates for you automatically on newer Java versions.',
    ],
    example: 'final class Point {\n  private final int x;\n  private final int y;\n\n  Point(int x, int y) {\n    this.x = x;\n    this.y = y;\n  }\n\n  int x() { return x; }\n  int y() { return y; }\n\n  double distanceFromOrigin() {\n    return Math.sqrt(x * x + y * y);\n  }\n\n  @Override\n  public boolean equals(Object obj) {\n    if (!(obj instanceof Point)) return false;\n    Point other = (Point) obj;\n    return x == other.x && y == other.y;\n  }\n\n  @Override\n  public String toString() {\n    return "Point[x=" + x + ", y=" + y + "]";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Point a = new Point(3, 4);\n    Point b = new Point(3, 4);\n\n    System.out.println(a);\n    System.out.println("x = " + a.x() + ", y = " + a.y());\n    System.out.println("Distance: " + a.distanceFromOrigin());\n    System.out.println("Equal: " + a.equals(b));\n  }\n}',
    starterCode: 'final class Range {\n  private final int low;\n  private final int high;\n\n  Range(int low, int high) {\n    this.low = low;\n    this.high = high;\n  }\n\n  int low() { return low; }\n  int high() { return high; }\n\n  int span() {\n    return high - low;\n  }\n\n  @Override\n  public String toString() {\n    return "Range[low=" + low + ", high=" + high + "]";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Range r = new Range(1, 10);\n    System.out.println(r);\n    System.out.println("Span: " + r.span());\n  }\n}',
  },
  {
    slug: 'sealed-classes',
    title: 'Sealed Classes',
    summary: 'Restricting which classes may extend or implement a type',
    explanation: [
      'Since Java 17, a sealed interface or class lists exactly which classes are allowed to implement or extend it using a permits clause, like "sealed interface Shape permits Circle, Square {}".',
      'This sandbox compiles against an older Java release where sealed types are not yet available, so the example below approximates the same closed hierarchy using a plain interface with only final implementing classes — the restriction is enforced by convention rather than the compiler.',
    ],
    example: 'interface Shape {}\n\nfinal class Circle implements Shape {\n  double radius;\n\n  Circle(double radius) {\n    this.radius = radius;\n  }\n\n  double area() {\n    return Math.PI * radius * radius;\n  }\n}\n\nfinal class Square implements Shape {\n  double side;\n\n  Square(double side) {\n    this.side = side;\n  }\n\n  double area() {\n    return side * side;\n  }\n}\n\npublic class Main {\n  static double areaOf(Shape shape) {\n    if (shape instanceof Circle) {\n      return ((Circle) shape).area();\n    } else if (shape instanceof Square) {\n      return ((Square) shape).area();\n    }\n    return 0;\n  }\n\n  public static void main(String[] args) {\n    Shape[] shapes = { new Circle(2), new Square(3) };\n    for (Shape s : shapes) {\n      System.out.println("Area: " + areaOf(s));\n    }\n  }\n}',
    starterCode: 'interface Vehicle {}\n\nfinal class Car implements Vehicle {\n  String describe() {\n    return "A car with four wheels";\n  }\n}\n\nfinal class Bike implements Vehicle {\n  String describe() {\n    return "A bike with two wheels";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Vehicle v = new Car();\n    if (v instanceof Car) {\n      System.out.println(((Car) v).describe());\n    }\n  }\n}',
  },
  {
    slug: 'multi-catch-exceptions',
    title: 'Multi-Catch Exceptions',
    summary: 'Catching several exception types in one block',
    explanation: [
      'A single catch block can handle more than one exception type by separating them with a pipe: catch (ArithmeticException | NumberFormatException e) { ... }.',
      'This avoids duplicating the same handling code across several catch blocks when multiple exception types should be treated the same way.',
    ],
    example: 'public class Main {\n  static void process(int choice) throws Exception {\n    if (choice == 1) {\n      throw new ArithmeticException("Cannot divide by zero");\n    } else if (choice == 2) {\n      throw new NumberFormatException("Not a valid number");\n    } else {\n      throw new Exception("Unknown failure");\n    }\n  }\n\n  public static void main(String[] args) {\n    for (int choice = 1; choice <= 3; choice++) {\n      try {\n        process(choice);\n      } catch (ArithmeticException | NumberFormatException e) {\n        System.out.println("Caught a math/format error: " + e.getMessage());\n      } catch (Exception e) {\n        System.out.println("Caught a general error: " + e.getMessage());\n      }\n    }\n  }\n}',
    starterCode: 'public class Main {\n  static void risky(boolean useIndex) {\n    if (useIndex) {\n      int[] arr = new int[2];\n      System.out.println(arr[5]);\n    } else {\n      String s = null;\n      System.out.println(s.length());\n    }\n  }\n\n  public static void main(String[] args) {\n    try {\n      risky(true);\n    } catch (ArrayIndexOutOfBoundsException | NullPointerException e) {\n      System.out.println("Caught: " + e.getClass().getSimpleName());\n    }\n  }\n}',
  },
  {
    slug: 'custom-exceptions-java',
    title: 'Custom Exceptions',
    summary: 'Defining your own exception types',
    explanation: [
      'You can define your own exception by extending Exception (a checked exception, which callers must handle or declare) or RuntimeException (unchecked, which callers may ignore).',
      'A custom exception usually just passes its message to the parent constructor with super(message), letting it carry a meaningful description specific to your application.',
    ],
    example: 'class InsufficientFundsException extends Exception {\n  InsufficientFundsException(String message) {\n    super(message);\n  }\n}\n\nclass Account {\n  double balance;\n\n  Account(double balance) {\n    this.balance = balance;\n  }\n\n  void withdraw(double amount) throws InsufficientFundsException {\n    if (amount > balance) {\n      throw new InsufficientFundsException("Cannot withdraw " + amount + ", balance is only " + balance);\n    }\n    balance -= amount;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Account acct = new Account(100);\n    try {\n      acct.withdraw(150);\n    } catch (InsufficientFundsException e) {\n      System.out.println("Error: " + e.getMessage());\n    }\n    System.out.println("Balance: " + acct.balance);\n  }\n}',
    starterCode: 'class NegativeAgeException extends RuntimeException {\n  NegativeAgeException(String message) {\n    super(message);\n  }\n}\n\npublic class Main {\n  static void setAge(int age) {\n    if (age < 0) {\n      throw new NegativeAgeException("Age cannot be negative: " + age);\n    }\n    System.out.println("Age set to " + age);\n  }\n\n  public static void main(String[] args) {\n    try {\n      setAge(-5);\n    } catch (NegativeAgeException e) {\n      System.out.println("Caught: " + e.getMessage());\n    }\n  }\n}',
  },
  {
    slug: 'equals-and-hashcode',
    title: 'equals() & hashCode()',
    summary: 'Defining what makes two objects equal',
    explanation: [
      'By default, equals() compares object references, not contents, so two separately created objects with the same data are considered unequal unless you override equals() to compare fields.',
      'Whenever you override equals(), you must also override hashCode() so that equal objects produce the same hash code — otherwise collections like HashSet and HashMap will behave incorrectly.',
    ],
    example: 'import java.util.*;\n\nclass Point {\n  int x;\n  int y;\n\n  Point(int x, int y) {\n    this.x = x;\n    this.y = y;\n  }\n\n  @Override\n  public boolean equals(Object obj) {\n    if (this == obj) return true;\n    if (!(obj instanceof Point)) return false;\n    Point other = (Point) obj;\n    return this.x == other.x && this.y == other.y;\n  }\n\n  @Override\n  public int hashCode() {\n    return Objects.hash(x, y);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Point a = new Point(1, 2);\n    Point b = new Point(1, 2);\n    Point c = new Point(9, 9);\n\n    System.out.println("a.equals(b): " + a.equals(b));\n    System.out.println("a.equals(c): " + a.equals(c));\n\n    HashSet<Point> points = new HashSet<>();\n    points.add(a);\n    points.add(b);\n    points.add(c);\n    System.out.println("Unique points: " + points.size());\n  }\n}',
    starterCode: 'import java.util.*;\n\nclass Pair {\n  String key;\n  int value;\n\n  Pair(String key, int value) {\n    this.key = key;\n    this.value = value;\n  }\n\n  @Override\n  public boolean equals(Object obj) {\n    if (!(obj instanceof Pair)) return false;\n    Pair other = (Pair) obj;\n    return key.equals(other.key) && value == other.value;\n  }\n\n  @Override\n  public int hashCode() {\n    return Objects.hash(key, value);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Pair p1 = new Pair("a", 1);\n    Pair p2 = new Pair("a", 1);\n    System.out.println(p1.equals(p2));\n    System.out.println(p1.hashCode() == p2.hashCode());\n  }\n}',
  },
  {
    slug: 'immutable-objects-java',
    title: 'Immutable Objects',
    summary: 'Designing classes whose state cannot change',
    explanation: [
      'An immutable class marks its fields private and final, sets them only in the constructor, and provides no setters — once created, the object\'s state can never change.',
      'Instead of mutating an immutable object, methods like translate(...) return a brand new instance with the updated values, leaving the original untouched.',
    ],
    example: 'final class ImmutablePoint {\n  private final int x;\n  private final int y;\n\n  ImmutablePoint(int x, int y) {\n    this.x = x;\n    this.y = y;\n  }\n\n  int getX() {\n    return x;\n  }\n\n  int getY() {\n    return y;\n  }\n\n  ImmutablePoint translate(int dx, int dy) {\n    return new ImmutablePoint(x + dx, y + dy);\n  }\n\n  @Override\n  public String toString() {\n    return "(" + x + ", " + y + ")";\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    ImmutablePoint p1 = new ImmutablePoint(1, 1);\n    ImmutablePoint p2 = p1.translate(2, 3);\n\n    System.out.println("p1: " + p1);\n    System.out.println("p2: " + p2);\n  }\n}',
    starterCode: 'final class ImmutableName {\n  private final String first;\n  private final String last;\n\n  ImmutableName(String first, String last) {\n    this.first = first;\n    this.last = last;\n  }\n\n  String full() {\n    return first + " " + last;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    ImmutableName name = new ImmutableName("Aria", "Lee");\n    System.out.println(name.full());\n  }\n}',
  },
  {
    slug: 'builder-pattern',
    title: 'Builder Pattern',
    summary: 'Constructing complex objects step by step',
    explanation: [
      'The builder pattern uses a separate Builder class with chainable setter-style methods (each returning this) to configure an object piece by piece before finally calling build().',
      'This avoids constructors with long parameter lists or many overloads, and makes the calling code self-documenting since each option is named explicitly.',
    ],
    example: 'class Pizza {\n  private final String size;\n  private final boolean cheese;\n  private final boolean pepperoni;\n\n  private Pizza(Builder builder) {\n    this.size = builder.size;\n    this.cheese = builder.cheese;\n    this.pepperoni = builder.pepperoni;\n  }\n\n  @Override\n  public String toString() {\n    return size + " pizza, cheese=" + cheese + ", pepperoni=" + pepperoni;\n  }\n\n  static class Builder {\n    private String size = "medium";\n    private boolean cheese = false;\n    private boolean pepperoni = false;\n\n    Builder size(String size) {\n      this.size = size;\n      return this;\n    }\n\n    Builder cheese(boolean cheese) {\n      this.cheese = cheese;\n      return this;\n    }\n\n    Builder pepperoni(boolean pepperoni) {\n      this.pepperoni = pepperoni;\n      return this;\n    }\n\n    Pizza build() {\n      return new Pizza(this);\n    }\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Pizza pizza = new Pizza.Builder()\n      .size("large")\n      .cheese(true)\n      .pepperoni(true)\n      .build();\n    System.out.println(pizza);\n  }\n}',
    starterCode: 'class Sandwich {\n  private final String bread;\n  private final boolean lettuce;\n\n  private Sandwich(Builder builder) {\n    this.bread = builder.bread;\n    this.lettuce = builder.lettuce;\n  }\n\n  @Override\n  public String toString() {\n    return bread + " sandwich, lettuce=" + lettuce;\n  }\n\n  static class Builder {\n    private String bread = "white";\n    private boolean lettuce = false;\n\n    Builder bread(String bread) {\n      this.bread = bread;\n      return this;\n    }\n\n    Builder lettuce(boolean lettuce) {\n      this.lettuce = lettuce;\n      return this;\n    }\n\n    Sandwich build() {\n      return new Sandwich(this);\n    }\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Sandwich s = new Sandwich.Builder().bread("rye").lettuce(true).build();\n    System.out.println(s);\n  }\n}',
  },
  {
    slug: 'singleton-pattern',
    title: 'Singleton Pattern',
    summary: 'Ensuring a class has only one instance',
    explanation: [
      'A singleton hides its constructor as private and exposes a static getInstance() method that creates the single instance the first time it is called and returns that same instance every time after.',
      'This is useful for shared resources like configuration or logging, where having more than one instance would not make sense.',
    ],
    example: 'class Configuration {\n  private static Configuration instance;\n  private String environment;\n\n  private Configuration() {\n    this.environment = "production";\n  }\n\n  static Configuration getInstance() {\n    if (instance == null) {\n      instance = new Configuration();\n    }\n    return instance;\n  }\n\n  String getEnvironment() {\n    return environment;\n  }\n\n  void setEnvironment(String environment) {\n    this.environment = environment;\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Configuration a = Configuration.getInstance();\n    Configuration b = Configuration.getInstance();\n\n    a.setEnvironment("staging");\n    System.out.println("b\'s environment: " + b.getEnvironment());\n    System.out.println("Same instance: " + (a == b));\n  }\n}',
    starterCode: 'class Logger {\n  private static Logger instance;\n  private int logCount = 0;\n\n  private Logger() {}\n\n  static Logger getInstance() {\n    if (instance == null) {\n      instance = new Logger();\n    }\n    return instance;\n  }\n\n  void log(String message) {\n    logCount++;\n    System.out.println("[" + logCount + "] " + message);\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) {\n    Logger.getInstance().log("Starting up");\n    Logger.getInstance().log("Still running");\n  }\n}',
  },
  {
    slug: 'threads-basics-java',
    title: 'Threads Basics',
    summary: 'Running code concurrently with Thread and Runnable',
    explanation: [
      'A Runnable describes a task to run; wrapping it in new Thread(runnable) and calling .start() runs that task on its own thread, separate from the main thread.',
      'Calling .join() on a thread pauses the current thread until the other one finishes, which is useful when you need its work done before continuing.',
    ],
    example: 'class CounterTask implements Runnable {\n  String name;\n\n  CounterTask(String name) {\n    this.name = name;\n  }\n\n  @Override\n  public void run() {\n    for (int i = 1; i <= 3; i++) {\n      System.out.println(name + " count: " + i);\n    }\n  }\n}\n\npublic class Main {\n  public static void main(String[] args) throws InterruptedException {\n    Thread t1 = new Thread(new CounterTask("Worker-A"));\n    Thread t2 = new Thread(new CounterTask("Worker-B"));\n\n    t1.start();\n    t1.join();\n    t2.start();\n    t2.join();\n\n    System.out.println("All threads finished");\n  }\n}',
    starterCode: 'public class Main {\n  public static void main(String[] args) throws InterruptedException {\n    Runnable task = () -> System.out.println("Running on: " + Thread.currentThread().getName());\n    Thread thread = new Thread(task, "MyThread");\n    thread.start();\n    thread.join();\n    System.out.println("Done");\n  }\n}',
  },
  {
    slug: 'treemap-and-treeset',
    title: 'TreeMap & TreeSet',
    summary: 'Collections that keep their elements sorted',
    explanation: [
      'TreeMap<K, V> behaves like HashMap but always keeps its keys sorted, so iterating over keySet() visits them in ascending order, and firstKey()/lastKey() give the smallest and largest keys.',
      'TreeSet<T> behaves like HashSet but keeps its elements sorted, with first() and last() giving the smallest and largest values directly.',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    TreeMap<String, Integer> scores = new TreeMap<>();\n    scores.put("Beck", 85);\n    scores.put("Aria", 92);\n    scores.put("Sam", 78);\n\n    for (String name : scores.keySet()) {\n      System.out.println(name + " -> " + scores.get(name));\n    }\n    System.out.println("Lowest name: " + scores.firstKey());\n    System.out.println("Highest name: " + scores.lastKey());\n\n    TreeSet<Integer> numbers = new TreeSet<>();\n    numbers.add(5);\n    numbers.add(1);\n    numbers.add(9);\n    numbers.add(3);\n    System.out.println("Sorted: " + numbers);\n    System.out.println("Smallest: " + numbers.first());\n    System.out.println("Largest: " + numbers.last());\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    TreeSet<String> names = new TreeSet<>();\n    names.add("Charlie");\n    names.add("Alice");\n    names.add("Bob");\n    System.out.println(names);\n\n    TreeMap<Integer, String> ranks = new TreeMap<>();\n    ranks.put(2, "Silver");\n    ranks.put(1, "Gold");\n    ranks.put(3, "Bronze");\n    System.out.println(ranks);\n  }\n}',
  },
  {
    slug: 'queue-and-deque-java',
    title: 'Queue & Deque',
    summary: 'First-in-first-out and double-ended collections',
    explanation: [
      'Queue<T> models a first-in-first-out line: offer(value) adds to the back, poll() removes and returns the front, and peek() looks at the front without removing it. ArrayDeque is a common, efficient implementation.',
      'Deque<T> ("double-ended queue") extends this idea to both ends — addFirst/addLast, removeFirst/removeLast — and can also be used as a stack with push() and pop(), which both operate on the front.',
    ],
    example: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    Queue<String> queue = new ArrayDeque<>();\n    queue.offer("first");\n    queue.offer("second");\n    queue.offer("third");\n\n    System.out.println("Front: " + queue.peek());\n    while (!queue.isEmpty()) {\n      System.out.println("Serving: " + queue.poll());\n    }\n\n    Deque<Integer> deque = new ArrayDeque<>();\n    deque.addFirst(2);\n    deque.addFirst(1);\n    deque.addLast(3);\n    System.out.println("Deque: " + deque);\n    System.out.println("First: " + deque.removeFirst());\n    System.out.println("Last: " + deque.removeLast());\n  }\n}',
    starterCode: 'import java.util.*;\n\npublic class Main {\n  public static void main(String[] args) {\n    Deque<String> stack = new ArrayDeque<>();\n    stack.push("bottom");\n    stack.push("middle");\n    stack.push("top");\n    System.out.println(stack.pop());\n    System.out.println(stack.pop());\n  }\n}',
  },
]
