import type { CodingLesson } from '../languages'

export const javascript: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to JavaScript',
    summary: 'Making web pages interactive — and printing your first output',
    explanation: [
      'JavaScript is the programming language of the web. It runs in the browser and can react to clicks, update content, fetch data, and much more.',
      'console.log(...) prints a value to the console — perfect for checking what your code is doing. In this playground, anything you log appears in the Output panel.',
      'Statements usually end with a semicolon ; (optional, but good practice).',
    ],
    example: "console.log('Hello, world!');\nconsole.log(2 + 3 * 4);",
    starterCode: "console.log('Hello, world!');\nconsole.log(10 - 4);",
  },
  {
    slug: 'variables',
    title: 'Variables & Data Types',
    summary: 'Storing values with let and const',
    explanation: [
      'Variables store values so you can use them later. Use let for values that may change, and const for values that should not be reassigned.',
      'JavaScript has several basic types: numbers (42), strings ("hello"), booleans (true/false), arrays ([1,2,3]), and objects ({name: "Aria"}).',
      'Template strings — backticks with ${...} — let you mix variables into text easily.',
    ],
    example: "const name = 'Aria';\nlet age = 12;\nage = age + 1;\nconsole.log(`${name} is now ${age} years old`);",
    starterCode: "const city = 'Kathmandu';\nlet temperature = 22;\nconsole.log(`${city} is ${temperature}°C today`);",
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Making decisions with if, else if, and else',
    explanation: [
      'if statements run code only when a condition is true. else if checks another condition, and else runs when nothing else matched.',
      'Comparison operators like ===, !==, >, and < produce true or false, which conditionals use to decide what to do.',
    ],
    example: "const score = 82;\nif (score >= 90) {\n  console.log('Grade: A');\n} else if (score >= 75) {\n  console.log('Grade: B');\n} else {\n  console.log('Keep practising!');\n}",
    starterCode: "const temperature = 30;\nif (temperature > 25) {\n  console.log('It is warm');\n} else {\n  console.log('It is cool');\n}",
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating actions with for and while',
    explanation: [
      'A for loop repeats code a set number of times: for (let i = 0; i < 5; i++) { ... }.',
      'A while loop repeats as long as a condition stays true — useful when you do not know in advance how many times you need to repeat.',
      'Arrays also have handy loop-like methods such as .forEach(item => ...) and .map(item => ...).',
    ],
    example: "for (let i = 1; i <= 5; i++) {\n  console.log(`Step ${i}`);\n}\n\nconst fruits = ['apple', 'banana', 'mango'];\nfruits.forEach(f => console.log(f.toUpperCase()));",
    starterCode: "for (let i = 1; i <= 3; i++) {\n  console.log(`Count: ${i}`);\n}",
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Packaging reusable blocks of logic',
    explanation: [
      'A function is a reusable block of code. Define one with function name(params) { ... } or as an arrow function const name = (params) => { ... }.',
      'Functions can take inputs (parameters) and give back an output with return.',
    ],
    example: "function double(n) {\n  return n * 2;\n}\n\nconst greet = (name) => `Hello, ${name}!`;\n\nconsole.log(double(21));\nconsole.log(greet('World'));",
    starterCode: "function square(n) {\n  return n * n;\n}\nconsole.log(square(6));",
  },
  {
    slug: 'arrays-and-objects',
    title: 'Arrays & Objects',
    summary: 'Working with collections and structured data',
    explanation: [
      'Arrays hold ordered lists of values: const nums = [1, 2, 3]. Access items with nums[0], get the length with nums.length.',
      'Objects hold named properties: const dog = { name: "Rex", age: 3 }. Access them with dog.name or dog["name"].',
      'Methods like .map(), .filter(), and .reduce() transform arrays without writing manual loops.',
    ],
    example: "const numbers = [1, 2, 3, 4, 5];\nconst doubled = numbers.map(n => n * 2);\nconst evens = numbers.filter(n => n % 2 === 0);\nconsole.log(doubled);\nconsole.log(evens);\n\nconst student = { name: 'Aria', grade: 7 };\nconsole.log(`${student.name} is in grade ${student.grade}`);",
    starterCode: "const scores = [70, 85, 92, 60];\nconst passing = scores.filter(s => s >= 70);\nconsole.log(passing);",
  },
  {
    slug: 'dom-basics',
    title: 'DOM Basics',
    summary: 'Creating and inspecting page elements with the DOM',
    explanation: [
      'The DOM (Document Object Model) is how JavaScript sees and changes a web page — every tag becomes an object you can read and modify.',
      'document.createElement(tag) makes a new element, .textContent sets its text, and parent.appendChild(child) attaches it to the page.',
      'document.querySelector(selector) finds the first matching element, and .classList lets you add, remove, or toggle CSS classes on it.',
    ],
    example: "const card = document.createElement('div');\ncard.textContent = 'Hello DOM!';\ncard.classList.add('card', 'highlight');\n\nconst container = document.createElement('section');\ncontainer.appendChild(card);\n\nconsole.log(container.children.length);\nconsole.log(card.textContent);\nconsole.log(card.classList.contains('highlight'));",
    starterCode: "const item = document.createElement('li');\nitem.textContent = 'Learn the DOM';\nitem.classList.add('todo-item');\n\nconsole.log(item.textContent);\nconsole.log(item.classList.contains('todo-item'));",
  },
  {
    slug: 'events',
    title: 'Events & Callbacks',
    summary: 'Reacting to things happening with addEventListener and callbacks',
    explanation: [
      'In the browser, element.addEventListener("click", callback) runs your callback function whenever that event happens — buttons get clicked, forms get submitted, keys get pressed.',
      'A callback is just a function passed as a value to be called later. Array methods like .forEach(item => ...) use the same idea: they call your function once for each item.',
      'This "tell me when it happens" pattern is everywhere in JavaScript, from button clicks to network responses.',
    ],
    example: "// Simulating how addEventListener works: store a callback, call it later\nfunction onClick(callback) {\n  console.log('Button was clicked!');\n  callback('click');\n}\n\nonClick((eventType) => console.log(`Handled event: ${eventType}`));\n\n// The same callback pattern powers array iteration\nconst names = ['Aria', 'Kiran', 'Maya'];\nnames.forEach((name, index) => {\n  console.log(`${index}: Hello, ${name}`);\n});",
    starterCode: "function onHover(callback) {\n  callback('mouseover');\n}\n\nonHover((eventType) => console.log(`Triggered: ${eventType}`));\n\n['red', 'green', 'blue'].forEach(color => console.log(`Color: ${color}`));",
  },
  {
    slug: 'destructuring-and-spread',
    title: 'Destructuring & Spread',
    summary: 'Unpacking values and combining collections with concise syntax',
    explanation: [
      'Destructuring unpacks values from arrays or objects into variables in one step: const [a, b] = [1, 2] or const { name } = person.',
      'The spread operator ... expands an array or object into individual elements — handy for copying, merging, or passing many arguments at once.',
      'Together they make working with collections shorter and easier to read than manual indexing.',
    ],
    example: "const point = [10, 20];\nconst [x, y] = point;\nconsole.log(`x=${x}, y=${y}`);\n\nconst person = { name: 'Aria', age: 12, city: 'Kathmandu' };\nconst { name, ...rest } = person;\nconsole.log(name);\nconsole.log(rest);\n\nconst nums = [1, 2, 3];\nconst moreNums = [...nums, 4, 5];\nconsole.log(moreNums);\n\nconst defaults = { theme: 'light', size: 'medium' };\nconst settings = { ...defaults, size: 'large' };\nconsole.log(settings);",
    starterCode: "const colors = ['red', 'green', 'blue'];\nconst [first, ...others] = colors;\nconsole.log(first);\nconsole.log(others);\n\nconst base = { a: 1, b: 2 };\nconst extended = { ...base, c: 3 };\nconsole.log(extended);",
  },
  {
    slug: 'higher-order-functions',
    title: 'Higher-Order Functions',
    summary: 'Functions that take or return other functions',
    explanation: [
      'A higher-order function either accepts a function as an argument or returns a new function — JavaScript treats functions as ordinary values that can be passed around.',
      '.map() transforms each item, .filter() keeps items that pass a test, and .reduce() combines all items into a single result; chaining them lets you express complex transformations clearly.',
      'Functions can also build and return other functions, which is useful for creating customized, reusable behavior.',
    ],
    example: "const numbers = [1, 2, 3, 4, 5, 6];\n\nconst total = numbers\n  .filter(n => n % 2 === 0)\n  .map(n => n * 10)\n  .reduce((sum, n) => sum + n, 0);\n\nconsole.log(total);\n\nfunction makeMultiplier(factor) {\n  return (n) => n * factor;\n}\n\nconst triple = makeMultiplier(3);\nconsole.log(triple(7));\nconsole.log(numbers.map(triple));",
    starterCode: "const prices = [5, 12, 8, 20];\nconst withTax = prices.map(p => p * 1.1);\nconst total = withTax.reduce((sum, p) => sum + p, 0);\nconsole.log(withTax);\nconsole.log(total);",
  },
  {
    slug: 'promises-and-async',
    title: 'Promises & Async/Await',
    summary: 'Handling work that finishes later, in order',
    explanation: [
      'A Promise represents a value that will be available later — it starts "pending" and then resolves (success) or rejects (failure).',
      'async functions let you write asynchronous code that reads top-to-bottom: await pauses the function until a Promise resolves, without blocking the rest of the program.',
      'Code after setTimeout or other async calls runs later, which is why the console.log order can look surprising at first — async/await makes that order easier to follow.',
    ],
    example: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function run() {\n  console.log('start');\n  const first = await wait(10, 'first result');\n  console.log(first);\n  const second = await wait(10, 'second result');\n  console.log(second);\n  console.log('done');\n}\n\nrun();\nconsole.log('this logs before the async work finishes');",
    starterCode: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function run() {\n  const message = await wait(10, 'Loaded!');\n  console.log(message);\n}\n\nrun();\nconsole.log('Loading...');",
  },
  {
    slug: 'classes',
    title: 'Classes',
    summary: 'Blueprints for creating objects with shared behavior',
    explanation: [
      'A class is a blueprint for objects: class Dog { constructor(name) { this.name = name } } defines what every dog instance will have.',
      'The constructor runs when you create a new instance with new, and methods defined inside the class become functions every instance can call.',
      'Classes group related data and behavior together, making it easier to create many similar objects.',
    ],
    example: "class Animal {\n  constructor(name, sound) {\n    this.name = name;\n    this.sound = sound;\n  }\n\n  speak() {\n    return `${this.name} says ${this.sound}`;\n  }\n}\n\nclass Dog extends Animal {\n  constructor(name) {\n    super(name, 'Woof');\n  }\n\n  fetch() {\n    return `${this.name} fetches the ball!`;\n  }\n}\n\nconst rex = new Dog('Rex');\nconsole.log(rex.speak());\nconsole.log(rex.fetch());\nconsole.log(rex instanceof Animal);",
    starterCode: "class Counter {\n  constructor() {\n    this.count = 0;\n  }\n\n  increment() {\n    this.count += 1;\n    return this.count;\n  }\n}\n\nconst counter = new Counter();\nconsole.log(counter.increment());\nconsole.log(counter.increment());\nconsole.log(counter.count);",
  },
  {
    slug: 'error-handling',
    title: 'Error Handling',
    summary: 'Dealing gracefully with things that go wrong',
    explanation: [
      'try { ... } catch (error) { ... } lets you run risky code and handle any error it throws instead of crashing the program.',
      'You can throw your own errors with throw new Error("message") to signal that something went wrong in a way callers can catch.',
      'finally { ... } runs no matter what — whether the code succeeded, failed, or threw — which is useful for cleanup.',
    ],
    example: "function parsePositiveNumber(value) {\n  const n = Number(value);\n  if (Number.isNaN(n)) {\n    throw new Error(`\"${value}\" is not a number`);\n  }\n  if (n <= 0) {\n    throw new Error(`${n} is not positive`);\n  }\n  return n;\n}\n\nfor (const input of ['12', 'abc', '-5']) {\n  try {\n    const n = parsePositiveNumber(input);\n    console.log(`Parsed: ${n}`);\n  } catch (error) {\n    console.log(`Error: ${error.message}`);\n  } finally {\n    console.log(`Finished checking \"${input}\"`);\n  }\n}",
    starterCode: "function divide(a, b) {\n  if (b === 0) {\n    throw new Error('Cannot divide by zero');\n  }\n  return a / b;\n}\n\ntry {\n  console.log(divide(10, 2));\n  console.log(divide(10, 0));\n} catch (error) {\n  console.log(`Caught: ${error.message}`);\n}",
  },
  {
    slug: 'closures-and-scope',
    title: 'Closures & Scope',
    summary: 'How inner functions remember the variables around them',
    explanation: [
      'Lexical scope means a function can see the variables that were in scope where it was defined — including variables from any enclosing (outer) function.',
      'A closure happens when an inner function keeps access to its outer function\'s variables even after that outer function has finished running. The function "remembers" its birthplace.',
      'This lets you create private state: a variable that only specific functions can read or change, with no other code able to reach in and mess with it directly.',
    ],
    example: "function makeCounter() {\n  let count = 0;\n  return () => {\n    count++;\n    return count;\n  };\n}\n\nconst counterA = makeCounter();\nconst counterB = makeCounter();\n\nconsole.log(counterA());\nconsole.log(counterA());\nconsole.log(counterA());\nconsole.log(counterB());",
    starterCode: "function makeGreeter(greeting) {\n  return (name) => `${greeting}, ${name}!`;\n}\n\nconst sayHello = makeGreeter('Hello');\nconst sayHowdy = makeGreeter('Howdy');\n\nconsole.log(sayHello('Aria'));\nconsole.log(sayHowdy('Kiran'));",
  },
  {
    slug: 'type-coercion-and-truthy-falsy',
    title: 'Type Coercion & Truthy/Falsy',
    summary: 'How JavaScript converts types automatically, and which values count as true or false',
    explanation: [
      'JavaScript often converts values between types automatically — this is called implicit coercion. The + operator prefers strings (so \'5\' + 1 becomes \'51\'), while - forces both sides to numbers (so \'5\' - 1 becomes 4).',
      'Every value is either "truthy" or "falsy" when used in a condition. There are only a few falsy values: 0, \'\' (empty string), null, undefined, NaN, and false — everything else is truthy.',
      'Knowing these rules helps you avoid confusing bugs, like accidentally concatenating numbers instead of adding them.',
    ],
    example: "console.log('5' + 1);\nconsole.log('5' - 1);\nconsole.log('5' + 1 + 1);\nconsole.log(1 + 1 + '5');\n\nconst falsyValues = [0, '', null, undefined, NaN, false];\nfor (const value of falsyValues) {\n  console.log(`${JSON.stringify(value)} is falsy: ${!value}`);\n}\n\nconsole.log(Boolean('hello'));\nconsole.log(Boolean(0));\nconsole.log(Boolean('0'));",
    starterCode: "console.log('3' + 4);\nconsole.log('3' - 4);\nconsole.log(Boolean(''));\nconsole.log(Boolean('not empty'));",
  },
  {
    slug: 'switch-statements',
    title: 'Switch Statements',
    summary: 'A cleaner way to handle many possible values for one variable',
    explanation: [
      'A switch statement compares one value against several possible cases, which can be tidier than a long chain of else if statements.',
      'Each case ends with break so execution does not "fall through" into the next case; default runs when nothing else matched.',
      'switch is most useful when you are checking the same variable against many exact values.',
    ],
    example: "function describeDay(day) {\n  switch (day) {\n    case 'Sat':\n    case 'Sun':\n      return 'Weekend!';\n    case 'Mon':\n      return 'Start of the week';\n    case 'Fri':\n      return 'Almost the weekend';\n    default:\n      return 'A regular weekday';\n  }\n}\n\nconsole.log(describeDay('Sat'));\nconsole.log(describeDay('Mon'));\nconsole.log(describeDay('Wed'));",
    starterCode: "const fruit = 'banana';\n\nswitch (fruit) {\n  case 'apple':\n    console.log('Crunchy!');\n    break;\n  case 'banana':\n    console.log('Soft and sweet!');\n    break;\n  default:\n    console.log('Not sure about that one.');\n}",
  },
  {
    slug: 'optional-chaining-and-nullish-coalescing',
    title: 'Optional Chaining & Nullish Coalescing',
    summary: 'Safely reading nested properties and providing fallback values',
    explanation: [
      'Optional chaining ?. lets you safely read a property that might not exist — if anything before the ?. is null or undefined, the whole expression short-circuits to undefined instead of throwing an error.',
      'The nullish coalescing operator ?? provides a fallback value, but only when the left side is null or undefined (unlike ||, which also replaces 0 or \'\').',
      'Together they make working with optional or incomplete data much safer.',
    ],
    example: "const user = {\n  name: 'Aria',\n  address: { city: 'Kathmandu' },\n};\n\nconsole.log(user.address?.city);\nconsole.log(user.address?.zip);\nconsole.log(user.contact?.email);\n\nconst nickname = user.nickname ?? 'Anonymous';\nconsole.log(nickname);\n\nconst visits = 0;\nconsole.log(visits ?? 10);\nconsole.log(visits || 10);",
    starterCode: "const profile = { name: 'Kiran' };\n\nconsole.log(profile.social?.twitter);\n\nconst age = profile.age ?? 'unknown';\nconsole.log(age);",
  },
  {
    slug: 'template-literals-advanced',
    title: 'Template Literals In Depth',
    summary: 'Multiline strings and tagged templates for processing string parts',
    explanation: [
      'Template literals (backtick strings) can span multiple lines naturally, without needing special newline characters.',
      'A tagged template is a function placed right before a template literal — it receives the literal text pieces and the interpolated values separately, letting you customize how the string gets built.',
      'Tagged templates are how libraries implement things like automatic escaping or custom formatting.',
    ],
    example: "const name = 'Aria';\nconst poem = `Roses are red,\nViolets are blue,\nHello, ${name},\nThis line is new too!`;\nconsole.log(poem);\n\nfunction shout(strings, ...values) {\n  return strings.reduce((result, str, i) => {\n    const value = values[i] !== undefined ? String(values[i]).toUpperCase() : '';\n    return result + str + value;\n  }, '');\n}\n\nconst place = 'Kathmandu';\nconsole.log(shout`Welcome to ${place}, traveler!`);",
    starterCode: "const item = 'sandwich';\nconst price = 5;\n\nconst receipt = `Item: ${item}\nPrice: $${price}`;\nconsole.log(receipt);",
  },
  {
    slug: 'array-methods-in-depth',
    title: 'Array Methods In Depth',
    summary: 'find, some, every, flat, and flatMap for searching and reshaping arrays',
    explanation: [
      '.find() returns the first element that passes a test (or undefined if none do); .some() and .every() return true/false depending on whether any or all elements pass a test.',
      '.flat() flattens nested arrays by one level (or more, if you pass a depth), and .flatMap() maps each element and flattens the result in one step.',
      'These build on .map(), .filter(), and .reduce() to cover more searching and reshaping scenarios.',
    ],
    example: "const numbers = [3, 7, 10, 15, 22];\n\nconsole.log(numbers.find(n => n > 9));\nconsole.log(numbers.some(n => n > 20));\nconsole.log(numbers.every(n => n > 0));\n\nconst nested = [[1, 2], [3, 4], [5]];\nconsole.log(nested.flat());\n\nconst sentences = ['hello world', 'have a nice day'];\nconst words = sentences.flatMap(s => s.split(' '));\nconsole.log(words);",
    starterCode: "const ages = [12, 17, 25, 9];\nconsole.log(ages.find(a => a >= 18));\nconsole.log(ages.some(a => a >= 18));\nconsole.log(ages.every(a => a >= 18));",
  },
  {
    slug: 'set-and-map',
    title: 'Set & Map',
    summary: 'Collections for unique values and flexible key-value pairs',
    explanation: [
      'A Set stores only unique values — adding a duplicate has no effect, which makes it perfect for removing duplicates or tracking membership.',
      'A Map stores key-value pairs like an object, but keys can be any type (not just strings) and Map keeps track of its size and insertion order reliably.',
      'Use .add()/.has() with Set, and .set()/.get()/.has() with Map.',
    ],
    example: "const uniqueNumbers = new Set([1, 2, 2, 3, 3, 3]);\nconsole.log(uniqueNumbers.size);\nconsole.log([...uniqueNumbers]);\nconsole.log(uniqueNumbers.has(2));\n\nconst scores = new Map();\nscores.set('Aria', 95);\nscores.set('Kiran', 88);\nconsole.log(scores.get('Aria'));\nconsole.log(scores.has('Maya'));\nconsole.log(scores.size);\n\nfor (const [name, score] of scores) {\n  console.log(`${name}: ${score}`);\n}",
    starterCode: "const colors = new Set(['red', 'blue', 'red', 'green']);\nconsole.log([...colors]);\n\nconst ages = new Map();\nages.set('Aria', 12);\nages.set('Kiran', 13);\nconsole.log(ages.get('Kiran'));",
  },
  {
    slug: 'json-basics',
    title: 'JSON Basics',
    summary: 'Converting values to JSON text and back',
    explanation: [
      'JSON.stringify(value) turns a JavaScript value (object, array, etc.) into a JSON-formatted string — useful for saving data or sending it elsewhere.',
      'JSON.parse(jsonString) does the reverse, turning a JSON string back into a real JavaScript value you can work with.',
      'JSON only supports plain data (objects, arrays, strings, numbers, booleans, null) — not functions or special objects like Date.',
    ],
    example: "const student = { name: 'Aria', age: 12, subjects: ['Math', 'Art'] };\n\nconst json = JSON.stringify(student);\nconsole.log(json);\nconsole.log(typeof json);\n\nconst parsed = JSON.parse(json);\nconsole.log(parsed.name);\nconsole.log(parsed.subjects[0]);\n\nconst pretty = JSON.stringify(student, null, 2);\nconsole.log(pretty);",
    starterCode: "const settings = { theme: 'dark', volume: 80 };\nconst text = JSON.stringify(settings);\nconsole.log(text);\n\nconst restored = JSON.parse(text);\nconsole.log(restored.theme);",
  },
  {
    slug: 'regular-expressions',
    title: 'Regular Expressions',
    summary: 'Pattern matching for finding and replacing text',
    explanation: [
      'A regular expression (regex) is a pattern for matching text, written between slashes like /hello/i (the i means case-insensitive).',
      '.test(str) returns true/false for whether a pattern matches, .match(regex) returns the matched parts, and str.replace(regex, replacement) swaps matched text.',
      'Regex is powerful for validating formats (like emails) or searching and cleaning up text.',
    ],
    example: "const pattern = /\\d+/;\nconsole.log(pattern.test('There are 12 apples'));\nconsole.log(pattern.test('No numbers here'));\n\nconst text = 'My phone numbers are 123-4567 and 987-6543';\nconst numbers = text.match(/\\d{3}-\\d{4}/g);\nconsole.log(numbers);\n\nconst sentence = 'Cats are great. Cats are fun.';\nconsole.log(sentence.replace(/Cats/g, 'Dogs'));\n\nconsole.log(/^[a-z]+$/i.test('Hello'));",
    starterCode: "const word = 'banana';\nconsole.log(/an/.test(word));\n\nconst message = 'I love cats and cats love me';\nconsole.log(message.replace(/cats/gi, 'dogs'));",
  },
  {
    slug: 'date-objects',
    title: 'Date Objects',
    summary: 'Creating dates, reading their parts, and doing basic date math',
    explanation: [
      'new Date() creates a date representing right now, and new Date(year, month, day) creates a specific date (note: months are 0-indexed, so 0 is January).',
      'Methods like .getFullYear(), .getMonth(), .getDate(), and .getDay() let you read individual parts of a date.',
      'Dates are stored internally as a timestamp (milliseconds since 1970), so you can do arithmetic, like adding days, by working with milliseconds.',
    ],
    example: "const today = new Date(2024, 0, 15);\nconsole.log(today.getFullYear());\nconsole.log(today.getMonth());\nconsole.log(today.getDate());\nconsole.log(today.getDay());\n\nconst oneDay = 24 * 60 * 60 * 1000;\nconst tomorrow = new Date(today.getTime() + oneDay);\nconsole.log(tomorrow.getDate());\n\nconst start = new Date(2024, 0, 1);\nconst end = new Date(2024, 0, 31);\nconst daysBetween = (end.getTime() - start.getTime()) / oneDay;\nconsole.log(daysBetween);",
    starterCode: "const birthday = new Date(2010, 5, 20);\nconsole.log(birthday.getFullYear());\nconsole.log(birthday.getMonth());\nconsole.log(birthday.getDate());",
  },
  {
    slug: 'generators-and-iterators',
    title: 'Generators & Iterators',
    summary: 'Functions that can pause and resume, yielding one value at a time',
    explanation: [
      'A generator function, written function* name() { ... }, can pause itself with yield and resume later — each call to .next() runs until the next yield.',
      'Generators are iterable, so you can consume their values one at a time with a for...of loop instead of calling .next() manually.',
      'They are useful for producing sequences of values lazily, without building a whole array upfront.',
    ],
    example: "function* countUpTo(max) {\n  for (let i = 1; i <= max; i++) {\n    yield i;\n  }\n}\n\nconst counter = countUpTo(3);\nconsole.log(counter.next());\nconsole.log(counter.next());\nconsole.log(counter.next());\nconsole.log(counter.next());\n\nfor (const value of countUpTo(5)) {\n  console.log(`Got: ${value}`);\n}",
    starterCode: "function* colors() {\n  yield 'red';\n  yield 'green';\n  yield 'blue';\n}\n\nfor (const color of colors()) {\n  console.log(color);\n}",
  },
  {
    slug: 'modules-import-export-concept',
    title: 'Modules: import & export (Concept)',
    summary: 'How real JavaScript projects split code across files',
    explanation: [
      'In real JavaScript projects, code is usually split across multiple files called modules. A file can mark something as reusable with export, like export function add(a, b) { return a + b }, and another file can pull it in with import { add } from \'./math.js\'.',
      'This playground runs as a single plain script (no bundler or module loader), so actual import/export statements would cause an error here — but the underlying idea is simple: organize related functions and values together, and expose only what other files need.',
      'Below, we simulate that idea using a plain object as a stand-in for a module, since that works in any script.',
    ],
    example: "// In a real project, this might be a file called mathUtils.js:\n//   export function add(a, b) { return a + b; }\n//   export function multiply(a, b) { return a * b; }\n// And another file would write:\n//   import { add, multiply } from './mathUtils.js';\n\n// Here, we simulate that module using a plain object instead,\n// since this sandbox runs one script with no module system:\nconst mathUtils = {\n  add(a, b) { return a + b; },\n  multiply(a, b) { return a * b; },\n};\n\nconsole.log(mathUtils.add(2, 3));\nconsole.log(mathUtils.multiply(2, 3));",
    starterCode: "// Simulating a 'stringUtils' module as a plain object\nconst stringUtils = {\n  shout(text) { return text.toUpperCase() + '!'; },\n  whisper(text) { return text.toLowerCase(); },\n};\n\nconsole.log(stringUtils.shout('hello'));\nconsole.log(stringUtils.whisper('HELLO'));",
  },
  {
    slug: 'this-keyword-and-binding',
    title: 'The this Keyword',
    summary: 'How this depends on the way a function is called',
    explanation: [
      'Inside a regular function, this refers to whatever called the function — for object.method(), this is object; called alone, this can be undefined or the global object.',
      'Arrow functions do not have their own this; instead they inherit this from the surrounding (enclosing) scope where they were defined, which makes them great for callbacks inside methods.',
      'Mixing the two up is a common source of bugs, especially with callbacks like setTimeout or array methods inside class methods.',
    ],
    example: "const person = {\n  name: 'Aria',\n  regularGreet: function () {\n    return `Hi, I'm ${this.name}`;\n  },\n  arrowGreet: () => {\n    return `Hi, I'm ${this?.name}`;\n  },\n};\n\nconsole.log(person.regularGreet());\nconsole.log(person.arrowGreet());\n\nfunction Timer() {\n  this.seconds = 0;\n  this.tickWithArrow = () => {\n    this.seconds++;\n    return this.seconds;\n  };\n}\n\nconst timer = new Timer();\nconsole.log(timer.tickWithArrow());\nconsole.log(timer.tickWithArrow());",
    starterCode: "const car = {\n  brand: 'Toyota',\n  describe: function () {\n    return `This car is a ${this.brand}`;\n  },\n};\n\nconsole.log(car.describe());",
  },
  {
    slug: 'static-and-private-class-fields',
    title: 'Static & Private Class Fields',
    summary: 'Class-level members and truly private instance data',
    explanation: [
      'A static member (static count = 0 or static helper() {}) belongs to the class itself, not to individual instances — you access it as ClassName.member.',
      'A field starting with # (like #balance) is a private field — it can only be read or changed from inside the class\'s own methods, not from outside code.',
      'Together, static and private fields help you model shared state and protected internal data cleanly.',
    ],
    example: "class BankAccount {\n  static accountsCreated = 0;\n  #balance;\n\n  constructor(initialBalance) {\n    this.#balance = initialBalance;\n    BankAccount.accountsCreated++;\n  }\n\n  deposit(amount) {\n    this.#balance += amount;\n    return this.#balance;\n  }\n\n  getBalance() {\n    return this.#balance;\n  }\n}\n\nconst acc1 = new BankAccount(100);\nconst acc2 = new BankAccount(50);\n\nconsole.log(acc1.deposit(25));\nconsole.log(acc2.getBalance());\nconsole.log(BankAccount.accountsCreated);",
    starterCode: "class Counter {\n  static instances = 0;\n  #count = 0;\n\n  constructor() {\n    Counter.instances++;\n  }\n\n  increment() {\n    this.#count++;\n    return this.#count;\n  }\n}\n\nconst c1 = new Counter();\nconsole.log(c1.increment());\nconsole.log(Counter.instances);",
  },
  {
    slug: 'getters-and-setters',
    title: 'Getters & Setters',
    summary: 'Accessor methods that run code when a property is read or written',
    explanation: [
      'A getter (get propertyName() { ... }) lets you compute a value on the fly whenever code reads obj.propertyName, even though it looks like a plain property.',
      'A setter (set propertyName(value) { ... }) runs custom code whenever someone assigns obj.propertyName = value, which is useful for validation.',
      'Getters and setters work on both classes and plain object literals, and they keep the simple property syntax while adding logic behind the scenes.',
    ],
    example: "class Rectangle {\n  constructor(width, height) {\n    this.width = width;\n    this.height = height;\n  }\n\n  get area() {\n    return this.width * this.height;\n  }\n\n  set width(value) {\n    if (value <= 0) throw new Error('Width must be positive');\n    this._width = value;\n  }\n\n  get width() {\n    return this._width;\n  }\n}\n\nconst rect = new Rectangle(4, 5);\nconsole.log(rect.area);\nrect.width = 10;\nconsole.log(rect.area);\n\ntry {\n  rect.width = -2;\n} catch (error) {\n  console.log(`Error: ${error.message}`);\n}",
    starterCode: "const temperature = {\n  celsius: 20,\n  get fahrenheit() {\n    return this.celsius * 9 / 5 + 32;\n  },\n  set fahrenheit(f) {\n    this.celsius = (f - 32) * 5 / 9;\n  },\n};\n\nconsole.log(temperature.fahrenheit);\ntemperature.fahrenheit = 100;\nconsole.log(temperature.celsius.toFixed(1));",
  },
  {
    slug: 'immutability-patterns',
    title: 'Immutability Patterns',
    summary: 'Preventing changes and preferring new copies over mutation',
    explanation: [
      'Object.freeze(obj) prevents any of an object\'s properties from being changed, added, or removed — attempts to modify it are silently ignored (or throw in strict mode).',
      'A common pattern is to avoid mutating arrays/objects directly and instead create new ones with the spread operator, like const updated = { ...original, age: 13 }.',
      'Favoring immutability makes code easier to reason about, since data does not change unexpectedly out from under you.',
    ],
    example: "const settings = Object.freeze({ theme: 'dark', volume: 80 });\nsettings.theme = 'light';\nconsole.log(settings.theme);\nconsole.log(Object.isFrozen(settings));\n\nconst original = { name: 'Aria', age: 12 };\nconst updated = { ...original, age: 13 };\nconsole.log(original);\nconsole.log(updated);\n\nconst numbers = [1, 2, 3];\nconst withFour = [...numbers, 4];\nconsole.log(numbers);\nconsole.log(withFour);",
    starterCode: "const config = Object.freeze({ version: 1 });\nconfig.version = 2;\nconsole.log(config.version);\n\nconst list = [1, 2, 3];\nconst extended = [...list, 4];\nconsole.log(list);\nconsole.log(extended);",
  },
  {
    slug: 'array-and-object-equality',
    title: 'Equality & Comparing Values',
    summary: 'Why === is preferred over ==, and how to compare objects and arrays',
    explanation: [
      '=== checks both value and type without converting anything, while == coerces types first, which can lead to surprising results like \'5\' == 5 being true — this is why === is generally preferred.',
      'Two arrays or objects with identical contents are NOT === equal, because === compares references (are they the same object in memory?), not contents.',
      'To compare contents, you can use JSON.stringify(a) === JSON.stringify(b) for simple cases, or Object.is() for precise value comparisons (which also distinguishes NaN and -0 from regular equality).',
    ],
    example: "console.log('5' == 5);\nconsole.log('5' === 5);\nconsole.log(null == undefined);\nconsole.log(null === undefined);\n\nconst arr1 = [1, 2, 3];\nconst arr2 = [1, 2, 3];\nconsole.log(arr1 === arr2);\nconsole.log(JSON.stringify(arr1) === JSON.stringify(arr2));\n\nconst arr3 = arr1;\nconsole.log(arr1 === arr3);\n\nconsole.log(Object.is(NaN, NaN));\nconsole.log(NaN === NaN);",
    starterCode: "const objA = { x: 1, y: 2 };\nconst objB = { x: 1, y: 2 };\n\nconsole.log(objA === objB);\nconsole.log(JSON.stringify(objA) === JSON.stringify(objB));\n\nconst objC = objA;\nconsole.log(objA === objC);",
  },
  {
    slug: 'array-flat-and-flatmap',
    title: 'Array.flat() & flatMap()',
    summary: 'Flattening nested arrays and mapping-then-flattening in one step',
    explanation: [
      '.flat(depth) flattens nested arrays into a single array. The default depth is 1, but you can pass Infinity to flatten arrays nested any number of levels deep.',
      '.flatMap(fn) is equivalent to calling .map(fn) followed by .flat(1), but it is slightly more efficient and is handy when each element maps to zero or more results.',
      'A common use is splitting and combining strings, or filtering out values by mapping some elements to empty arrays.',
    ],
    example: "const nested = [1, [2, 3], [4, [5, 6]]];\nconsole.log(nested.flat());\nconsole.log(nested.flat(2));\nconsole.log(nested.flat(Infinity));\n\nconst sentences = ['hello there', 'how are you'];\nconst words = sentences.flatMap(s => s.split(' '));\nconsole.log(words);\n\nconst numbers = [1, 2, 3, 4, 5];\nconst onlyEvensDoubled = numbers.flatMap(n => (n % 2 === 0 ? [n * 2] : []));\nconsole.log(onlyEvensDoubled);",
    starterCode: "const groups = [[1, 2], [3, 4], [5]];\nconsole.log(groups.flat());\n\nconst names = ['Aria Lee', 'Kiran Shah'];\nconsole.log(names.flatMap(n => n.split(' ')));",
  },
  {
    slug: 'proxy-and-reflect',
    title: 'Proxy & Reflect',
    summary: 'Intercepting and customizing fundamental object operations',
    explanation: [
      'A Proxy wraps a target object and lets you intercept operations on it (reading, writing, checking properties) using a "handler" object of trap functions like get and set.',
      'new Proxy(target, { get(target, prop) { ... }, set(target, prop, value) { ... } }) lets you add logging, validation, or default values without changing the original object.',
      'Reflect provides the default behavior for these operations (Reflect.get, Reflect.set), so traps can easily delegate back to the normal behavior after doing their custom work.',
    ],
    example: "const target = { name: 'Aria', age: 12 };\n\nconst handler = {\n  get(obj, prop) {\n    console.log(`Reading property: ${prop}`);\n    return Reflect.get(obj, prop);\n  },\n  set(obj, prop, value) {\n    if (prop === 'age' && typeof value !== 'number') {\n      throw new TypeError('age must be a number');\n    }\n    console.log(`Setting ${prop} to ${value}`);\n    return Reflect.set(obj, prop, value);\n  },\n};\n\nconst proxy = new Proxy(target, handler);\nconsole.log(proxy.name);\nproxy.age = 13;\nconsole.log(proxy.age);",
    starterCode: "const data = { score: 0 };\n\nconst guarded = new Proxy(data, {\n  set(obj, prop, value) {\n    console.log(`Updating ${prop} -> ${value}`);\n    return Reflect.set(obj, prop, value);\n  },\n});\n\nguarded.score = 100;\nconsole.log(data.score);",
  },
  {
    slug: 'symbol-type',
    title: 'The Symbol Type',
    summary: 'A primitive type for creating guaranteed-unique values',
    explanation: [
      'Symbol() creates a new, completely unique value every time it is called — even two symbols created with the same description are never equal to each other.',
      'Symbols are often used as "hidden" or collision-free object keys, since a symbol key cannot accidentally clash with a string key or another symbol.',
      'Built-in symbols like Symbol.iterator let objects define custom iteration behavior, which is how for...of knows how to loop over arrays, strings, Maps, and Sets.',
    ],
    example: "const sym1 = Symbol('id');\nconst sym2 = Symbol('id');\nconsole.log(sym1 === sym2);\nconsole.log(typeof sym1);\n\nconst user = {\n  name: 'Aria',\n  [sym1]: 'secret-internal-id',\n};\nconsole.log(user.name);\nconsole.log(user[sym1]);\nconsole.log(Object.keys(user));\n\nconst range = {\n  from: 1,\n  to: 3,\n  [Symbol.iterator]() {\n    let current = this.from;\n    const last = this.to;\n    return {\n      next() {\n        return current <= last ? { value: current++, done: false } : { value: undefined, done: true };\n      },\n    };\n  },\n};\n\nconsole.log([...range]);",
    starterCode: "const idA = Symbol('id');\nconst idB = Symbol('id');\nconsole.log(idA === idB);\n\nconst record = { label: 'item', [idA]: 42 };\nconsole.log(record[idA]);\nconsole.log(Object.keys(record));",
  },
  {
    slug: 'weakmap-and-weakset',
    title: 'WeakMap & WeakSet',
    summary: 'Collections that hold object keys weakly, allowing garbage collection',
    explanation: [
      'A WeakMap is like a Map, but its keys must be objects, and those keys are held "weakly" — if nothing else references the key object, it can be garbage-collected even while still in the WeakMap.',
      'This makes WeakMap great for attaching private or extra data to an object without preventing that object from being cleaned up when no longer needed elsewhere.',
      'A WeakSet works the same way but only stores objects (no values), useful for tracking "has this object been seen" without keeping it alive.',
      'Unlike Map and Set, WeakMap and WeakSet are not iterable and have no .size, because their contents can change at any time due to garbage collection.',
    ],
    example: "const cache = new WeakMap();\n\nfunction getMetadata(obj) {\n  if (!cache.has(obj)) {\n    cache.set(obj, { computedAt: Date.now() });\n  }\n  return cache.get(obj);\n}\n\nconst user = { name: 'Aria' };\nconst meta1 = getMetadata(user);\nconst meta2 = getMetadata(user);\nconsole.log(meta1 === meta2);\n\nconst visited = new WeakSet();\nconst pageA = {};\nconst pageB = {};\nvisited.add(pageA);\nconsole.log(visited.has(pageA));\nconsole.log(visited.has(pageB));",
    starterCode: "const seen = new WeakSet();\nconst objA = {};\nconst objB = {};\n\nseen.add(objA);\nconsole.log(seen.has(objA));\nconsole.log(seen.has(objB));",
  },
  {
    slug: 'async-iterators',
    title: 'Async Iterators & for-await-of',
    summary: 'Looping over values that arrive one at a time, asynchronously',
    explanation: [
      'An async generator, written async function* name() { ... }, can yield values over time using await and yield together — each yielded value resolves whenever it is ready.',
      'for await (const value of asyncIterable) { ... } consumes an async iterable one value at a time, pausing the loop until each value resolves, similar to how for...of works with regular iterables.',
      'This pattern is useful for things like reading paginated API results or streaming data, where each chunk takes some time to become available.',
    ],
    example: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function* countUp(max) {\n  for (let i = 1; i <= max; i++) {\n    const value = await wait(10, i);\n    yield value;\n  }\n}\n\nasync function run() {\n  for await (const n of countUp(3)) {\n    console.log(`Got: ${n}`);\n  }\n  console.log('done');\n}\n\nrun();",
    starterCode: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function* fetchNames() {\n  yield await wait(10, 'Aria');\n  yield await wait(10, 'Kiran');\n}\n\nasync function run() {\n  for await (const name of fetchNames()) {\n    console.log(name);\n  }\n}\n\nrun();",
  },
  {
    slug: 'tagged-template-literals',
    title: 'Tagged Template Literals',
    summary: 'Functions that customize how a template literal gets built',
    explanation: [
      'Placing a function name right before a template literal, like myTag`Hello ${name}`, "tags" it — instead of producing a string directly, the literal is passed to the function to process.',
      'The tag function receives an array of the literal text pieces as its first argument, followed by each interpolated value as the remaining arguments.',
      'Tagged templates are how libraries build features like automatic HTML escaping, internationalization, or custom formatting (e.g. styled-components uses this for CSS).',
    ],
    example: "function highlight(strings, ...values) {\n  return strings.reduce((result, str, i) => {\n    const value = values[i] !== undefined ? `[${values[i]}]` : '';\n    return result + str + value;\n  }, '');\n}\n\nconst name = 'Aria';\nconst score = 95;\nconsole.log(highlight`${name} scored ${score} points!`);\n\nfunction currency(strings, ...values) {\n  return strings.reduce((result, str, i) => {\n    const value = values[i] !== undefined ? `$${values[i].toFixed(2)}` : '';\n    return result + str + value;\n  }, '');\n}\n\nconsole.log(currency`Total: ${19.5}, Tax: ${1.46}`);",
    starterCode: "function shout(strings, ...values) {\n  return strings.reduce((result, str, i) => {\n    const value = values[i] !== undefined ? String(values[i]).toUpperCase() : '';\n    return result + str + value;\n  }, '');\n}\n\nconst place = 'park';\nconsole.log(shout`Let's go to the ${place} today!`);",
  },
  {
    slug: 'currying-and-partial-application',
    title: 'Currying & Partial Application',
    summary: 'Breaking multi-argument functions into chains of single-argument functions',
    explanation: [
      'Currying transforms a function that takes multiple arguments into a sequence of functions that each take one argument: add(a, b) becomes add(a)(b).',
      'Partial application is related — it means fixing some arguments of a function in advance, producing a new function that only needs the remaining ones.',
      'These patterns are useful for creating specialized, reusable functions from a more general one, like building a discount(rate) function from a generic applyDiscount(rate, price).',
    ],
    example: "function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn(...args);\n    }\n    return (...moreArgs) => curried(...args, ...moreArgs);\n  };\n}\n\nfunction add3(a, b, c) {\n  return a + b + c;\n}\n\nconst curriedAdd3 = curry(add3);\nconsole.log(curriedAdd3(1)(2)(3));\nconsole.log(curriedAdd3(1, 2)(3));\nconsole.log(curriedAdd3(1, 2, 3));\n\nfunction applyDiscount(rate, price) {\n  return price - price * rate;\n}\nconst tenPercentOff = (price) => applyDiscount(0.1, price);\nconsole.log(tenPercentOff(200));",
    starterCode: "function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn(...args);\n    }\n    return (...moreArgs) => curried(...args, ...moreArgs);\n  };\n}\n\nconst multiply = curry((a, b) => a * b);\nconst double = multiply(2);\nconsole.log(double(5));\nconsole.log(multiply(3)(4));",
  },
  {
    slug: 'debounce-and-throttle',
    title: 'Debounce & Throttle',
    summary: 'Controlling how often a fast-firing function actually runs',
    explanation: [
      'debounce(fn, delay) returns a wrapped function that waits until calls stop happening for delay milliseconds before actually running fn — great for things like "search as you type" where you only want the final value.',
      'throttle(fn, interval) returns a wrapped function that runs fn at most once per interval, ignoring extra calls in between — great for things like scroll or resize handlers that fire very rapidly.',
      'Both patterns use setTimeout internally to control timing, and are common tools for improving performance when handling frequent events.',
    ],
    example: "function debounce(fn, delay) {\n  let timeoutId;\n  return (...args) => {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => fn(...args), delay);\n  };\n}\n\nfunction throttle(fn, interval) {\n  let lastRun = 0;\n  return (...args) => {\n    const now = Date.now();\n    if (now - lastRun >= interval) {\n      lastRun = now;\n      fn(...args);\n    }\n  };\n}\n\nconst logSearch = debounce((term) => console.log(`Searching for: ${term}`), 20);\nlogSearch('a');\nlogSearch('ap');\nlogSearch('app');\n\nsetTimeout(() => console.log('debounce demo finished'), 40);\n\nconst logScroll = throttle((pos) => console.log(`Scroll position: ${pos}`), 20);\nlogScroll(10);\nlogScroll(20);\nsetTimeout(() => logScroll(30), 30);",
    starterCode: "function debounce(fn, delay) {\n  let timeoutId;\n  return (...args) => {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => fn(...args), delay);\n  };\n}\n\nconst greet = debounce((name) => console.log(`Hello, ${name}!`), 15);\ngreet('A');\ngreet('Ar');\ngreet('Aria');",
  },
  {
    slug: 'memoization-pattern',
    title: 'Memoization',
    summary: 'Caching function results to avoid repeating expensive work',
    explanation: [
      'Memoization caches the result of a function call keyed by its arguments, so calling the function again with the same arguments returns the cached result instantly instead of recomputing it.',
      'A simple memoize(fn) wrapper can use a Map to store "arguments -> result" pairs, checking the cache before calling the original function.',
      'This is especially useful for expensive pure functions (same input always gives same output), like recursive calculations or processing large datasets.',
    ],
    example: "function memoize(fn) {\n  const cache = new Map();\n  return (...args) => {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) {\n      console.log(`Cache hit for ${key}`);\n      return cache.get(key);\n    }\n    console.log(`Computing for ${key}`);\n    const result = fn(...args);\n    cache.set(key, result);\n    return result;\n  };\n}\n\nfunction slowSquare(n) {\n  return n * n;\n}\n\nconst fastSquare = memoize(slowSquare);\nconsole.log(fastSquare(5));\nconsole.log(fastSquare(5));\nconsole.log(fastSquare(6));",
    starterCode: "function memoize(fn) {\n  const cache = new Map();\n  return (...args) => {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key);\n    const result = fn(...args);\n    cache.set(key, result);\n    return result;\n  };\n}\n\nconst memoAdd = memoize((a, b) => a + b);\nconsole.log(memoAdd(2, 3));\nconsole.log(memoAdd(2, 3));",
  },
  {
    slug: 'event-delegation',
    title: 'Event Delegation',
    summary: 'Handling events on dynamic children through a single parent listener',
    explanation: [
      'Instead of adding a separate event listener to every child element, event delegation adds one listener to a shared parent — events from children "bubble up" to the parent, where you can handle them.',
      'Inside the parent\'s handler, event.target tells you exactly which child element triggered the event, so you can react differently based on what was clicked.',
      'This is especially useful for lists where items are added or removed dynamically, since you do not need to attach or remove listeners as children change.',
    ],
    example: "const list = document.createElement('ul');\n['Apples', 'Bananas', 'Cherries'].forEach(text => {\n  const item = document.createElement('li');\n  item.textContent = text;\n  list.appendChild(item);\n});\n\nlist.addEventListener('click', (event) => {\n  console.log(`Clicked on: ${event.target.textContent}`);\n});\n\nfunction simulateClick(element) {\n  element.dispatchEvent(new MouseEvent('click', { bubbles: true }));\n}\n\nsimulateClick(list.children[1]);\n\nconst newItem = document.createElement('li');\nnewItem.textContent = 'Dates';\nlist.appendChild(newItem);\nsimulateClick(newItem);",
    starterCode: "const menu = document.createElement('div');\n['Home', 'About', 'Contact'].forEach(text => {\n  const link = document.createElement('a');\n  link.textContent = text;\n  menu.appendChild(link);\n});\n\nmenu.addEventListener('click', (event) => {\n  console.log(`Navigating to: ${event.target.textContent}`);\n});\n\nmenu.children[0].dispatchEvent(new MouseEvent('click', { bubbles: true }));",
  },
  {
    slug: 'custom-events',
    title: 'Custom Events',
    summary: 'Creating and dispatching your own named events',
    explanation: [
      'new CustomEvent(name, { detail }) creates an event of your own design, where detail can carry any data you want to send along with the event.',
      'element.dispatchEvent(event) fires the event on that element, and any listeners registered with addEventListener(name, handler) will run, receiving the event (including event.detail).',
      'Custom events let separate parts of an app communicate without calling each other\'s functions directly — one part dispatches an event, and any interested part can listen for it.',
    ],
    example: "const app = document.createElement('div');\n\napp.addEventListener('user-logged-in', (event) => {\n  console.log(`Welcome, ${event.detail.name}!`);\n});\n\nconst loginEvent = new CustomEvent('user-logged-in', {\n  detail: { name: 'Aria', role: 'admin' },\n});\n\napp.dispatchEvent(loginEvent);\nconsole.log(loginEvent.detail.role);",
    starterCode: "const widget = document.createElement('div');\n\nwidget.addEventListener('score-updated', (event) => {\n  console.log(`New score: ${event.detail.score}`);\n});\n\nconst event = new CustomEvent('score-updated', { detail: { score: 42 } });\nwidget.dispatchEvent(event);",
  },
  {
    slug: 'local-storage-basics',
    title: 'localStorage Basics',
    summary: 'Saving simple data in the browser that persists between visits',
    explanation: [
      'localStorage.setItem(key, value) saves a string under a key in the browser, and it stays there even after the page reloads or the browser closes — until explicitly removed.',
      'localStorage.getItem(key) reads a saved value back (returning null if the key does not exist), and localStorage.removeItem(key) deletes it.',
      'localStorage only stores strings, so objects and arrays need JSON.stringify() before saving and JSON.parse() after reading them back.',
    ],
    example: "localStorage.setItem('username', 'Aria');\nconsole.log(localStorage.getItem('username'));\n\nconst settings = { theme: 'dark', fontSize: 16 };\nlocalStorage.setItem('settings', JSON.stringify(settings));\n\nconst saved = JSON.parse(localStorage.getItem('settings'));\nconsole.log(saved.theme);\nconsole.log(saved.fontSize);\n\nlocalStorage.removeItem('username');\nconsole.log(localStorage.getItem('username'));",
    starterCode: "localStorage.setItem('visits', '1');\nconsole.log(localStorage.getItem('visits'));\n\nconst current = Number(localStorage.getItem('visits'));\nlocalStorage.setItem('visits', String(current + 1));\nconsole.log(localStorage.getItem('visits'));",
  },
  {
    slug: 'fetch-api-basics',
    title: 'Fetch API Basics',
    summary: 'The syntax for requesting data from a server with fetch()',
    explanation: [
      'fetch(url) starts an HTTP request and returns a Promise that resolves to a Response object once the server replies — you typically call .json() on that response to get the parsed data.',
      'Written with async/await, a typical request looks like: const response = await fetch(url); const data = await response.json();, wrapped in a try/catch to handle network errors.',
      'Note: this sandbox does not have real network access, so this lesson shows the syntax using a mocked fetch function instead of calling a real API — in a real browser, fetch would hit an actual server.',
    ],
    example: "// Simulating fetch since this sandbox has no real network access.\n// In a real browser, you would call the actual fetch(url) instead.\nfunction fetch(url) {\n  return new Promise((resolve) => {\n    setTimeout(() => {\n      resolve({\n        ok: true,\n        json: async () => ({ url, message: 'Hello from the server!' }),\n      });\n    }, 10);\n  });\n}\n\nasync function loadData() {\n  try {\n    const response = await fetch('/api/greeting');\n    if (!response.ok) {\n      throw new Error('Request failed');\n    }\n    const data = await response.json();\n    console.log(data.message);\n  } catch (error) {\n    console.log(`Error: ${error.message}`);\n  }\n}\n\nloadData();",
    starterCode: "// Mocked fetch — in a real app this would be the browser's built-in fetch(url)\nfunction fetch(url) {\n  return new Promise((resolve) => {\n    setTimeout(() => resolve({ ok: true, json: async () => ({ id: 1, name: 'Aria' }) }), 10);\n  });\n}\n\nasync function loadUser() {\n  const response = await fetch('/api/user/1');\n  const user = await response.json();\n  console.log(user.name);\n}\n\nloadUser();",
  },
  {
    slug: 'promise-all-and-race',
    title: 'Promise.all & Promise.race',
    summary: 'Coordinating multiple promises that run at the same time',
    explanation: [
      'Promise.all([p1, p2, p3]) waits for every promise to resolve and returns an array of all their results, in order — but if any one promise rejects, the whole thing rejects immediately.',
      'Promise.race([p1, p2, p3]) settles as soon as the first promise settles (resolves or rejects), ignoring the rest — useful for timeouts or picking the fastest of several sources.',
      'Both let multiple async operations run concurrently instead of awaiting them one after another, which can be much faster when the operations do not depend on each other.',
    ],
    example: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function runAll() {\n  const results = await Promise.all([\n    wait(10, 'first'),\n    wait(20, 'second'),\n    wait(5, 'third'),\n  ]);\n  console.log(results);\n}\n\nasync function runRace() {\n  const winner = await Promise.race([\n    wait(30, 'slow'),\n    wait(5, 'fast'),\n  ]);\n  console.log(`Winner: ${winner}`);\n}\n\nrunAll();\nrunRace();",
    starterCode: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function run() {\n  const all = await Promise.all([wait(10, 'a'), wait(10, 'b')]);\n  console.log(all);\n\n  const fastest = await Promise.race([wait(20, 'slow'), wait(5, 'quick')]);\n  console.log(fastest);\n}\n\nrun();",
  },
  {
    slug: 'settimeout-and-setinterval',
    title: 'setTimeout & setInterval',
    summary: 'Scheduling code to run later, once or repeatedly',
    explanation: [
      'setTimeout(callback, delay) schedules callback to run once after delay milliseconds, and returns an ID you can pass to clearTimeout(id) to cancel it before it runs.',
      'setInterval(callback, delay) is similar but runs callback repeatedly, every delay milliseconds, until you stop it with clearInterval(id).',
      'These functions do not pause the program — code after them keeps running immediately, and the scheduled callback runs later, which is the foundation of asynchronous timing in JavaScript.',
    ],
    example: "console.log('Start');\n\nconst timeoutId = setTimeout(() => {\n  console.log('This runs once, after a delay');\n}, 10);\n\nlet count = 0;\nconst intervalId = setInterval(() => {\n  count++;\n  console.log(`Tick ${count}`);\n  if (count === 3) {\n    clearInterval(intervalId);\n    console.log('Interval stopped');\n  }\n}, 10);\n\nclearTimeout(timeoutId);\nconsole.log('End of script (timeout was cancelled)');",
    starterCode: "console.log('Begin');\n\nlet ticks = 0;\nconst id = setInterval(() => {\n  ticks++;\n  console.log(`Tick ${ticks}`);\n  if (ticks === 2) {\n    clearInterval(id);\n  }\n}, 10);",
  },
]
