import type { CodingLesson } from '../languages'

export const php: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to PHP',
    summary: 'PHP tags, echo, and your first output',
    explanation: [
      'PHP is a server-side scripting language that powers a huge share of the web (including WordPress). Code lives between <?php and ?> tags.',
      'echo "..."; prints output. Strings can use single or double quotes — double quotes allow variable interpolation.',
      'Each statement ends with a semicolon ;. Variables start with a dollar sign, like $name.',
    ],
    example: '<?php\necho "Hello, world!\\n";\necho 2 + 3 * 4;\necho "\\n";\n?>',
    starterCode: '<?php\necho "Hello, world!\\n";\necho 7 * 6;\necho "\\n";\n?>',
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Storing and combining values',
    explanation: [
      'Create a variable with a $ prefix: $name = "Aria"; $age = 12;. PHP figures out the type automatically.',
      'Inside double-quoted strings, variables are interpolated directly: "echo $name is $age";. Use . to concatenate strings.',
    ],
    example: '<?php\n$name = "Aria";\n$age = 12;\necho "$name is $age years old\\n";\necho gettype($age) . "\\n";\n?>',
    starterCode: '<?php\n$city = "Pokhara";\n$temperature = 24;\necho "$city is $temperature degrees today\\n";\n?>',
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Branching with if / elseif / else',
    explanation: [
      'if checks a condition; elseif checks another; else runs otherwise. Blocks are wrapped in { }.',
      'Comparison operators ==, !=, >, < produce true or false, which conditionals use to decide what to run.',
    ],
    example: '<?php\n$score = 82;\nif ($score >= 90) {\n  echo "Grade: A\\n";\n} elseif ($score >= 75) {\n  echo "Grade: B\\n";\n} else {\n  echo "Keep practising!\\n";\n}\n?>',
    starterCode: '<?php\n$temperature = 30;\nif ($temperature > 25) {\n  echo "It is warm\\n";\n} else {\n  echo "It is cool\\n";\n}\n?>',
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating actions with for and while',
    explanation: [
      'A for loop has three parts: for ($i = 1; $i <= 5; $i++) { ... } — start, condition, and update.',
      'A while loop repeats as long as its condition stays true. foreach loops walk through arrays directly.',
    ],
    example: '<?php\nfor ($i = 1; $i <= 5; $i++) {\n  echo "Step $i\\n";\n}\n$fruits = ["apple", "banana", "mango"];\nforeach ($fruits as $fruit) {\n  echo strtoupper($fruit) . "\\n";\n}\n?>',
    starterCode: '<?php\nfor ($i = 1; $i <= 3; $i++) {\n  echo "Count: $i\\n";\n}\n?>',
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Packaging reusable logic with function',
    explanation: [
      'Define a function with function name($parameters) { ... }. Use return to send a value back to the caller.',
      'Functions help you avoid repeating yourself and make programs easier to read.',
    ],
    example: '<?php\nfunction double($n) {\n  return $n * 2;\n}\nfunction greet($name) {\n  return "Hello, $name!";\n}\necho double(21) . "\\n";\necho greet("World") . "\\n";\n?>',
    starterCode: '<?php\nfunction square($n) {\n  return $n * $n;\n}\necho square(6) . "\\n";\n?>',
  },
  {
    slug: 'arrays',
    title: 'Arrays',
    summary: 'Working with ordered and associative collections',
    explanation: [
      'Indexed arrays hold ordered values: $numbers = [1, 2, 3];. Access with $numbers[0], and count() gives the length.',
      'Associative arrays hold key-value pairs: $student = ["name" => "Aria", "grade" => 7]; — access with $student["name"].',
    ],
    example: '<?php\n$scores = [70, 85, 92, 60];\n$total = 0;\nforeach ($scores as $s) {\n  $total += $s;\n}\necho "Total: $total\\n";\necho "Average: " . intdiv($total, count($scores)) . "\\n";\n\n$student = ["name" => "Aria", "grade" => 7];\necho "{$student[\'name\']} is in grade {$student[\'grade\']}\\n";\n?>',
    starterCode: '<?php\n$scores = [70, 85, 92, 60];\n$passing = array_filter($scores, fn($s) => $s >= 70);\nprint_r(array_values($passing));\n?>',
  },
  {
    slug: 'string-functions',
    title: 'String Functions',
    summary: 'Measuring, transforming, and formatting text',
    explanation: [
      'strlen($s) counts characters, strtoupper / strtolower change case, and str_replace($search, $replace, $s) swaps text.',
      'trim($s) removes surrounding whitespace, and sprintf("%s is %d", $name, $age) builds formatted strings from placeholders.',
    ],
    example: '<?php\n$name = "  Aria  ";\necho strlen($name) . "\\n";\necho strtoupper(trim($name)) . "\\n";\necho str_replace("Aria", "Maya", trim($name)) . "\\n";\necho sprintf("%s is %d years old\\n", trim($name), 12);\n?>',
    starterCode: '<?php\n$word = "hello";\necho strtoupper($word) . "\\n";\necho strlen($word) . "\\n";\necho str_replace("l", "L", $word) . "\\n";\n?>',
  },
  {
    slug: 'associative-arrays-in-depth',
    title: 'Associative Arrays In Depth',
    summary: 'Looping, sorting, mapping, and reducing key-value data',
    explanation: [
      'foreach ($array as $key => $value) walks through an associative array giving you both the key and the value.',
      'ksort() sorts by key and asort() sorts by value while keeping keys attached; array_map() transforms every value and array_reduce() folds them into one result.',
    ],
    example: '<?php\n$scores = ["Leo" => 88, "Aria" => 95, "Maya" => 72];\nforeach ($scores as $name => $score) {\n  echo "$name scored $score\\n";\n}\nksort($scores);\necho "Sorted by name: " . implode(", ", array_keys($scores)) . "\\n";\n$bonused = array_map(fn($s) => $s + 5, $scores);\necho "With bonus: " . implode(", ", $bonused) . "\\n";\n$total = array_reduce($scores, fn($carry, $s) => $carry + $s, 0);\necho "Total: $total\\n";\n?>',
    starterCode: '<?php\n$prices = ["apple" => 2, "banana" => 1, "mango" => 3];\nasort($prices);\nforeach ($prices as $fruit => $price) {\n  echo "$fruit costs $price\\n";\n}\n?>',
  },
  {
    slug: 'oop-basics',
    title: 'OOP Basics',
    summary: 'Classes, constructors, properties, and methods',
    explanation: [
      'A class is a blueprint: class Student { public $name; } groups data and behaviour together.',
      '__construct($...) runs automatically when you create an object with new, and methods are functions defined inside the class that act on its properties.',
    ],
    example: '<?php\nclass Student {\n  public $name;\n  public $score;\n\n  public function __construct($name, $score) {\n    $this->name = $name;\n    $this->score = $score;\n  }\n\n  public function describe() {\n    return "$this->name scored $this->score";\n  }\n}\n\n$aria = new Student("Aria", 95);\n$leo = new Student("Leo", 88);\necho $aria->describe() . "\\n";\necho $leo->describe() . "\\n";\n?>',
    starterCode: '<?php\nclass Counter {\n  public $count;\n\n  public function __construct() {\n    $this->count = 0;\n  }\n\n  public function increment() {\n    $this->count += 1;\n  }\n}\n\n$c = new Counter();\n$c->increment();\n$c->increment();\necho "Count: $c->count\\n";\n?>',
  },
  {
    slug: 'superglobals-and-forms',
    title: 'Superglobals & Forms',
    summary: 'How PHP reads incoming request data like $_GET and $_POST',
    explanation: [
      'In a real web app, $_GET and $_POST hold form/query data sent by the browser, and $_SERVER holds info about the request — PHP fills these in automatically for each HTTP request.',
      "This sandbox has no real HTTP request, so we simulate one with a plain associative array and access it the same way you'd access $_POST.",
      'Always validate incoming data — check that a key exists with isset() before trusting its value.',
    ],
    example: '<?php\n// Simulating what $_POST might contain after a form submission\n$_POST = ["username" => "aria123", "age" => "12"];\n\nif (isset($_POST["username"]) && trim($_POST["username"]) !== "") {\n  echo "Welcome, " . $_POST["username"] . "!\\n";\n} else {\n  echo "Username is required\\n";\n}\n\n$age = isset($_POST["age"]) ? (int) $_POST["age"] : 0;\necho "Age next year: " . ($age + 1) . "\\n";\n?>',
    starterCode: '<?php\n// Simulating $_GET data from a URL like page.php?name=Leo\n$_GET = ["name" => "Leo"];\n\n$name = isset($_GET["name"]) ? $_GET["name"] : "Guest";\necho "Hello, $name!\\n";\n?>',
  },
  {
    slug: 'error-handling',
    title: 'Error Handling',
    summary: 'Catching problems gracefully with try/catch/finally',
    explanation: [
      'Wrap risky code in a try block; if it throw new Exception("message"), a matching catch (Exception $e) block handles it instead of crashing the script.',
      'finally runs whether or not an exception was thrown — useful for cleanup that must always happen.',
    ],
    example: '<?php\nfunction divide($a, $b) {\n  if ($b === 0) {\n    throw new Exception("Cannot divide by zero");\n  }\n  return $a / $b;\n}\n\ntry {\n  echo divide(10, 2) . "\\n";\n  echo divide(10, 0) . "\\n";\n} catch (Exception $e) {\n  echo "Error: " . $e->getMessage() . "\\n";\n} finally {\n  echo "Done trying to divide\\n";\n}\n?>',
    starterCode: '<?php\nfunction checkAge($age) {\n  if ($age < 0) {\n    throw new Exception("Age cannot be negative");\n  }\n  return "Age is $age";\n}\n\ntry {\n  echo checkAge(12) . "\\n";\n  echo checkAge(-5) . "\\n";\n} catch (Exception $e) {\n  echo "Error: " . $e->getMessage() . "\\n";\n}\n?>',
  },
  {
    slug: 'regular-expressions',
    title: 'Regular Expressions',
    summary: 'Matching and replacing text patterns with preg_*',
    explanation: [
      'preg_match($pattern, $subject, $matches) tests whether a string matches a pattern (written between slashes, like \'/[0-9]+/\') and captures the result.',
      'preg_replace($pattern, $replacement, $subject) finds every match of a pattern and swaps it for replacement text.',
    ],
    example: '<?php\n$text = "Contact: aria@example.com or call 98765";\n\nif (preg_match(\'/[\\w.]+@[\\w.]+/\', $text, $matches)) {\n  echo "Found email: " . $matches[0] . "\\n";\n}\n\n$digitsOnly = preg_replace(\'/[^0-9]/\', \'\', $text);\necho "Digits only: $digitsOnly\\n";\n\n$masked = preg_replace(\'/[0-9]/\', \'#\', $text);\necho "Masked: $masked\\n";\n?>',
    starterCode: '<?php\n$word = "Hello123World456";\n\nif (preg_match(\'/[0-9]+/\', $word, $matches)) {\n  echo "First number found: " . $matches[0] . "\\n";\n}\n\n$lettersOnly = preg_replace(\'/[0-9]/\', \'\', $word);\necho "Letters only: $lettersOnly\\n";\n?>',
  },
  {
    slug: 'inheritance-and-interfaces',
    title: 'Inheritance & Interfaces',
    summary: 'Sharing behaviour with extends, parent::__construct, and interface',
    explanation: [
      'A class can extend another class to inherit its properties and methods: class Dog extends Animal { ... } makes every Dog automatically an Animal too, without copying any code.',
      "Inside a child class's constructor, parent::__construct(...) calls the parent's constructor first, so shared setup only has to be written once. The child can then add its own properties or override a method with a new version.",
      'An interface describes a set of methods a class promises to have, without providing the code for them. class Robot implements Greets means Robot guarantees a greet() method, which is handy when different classes need to support the same contract.',
    ],
    example: '<?php\nclass Animal {\n  public $name;\n\n  public function __construct($name) {\n    $this->name = $name;\n  }\n\n  public function speak() {\n    return "$this->name makes a sound";\n  }\n}\n\nclass Dog extends Animal {\n  public $breed;\n\n  public function __construct($name, $breed) {\n    parent::__construct($name);\n    $this->breed = $breed;\n  }\n\n  public function speak() {\n    return "$this->name barks";\n  }\n}\n\ninterface Greets {\n  public function greet();\n}\n\nclass Robot implements Greets {\n  public function greet() {\n    return "Beep boop, hello!";\n  }\n}\n\n$generic = new Animal("Creature");\n$rex = new Dog("Rex", "Labrador");\necho $generic->speak() . "\\n";\necho $rex->speak() . "\\n";\necho "$rex->name is a $rex->breed\\n";\n\n$bot = new Robot();\necho $bot->greet() . "\\n";\n?>',
    starterCode: '<?php\nclass Vehicle {\n  public $wheels;\n\n  public function __construct($wheels) {\n    $this->wheels = $wheels;\n  }\n\n  public function describe() {\n    return "Has $this->wheels wheels";\n  }\n}\n\nclass Car extends Vehicle {\n  public $brand;\n\n  public function __construct($brand) {\n    parent::__construct(4);\n    $this->brand = $brand;\n  }\n}\n\n$car = new Car("Toyota");\necho $car->brand . ": " . $car->describe() . "\\n";\n?>',
  },
  {
    slug: 'null-coalescing-and-ternary',
    title: 'Null Coalescing & Ternary Operators',
    summary: 'Shortening if/else with ?:, ??, and ??=',
    explanation: [
      'The ternary operator squeezes a simple if/else into one line: $x = $condition ? $a : $b; stores $a if the condition is true, otherwise $b.',
      'The null coalescing operator ?? picks the left-hand value if it exists and is not null, otherwise it falls back to the right-hand value: $x = $maybeNull ?? $default;. It works just as well for array keys that might not be set, like $settings["fontSize"] ?? 14.',
      'The null coalescing assignment operator ??= only assigns a new value when the variable is currently null or unset: $x ??= $default;. If $x already holds a real value, ??= leaves it untouched.',
    ],
    example: '<?php\n$score = 55;\n$result = $score >= 60 ? "Pass" : "Fail";\necho "Result: $result\\n";\n\n$nickname = null;\n$displayName = $nickname ?? "Anonymous";\necho "Hello, $displayName!\\n";\n\n$settings = ["theme" => "dark"];\n$fontSize = $settings["fontSize"] ?? 14;\necho "Font size: $fontSize\\n";\n\n$settings["fontSize"] ??= 16;\necho "Font size is now: " . $settings["fontSize"] . "\\n";\n?>',
    starterCode: '<?php\n$age = 16;\n$ticketType = $age >= 18 ? "Adult" : "Child";\necho "Ticket: $ticketType\\n";\n\n$color = null;\n$chosenColor = $color ?? "blue";\necho "Color: $chosenColor\\n";\n\n$chosenColor ??= "green";\necho "Color is still: $chosenColor\\n";\n?>',
  },
  {
    slug: 'switch-statements-php',
    title: 'Switch Statements',
    summary: 'A tidy alternative to long if/elseif chains',
    explanation: [
      'switch ($value) { case 1: ...; break; } compares $value against each case in turn and runs the matching block.',
      "Don't forget break; — without it, execution 'falls through' into the next case. default: handles anything that didn't match.",
    ],
    example: '<?php\n$day = 3;\n\nswitch ($day) {\n  case 1:\n    echo "Monday\\n";\n    break;\n  case 2:\n    echo "Tuesday\\n";\n    break;\n  case 3:\n    echo "Wednesday\\n";\n    break;\n  default:\n    echo "Some other day\\n";\n}\n?>',
    starterCode: '<?php\n$grade = "B";\n\nswitch ($grade) {\n  case "A":\n    echo "Excellent!\\n";\n    break;\n  case "B":\n    echo "Good job!\\n";\n    break;\n  default:\n    echo "Keep practising\\n";\n}\n?>',
  },
  {
    slug: 'static-properties-and-methods',
    title: 'Static Properties & Methods',
    summary: 'Class members shared across every instance',
    explanation: [
      'A static property or method belongs to the class itself, not to any one object: public static $count = 0; is accessed as ClassName::$count.',
      'Static methods are called the same way, like Counter::reset(), and inside a static method you use self:: instead of $this-> since there is no specific object.',
    ],
    example: '<?php\nclass Counter {\n  public static $count = 0;\n\n  public static function increment() {\n    self::$count += 1;\n  }\n}\n\nCounter::increment();\nCounter::increment();\nCounter::increment();\necho "Count: " . Counter::$count . "\\n";\n?>',
    starterCode: '<?php\nclass MathHelper {\n  public static function square($n) {\n    return $n * $n;\n  }\n}\n\necho MathHelper::square(5) . "\\n";\necho MathHelper::square(9) . "\\n";\n?>',
  },
  {
    slug: 'traits',
    title: 'Traits',
    summary: 'Sharing method code across unrelated classes',
    explanation: [
      "PHP classes can only extend one parent, but a trait lets you share ready-made methods with any class using the use TraitName; keyword inside it.",
      'Think of a trait as a mixin: it adds behaviour to a class without forcing it into a shared inheritance hierarchy.',
    ],
    example: '<?php\ntrait Greetable {\n  public function greet() {\n    return "Hi, I am " . $this->name;\n  }\n}\n\nclass Person {\n  use Greetable;\n  public $name;\n\n  public function __construct($name) {\n    $this->name = $name;\n  }\n}\n\nclass Robot {\n  use Greetable;\n  public $name = "R2D2";\n}\n\n$p = new Person("Aria");\n$r = new Robot();\necho $p->greet() . "\\n";\necho $r->greet() . "\\n";\n?>',
    starterCode: '<?php\ntrait Loggable {\n  public function log($message) {\n    echo "[LOG] $message\\n";\n  }\n}\n\nclass Task {\n  use Loggable;\n}\n\n$t = new Task();\n$t->log("Task started");\n?>',
  },
  {
    slug: 'magic-methods',
    title: 'Magic Methods',
    summary: 'Customising how objects behave with __toString, __get, __set',
    explanation: [
      'PHP calls __toString() automatically whenever an object is used as a string, like in echo $obj; — handy for readable output.',
      '__get($name) and __set($name, $value) intercept access to properties that are not directly defined, letting you control reads and writes dynamically.',
    ],
    example: '<?php\nclass Money {\n  public $amount;\n\n  public function __construct($amount) {\n    $this->amount = $amount;\n  }\n\n  public function __toString() {\n    return "$" . number_format($this->amount, 2);\n  }\n}\n\n$price = new Money(19.5);\necho "Price: $price\\n";\n\nclass Magic {\n  private $data = [];\n\n  public function __get($name) {\n    return $this->data[$name] ?? "undefined";\n  }\n\n  public function __set($name, $value) {\n    $this->data[$name] = $value;\n  }\n}\n\n$m = new Magic();\n$m->color = "blue";\necho $m->color . "\\n";\necho $m->missing . "\\n";\n?>',
    starterCode: '<?php\nclass Point {\n  public $x;\n  public $y;\n\n  public function __construct($x, $y) {\n    $this->x = $x;\n    $this->y = $y;\n  }\n\n  public function __toString() {\n    return "($this->x, $this->y)";\n  }\n}\n\n$p = new Point(3, 4);\necho "Point: $p\\n";\n?>',
  },
  {
    slug: 'array-functions-in-depth',
    title: 'Array Functions In Depth',
    summary: 'Transforming and combining arrays with map, filter, reduce, and usort',
    explanation: [
      'array_map(fn($x) => ..., $array) transforms every element, array_filter($array, fn($x) => ...) keeps only elements passing a test, and array_reduce($array, fn($carry, $x) => ..., $start) folds everything into one value.',
      'usort($array, fn($a, $b) => ...) sorts an array in place using a custom comparator that returns a negative, zero, or positive number.',
    ],
    example: '<?php\n$numbers = [5, 2, 8, 1, 9, 3];\n\n$doubled = array_map(fn($n) => $n * 2, $numbers);\necho "Doubled: " . implode(", ", $doubled) . "\\n";\n\n$evens = array_filter($numbers, fn($n) => $n % 2 === 0);\necho "Evens: " . implode(", ", $evens) . "\\n";\n\n$sum = array_reduce($numbers, fn($carry, $n) => $carry + $n, 0);\necho "Sum: $sum\\n";\n\nusort($numbers, fn($a, $b) => $a <=> $b);\necho "Sorted: " . implode(", ", $numbers) . "\\n";\n?>',
    starterCode: '<?php\n$words = ["banana", "fig", "apple"];\n\nusort($words, fn($a, $b) => strlen($a) <=> strlen($b));\necho implode(", ", $words) . "\\n";\n\n$lengths = array_map(fn($w) => strlen($w), $words);\necho implode(", ", $lengths) . "\\n";\n?>',
  },
  {
    slug: 'multidimensional-arrays-php',
    title: 'Multidimensional Arrays',
    summary: 'Arrays of associative arrays, like a list of records',
    explanation: [
      'You can nest arrays inside arrays to represent structured records: $students = [["name" => "Aria", "score" => 95], ["name" => "Leo", "score" => 88]];.',
      'Loop over the outer array with foreach to get each record, then access its fields like a normal associative array.',
    ],
    example: '<?php\n$students = [\n  ["name" => "Aria", "score" => 95],\n  ["name" => "Leo", "score" => 88],\n  ["name" => "Maya", "score" => 72],\n];\n\nforeach ($students as $student) {\n  echo "{$student[\'name\']}: {$student[\'score\']}\\n";\n}\n\n$total = 0;\nforeach ($students as $student) {\n  $total += $student["score"];\n}\necho "Average: " . intdiv($total, count($students)) . "\\n";\n?>',
    starterCode: '<?php\n$books = [\n  ["title" => "Dune", "year" => 1965],\n  ["title" => "Emma", "year" => 1815],\n];\n\nforeach ($books as $book) {\n  echo "{$book[\'title\']} ({$book[\'year\']})\\n";\n}\n?>',
  },
  {
    slug: 'closures-and-anonymous-functions',
    title: 'Closures & Anonymous Functions',
    summary: 'Functions without names, and capturing variables with use',
    explanation: [
      'An anonymous function is a function with no name, often stored in a variable: $double = function($x) { return $x * 2; };.',
      'use ($y) lets a closure capture a variable from the surrounding scope. Arrow functions fn($x) => $x * 2 are a shorter syntax that automatically capture outer variables.',
    ],
    example: '<?php\n$tax = 0.1;\n$addTax = function($price) use ($tax) {\n  return $price + ($price * $tax);\n};\necho $addTax(100) . "\\n";\n\n$square = fn($x) => $x * $x;\necho $square(7) . "\\n";\n\n$numbers = [1, 2, 3, 4];\n$squared = array_map(fn($n) => $n * $n, $numbers);\necho implode(", ", $squared) . "\\n";\n?>',
    starterCode: '<?php\n$greeting = "Hello";\n$greet = function($name) use ($greeting) {\n  return "$greeting, $name!";\n};\necho $greet("Aria") . "\\n";\n\n$triple = fn($x) => $x * 3;\necho $triple(4) . "\\n";\n?>',
  },
  {
    slug: 'date-and-time-php',
    title: 'Date & Time',
    summary: 'Formatting and computing dates with DateTime and date()',
    explanation: [
      "date('Y-m-d') formats the current time using letter codes, while the DateTime class wraps a moment in time as an object you can modify.",
      "->modify('+1 day') and ->diff() let you compute new dates and the gap between two dates.",
    ],
    example: '<?php\n$today = new DateTime("2024-01-15");\necho "Today: " . $today->format("Y-m-d") . "\\n";\n\n$nextWeek = clone $today;\n$nextWeek->modify("+7 days");\necho "Next week: " . $nextWeek->format("Y-m-d") . "\\n";\n\n$diff = $today->diff($nextWeek);\necho "Days between: " . $diff->days . "\\n";\n\necho "Formatted: " . date("l, F j, Y", strtotime("2024-12-25")) . "\\n";\n?>',
    starterCode: '<?php\n$birthday = new DateTime("2024-06-01");\necho "Birthday: " . $birthday->format("F j, Y") . "\\n";\n\n$birthday->modify("+30 days");\necho "30 days later: " . $birthday->format("Y-m-d") . "\\n";\n?>',
  },
  {
    slug: 'sorting-arrays-in-depth',
    title: 'Sorting Arrays In Depth',
    summary: 'sort, rsort, and usort for full control over ordering',
    explanation: [
      'sort($array) reorders values ascending and re-indexes the keys from 0; rsort($array) does the same in descending order. Both modify the array in place.',
      'When the default ordering is not enough, usort($array, fn($a, $b) => ...) lets you compare elements with your own logic — handy for sorting associative records, unlike ksort/asort which only sort by existing keys or values.',
    ],
    example: '<?php\n$numbers = [42, 7, 19, 3, 88];\nsort($numbers);\necho "Ascending: " . implode(", ", $numbers) . "\\n";\n\nrsort($numbers);\necho "Descending: " . implode(", ", $numbers) . "\\n";\n\n$people = [\n  ["name" => "Leo", "age" => 30],\n  ["name" => "Aria", "age" => 12],\n  ["name" => "Maya", "age" => 22],\n];\nusort($people, fn($a, $b) => $a["age"] <=> $b["age"]);\nforeach ($people as $p) {\n  echo "{$p[\'name\']}: {$p[\'age\']}\\n";\n}\n?>',
    starterCode: '<?php\n$scores = [55, 90, 12, 77];\nsort($scores);\necho implode(", ", $scores) . "\\n";\n\nrsort($scores);\necho implode(", ", $scores) . "\\n";\n?>',
  },
  {
    slug: 'string-interpolation-and-heredoc',
    title: 'String Interpolation & Heredoc',
    summary: 'Embedding variables in strings, and multi-line text with heredoc',
    explanation: [
      'Double-quoted strings interpolate variables directly, like "Hello, $name!", and curly braces {$expr} handle more complex expressions like array access.',
      'Heredoc syntax <<<EOT ... EOT; lets you write multi-line strings with full interpolation, without escaping quotes — great for templates or longer text blocks.',
    ],
    example: '<?php\n$name = "Aria";\n$age = 12;\necho "Hello, $name! You are $age years old.\\n";\n\n$student = ["name" => "Leo", "grade" => 7];\necho "{$student[\'name\']} is in grade {$student[\'grade\']}\\n";\n\n$message = <<<EOT\nDear $name,\n\nYou are turning $age this year.\nCongratulations!\nEOT;\necho $message . "\\n";\n?>',
    starterCode: '<?php\n$city = "Pokhara";\n$temp = 24;\n\n$report = <<<EOT\nWeather Report\nCity: $city\nTemperature: $temp degrees\nEOT;\necho $report . "\\n";\n?>',
  },
  {
    slug: 'type-declarations',
    title: 'Type Declarations',
    summary: 'Typed parameters, return types, and strict_types',
    explanation: [
      'You can declare the type of each function parameter and its return value: function add(int $a, int $b): int { return $a + $b; } — PHP will try to convert mismatched types unless strict mode is on.',
      "declare(strict_types=1); at the very top of a file turns off automatic type coercion, so passing a string where an int is expected throws an error instead of silently converting.",
    ],
    example: '<?php\ndeclare(strict_types=1);\n\nfunction add(int $a, int $b): int {\n  return $a + $b;\n}\n\nfunction greet(string $name): string {\n  return "Hello, $name!";\n}\n\necho add(3, 4) . "\\n";\necho greet("Aria") . "\\n";\n\ntry {\n  echo add(3, "4") . "\\n";\n} catch (TypeError $e) {\n  echo "Type error: " . $e->getMessage() . "\\n";\n}\n?>',
    starterCode: '<?php\nfunction multiply(float $a, float $b): float {\n  return $a * $b;\n}\n\necho multiply(2.5, 4) . "\\n";\n?>',
  },
  {
    slug: 'match-expression',
    title: 'The match Expression',
    summary: "PHP 8's compact, value-returning alternative to switch",
    explanation: [
      "match ($value) { 1, 2 => 'low', 3 => 'mid', default => 'high' }; compares with strict (===) checks, has no fallthrough, and returns a value directly instead of needing break.",
      'Multiple conditions can share one arm by separating them with commas, and you can assign the result of match straight to a variable.',
    ],
    example: '<?php\n$level = 2;\n\n$label = match ($level) {\n  1, 2 => "Beginner",\n  3, 4 => "Intermediate",\n  5 => "Advanced",\n  default => "Unknown",\n};\necho "Level $level: $label\\n";\n\n$status = 404;\n$message = match ($status) {\n  200 => "OK",\n  404 => "Not Found",\n  500 => "Server Error",\n  default => "Unknown Status",\n};\necho $message . "\\n";\n?>',
    starterCode: '<?php\n$day = 6;\n\n$type = match ($day) {\n  6, 7 => "Weekend",\n  default => "Weekday",\n};\necho "Day $day is a $type\\n";\n?>',
  },
  {
    slug: 'constants-and-define',
    title: 'Constants',
    summary: 'Fixed values that never change, with define() and const',
    explanation: [
      "define('NAME', value) creates a global constant that cannot be changed once set, accessed without a $ prefix: echo NAME;.",
      'Inside a class, const NAME = value; defines a constant tied to that class, accessed with ClassName::NAME — useful for fixed settings like a maximum size or a tax rate.',
    ],
    example: '<?php\ndefine("SITE_NAME", "Learn PHP");\necho SITE_NAME . "\\n";\n\nclass Circle {\n  const PI = 3.14159;\n\n  public $radius;\n\n  public function __construct($radius) {\n    $this->radius = $radius;\n  }\n\n  public function area() {\n    return self::PI * $this->radius * $this->radius;\n  }\n}\n\n$c = new Circle(4);\necho "Area: " . $c->area() . "\\n";\necho "PI constant: " . Circle::PI . "\\n";\n?>',
    starterCode: '<?php\ndefine("MAX_SCORE", 100);\necho "Max score is " . MAX_SCORE . "\\n";\n\nclass Config {\n  const VERSION = "1.0";\n}\n\necho "Version: " . Config::VERSION . "\\n";\n?>',
  },
  {
    slug: 'namespaces-in-php',
    title: 'Namespaces',
    summary: 'Organising classes into named groups to avoid name clashes',
    explanation: [
      "namespace App\\Models; at the top of a file groups everything below it under that name, so a class Models\\User and a class Auth\\User can coexist without colliding.",
      "The use keyword imports a class from another namespace so you can refer to it by its short name. This sandbox runs a single file, so we simulate multiple namespaces with PHP's curly-brace namespace syntax.",
    ],
    example: '<?php\nnamespace App\\Models {\n  class User {\n    public function describe() {\n      return "A Models User";\n    }\n  }\n}\n\nnamespace App\\Auth {\n  class User {\n    public function describe() {\n      return "An Auth User";\n    }\n  }\n}\n\nnamespace App {\n  use App\\Models\\User as ModelUser;\n  use App\\Auth\\User as AuthUser;\n\n  $m = new ModelUser();\n  $a = new AuthUser();\n  echo $m->describe() . "\\n";\n  echo $a->describe() . "\\n";\n}\n?>',
    starterCode: '<?php\nnamespace Shapes {\n  class Square {\n    public function area($side) {\n      return $side * $side;\n    }\n  }\n}\n\nnamespace Main {\n  use Shapes\\Square;\n\n  $s = new Square();\n  echo "Area: " . $s->area(5) . "\\n";\n}\n?>',
  },
  {
    slug: 'json-in-php',
    title: 'JSON in PHP',
    summary: 'Converting between PHP data and JSON strings',
    explanation: [
      'json_encode($data) turns a PHP array or object into a JSON string, ready to send over a network or save to a file.',
      'json_decode($json, true) parses a JSON string back into a PHP value — passing true returns an associative array instead of an object.',
    ],
    example: '<?php\n$student = ["name" => "Aria", "age" => 12, "subjects" => ["Math", "Art"]];\n\n$json = json_encode($student);\necho "Encoded: $json\\n";\n\n$decoded = json_decode($json, true);\necho "Name: " . $decoded["name"] . "\\n";\necho "First subject: " . $decoded["subjects"][0] . "\\n";\n?>',
    starterCode: '<?php\n$data = ["city" => "Pokhara", "temperature" => 24];\n\n$json = json_encode($data);\necho $json . "\\n";\n\n$back = json_decode($json, true);\necho "City: " . $back["city"] . "\\n";\n?>',
  },
  {
    slug: 'array-destructuring-php',
    title: 'Array Destructuring',
    summary: 'Unpacking array values into separate variables in one line',
    explanation: [
      'List assignment lets you unpack an indexed array directly into variables: [$a, $b] = [1, 2]; sets $a to 1 and $b to 2 in a single statement.',
      'Associative arrays can be destructured by key too: [\'name\' => $name] = $data; pulls out just the value you need by matching the key.',
    ],
    example: '<?php\n[$first, $second, $third] = ["red", "green", "blue"];\necho "$first, $second, $third\\n";\n\n$data = ["name" => "Aria", "age" => 12];\n["name" => $name, "age" => $age] = $data;\necho "$name is $age years old\\n";\n\nforeach ([[1, 2], [3, 4], [5, 6]] as [$x, $y]) {\n  echo "Pair: $x, $y\\n";\n}\n?>',
    starterCode: '<?php\n[$a, $b] = [10, 20];\necho "a=$a b=$b\\n";\n\n$person = ["name" => "Leo", "city" => "Pokhara"];\n["name" => $name] = $person;\necho "Name: $name\\n";\n?>',
  },
]
