import type { CodingLesson } from '../languages'

export const python: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to Python',
    summary: 'Friendly syntax and your first print statement',
    explanation: [
      'Python is famous for being readable and beginner-friendly. There are no semicolons or curly braces — indentation (spaces) defines blocks of code.',
      'print(...) displays output. Try changing the text below and press Run — your output appears in the Output panel.',
      'Lines starting with # are comments — notes for humans that Python ignores.',
    ],
    example: "print('Hello, world!')\nprint(2 + 3 * 4)\n# This is a comment",
    starterCode: "print('Hello, world!')\nprint(7 * 6)",
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Storing and combining values',
    explanation: [
      'Create a variable by assigning a value: name = "Aria". Python figures out the type automatically — strings, integers, floats, booleans, lists, and more.',
      'f-strings — f"{variable}" — let you embed variables directly inside text.',
    ],
    example: "name = 'Aria'\nage = 12\nprint(f'{name} is {age} years old')\nprint(type(age))",
    starterCode: "city = 'Pokhara'\ntemperature = 24\nprint(f'{city} is {temperature} degrees today')",
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Choosing what happens with if / elif / else',
    explanation: [
      'if checks a condition; elif ("else if") checks another; else runs when nothing matched. Each block is defined purely by indentation.',
      'Comparisons like ==, !=, >, and < produce True or False.',
    ],
    example: "score = 82\nif score >= 90:\n    print('Grade: A')\nelif score >= 75:\n    print('Grade: B')\nelse:\n    print('Keep practising!')",
    starterCode: "temperature = 30\nif temperature > 25:\n    print('It is warm')\nelse:\n    print('It is cool')",
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating actions with for and while',
    explanation: [
      'A for loop walks through a sequence: for i in range(5): repeats with i = 0,1,2,3,4.',
      'A while loop repeats as long as its condition stays True.',
      'You can loop directly over lists: for fruit in fruits: ...',
    ],
    example: "for i in range(1, 6):\n    print(f'Step {i}')\n\nfruits = ['apple', 'banana', 'mango']\nfor fruit in fruits:\n    print(fruit.upper())",
    starterCode: "for i in range(1, 4):\n    print(f'Count: {i}')",
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Packaging reusable logic with def',
    explanation: [
      'Define a function with def name(parameters):. Use return to send a value back to the caller.',
      'Functions help you avoid repeating yourself and make programs easier to understand.',
    ],
    example: "def double(n):\n    return n * 2\n\ndef greet(name):\n    return f'Hello, {name}!'\n\nprint(double(21))\nprint(greet('World'))",
    starterCode: "def square(n):\n    return n * n\n\nprint(square(6))",
  },
  {
    slug: 'lists-and-dicts',
    title: 'Lists & Dictionaries',
    summary: 'Working with collections of data',
    explanation: [
      'Lists hold ordered values: numbers = [1, 2, 3]. Use numbers[0] to access, len(numbers) for the length, and numbers.append(4) to add.',
      'Dictionaries hold key-value pairs: student = {"name": "Aria", "grade": 7}. Access values with student["name"].',
      'List comprehensions like [n * 2 for n in numbers] transform lists in one concise line.',
    ],
    example: "numbers = [1, 2, 3, 4, 5]\ndoubled = [n * 2 for n in numbers]\nevens = [n for n in numbers if n % 2 == 0]\nprint(doubled)\nprint(evens)\n\nstudent = {'name': 'Aria', 'grade': 7}\nprint(f\"{student['name']} is in grade {student['grade']}\")",
    starterCode: "scores = [70, 85, 92, 60]\npassing = [s for s in scores if s >= 70]\nprint(passing)",
  },
  {
    slug: 'strings',
    title: 'Strings in Depth',
    summary: 'Slicing, transforming, and formatting text',
    explanation: [
      'Strings can be sliced like lists: text[0:3] grabs a portion, and text[::-1] reverses it. Methods like .upper(), .lower(), .strip(), .split(), and .join() transform and combine text.',
      'f-strings let you embed expressions and formatting directly: f"{value:.2f}" formats a number to two decimal places.',
      '" ".join(words) glues a list of strings together with a separator, while .split() does the reverse.',
    ],
    example: "sentence = 'Python is fun to learn'\nprint(sentence[:6])\nprint(sentence[::-1])\nprint(sentence.upper())\n\nwords = sentence.split(' ')\nprint(words)\nprint('-'.join(words))\n\nprice = 19.999\nprint(f'Total: ${price:.2f}')",
    starterCode: "name = '  Aria Sharma  '\nclean = name.strip()\nprint(clean.upper())\nprint(clean.split(' '))\nprint('_'.join(clean.split(' ')))",
  },
  {
    slug: 'tuples-and-sets',
    title: 'Tuples & Sets',
    summary: 'Immutable sequences and collections of unique values',
    explanation: [
      'A tuple is like a list but cannot be changed after creation: point = (3, 4). Tuples are great for fixed groups of values, like coordinates.',
      'A set holds only unique values and supports math-like operations: union (|), intersection (&), and difference (-).',
      'Converting a list to a set with set(my_list) is a quick way to remove duplicates.',
    ],
    example: "point = (3, 4)\nx, y = point\nprint(f'x={x}, y={y}')\n\ntry:\n    point[0] = 10\nexcept TypeError as e:\n    print(f'Cannot modify a tuple: {e}')\n\nfruits_a = {'apple', 'banana', 'mango'}\nfruits_b = {'banana', 'kiwi', 'mango'}\nprint(fruits_a | fruits_b)\nprint(fruits_a & fruits_b)\nprint(fruits_a - fruits_b)\n\nnumbers = [1, 2, 2, 3, 3, 3]\nprint(set(numbers))",
    starterCode: "colors = ('red', 'green', 'blue')\nprint(colors[1])\n\nunique_letters = set('mississippi')\nprint(unique_letters)\nprint(len(unique_letters))",
  },
  {
    slug: 'dictionaries-in-depth',
    title: 'Dictionaries in Depth',
    summary: 'Looking up, looping, and nesting key-value data',
    explanation: [
      'Dictionaries map keys to values: student = {"name": "Aria", "grade": 7}. Use .get(key, default) to safely look up a key that might not exist.',
      '.keys(), .values(), and .items() let you loop over a dictionary\'s keys, values, or key-value pairs.',
      'Dictionaries can nest inside each other to represent more complex data, like a list of student records.',
    ],
    example: "student = {'name': 'Aria', 'grade': 7, 'subjects': ['Math', 'Art']}\n\nprint(student.get('name'))\nprint(student.get('age', 'unknown'))\n\nfor key, value in student.items():\n    print(f'{key}: {value}')\n\nschool = {\n    'Aria': {'grade': 7, 'club': 'Robotics'},\n    'Kiran': {'grade': 8, 'club': 'Chess'},\n}\nfor person, info in school.items():\n    print(f\"{person} is in grade {info['grade']} and joined {info['club']}\")",
    starterCode: "scores = {'Aria': 92, 'Kiran': 78, 'Maya': 85}\nfor name, score in scores.items():\n    print(f'{name}: {score}')\n\nprint(scores.get('Sam', 'no score yet'))\nprint(list(scores.keys()))",
  },
  {
    slug: 'file-and-exception-handling',
    title: 'Exception Handling',
    summary: 'Catching, raising, and cleaning up after errors',
    explanation: [
      'try / except lets you run code that might fail and handle the error instead of crashing: except ValueError as e: ...',
      'You can signal your own problems with raise ValueError("message"), which calling code can then catch and respond to.',
      'finally runs no matter what happened — perfect for cleanup steps that must always occur, like closing a connection.',
    ],
    example: "def parse_positive(value):\n    number = int(value)\n    if number <= 0:\n        raise ValueError(f'{number} is not positive')\n    return number\n\nfor text in ['12', 'abc', '-5']:\n    try:\n        n = parse_positive(text)\n        print(f'Parsed: {n}')\n    except ValueError as e:\n        print(f'Error: {e}')\n    finally:\n        print(f'Finished checking \"{text}\"')",
    starterCode: "def divide(a, b):\n    if b == 0:\n        raise ZeroDivisionError('Cannot divide by zero')\n    return a / b\n\ntry:\n    print(divide(10, 2))\n    print(divide(10, 0))\nexcept ZeroDivisionError as e:\n    print(f'Caught: {e}')",
  },
  {
    slug: 'classes-and-objects',
    title: 'Classes & Objects',
    summary: 'Blueprints for bundling data and behavior together',
    explanation: [
      'A class is a blueprint for creating objects: class Dog: defines what every dog will have. The __init__ method runs when you create a new instance and sets up its starting data.',
      'self refers to the specific instance a method is working with — it is always the first parameter of an instance method.',
      'Methods are functions defined inside a class that describe what instances of that class can do.',
    ],
    example: "class Animal:\n    def __init__(self, name, sound):\n        self.name = name\n        self.sound = sound\n\n    def speak(self):\n        return f'{self.name} says {self.sound}'\n\n\nclass Dog(Animal):\n    def __init__(self, name):\n        super().__init__(name, 'Woof')\n\n    def fetch(self):\n        return f'{self.name} fetches the ball!'\n\n\nrex = Dog('Rex')\nprint(rex.speak())\nprint(rex.fetch())\nprint(isinstance(rex, Animal))",
    starterCode: "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increment(self):\n        self.count += 1\n        return self.count\n\n\ncounter = Counter()\nprint(counter.increment())\nprint(counter.increment())\nprint(counter.count)",
  },
  {
    slug: 'comprehensions-and-generators',
    title: 'Comprehensions & Generators',
    summary: 'Building collections concisely and lazily',
    explanation: [
      'List, dict, and set comprehensions build new collections in one readable line: [n * n for n in range(5)], {n: n * n for n in range(5)}, {n % 3 for n in range(10)}.',
      'A generator expression looks like a list comprehension with parentheses — (n * n for n in range(5)) — but produces values one at a time instead of building the whole list in memory.',
      'Comprehensions can include conditions, like [n for n in numbers if n % 2 == 0], to filter while transforming.',
    ],
    example: "squares = [n * n for n in range(6)]\nprint(squares)\n\nsquare_map = {n: n * n for n in range(6)}\nprint(square_map)\n\nremainders = {n % 3 for n in range(10)}\nprint(remainders)\n\ntotal = sum(n * n for n in range(6))\nprint(total)\n\nwords = ['apple', 'kiwi', 'banana', 'fig']\nshort_upper = [w.upper() for w in words if len(w) <= 4]\nprint(short_upper)",
    starterCode: "numbers = [1, 2, 3, 4, 5, 6, 7, 8]\nevens_squared = [n * n for n in numbers if n % 2 == 0]\nprint(evens_squared)\n\ntotal = sum(n for n in numbers if n % 2 == 0)\nprint(total)",
  },
  {
    slug: 'modules-and-built-ins',
    title: 'Modules & Built-ins',
    summary: 'Borrowing tools from the standard library and built-in functions',
    explanation: [
      'import brings in extra functionality: import math gives you math.sqrt, math.pi, and more; import random gives you random.randint and random.choice.',
      'Handy built-in functions work on any sequence: sorted() orders items, enumerate() pairs items with their index, zip() pairs up multiple sequences, and map()/filter() transform or select items.',
      'Reaching for these built-ins instead of writing manual loops makes code shorter and easier to read.',
    ],
    example: "import math\nimport random\n\nprint(math.sqrt(144))\nprint(round(math.pi, 2))\n\nrandom.seed(42)\nprint(random.randint(1, 10))\n\nnames = ['Maya', 'Aria', 'Kiran']\nscores = [85, 92, 78]\n\nfor index, name in enumerate(names, start=1):\n    print(f'{index}. {name}')\n\nfor name, score in zip(names, scores):\n    print(f'{name}: {score}')\n\nprint(sorted(scores, reverse=True))\nprint(list(map(lambda s: s + 5, scores)))\nprint(list(filter(lambda s: s >= 85, scores)))",
    starterCode: "import math\n\nvalues = [4, 9, 16, 25]\nroots = list(map(math.sqrt, values))\nprint(roots)\n\nfor index, value in enumerate(values):\n    print(f'{index}: {value}')\n\nprint(sorted(values, reverse=True))",
  },
  {
    slug: 'args-kwargs-and-lambda',
    title: '*args, **kwargs & Lambda',
    summary: 'Flexible function signatures and tiny anonymous functions',
    explanation: [
      'def f(*args): collects any number of positional arguments into a tuple named args, so a function can accept 0, 1, or 100 values without changing its signature.',
      'def f(**kwargs): collects any number of named arguments into a dict named kwargs, letting callers pass arbitrary keyword=value pairs.',
      'lambda x: x * 2 creates a small anonymous function inline — handy as a quick argument to something like sorted(..., key=...) or map(...) when writing a full def would be overkill.',
    ],
    example: "def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3))\nprint(total(10, 20))\n\ndef describe(**kwargs):\n    for key, value in kwargs.items():\n        print(f'{key}: {value}')\n\ndescribe(name='Aria', grade=7)\n\nsquare = lambda x: x * 2\nprint(square(21))\n\npeople = [('Maya', 92), ('Aria', 78), ('Kiran', 85)]\nby_score = sorted(people, key=lambda person: person[1], reverse=True)\nprint(by_score)",
    starterCode: "def multiply_all(*args):\n    result = 1\n    for n in args:\n        result *= n\n    return result\n\nprint(multiply_all(2, 3, 4))\n\nwords = ['fig', 'banana', 'kiwi']\nprint(sorted(words, key=lambda w: len(w)))",
  },
]
