import type { CodingLesson } from '../languages'

export const python: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to Python',
    summary: 'Friendly syntax and your first print statement',
    explanation: [
      'Python is famous for being readable and beginner-friendly. There are no semicolons or curly braces — indentation (spaces) defines blocks of code.',
      'print(...) displays output. Try changing the text below and press Run — your output appears in the Output panel.',
      'Lines starting with # are comments — notes for humans that Python ignores.',
    ],
    example: "print('Hello, world!')\nprint(2 + 3 * 4)\n# This is a comment",
    starterCode: "print('Hello, world!')\nprint(7 * 6)",
  },
  {
    slug: 'variables',
    title: 'Variables & Types',
    summary: 'Storing and combining values',
    explanation: [
      'Create a variable by assigning a value: name = "Aria". Python figures out the type automatically — strings, integers, floats, booleans, lists, and more.',
      'f-strings — f"{variable}" — let you embed variables directly inside text.',
    ],
    example: "name = 'Aria'\nage = 12\nprint(f'{name} is {age} years old')\nprint(type(age))",
    starterCode: "city = 'Pokhara'\ntemperature = 24\nprint(f'{city} is {temperature} degrees today')",
  },
  {
    slug: 'conditionals',
    title: 'Conditionals',
    summary: 'Choosing what happens with if / elif / else',
    explanation: [
      'if checks a condition; elif ("else if") checks another; else runs when nothing matched. Each block is defined purely by indentation.',
      'Comparisons like ==, !=, >, and < produce True or False.',
    ],
    example: "score = 82\nif score >= 90:\n    print('Grade: A')\nelif score >= 75:\n    print('Grade: B')\nelse:\n    print('Keep practising!')",
    starterCode: "temperature = 30\nif temperature > 25:\n    print('It is warm')\nelse:\n    print('It is cool')",
  },
  {
    slug: 'loops',
    title: 'Loops',
    summary: 'Repeating actions with for and while',
    explanation: [
      'A for loop walks through a sequence: for i in range(5): repeats with i = 0,1,2,3,4.',
      'A while loop repeats as long as its condition stays True.',
      'You can loop directly over lists: for fruit in fruits: ...',
    ],
    example: "for i in range(1, 6):\n    print(f'Step {i}')\n\nfruits = ['apple', 'banana', 'mango']\nfor fruit in fruits:\n    print(fruit.upper())",
    starterCode: "for i in range(1, 4):\n    print(f'Count: {i}')",
  },
  {
    slug: 'functions',
    title: 'Functions',
    summary: 'Packaging reusable logic with def',
    explanation: [
      'Define a function with def name(parameters):. Use return to send a value back to the caller.',
      'Functions help you avoid repeating yourself and make programs easier to understand.',
    ],
    example: "def double(n):\n    return n * 2\n\ndef greet(name):\n    return f'Hello, {name}!'\n\nprint(double(21))\nprint(greet('World'))",
    starterCode: "def square(n):\n    return n * n\n\nprint(square(6))",
  },
  {
    slug: 'lists-and-dicts',
    title: 'Lists & Dictionaries',
    summary: 'Working with collections of data',
    explanation: [
      'Lists hold ordered values: numbers = [1, 2, 3]. Use numbers[0] to access, len(numbers) for the length, and numbers.append(4) to add.',
      'Dictionaries hold key-value pairs: student = {"name": "Aria", "grade": 7}. Access values with student["name"].',
      'List comprehensions like [n * 2 for n in numbers] transform lists in one concise line.',
    ],
    example: "numbers = [1, 2, 3, 4, 5]\ndoubled = [n * 2 for n in numbers]\nevens = [n for n in numbers if n % 2 == 0]\nprint(doubled)\nprint(evens)\n\nstudent = {'name': 'Aria', 'grade': 7}\nprint(f\"{student['name']} is in grade {student['grade']}\")",
    starterCode: "scores = [70, 85, 92, 60]\npassing = [s for s in scores if s >= 70]\nprint(passing)",
  },
  {
    slug: 'strings',
    title: 'Strings in Depth',
    summary: 'Slicing, transforming, and formatting text',
    explanation: [
      'Strings can be sliced like lists: text[0:3] grabs a portion, and text[::-1] reverses it. Methods like .upper(), .lower(), .strip(), .split(), and .join() transform and combine text.',
      'f-strings let you embed expressions and formatting directly: f"{value:.2f}" formats a number to two decimal places.',
      '" ".join(words) glues a list of strings together with a separator, while .split() does the reverse.',
    ],
    example: "sentence = 'Python is fun to learn'\nprint(sentence[:6])\nprint(sentence[::-1])\nprint(sentence.upper())\n\nwords = sentence.split(' ')\nprint(words)\nprint('-'.join(words))\n\nprice = 19.999\nprint(f'Total: ${price:.2f}')",
    starterCode: "name = '  Aria Sharma  '\nclean = name.strip()\nprint(clean.upper())\nprint(clean.split(' '))\nprint('_'.join(clean.split(' ')))",
  },
  {
    slug: 'tuples-and-sets',
    title: 'Tuples & Sets',
    summary: 'Immutable sequences and collections of unique values',
    explanation: [
      'A tuple is like a list but cannot be changed after creation: point = (3, 4). Tuples are great for fixed groups of values, like coordinates.',
      'A set holds only unique values and supports math-like operations: union (|), intersection (&), and difference (-).',
      'Converting a list to a set with set(my_list) is a quick way to remove duplicates.',
    ],
    example: "point = (3, 4)\nx, y = point\nprint(f'x={x}, y={y}')\n\ntry:\n    point[0] = 10\nexcept TypeError as e:\n    print(f'Cannot modify a tuple: {e}')\n\nfruits_a = {'apple', 'banana', 'mango'}\nfruits_b = {'banana', 'kiwi', 'mango'}\nprint(fruits_a | fruits_b)\nprint(fruits_a & fruits_b)\nprint(fruits_a - fruits_b)\n\nnumbers = [1, 2, 2, 3, 3, 3]\nprint(set(numbers))",
    starterCode: "colors = ('red', 'green', 'blue')\nprint(colors[1])\n\nunique_letters = set('mississippi')\nprint(unique_letters)\nprint(len(unique_letters))",
  },
  {
    slug: 'dictionaries-in-depth',
    title: 'Dictionaries in Depth',
    summary: 'Looking up, looping, and nesting key-value data',
    explanation: [
      'Dictionaries map keys to values: student = {"name": "Aria", "grade": 7}. Use .get(key, default) to safely look up a key that might not exist.',
      '.keys(), .values(), and .items() let you loop over a dictionary\'s keys, values, or key-value pairs.',
      'Dictionaries can nest inside each other to represent more complex data, like a list of student records.',
    ],
    example: "student = {'name': 'Aria', 'grade': 7, 'subjects': ['Math', 'Art']}\n\nprint(student.get('name'))\nprint(student.get('age', 'unknown'))\n\nfor key, value in student.items():\n    print(f'{key}: {value}')\n\nschool = {\n    'Aria': {'grade': 7, 'club': 'Robotics'},\n    'Kiran': {'grade': 8, 'club': 'Chess'},\n}\nfor person, info in school.items():\n    print(f\"{person} is in grade {info['grade']} and joined {info['club']}\")",
    starterCode: "scores = {'Aria': 92, 'Kiran': 78, 'Maya': 85}\nfor name, score in scores.items():\n    print(f'{name}: {score}')\n\nprint(scores.get('Sam', 'no score yet'))\nprint(list(scores.keys()))",
  },
  {
    slug: 'file-and-exception-handling',
    title: 'Exception Handling',
    summary: 'Catching, raising, and cleaning up after errors',
    explanation: [
      'try / except lets you run code that might fail and handle the error instead of crashing: except ValueError as e: ...',
      'You can signal your own problems with raise ValueError("message"), which calling code can then catch and respond to.',
      'finally runs no matter what happened — perfect for cleanup steps that must always occur, like closing a connection.',
    ],
    example: "def parse_positive(value):\n    number = int(value)\n    if number <= 0:\n        raise ValueError(f'{number} is not positive')\n    return number\n\nfor text in ['12', 'abc', '-5']:\n    try:\n        n = parse_positive(text)\n        print(f'Parsed: {n}')\n    except ValueError as e:\n        print(f'Error: {e}')\n    finally:\n        print(f'Finished checking \"{text}\"')",
    starterCode: "def divide(a, b):\n    if b == 0:\n        raise ZeroDivisionError('Cannot divide by zero')\n    return a / b\n\ntry:\n    print(divide(10, 2))\n    print(divide(10, 0))\nexcept ZeroDivisionError as e:\n    print(f'Caught: {e}')",
  },
  {
    slug: 'classes-and-objects',
    title: 'Classes & Objects',
    summary: 'Blueprints for bundling data and behavior together',
    explanation: [
      'A class is a blueprint for creating objects: class Dog: defines what every dog will have. The __init__ method runs when you create a new instance and sets up its starting data.',
      'self refers to the specific instance a method is working with — it is always the first parameter of an instance method.',
      'Methods are functions defined inside a class that describe what instances of that class can do.',
    ],
    example: "class Animal:\n    def __init__(self, name, sound):\n        self.name = name\n        self.sound = sound\n\n    def speak(self):\n        return f'{self.name} says {self.sound}'\n\n\nclass Dog(Animal):\n    def __init__(self, name):\n        super().__init__(name, 'Woof')\n\n    def fetch(self):\n        return f'{self.name} fetches the ball!'\n\n\nrex = Dog('Rex')\nprint(rex.speak())\nprint(rex.fetch())\nprint(isinstance(rex, Animal))",
    starterCode: "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increment(self):\n        self.count += 1\n        return self.count\n\n\ncounter = Counter()\nprint(counter.increment())\nprint(counter.increment())\nprint(counter.count)",
  },
  {
    slug: 'comprehensions-and-generators',
    title: 'Comprehensions & Generators',
    summary: 'Building collections concisely and lazily',
    explanation: [
      'List, dict, and set comprehensions build new collections in one readable line: [n * n for n in range(5)], {n: n * n for n in range(5)}, {n % 3 for n in range(10)}.',
      'A generator expression looks like a list comprehension with parentheses — (n * n for n in range(5)) — but produces values one at a time instead of building the whole list in memory.',
      'Comprehensions can include conditions, like [n for n in numbers if n % 2 == 0], to filter while transforming.',
    ],
    example: "squares = [n * n for n in range(6)]\nprint(squares)\n\nsquare_map = {n: n * n for n in range(6)}\nprint(square_map)\n\nremainders = {n % 3 for n in range(10)}\nprint(remainders)\n\ntotal = sum(n * n for n in range(6))\nprint(total)\n\nwords = ['apple', 'kiwi', 'banana', 'fig']\nshort_upper = [w.upper() for w in words if len(w) <= 4]\nprint(short_upper)",
    starterCode: "numbers = [1, 2, 3, 4, 5, 6, 7, 8]\nevens_squared = [n * n for n in numbers if n % 2 == 0]\nprint(evens_squared)\n\ntotal = sum(n for n in numbers if n % 2 == 0)\nprint(total)",
  },
  {
    slug: 'modules-and-built-ins',
    title: 'Modules & Built-ins',
    summary: 'Borrowing tools from the standard library and built-in functions',
    explanation: [
      'import brings in extra functionality: import math gives you math.sqrt, math.pi, and more; import random gives you random.randint and random.choice.',
      'Handy built-in functions work on any sequence: sorted() orders items, enumerate() pairs items with their index, zip() pairs up multiple sequences, and map()/filter() transform or select items.',
      'Reaching for these built-ins instead of writing manual loops makes code shorter and easier to read.',
    ],
    example: "import math\nimport random\n\nprint(math.sqrt(144))\nprint(round(math.pi, 2))\n\nrandom.seed(42)\nprint(random.randint(1, 10))\n\nnames = ['Maya', 'Aria', 'Kiran']\nscores = [85, 92, 78]\n\nfor index, name in enumerate(names, start=1):\n    print(f'{index}. {name}')\n\nfor name, score in zip(names, scores):\n    print(f'{name}: {score}')\n\nprint(sorted(scores, reverse=True))\nprint(list(map(lambda s: s + 5, scores)))\nprint(list(filter(lambda s: s >= 85, scores)))",
    starterCode: "import math\n\nvalues = [4, 9, 16, 25]\nroots = list(map(math.sqrt, values))\nprint(roots)\n\nfor index, value in enumerate(values):\n    print(f'{index}: {value}')\n\nprint(sorted(values, reverse=True))",
  },
  {
    slug: 'args-kwargs-and-lambda',
    title: '*args, **kwargs & Lambda',
    summary: 'Flexible function signatures and tiny anonymous functions',
    explanation: [
      'def f(*args): collects any number of positional arguments into a tuple named args, so a function can accept 0, 1, or 100 values without changing its signature.',
      'def f(**kwargs): collects any number of named arguments into a dict named kwargs, letting callers pass arbitrary keyword=value pairs.',
      'lambda x: x * 2 creates a small anonymous function inline — handy as a quick argument to something like sorted(..., key=...) or map(...) when writing a full def would be overkill.',
    ],
    example: "def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3))\nprint(total(10, 20))\n\ndef describe(**kwargs):\n    for key, value in kwargs.items():\n        print(f'{key}: {value}')\n\ndescribe(name='Aria', grade=7)\n\nsquare = lambda x: x * 2\nprint(square(21))\n\npeople = [('Maya', 92), ('Aria', 78), ('Kiran', 85)]\nby_score = sorted(people, key=lambda person: person[1], reverse=True)\nprint(by_score)",
    starterCode: "def multiply_all(*args):\n    result = 1\n    for n in args:\n        result *= n\n    return result\n\nprint(multiply_all(2, 3, 4))\n\nwords = ['fig', 'banana', 'kiwi']\nprint(sorted(words, key=lambda w: len(w)))",
  },
  {
    slug: 'decorators',
    title: 'Decorators',
    summary: 'Wrapping functions to add extra behavior',
    explanation: [
      'A decorator is a function that takes another function and returns a new, enhanced version of it. The @my_decorator syntax above a function definition is shorthand for wrapping it automatically.',
      'Decorators are great for adding behavior — like timing, logging, or checks — without changing the original function\'s code.',
      'Inside a decorator, the inner function usually accepts *args and **kwargs so it can wrap functions with any signature.',
    ],
    example: "import time\n\ndef log_calls(func):\n    def wrapper(*args, **kwargs):\n        print(f'Calling {func.__name__} with {args}')\n        result = func(*args, **kwargs)\n        print(f'{func.__name__} returned {result}')\n        return result\n    return wrapper\n\n\n@log_calls\ndef add(a, b):\n    return a + b\n\n\nadd(3, 4)",
    starterCode: "def shout(func):\n    def wrapper(*args, **kwargs):\n        result = func(*args, **kwargs)\n        return result.upper()\n    return wrapper\n\n\n@shout\ndef greet(name):\n    return f'hello, {name}'\n\n\nprint(greet('aria'))",
  },
  {
    slug: 'context-managers',
    title: 'Context Managers',
    summary: 'Setting up and tearing down with the with statement',
    explanation: [
      'The with statement guarantees that setup and cleanup code run together, even if an error happens in between — commonly used for files or connections.',
      'You can write your own context manager by defining a class with __enter__ (runs at the start of the with block) and __exit__ (runs at the end, even on error).',
      '__enter__ returns the value used after as, and __exit__ is where cleanup logic belongs.',
    ],
    example: "class Resource:\n    def __init__(self, name):\n        self.name = name\n\n    def __enter__(self):\n        print(f'Opening {self.name}')\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        print(f'Closing {self.name}')\n        return False\n\n\nwith Resource('database connection') as res:\n    print(f'Using {res.name}')",
    starterCode: "class Timer:\n    def __enter__(self):\n        print('Starting timer')\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        print('Stopping timer')\n\n\nwith Timer():\n    print('Doing some work...')",
  },
  {
    slug: 'dunder-methods',
    title: 'Dunder Methods',
    summary: 'Special methods that customize how your class behaves',
    explanation: [
      '"Dunder" methods (double underscore, like __init__) let your class hook into Python\'s built-in behavior. __str__ controls what print() shows, and __repr__ controls the developer-facing representation.',
      '__eq__ lets you define what == means for your objects, and __len__ lets len() work on your instances.',
      'Without these, Python falls back to generic defaults like a memory address — dunder methods make your objects feel like native Python types.',
    ],
    example: "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __str__(self):\n        return f'({self.x}, {self.y})'\n\n    def __repr__(self):\n        return f'Point({self.x!r}, {self.y!r})'\n\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\n\n\np1 = Point(1, 2)\np2 = Point(1, 2)\nprint(p1)\nprint(repr(p1))\nprint(p1 == p2)",
    starterCode: "class Playlist:\n    def __init__(self, songs):\n        self.songs = songs\n\n    def __len__(self):\n        return len(self.songs)\n\n    def __str__(self):\n        return f'Playlist with {len(self)} songs'\n\n\nmy_playlist = Playlist(['Song A', 'Song B', 'Song C'])\nprint(my_playlist)\nprint(len(my_playlist))",
  },
  {
    slug: 'property-decorator',
    title: 'The @property Decorator',
    summary: 'Computed attributes that look like plain data',
    explanation: [
      '@property turns a method into something you access like a regular attribute, without parentheses — useful for values computed from other attributes.',
      'Pairing it with @name.setter lets you control what happens when someone assigns to that attribute, like validating the new value.',
      'This keeps your class\'s interface simple while still letting you add logic behind the scenes.',
    ],
    example: "class Circle:\n    def __init__(self, radius):\n        self._radius = radius\n\n    @property\n    def radius(self):\n        return self._radius\n\n    @radius.setter\n    def radius(self, value):\n        if value <= 0:\n            raise ValueError('radius must be positive')\n        self._radius = value\n\n    @property\n    def area(self):\n        return 3.14159 * self._radius ** 2\n\n\ncircle = Circle(4)\nprint(circle.radius)\nprint(circle.area)\ncircle.radius = 10\nprint(circle.area)",
    starterCode: "class Temperature:\n    def __init__(self, celsius):\n        self._celsius = celsius\n\n    @property\n    def fahrenheit(self):\n        return self._celsius * 9 / 5 + 32\n\n\ntemp = Temperature(20)\nprint(temp.fahrenheit)",
  },
  {
    slug: 'static-and-class-methods',
    title: 'Static & Class Methods',
    summary: 'Three flavors of methods: instance, class, and static',
    explanation: [
      'A regular instance method takes self and works with one specific object. A @classmethod takes cls instead, and works with the class itself — often used for alternate constructors.',
      'A @staticmethod takes neither self nor cls — it is just a regular function that happens to live inside the class because it is logically related.',
      'Use @classmethod when you need access to the class, and @staticmethod when you do not need access to the instance or the class at all.',
    ],
    example: "class Pizza:\n    def __init__(self, toppings):\n        self.toppings = toppings\n\n    def describe(self):\n        return f'Pizza with {\", \".join(self.toppings)}'\n\n    @classmethod\n    def margherita(cls):\n        return cls(['tomato', 'mozzarella', 'basil'])\n\n    @staticmethod\n    def is_valid_topping(topping):\n        return topping.lower() not in {'pineapple'}\n\n\npizza = Pizza.margherita()\nprint(pizza.describe())\nprint(Pizza.is_valid_topping('mushroom'))\nprint(Pizza.is_valid_topping('pineapple'))",
    starterCode: "class MathHelper:\n    @staticmethod\n    def add(a, b):\n        return a + b\n\n    @classmethod\n    def class_name(cls):\n        return cls.__name__\n\n\nprint(MathHelper.add(3, 5))\nprint(MathHelper.class_name())",
  },
  {
    slug: 'type-hints',
    title: 'Type Hints',
    summary: 'Documenting expected types without changing runtime behavior',
    explanation: [
      'Type hints let you write def greet(name: str) -> str: to show what types a function expects and returns. Variables can be hinted too: age: int = 12.',
      'Python does not actually enforce these hints at runtime — they are purely for humans and tools like editors and type checkers to catch mistakes early.',
      'Hints make code easier to read and help catch bugs before you even run the program.',
    ],
    example: "def greet(name: str) -> str:\n    return f'Hello, {name}!'\n\n\ndef total_price(prices: list[float], tax_rate: float = 0.1) -> float:\n    subtotal = sum(prices)\n    return subtotal * (1 + tax_rate)\n\n\nprint(greet('Aria'))\nprint(total_price([10.0, 20.0, 5.5]))\n\n# Python won't stop this even though it 'breaks' the hint:\nprint(greet(42))",
    starterCode: "def square(n: int) -> int:\n    return n * n\n\n\nage: int = 12\nname: str = 'Kiran'\nprint(square(age))\nprint(f'{name} is {age}')",
  },
  {
    slug: 'custom-exceptions-and-hierarchy',
    title: 'Custom Exceptions & Hierarchy',
    summary: 'Defining your own error types for clearer handling',
    explanation: [
      'You can create your own exception types by subclassing Exception: class ValidationError(Exception): pass. This lets calling code catch exactly the errors your program raises.',
      'Catching the specific exception type (except ValidationError) is more precise than catching the general Exception, which would also swallow unrelated bugs.',
      'You can build a small hierarchy of related exceptions, letting code catch a broad category or a specific case as needed.',
    ],
    example: "class ValidationError(Exception):\n    pass\n\n\nclass AgeError(ValidationError):\n    pass\n\n\ndef check_age(age):\n    if age < 0:\n        raise AgeError(f'Age cannot be negative: {age}')\n    return age\n\n\nfor value in [12, -5]:\n    try:\n        print(check_age(value))\n    except AgeError as e:\n        print(f'Age problem: {e}')\n    except ValidationError as e:\n        print(f'Validation problem: {e}')",
    starterCode: "class InsufficientFundsError(Exception):\n    pass\n\n\ndef withdraw(balance, amount):\n    if amount > balance:\n        raise InsufficientFundsError('Not enough money!')\n    return balance - amount\n\n\ntry:\n    print(withdraw(100, 150))\nexcept InsufficientFundsError as e:\n    print(f'Error: {e}')",
  },
  {
    slug: 'iterator-protocol',
    title: 'The Iterator Protocol',
    summary: 'Making your own objects work in a for loop',
    explanation: [
      'A class becomes iterable by defining __iter__ (which returns an iterator) and __next__ (which returns the next value, raising StopIteration when done).',
      'This is the same protocol that powers for loops over lists and dicts — once your class implements it, instances work directly in a for loop.',
      'The comprehensions-and-generators lesson showed generators as a shortcut for this — a generator function automatically creates an object that follows this same protocol for you.',
    ],
    example: "class Countdown:\n    def __init__(self, start):\n        self.current = start\n\n    def __iter__(self):\n        return self\n\n    def __next__(self):\n        if self.current <= 0:\n            raise StopIteration\n        value = self.current\n        self.current -= 1\n        return value\n\n\nfor number in Countdown(5):\n    print(number)",
    starterCode: "class Evens:\n    def __init__(self, limit):\n        self.limit = limit\n        self.current = 0\n\n    def __iter__(self):\n        return self\n\n    def __next__(self):\n        if self.current > self.limit:\n            raise StopIteration\n        value = self.current\n        self.current += 2\n        return value\n\n\nfor n in Evens(10):\n    print(n)",
  },
  {
    slug: 'unpacking-and-star-expressions',
    title: 'Unpacking & Star Expressions',
    summary: 'Spreading sequences into multiple variables at once',
    explanation: [
      'You can unpack a sequence directly into variables: a, b, c = [1, 2, 3]. The * symbol lets one variable soak up the leftover items: first, *rest = [1, 2, 3, 4].',
      'The star variable can appear anywhere: first, *middle, last = items grabs the first and last items, with everything else collected into middle as a list.',
      'This is handy for quickly pulling out the parts of a sequence you care about without manual indexing.',
    ],
    example: "numbers = [1, 2, 3, 4, 5]\nfirst, *rest = numbers\nprint(first)\nprint(rest)\n\n*beginning, last = numbers\nprint(beginning)\nprint(last)\n\nfirst, *middle, last = numbers\nprint(first, middle, last)\n\na, b, *_ = (10, 20, 30, 40)\nprint(a, b)",
    starterCode: "scores = [95, 80, 70, 65, 50]\nhighest, *rest, lowest = scores\nprint(f'Highest: {highest}')\nprint(f'Lowest: {lowest}')\nprint(f'Middle: {rest}')",
  },
  {
    slug: 'string-formatting-mini-language',
    title: 'String Formatting Mini-Language',
    summary: 'Fine control over width, alignment, and decimals',
    explanation: [
      'Inside an f-string, a colon introduces a format spec: f"{value:>10.2f}" right-aligns a number in a 10-character field with 2 decimal places.',
      'Common specs include .2f for fixed decimals, .1% for a percentage, , for thousands separators, and < > ^ for left/right/center alignment with optional padding characters.',
      'These specs work the same way with the format() function, so format(value, ".2f") behaves identically to an f-string version.',
    ],
    example: "price = 1234.5\nprint(f'{price:,.2f}')\n\nratio = 0.4567\nprint(f'{ratio:.1%}')\n\nfor word in ['cat', 'elephant', 'fox']:\n    print(f'{word:<10}|')\n\nfor word in ['cat', 'elephant', 'fox']:\n    print(f'{word:>10}|')\n\nfor word in ['cat', 'elephant', 'fox']:\n    print(f'{word:^10}|')\n\nprint(f'{42:05d}')",
    starterCode: "values = [3.14159, 2.71828, 1.41421]\nfor v in values:\n    print(f'{v:8.2f}')\n\ndiscount = 0.25\nprint(f'Discount: {discount:.0%}')",
  },
  {
    slug: 'collections-module',
    title: 'The collections Module',
    summary: 'Specialized containers for common patterns',
    explanation: [
      'Counter(items) tallies how many times each item appears, and gives you handy methods like .most_common().',
      'defaultdict(list) is a dictionary that automatically creates a default value (like an empty list) the first time you access a missing key, avoiding manual key checks.',
      'namedtuple lets you create lightweight, readable record types where fields are accessed by name instead of by index.',
    ],
    example: "from collections import Counter, defaultdict, namedtuple\n\nwords = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']\ncounts = Counter(words)\nprint(counts)\nprint(counts.most_common(2))\n\ngroups = defaultdict(list)\nfor word in words:\n    groups[word[0]].append(word)\nprint(dict(groups))\n\nPoint = namedtuple('Point', ['x', 'y'])\np = Point(3, 4)\nprint(p.x, p.y)\nprint(p)",
    starterCode: "from collections import Counter\n\nletters = list('mississippi')\ncounts = Counter(letters)\nprint(counts)\nprint(counts.most_common(1))",
  },
  {
    slug: 'itertools-basics',
    title: 'itertools Basics',
    summary: 'Combining and iterating sequences efficiently',
    explanation: [
      'itertools.chain(a, b) lets you loop over multiple sequences as if they were one, without copying them into a new list.',
      'itertools.product(a, b) gives every combination of pairs (like a nested loop), while itertools.combinations(a, r) gives every unique group of r items, ignoring order.',
      'These tools are memory-efficient because they generate values lazily, one at a time, instead of building everything up front.',
    ],
    example: "import itertools\n\nlist_a = [1, 2, 3]\nlist_b = ['x', 'y']\n\nprint(list(itertools.chain(list_a, list_b)))\n\nprint(list(itertools.product(list_a, list_b)))\n\nprint(list(itertools.combinations(list_a, 2)))",
    starterCode: "import itertools\n\ncolors = ['red', 'blue']\nsizes = ['S', 'M', 'L']\n\nfor color, size in itertools.product(colors, sizes):\n    print(f'{color} - {size}')",
  },
  {
    slug: 'recursion',
    title: 'Recursion',
    summary: 'Functions that solve problems by calling themselves',
    explanation: [
      'A recursive function calls itself with a smaller version of the problem, until it reaches a base case that stops the recursion.',
      'Every recursive function needs at least one base case (a simple condition that returns directly) to avoid calling itself forever.',
      'Recursion is often used for problems that naturally break into smaller versions of themselves, like factorials or Fibonacci numbers.',
    ],
    example: "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\n\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\n\nprint(factorial(5))\nfor i in range(8):\n    print(fibonacci(i), end=' ')\nprint()",
    starterCode: "def countdown(n):\n    if n <= 0:\n        print('Done!')\n        return\n    print(n)\n    countdown(n - 1)\n\n\ncountdown(5)",
  },
  {
    slug: 'walrus-operator',
    title: 'The Walrus Operator :=',
    summary: 'Assigning a value as part of an expression',
    explanation: [
      'The walrus operator := lets you assign a variable and use its value in the same expression, instead of assigning it on a separate line first.',
      'It is especially handy in while loop conditions, like while (line := get_next()) is not None:, and inside comprehensions to avoid recomputing a value.',
      'Use it when you would otherwise compute the same value twice — once to check it, and once to use it.',
    ],
    example: "import random\nrandom.seed(7)\n\nvalues = [random.randint(1, 20) for _ in range(8)]\nprint(values)\n\nbig_values = [v for v in values if (doubled := v * 2) > 20]\nprint(big_values)\n\nindex = 0\nwhile (current := values[index]) != values[-1]:\n    print(f'Checking {current}')\n    index += 1\nprint('Reached the last value')",
    starterCode: "numbers = [3, 8, 1, 15, 6, 20]\nresults = [half for n in numbers if (half := n / 2) > 4]\nprint(results)",
  },
  {
    slug: 'json-module',
    title: 'The json Module',
    summary: 'Converting between Python objects and JSON text',
    explanation: [
      'json.dumps(obj) turns a Python dict or list into a JSON-formatted string, useful for sending data or saving it as text.',
      'json.loads(text) does the reverse, parsing a JSON string back into Python dicts, lists, numbers, and strings.',
      'json.dumps(obj, indent=2) produces nicely formatted, human-readable output, which is great for debugging.',
    ],
    example: "import json\n\nstudent = {'name': 'Aria', 'grade': 7, 'subjects': ['Math', 'Art'], 'active': True}\n\njson_text = json.dumps(student)\nprint(json_text)\n\npretty = json.dumps(student, indent=2)\nprint(pretty)\n\nparsed = json.loads(json_text)\nprint(parsed['name'])\nprint(type(parsed))",
    starterCode: "import json\n\ndata = {'city': 'Pokhara', 'temperature': 24, 'sunny': True}\ntext = json.dumps(data)\nprint(text)\n\nback = json.loads(text)\nprint(back['city'], back['temperature'])",
  },
  {
    slug: 'sorting-with-key-functions',
    title: 'Sorting with Key Functions',
    summary: 'Customizing sort order with key and reverse',
    explanation: [
      'sorted(items, key=...) lets you control what value Python compares when sorting — pass a function (often a lambda) that extracts the part you care about.',
      'reverse=True flips the order from ascending to descending without changing the key logic.',
      'For sorting by multiple criteria, use a tuple as the key, like key=lambda p: (p["grade"], p["name"]) — Python compares tuples element by element.',
    ],
    example: "students = [\n    {'name': 'Maya', 'grade': 7, 'score': 92},\n    {'name': 'Aria', 'grade': 8, 'score': 78},\n    {'name': 'Kiran', 'grade': 7, 'score': 85},\n]\n\nby_score = sorted(students, key=lambda s: s['score'], reverse=True)\nfor s in by_score:\n    print(s['name'], s['score'])\n\nby_grade_then_name = sorted(students, key=lambda s: (s['grade'], s['name']))\nfor s in by_grade_then_name:\n    print(s['grade'], s['name'])",
    starterCode: "words = ['banana', 'fig', 'kiwi', 'apple']\nby_length = sorted(words, key=lambda w: len(w))\nprint(by_length)\n\nby_length_desc = sorted(words, key=lambda w: len(w), reverse=True)\nprint(by_length_desc)",
  },
  {
    slug: 'f-strings-advanced',
    title: 'Advanced f-strings',
    summary: 'Embedding expressions and format specs inside f-strings',
    explanation: [
      'f-strings can hold more than plain variables — any expression works inside the braces, like f"{a + b}" or f"{name.upper()}".',
      'Adding != or = after an expression, like f"{value=}", prints both the expression text and its value — handy for quick debugging.',
      'You can nest a format spec dynamically using another pair of braces: f"{number:{width}.2f}" lets the width itself come from a variable.',
    ],
    example: "name = 'aria'\nscore = 87.5\nprint(f'{name.title()} scored {score:.1f} points')\nprint(f'{score=}')\n\nwidth = 10\nfor n in [3.5, 42.125, 7]:\n    print(f'{n:{width}.2f}')\n\nitems = ['apple', 'kiwi']\nprint(f'You have {len(items)} item{\"s\" if len(items) != 1 else \"\"}')",
    starterCode: "a = 6\nb = 7\nprint(f'{a} * {b} = {a * b}')\nprint(f'{a=} {b=}')\n\nprecision = 3\npi = 3.14159265\nprint(f'{pi:.{precision}f}')",
  },
  {
    slug: 'enumerate-and-zip',
    title: 'enumerate() & zip()',
    summary: 'Pairing values with indexes, and combining parallel sequences',
    explanation: [
      'enumerate(sequence) gives you (index, value) pairs as you loop, so you never need to manually track a counter. enumerate(sequence, start=1) lets you choose the starting number.',
      'zip(a, b) walks through two (or more) sequences together, pairing up items at the same position — great for combining related lists.',
      'zip stops as soon as the shortest sequence runs out, so mismatched lengths simply get truncated rather than causing an error.',
    ],
    example: "fruits = ['apple', 'banana', 'mango']\nfor index, fruit in enumerate(fruits):\n    print(index, fruit)\n\nfor rank, fruit in enumerate(fruits, start=1):\n    print(f'{rank}. {fruit}')\n\nnames = ['Maya', 'Aria', 'Kiran']\nscores = [92, 78, 85]\nfor name, score in zip(names, scores):\n    print(f'{name}: {score}')\n\nshort = [1, 2]\nlong = ['a', 'b', 'c', 'd']\nprint(list(zip(short, long)))",
    starterCode: "colors = ['red', 'green', 'blue']\nfor i, color in enumerate(colors, start=1):\n    print(f'{i}: {color}')\n\nnumbers = [1, 2, 3]\nletters = ['a', 'b', 'c']\npaired = list(zip(numbers, letters))\nprint(paired)",
  },
  {
    slug: 'multiple-inheritance-and-mro',
    title: 'Multiple Inheritance & MRO',
    summary: 'Classes that inherit from more than one parent',
    explanation: [
      'A class can inherit from multiple parents at once: class Hybrid(Flyer, Swimmer):. It gains the attributes and methods of both.',
      'When two parents define the same method, Python decides which one wins using the Method Resolution Order (MRO) — check it with ClassName.__mro__ or ClassName.mro().',
      'super() follows the MRO, not just "the direct parent", so in multiple inheritance it can hop between sibling classes in a predictable, linear order.',
    ],
    example: "class Flyer:\n    def move(self):\n        return 'flies through the air'\n\n\nclass Swimmer:\n    def move(self):\n        return 'swims through water'\n\n\nclass Duck(Flyer, Swimmer):\n    pass\n\n\nduck = Duck()\nprint(duck.move())\nprint([cls.__name__ for cls in Duck.__mro__])",
    starterCode: "class Walker:\n    def move(self):\n        return 'walks'\n\n\nclass Climber:\n    def move(self):\n        return 'climbs'\n\n\nclass Bear(Walker, Climber):\n    pass\n\n\nbear = Bear()\nprint(bear.move())\nprint([cls.__name__ for cls in Bear.__mro__])",
  },
  {
    slug: 'abstract-base-classes',
    title: 'Abstract Base Classes',
    summary: 'Defining required methods with the abc module',
    explanation: [
      'ABC (from the abc module) marks a class as abstract — it cannot be instantiated directly, only subclassed.',
      '@abstractmethod marks a method that every concrete subclass must override. Trying to instantiate a subclass that skips an abstract method raises a TypeError.',
      'Abstract base classes are useful for defining a shared interface, guaranteeing that all subclasses implement certain behavior.',
    ],
    example: "from abc import ABC, abstractmethod\n\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\n\nclass Square(Shape):\n    def __init__(self, side):\n        self.side = side\n\n    def area(self):\n        return self.side ** 2\n\n\nsquare = Square(4)\nprint(square.area())\n\ntry:\n    shape = Shape()\nexcept TypeError as e:\n    print(f'Error: {e}')",
    starterCode: "from abc import ABC, abstractmethod\n\n\nclass Vehicle(ABC):\n    @abstractmethod\n    def wheels(self):\n        pass\n\n\nclass Car(Vehicle):\n    def wheels(self):\n        return 4\n\n\ncar = Car()\nprint(car.wheels())",
  },
  {
    slug: 'dataclasses',
    title: 'Dataclasses',
    summary: 'Less boilerplate for classes that mainly hold data',
    explanation: [
      '@dataclass automatically generates __init__, __repr__, and __eq__ for a class based on its annotated fields, saving you from writing them by hand.',
      'Fields can have default values, like quantity: int = 1, and the generated __init__ accepts them as keyword arguments too.',
      'Because __eq__ is generated, two dataclass instances with the same field values compare as equal, unlike plain classes.',
    ],
    example: "from dataclasses import dataclass\n\n\n@dataclass\nclass Product:\n    name: str\n    price: float\n    quantity: int = 1\n\n\np1 = Product('Notebook', 2.5)\np2 = Product('Notebook', 2.5)\nprint(p1)\nprint(p1 == p2)\nprint(p1.price * p1.quantity)",
    starterCode: "from dataclasses import dataclass\n\n\n@dataclass\nclass Point:\n    x: int\n    y: int\n\n\np = Point(3, 4)\nprint(p)\nprint(p.x + p.y)",
  },
  {
    slug: 'named-tuples',
    title: 'Named Tuples',
    summary: 'Lightweight, immutable records with named fields',
    explanation: [
      'collections.namedtuple(\"Point\", [\"x\", \"y\"]) creates a tuple subclass where fields can be accessed by name (p.x) instead of only by index (p[0]).',
      'Named tuples are still regular tuples — they support unpacking, indexing, and iteration — but reading p.x is clearer than p[0].',
      '._asdict() converts a named tuple into a regular dict, and ._replace(x=10) creates a modified copy since named tuples remain immutable.',
    ],
    example: "from collections import namedtuple\n\nPoint = namedtuple('Point', ['x', 'y'])\np = Point(3, 4)\nprint(p.x, p.y)\nprint(p[0], p[1])\n\nx, y = p\nprint(x, y)\n\nprint(p._asdict())\nmoved = p._replace(x=10)\nprint(moved)",
    starterCode: "from collections import namedtuple\n\nStudent = namedtuple('Student', ['name', 'grade'])\ns = Student('Aria', 7)\nprint(s.name, s.grade)\nprint(s._asdict())",
  },
  {
    slug: 'deque-and-heapq',
    title: 'deque & heapq',
    summary: 'Fast queues and priority queues from the standard library',
    explanation: [
      'collections.deque is a double-ended queue — appendleft() and popleft() run in constant time, unlike a regular list where removing from the front is slow.',
      'deque(maxlen=3) automatically discards old items once it is full, which is handy for things like a rolling window of recent values.',
      'heapq turns a regular list into a min-heap: heapq.heappush(heap, value) and heapq.heappop(heap) always return the smallest item efficiently, which is the basis of a priority queue.',
    ],
    example: "from collections import deque\nimport heapq\n\nqueue = deque()\nqueue.append('a')\nqueue.append('b')\nqueue.appendleft('z')\nprint(queue)\nprint(queue.popleft())\n\nrecent = deque(maxlen=3)\nfor n in range(6):\n    recent.append(n)\nprint(recent)\n\nheap = [5, 1, 8, 3]\nheapq.heapify(heap)\nheapq.heappush(heap, 0)\nprint(heapq.heappop(heap))\nprint(heapq.heappop(heap))",
    starterCode: "from collections import deque\nimport heapq\n\ntasks = deque(['email', 'report'])\ntasks.appendleft('urgent fix')\nprint(tasks)\n\npriorities = [4, 1, 7, 2]\nheapq.heapify(priorities)\nprint(heapq.heappop(priorities))",
  },
  {
    slug: 'functools-reduce-and-partial',
    title: 'functools.reduce & partial',
    summary: 'Folding sequences into a single value, and pre-filling arguments',
    explanation: [
      'functools.reduce(function, sequence, initial) repeatedly applies a two-argument function, folding a sequence down into a single accumulated result.',
      'reduce(lambda acc, n: acc + n, numbers, 0) is equivalent to summing — reduce is general enough to express sum, product, max, and more.',
      'functools.partial(function, fixed_arg) creates a new function with some arguments already filled in, useful for adapting a general function to a more specific use.',
    ],
    example: "from functools import reduce, partial\n\nnumbers = [1, 2, 3, 4, 5]\ntotal = reduce(lambda acc, n: acc + n, numbers, 0)\nprint(total)\n\nproduct = reduce(lambda acc, n: acc * n, numbers, 1)\nprint(product)\n\ndef power(base, exponent):\n    return base ** exponent\n\nsquare = partial(power, exponent=2)\ncube = partial(power, exponent=3)\nprint(square(5))\nprint(cube(2))",
    starterCode: "from functools import reduce, partial\n\nwords = ['Py', 'thon', ' is', ' fun']\nsentence = reduce(lambda acc, w: acc + w, words, '')\nprint(sentence)\n\ndef multiply(a, b):\n    return a * b\n\ndouble = partial(multiply, 2)\nprint(double(9))",
  },
  {
    slug: 'regular-expressions-python',
    title: 'Regular Expressions',
    summary: 'Pattern matching text with the re module',
    explanation: [
      're.match(pattern, text) checks for a match at the start of a string, while re.search(pattern, text) looks for a match anywhere in it. Both return a Match object or None.',
      'Patterns use special symbols: \\d for digits, \\w for word characters, + for "one or more", and () to capture groups you can extract with .group(1).',
      're.sub(pattern, replacement, text) finds all matches and replaces them, similar to a smarter version of str.replace().',
    ],
    example: "import re\n\ntext = 'Call 555-1234 or 555-9876'\n\nmatch = re.search(r'\\d{3}-\\d{4}', text)\nprint(match.group())\n\nall_numbers = re.findall(r'\\d{3}-\\d{4}', text)\nprint(all_numbers)\n\nemail = 'aria@example.com'\nresult = re.match(r'(\\w+)@(\\w+)\\.com', email)\nprint(result.group(1))\nprint(result.group(2))\n\ncensored = re.sub(r'\\d', '#', text)\nprint(censored)",
    starterCode: "import re\n\ntext = 'Order ID: A123, Order ID: B456'\nids = re.findall(r'[A-Z]\\d+', text)\nprint(ids)\n\ncleaned = re.sub(r'\\s+', ' ', '  Aria   Sharma  ')\nprint(cleaned.strip())",
  },
  {
    slug: 'slicing-advanced',
    title: 'Advanced Slicing',
    summary: 'Steps, negative indices, and slicing tricks',
    explanation: [
      'A slice has the form sequence[start:stop:step]. Any of the three parts can be omitted: numbers[::2] takes every second item from start to end.',
      'A negative step reverses direction: numbers[::-1] reverses the whole sequence, and numbers[5:1:-1] walks backward between two positions.',
      'Negative indices count from the end: numbers[-3:] grabs the last three items, and slicing never raises an IndexError even if the range goes out of bounds.',
    ],
    example: "numbers = list(range(10))\nprint(numbers[::2])\nprint(numbers[1::2])\nprint(numbers[::-1])\nprint(numbers[-3:])\nprint(numbers[2:8:3])\nprint(numbers[100:200])\n\ntext = 'Python Programming'\nprint(text[::-1])\nprint(text[::3])",
    starterCode: "letters = list('abcdefghij')\nprint(letters[::2])\nprint(letters[::-1])\nprint(letters[-4:])\nprint(letters[2:9:2])",
  },
  {
    slug: 'generator-expressions-vs-list-comprehensions',
    title: 'Generator Expressions vs List Comprehensions',
    summary: 'Lazy evaluation and memory tradeoffs',
    explanation: [
      'A list comprehension [n * n for n in range(5)] builds the entire list in memory immediately. A generator expression (n * n for n in range(5)) instead produces a lazy iterator that computes one value at a time.',
      'Generators are far more memory-efficient for large or infinite sequences, since they never hold the whole sequence at once — but they can only be iterated through once.',
      'sum(...), any(...), and other functions that consume an iterable work directly with generator expressions, so you often do not need the extra brackets of a list comprehension at all.',
    ],
    example: "import sys\n\nlist_comp = [n * n for n in range(1000)]\ngen_exp = (n * n for n in range(1000))\n\nprint(sys.getsizeof(list_comp))\nprint(sys.getsizeof(gen_exp))\n\nprint(sum(n * n for n in range(10)))\n\ngen = (n for n in range(3))\nprint(list(gen))\nprint(list(gen))",
    starterCode: "numbers = range(1, 1000001)\ntotal = sum(n for n in numbers if n % 7 == 0)\nprint(total)\n\nsquares_gen = (n * n for n in range(5))\nfor value in squares_gen:\n    print(value)",
  },
  {
    slug: 'exception-chaining',
    title: 'Exception Chaining',
    summary: 'Connecting a new error to the one that caused it',
    explanation: [
      'raise NewError("message") from original_error attaches the original exception as the __cause__ of the new one, preserving the full story of what went wrong.',
      'This is useful inside an except block when you want to raise a more specific or higher-level error without losing the original traceback information.',
      'Printing or logging a chained exception shows both errors: "The above exception was the direct cause of the following exception."',
    ],
    example: "class DataError(Exception):\n    pass\n\n\ndef parse(value):\n    try:\n        return int(value)\n    except ValueError as e:\n        raise DataError(f'Could not parse {value!r}') from e\n\n\ntry:\n    parse('abc')\nexcept DataError as e:\n    print(f'Error: {e}')\n    print(f'Caused by: {e.__cause__}')",
    starterCode: "class ConfigError(Exception):\n    pass\n\n\ndef load_setting(value):\n    try:\n        return 100 / value\n    except ZeroDivisionError as e:\n        raise ConfigError('Setting cannot be zero') from e\n\n\ntry:\n    load_setting(0)\nexcept ConfigError as e:\n    print(f'{e} (caused by {type(e.__cause__).__name__})')",
  },
  {
    slug: 'operator-overloading-python',
    title: 'Operator Overloading',
    summary: 'Defining how +, ==, and other operators work for your objects',
    explanation: [
      'Dunder methods like __add__ let you define what + means between instances of your class: def __add__(self, other): return Vector(self.x + other.x, ...).',
      'Comparison operators each have their own dunder: __eq__ for ==, __lt__ for <, and so on — defining these lets your objects work with sorted() and comparisons naturally.',
      'Python calls these methods automatically whenever the corresponding operator is used, so a + b becomes a.__add__(b) behind the scenes.',
    ],
    example: "class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\n\n    def __repr__(self):\n        return f'Vector({self.x}, {self.y})'\n\n\nv1 = Vector(1, 2)\nv2 = Vector(3, 4)\nprint(v1 + v2)\nprint(v1 == Vector(1, 2))",
    starterCode: "class Money:\n    def __init__(self, amount):\n        self.amount = amount\n\n    def __add__(self, other):\n        return Money(self.amount + other.amount)\n\n    def __repr__(self):\n        return f'${self.amount}'\n\n\nwallet = Money(10) + Money(25)\nprint(wallet)",
  },
  {
    slug: 'copy-shallow-vs-deep',
    title: 'Shallow vs Deep Copy',
    summary: 'Understanding copy.copy() and copy.deepcopy()',
    explanation: [
      'Assigning a list to a new variable (b = a) does not copy it — both names point to the same object, so changes through one affect the other.',
      'copy.copy(obj) makes a shallow copy: the outer container is new, but nested objects inside it (like lists within a list) are still shared with the original.',
      'copy.deepcopy(obj) recursively copies everything, including nested objects, so the result is fully independent of the original.',
    ],
    example: "import copy\n\noriginal = [1, 2, [3, 4]]\n\nreference = original\nreference[0] = 99\nprint(original)\n\nshallow = copy.copy(original)\nshallow[1] = 100\nprint(original, shallow)\n\nshallow[2].append(5)\nprint(original, shallow)\n\ndeep = copy.deepcopy(original)\ndeep[2].append(6)\nprint(original, deep)",
    starterCode: "import copy\n\nmatrix = [[1, 2], [3, 4]]\nshallow = copy.copy(matrix)\nshallow[0].append(99)\nprint(matrix)\n\ndeep = copy.deepcopy(matrix)\ndeep[0].append(0)\nprint(matrix, deep)",
  },
  {
    slug: 'math-and-random-modules',
    title: 'math & random Modules',
    summary: 'Common numeric helpers and pseudo-random values',
    explanation: [
      'The math module provides constants like math.pi and math.e, and functions like math.sqrt(), math.floor(), math.ceil(), and math.gcd().',
      'The random module generates pseudo-random values: random.random() for a float between 0 and 1, random.randint(a, b) for an integer in a range, and random.choice(seq) to pick one item.',
      'random.seed(n) makes "random" results reproducible — useful for testing, since the same seed always produces the same sequence of values.',
    ],
    example: "import math\nimport random\n\nprint(math.sqrt(81))\nprint(math.floor(4.7), math.ceil(4.3))\nprint(math.gcd(12, 18))\nprint(round(math.pi, 4))\n\nrandom.seed(1)\nprint(random.randint(1, 6))\nprint(random.choice(['rock', 'paper', 'scissors']))\n\nnumbers = [3, 1, 4, 1, 5, 9]\nrandom.shuffle(numbers)\nprint(numbers)",
    starterCode: "import math\nimport random\n\nrandom.seed(5)\nprint(math.sqrt(64))\nprint(math.ceil(3.2))\nprint(random.randint(1, 100))\nprint(random.choice(['red', 'green', 'blue']))",
  },
]
