import type { CodingLesson } from '../languages'

export const react: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to React',
    summary: 'Building UIs out of components with JSX',
    explanation: [
      'React is a library for building user interfaces out of small, reusable pieces called components. A component is just a function that returns what should appear on screen.',
      'JSX is a syntax that lets you write HTML-like markup inside JavaScript, like <h1>Hello</h1> — it gets transformed into regular function calls behind the scenes.',
      'ReactDOM.createRoot(container).render(<App />) takes a component and draws it onto the page.',
    ],
    example: "function App() {\n  return (\n    <div>\n      <h1>Hello, React!</h1>\n      <p>This is your first component.</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function App() {\n  return <h1>Welcome to React</h1>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'jsx-basics',
    title: 'JSX Basics',
    summary: 'Mixing expressions, attributes, and tags in your markup',
    explanation: [
      'Curly braces {} let you drop any JavaScript expression straight into your JSX, like {2 + 2} or {user.name}.',
      'JSX attributes look like HTML but use camelCase and className instead of class, since class is a reserved word in JavaScript.',
      'Tags that have no children can self-close with a slash, like <img /> or <br />.',
    ],
    example: "function App() {\n  const name = 'Aria';\n  const score = 92;\n\n  return (\n    <div className=\"card\">\n      <h2>Hello, {name}!</h2>\n      <p>Your score is {score} out of 100.</p>\n      <p>Doubled: {score * 2}</p>\n      <hr />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function App() {\n  const language = 'React';\n\n  return (\n    <div className=\"box\">\n      <h2>Learning {language}</h2>\n      <p>2 + 2 = {2 + 2}</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'props',
    title: 'Props',
    summary: 'Passing data into components',
    explanation: [
      'Props are how a parent component passes data down to a child component, similar to arguments passed into a function.',
      'A component receives its props as an object: function Greeting(props) { return <p>{props.name}</p> }. You can also destructure them directly: function Greeting({ name }) { ... }.',
      'Props make components reusable — the same component can render differently depending on what data it receives.',
    ],
    example: "function Greeting({ name, role }) {\n  return (\n    <li>\n      {name} — <strong>{role}</strong>\n    </li>\n  );\n}\n\nfunction App() {\n  return (\n    <ul>\n      <Greeting name=\"Aria\" role=\"Captain\" />\n      <Greeting name=\"Kiran\" role=\"Coder\" />\n      <Greeting name=\"Maya\" role=\"Designer\" />\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Badge({ label, color }) {\n  return <span className={color}>{label}</span>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Badge label=\"New\" color=\"green\" />\n      <Badge label=\"Hot\" color=\"red\" />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'state-and-hooks',
    title: 'State & Hooks',
    summary: 'Letting components remember and update values with useState',
    explanation: [
      'State is data a component remembers between renders. The useState hook gives you a value and a function to update it: const [count, setCount] = React.useState(0).',
      'Calling the setter function (like setCount(count + 1)) updates the state and tells React to re-render the component with the new value.',
      'Because React is loaded globally here, hooks are accessed as React.useState, React.useEffect, and so on.',
    ],
    example: "function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Add one</button>\n      <button onClick={() => setCount(0)}>Reset</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
    starterCode: "function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <div>\n      <p>You clicked {count} times</p>\n      <button onClick={() => setCount(count + 1)}>Click me</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
  },
  {
    slug: 'event-handling',
    title: 'Event Handling',
    summary: 'Responding to clicks and other user actions',
    explanation: [
      'In JSX, you attach event handlers with camelCase props like onClick, onChange, or onSubmit, and pass them a function to run.',
      'Event handlers are often used together with useState to update what the component remembers in response to what the user does.',
      'Writing onClick={() => doSomething()} creates a function that only runs when the event actually happens, not while rendering.',
    ],
    example: "function LikeButton() {\n  const [likes, setLikes] = React.useState(0);\n  const [liked, setLiked] = React.useState(false);\n\n  function handleClick() {\n    setLikes(liked ? likes - 1 : likes + 1);\n    setLiked(!liked);\n  }\n\n  return (\n    <div>\n      <button onClick={handleClick}>{liked ? 'Liked!' : 'Like'}</button>\n      <p>{likes} people like this</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<LikeButton />);",
    starterCode: "function ColorPicker() {\n  const [color, setColor] = React.useState('gray');\n\n  return (\n    <div>\n      <p>Selected color: {color}</p>\n      <button onClick={() => setColor('red')}>Red</button>\n      <button onClick={() => setColor('blue')}>Blue</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<ColorPicker />);",
  },
  {
    slug: 'conditional-rendering',
    title: 'Conditional Rendering',
    summary: 'Showing different JSX depending on a condition',
    explanation: [
      'You can use a regular JavaScript if statement before the return to decide what JSX to send back.',
      'Inside JSX, the && operator shows something only when a condition is true: {isLoggedIn && <p>Welcome back!</p>}.',
      'The ternary operator condition ? a : b lets you pick between two pieces of JSX in a single expression.',
    ],
    example: "function Status({ isOnline, messages }) {\n  return (\n    <div>\n      <p>Status: {isOnline ? 'Online 🟢' : 'Offline ⚪'}</p>\n      {messages > 0 && <p>You have {messages} new messages</p>}\n      {messages === 0 && <p>No new messages</p>}\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <Status isOnline={true} messages={3} />\n      <Status isOnline={false} messages={0} />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Greeting({ loggedIn }) {\n  return (\n    <div>\n      {loggedIn ? <p>Welcome back!</p> : <p>Please log in.</p>}\n      {loggedIn && <button>Log out</button>}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Greeting loggedIn={true} />);",
  },
  {
    slug: 'lists-and-keys',
    title: 'Lists & Keys',
    summary: 'Rendering arrays of data with .map()',
    explanation: [
      'To render a list of items, use .map() to turn an array of data into an array of JSX elements.',
      'Each item in a rendered list needs a unique key prop, like key={item.id} — this helps React keep track of which item is which when the list changes.',
      'Keys should come from stable data (like an id), not from the array index, whenever possible.',
    ],
    example: "function TodoList() {\n  const todos = [\n    { id: 1, text: 'Learn JSX' },\n    { id: 2, text: 'Build a component' },\n    { id: 3, text: 'Use props and state' },\n  ];\n\n  return (\n    <ul>\n      {todos.map(todo => (\n        <li key={todo.id}>{todo.text}</li>\n      ))}\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<TodoList />);",
    starterCode: "function FruitList() {\n  const fruits = ['Apple', 'Banana', 'Mango'];\n\n  return (\n    <ul>\n      {fruits.map((fruit, index) => (\n        <li key={index}>{fruit}</li>\n      ))}\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<FruitList />);",
  },
  {
    slug: 'effects',
    title: 'Effects',
    summary: 'Running code in response to rendering with useEffect',
    explanation: [
      'The useEffect hook lets a component run code "on the side" — after it renders — such as logging, fetching data, or setting up a timer.',
      'React.useEffect(() => { ... }, []) with an empty array runs the effect only once, right after the component first appears.',
      'If you list values in the second argument, like [count], the effect re-runs whenever those values change.',
    ],
    example: "function Welcome() {\n  const [seconds, setSeconds] = React.useState(0);\n\n  React.useEffect(() => {\n    console.log('Welcome component mounted');\n    const timer = setInterval(() => {\n      setSeconds(s => s + 1);\n    }, 1000);\n    return () => clearInterval(timer);\n  }, []);\n\n  React.useEffect(() => {\n    console.log(`Seconds elapsed: ${seconds}`);\n  }, [seconds]);\n\n  return <p>Seconds since mount: {seconds}</p>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Welcome />);",
    starterCode: "function Logger() {\n  const [count, setCount] = React.useState(0);\n\n  React.useEffect(() => {\n    console.log('Logger mounted');\n  }, []);\n\n  React.useEffect(() => {\n    console.log(`Count is now ${count}`);\n  }, [count]);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Increase</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Logger />);",
  },
  {
    slug: 'forms-and-controlled-inputs',
    title: 'Forms & Controlled Inputs',
    summary: "Letting React state drive an input's value",
    explanation: [
      "A controlled input's value comes from state, not from the DOM: <input value={text} onChange={e => setText(e.target.value)} /> keeps state and the input perfectly in sync.",
      'Because state holds the current value, you can validate, transform, or react to every keystroke before it ever reaches the input.',
      "Submitting a form calls a handler on its onSubmit event; calling event.preventDefault() stops the browser's default full-page reload so React can handle the submission itself.",
    ],
    example: "function SignupForm() {\n  const [name, setName] = React.useState('');\n  const [submitted, setSubmitted] = React.useState('');\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    setSubmitted(name);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        Name:\n        <input value={name} onChange={e => setName(e.target.value)} />\n      </label>\n      <button type=\"submit\">Sign up</button>\n      {submitted && <p>Welcome, {submitted}!</p>}\n    </form>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SignupForm />);",
    starterCode: "function SearchBox() {\n  const [query, setQuery] = React.useState('');\n\n  return (\n    <div>\n      <input\n        value={query}\n        onChange={e => setQuery(e.target.value)}\n        placeholder=\"Search...\"\n      />\n      <p>You typed: {query}</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SearchBox />);",
  },
  {
    slug: 'lifting-state-and-composition',
    title: 'Lifting State Up & Composition',
    summary: 'Sharing state between components and nesting components with children',
    explanation: [
      '"Lifting state up" means moving state to the nearest shared parent of the components that need it, then passing both the value and an updater function down as props.',
      'A component can accept other JSX as a prop called children — <Card><p>Inside</p></Card> passes the paragraph to Card as props.children — which lets components wrap arbitrary content.',
      'Composition (building bigger components out of smaller ones passed as children or props) is usually more flexible than trying to make one component handle every possible case through configuration props.',
    ],
    example: "function Card({ children }) {\n  return <div className=\"card\">{children}</div>;\n}\n\nfunction TemperatureInput({ label, value, onChange }) {\n  return (\n    <label>\n      {label}: <input value={value} onChange={e => onChange(e.target.value)} />\n    </label>\n  );\n}\n\nfunction Converter() {\n  const [celsius, setCelsius] = React.useState('0');\n  const fahrenheit = (Number(celsius) * 9) / 5 + 32;\n\n  return (\n    <Card>\n      <TemperatureInput label=\"Celsius\" value={celsius} onChange={setCelsius} />\n      <p>Fahrenheit: {fahrenheit}</p>\n    </Card>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Converter />);",
    starterCode: "function Panel({ children }) {\n  return <div style={{ border: '1px solid gray', padding: '8px' }}>{children}</div>;\n}\n\nfunction NameInput({ value, onChange }) {\n  return <input value={value} onChange={e => onChange(e.target.value)} />;\n}\n\nfunction App() {\n  const [name, setName] = React.useState('');\n\n  return (\n    <Panel>\n      <NameInput value={name} onChange={setName} />\n      <p>Hello, {name || 'stranger'}!</p>\n    </Panel>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'context',
    title: 'Context & useContext',
    summary: 'Sharing a value with every component below, without passing props by hand',
    explanation: [
      'React.createContext(defaultValue) creates a Context object — a channel for sharing a value with any component underneath it in the tree, no matter how deeply nested.',
      'A <ThemeContext.Provider value={...}> wraps part of the tree and supplies the actual value; every descendant can read it.',
      "Inside any descendant, React.useContext(ThemeContext) reads the nearest Provider's value directly, skipping the need to pass it down through every component in between as a prop.",
    ],
    example: "const ThemeContext = React.createContext('light');\n\nfunction ThemedButton() {\n  const theme = React.useContext(ThemeContext);\n  return <button>Current theme: {theme}</button>;\n}\n\nfunction Toolbar() {\n  return (\n    <div>\n      <ThemedButton />\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "const UserContext = React.createContext('Guest');\n\nfunction Greeting() {\n  const user = React.useContext(UserContext);\n  return <p>Hello, {user}!</p>;\n}\n\nfunction App() {\n  return (\n    <UserContext.Provider value=\"Aria\">\n      <Greeting />\n    </UserContext.Provider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'custom-hooks',
    title: 'Custom Hooks',
    summary: 'Packaging reusable stateful logic into your own hook',
    explanation: [
      'A custom hook is just a regular function whose name starts with use and which calls other hooks inside it — that naming convention is how React and linters know it follows the rules of hooks.',
      "Custom hooks let you extract logic like 'track a toggled boolean' or 'track a counter' out of a component and reuse it in many components without copying code.",
      'A custom hook returns whatever is useful to its caller — often the current state plus one or more functions to update it, similar to what useState itself returns.',
    ],
    example: "function useCounter(initial = 0) {\n  const [count, setCount] = React.useState(initial);\n  const increment = () => setCount(c => c + 1);\n  const reset = () => setCount(initial);\n  return { count, increment, reset };\n}\n\nfunction Counter() {\n  const { count, increment, reset } = useCounter(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={increment}>+1</button>\n      <button onClick={reset}>Reset</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
    starterCode: "function useToggle(initial = false) {\n  const [value, setValue] = React.useState(initial);\n  const toggle = () => setValue(v => !v);\n  return [value, toggle];\n}\n\nfunction Light() {\n  const [isOn, toggle] = useToggle(false);\n\n  return (\n    <button onClick={toggle}>\n      {isOn ? 'Light is ON' : 'Light is OFF'}\n    </button>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Light />);",
  },
  {
    slug: 'refs-and-dom',
    title: 'Refs & useRef',
    summary: 'Reaching directly into a DOM node, or remembering a value without re-rendering',
    explanation: [
      'React.useRef(initialValue) returns a mutable ref object with a single .current property that persists across renders without causing a re-render when it changes.',
      "Passing a ref to an element's ref attribute, like <input ref={inputRef} />, gives you direct access to that real DOM node in inputRef.current — handy for focusing an input or measuring it.",
      'Unlike state, updating a ref\'s .current value does not trigger a re-render, which makes refs ideal for values you need to track but never need to show on screen, like a previous value or a timer ID.',
    ],
    example: "function FocusableInput() {\n  const inputRef = React.useRef(null);\n\n  function focusInput() {\n    inputRef.current.focus();\n  }\n\n  return (\n    <div>\n      <input ref={inputRef} placeholder=\"Click the button to focus me\" />\n      <button onClick={focusInput}>Focus the input</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<FocusableInput />);",
    starterCode: "function ClickCounter() {\n  const countRef = React.useRef(0);\n  const [display, setDisplay] = React.useState(0);\n\n  function handleClick() {\n    countRef.current += 1;\n    setDisplay(countRef.current);\n  }\n\n  return (\n    <div>\n      <p>Clicked {display} times (tracked in a ref)</p>\n      <button onClick={handleClick}>Click me</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<ClickCounter />);",
  },
  {
    slug: 'performance-and-memoization',
    title: 'Performance & Memoization',
    summary: 'Skipping unnecessary recalculations with useMemo and useCallback',
    explanation: [
      'React.useMemo(() => computeValue(), [deps]) re-runs an expensive calculation only when one of its dependencies actually changes, reusing the previous result otherwise.',
      "React.useCallback(fn, [deps]) does the same thing for functions — it returns the same function reference between renders as long as the dependencies haven't changed, which matters when that function is passed to a child component.",
      'These hooks are optimizations, not requirements — reach for them when you notice a real slowdown from expensive work or unnecessary re-renders, not on every value by default.',
    ],
    example: "function expensiveSum(n) {\n  let total = 0;\n  for (let i = 0; i <= n; i++) total += i;\n  return total;\n}\n\nfunction Calculator() {\n  const [n, setN] = React.useState(10);\n  const [theme, setTheme] = React.useState('light');\n\n  const sum = React.useMemo(() => expensiveSum(n), [n]);\n\n  return (\n    <div>\n      <p>Sum up to {n}: {sum}</p>\n      <button onClick={() => setN(n + 1)}>Increase n</button>\n      <button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>\n        Toggle theme ({theme})\n      </button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Calculator />);",
    starterCode: "function square(n) {\n  return n * n;\n}\n\nfunction SquareCalculator() {\n  const [number, setNumber] = React.useState(4);\n  const result = React.useMemo(() => square(number), [number]);\n\n  return (\n    <div>\n      <p>{number} squared is {result}</p>\n      <button onClick={() => setNumber(number + 1)}>+1</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SquareCalculator />);",
  },
  {
    slug: 'fragments',
    title: 'Fragments',
    summary: 'Grouping elements without adding an extra wrapper node',
    explanation: [
      "A component can only return one element, but you don't always want an extra <div> just to group siblings — Fragments solve that.",
      "Writing <>...</> (or the longer <React.Fragment>...</React.Fragment>) groups multiple children together without adding anything to the actual DOM.",
      'Use the explicit React.Fragment form (instead of <>) when you need to pass a key, such as inside a .map() call.',
    ],
    example: "function Glossary() {\n  return (\n    <>\n      <dt>JSX</dt>\n      <dd>A syntax extension that lets you write HTML-like markup in JavaScript.</dd>\n      <dt>Props</dt>\n      <dd>Data passed from a parent component to a child component.</dd>\n    </>\n  );\n}\n\nfunction App() {\n  return (\n    <dl>\n      <Glossary />\n    </dl>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function NameParts() {\n  return (\n    <>\n      <span>Ada</span>\n      <span> </span>\n      <span>Lovelace</span>\n    </>\n  );\n}\n\nfunction App() {\n  return (\n    <p>\n      <NameParts />\n    </p>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'default-props-and-validation',
    title: 'Default Props & Validation',
    summary: 'Giving props sensible fallback values and sanity-checking them',
    explanation: [
      "You can give a destructured prop a default value right in the function signature, like function Greeting({ name = 'Guest' }) — if name is never passed, it falls back to 'Guest'.",
      'Default values only kick in when the prop is undefined, so passing an empty string or 0 will not trigger the fallback.',
      'A simple manual check (like verifying a prop is the expected type before using it) can catch mistakes early and give a clearer error than a confusing crash later.',
    ],
    example: "function Avatar({ name = 'Guest', size = 40 }) {\n  if (typeof size !== 'number') {\n    console.warn('Avatar expected a numeric size, got', typeof size);\n  }\n\n  return (\n    <div style={{ width: size, height: size, border: '1px solid gray', borderRadius: '50%' }}>\n      {name[0]}\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <Avatar name=\"Maya\" size={60} />\n      <Avatar />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Greeting({ name = 'Guest' }) {\n  return <p>Hello, {name}!</p>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Greeting name=\"Aria\" />\n      <Greeting />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'error-boundaries',
    title: 'Error Boundaries',
    summary: 'Catching rendering errors in child components with a fallback UI',
    explanation: [
      'An error boundary is a class component that catches JavaScript errors thrown while rendering its children, instead of letting the whole app crash.',
      'static getDerivedStateFromError(error) updates state so the next render shows a fallback UI, and componentDidCatch(error, info) lets you log what went wrong.',
      'Wrap any part of your tree that might fail in an error boundary, like <ErrorBoundary><RiskyWidget /></ErrorBoundary>, to contain the damage to just that section.',
    ],
    example: "class ErrorBoundary extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state = { hasError: false };\n  }\n\n  static getDerivedStateFromError(error) {\n    return { hasError: true };\n  }\n\n  componentDidCatch(error, info) {\n    console.log('Caught an error:', error.message);\n  }\n\n  render() {\n    if (this.state.hasError) {\n      return <p>Something went wrong in this section.</p>;\n    }\n    return this.props.children;\n  }\n}\n\nfunction Bomb() {\n  throw new Error('Boom!');\n}\n\nfunction App() {\n  return (\n    <div>\n      <p>This part is fine.</p>\n      <ErrorBoundary>\n        <Bomb />\n      </ErrorBoundary>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "class ErrorBoundary extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state = { hasError: false };\n  }\n\n  static getDerivedStateFromError(error) {\n    return { hasError: true };\n  }\n\n  render() {\n    if (this.state.hasError) {\n      return <p>Oops, that widget broke.</p>;\n    }\n    return this.props.children;\n  }\n}\n\nfunction Risky({ shouldThrow }) {\n  if (shouldThrow) throw new Error('Failed to render');\n  return <p>Widget rendered safely.</p>;\n}\n\nfunction App() {\n  return (\n    <ErrorBoundary>\n      <Risky shouldThrow={true} />\n    </ErrorBoundary>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'usereducer-basics',
    title: 'useReducer Basics',
    summary: 'Managing more complex state with a reducer function and dispatched actions',
    explanation: [
      'React.useReducer(reducer, initialState) is an alternative to useState for state that changes in several related ways — it returns the current state and a dispatch function.',
      "Instead of calling a setter directly, you dispatch action objects like dispatch({ type: 'increment' }), and the reducer function decides how each action changes the state.",
      "Reducers keep all your state transition logic in one place, which can be easier to follow than scattering several useState calls and updater functions around a component.",
    ],
    example: "function reducer(state, action) {\n  switch (action.type) {\n    case 'increment':\n      return { count: state.count + 1 };\n    case 'decrement':\n      return { count: state.count - 1 };\n    case 'reset':\n      return { count: 0 };\n    default:\n      throw new Error('Unknown action: ' + action.type);\n  }\n}\n\nfunction Counter() {\n  const [state, dispatch] = React.useReducer(reducer, { count: 0 });\n\n  return (\n    <div>\n      <p>Count: {state.count}</p>\n      <button onClick={() => dispatch({ type: 'increment' })}>+1</button>\n      <button onClick={() => dispatch({ type: 'decrement' })}>-1</button>\n      <button onClick={() => dispatch({ type: 'reset' })}>Reset</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
    starterCode: "function reducer(state, action) {\n  if (action.type === 'add') {\n    return { total: state.total + action.amount };\n  }\n  return state;\n}\n\nfunction Wallet() {\n  const [state, dispatch] = React.useReducer(reducer, { total: 0 });\n\n  return (\n    <div>\n      <p>Total: ${state.total}</p>\n      <button onClick={() => dispatch({ type: 'add', amount: 10 })}>Add $10</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Wallet />);",
  },
  {
    slug: 'controlled-vs-uncontrolled',
    title: 'Controlled vs Uncontrolled Inputs',
    summary: 'Letting React state drive an input, versus reading the DOM only when needed',
    explanation: [
      "A controlled input's value always comes from React state, so the input and state can never get out of sync — React re-renders the input every time state changes.",
      "An uncontrolled input keeps its own value in the DOM, and you only read it when you need to (often with a ref), which means fewer re-renders but less moment-to-moment control.",
      'Controlled inputs are usually preferred when you need live validation or to react to every keystroke; uncontrolled inputs are simpler for plain forms where you just need the final value on submit.',
    ],
    example: "function ControlledExample() {\n  const [value, setValue] = React.useState('');\n  return (\n    <div>\n      <input value={value} onChange={e => setValue(e.target.value)} />\n      <p>Controlled value: {value}</p>\n    </div>\n  );\n}\n\nfunction UncontrolledExample() {\n  const inputRef = React.useRef(null);\n  const [submitted, setSubmitted] = React.useState('');\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    setSubmitted(inputRef.current.value);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input ref={inputRef} defaultValue=\"\" />\n      <button type=\"submit\">Read value</button>\n      <p>Uncontrolled value read on submit: {submitted}</p>\n    </form>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <ControlledExample />\n      <UncontrolledExample />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function App() {\n  const [name, setName] = React.useState('');\n  const ageRef = React.useRef(null);\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    console.log('Name (controlled):', name);\n    console.log('Age (uncontrolled):', ageRef.current.value);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input value={name} onChange={e => setName(e.target.value)} placeholder=\"Name (controlled)\" />\n      <input ref={ageRef} defaultValue=\"\" placeholder=\"Age (uncontrolled)\" />\n      <button type=\"submit\">Submit</button>\n    </form>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'conditional-classnames-and-styling',
    title: 'Conditional Class Names & Styling',
    summary: 'Building className strings on the fly and using inline style objects',
    explanation: [
      "You can build a className conditionally with a template literal or ternary, like className={`button ${isActive ? 'active' : ''}`}, to toggle styles based on state.",
      'Inline styles use the style prop with a JavaScript object, where CSS properties are camelCase and values are usually strings or numbers, like style={{ color: "red", fontSize: 14 }}.',
      'Mixing both approaches is common: className for styles defined in CSS, and an inline style object for values that need to be computed dynamically.',
    ],
    example: "function Badge({ status }) {\n  const className = `badge ${status === 'error' ? 'badge-error' : 'badge-ok'}`;\n  const style = { padding: '4px 8px', color: status === 'error' ? 'white' : 'black', backgroundColor: status === 'error' ? 'crimson' : 'lightgreen' };\n\n  return <span className={className} style={style}>{status}</span>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Badge status=\"ok\" />\n      <Badge status=\"error\" />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Toggle() {\n  const [on, setOn] = React.useState(false);\n\n  return (\n    <button\n      className={on ? 'switch switch-on' : 'switch switch-off'}\n      style={{ backgroundColor: on ? 'green' : 'gray', color: 'white', padding: '8px' }}\n      onClick={() => setOn(!on)}\n    >\n      {on ? 'ON' : 'OFF'}\n    </button>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Toggle />);",
  },
  {
    slug: 'effect-cleanup-and-lifecycle',
    title: 'Effect Cleanup & Lifecycle',
    summary: "Mapping mount, update, and unmount onto useEffect's dependency array and cleanup function",
    explanation: [
      'An effect with an empty dependency array, React.useEffect(() => { ... }, []), runs once when the component mounts — similar to old lifecycle methods like componentDidMount.',
      'If an effect returns a function, React calls that returned function as cleanup — right before the effect runs again, and one final time when the component unmounts.',
      'A timer or subscription set up in an effect should almost always be cleared in its cleanup function, otherwise it keeps running even after the component is gone.',
    ],
    example: "function Clock() {\n  const [time, setTime] = React.useState(() => new Date().toLocaleTimeString());\n\n  React.useEffect(() => {\n    console.log('Clock mounted, starting timer');\n    const id = setInterval(() => {\n      setTime(new Date().toLocaleTimeString());\n    }, 1000);\n\n    return () => {\n      console.log('Cleaning up timer (update or unmount)');\n      clearInterval(id);\n    };\n  }, []);\n\n  return <p>Current time: {time}</p>;\n}\n\nfunction App() {\n  const [showClock, setShowClock] = React.useState(true);\n\n  return (\n    <div>\n      <button onClick={() => setShowClock(!showClock)}>\n        {showClock ? 'Unmount clock' : 'Mount clock'}\n      </button>\n      {showClock && <Clock />}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Ticker() {\n  const [count, setCount] = React.useState(0);\n\n  React.useEffect(() => {\n    const id = setInterval(() => setCount(c => c + 1), 1000);\n    return () => clearInterval(id);\n  }, []);\n\n  return <p>Ticks: {count}</p>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Ticker />);",
  },
  {
    slug: 'render-props-pattern',
    title: 'Render Props Pattern',
    summary: 'Sharing logic by passing a function as a prop that decides what to render',
    explanation: [
      'A render prop is a prop whose value is a function that returns JSX — the component calls that function to decide what to display, instead of hard-coding it.',
      "This lets one component own some shared logic (like tracking a mouse position or a counter) while letting the caller fully control the visual output.",
      'Render props can be passed as a regular prop or as children, like <MouseTracker>{pos => <p>{pos.x}</p>}</MouseTracker>.',
    ],
    example: "function Counter({ render }) {\n  const [count, setCount] = React.useState(0);\n  return render(count, () => setCount(count + 1));\n}\n\nfunction App() {\n  return (\n    <div>\n      <Counter render={(count, increment) => (\n        <button onClick={increment}>Clicked {count} times</button>\n      )} />\n      <Counter render={(count, increment) => (\n        <p onClick={increment}>Tap me — {count}</p>\n      )} />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function DataProvider({ children }) {\n  const [value, setValue] = React.useState('hello');\n  return children(value, () => setValue(value + '!'));\n}\n\nfunction App() {\n  return (\n    <DataProvider>\n      {(value, shout) => (\n        <div>\n          <p>{value}</p>\n          <button onClick={shout}>Shout</button>\n        </div>\n      )}\n    </DataProvider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'higher-order-components',
    title: 'Higher-Order Components',
    summary: 'A function that takes a component and returns a new, enhanced component',
    explanation: [
      'A higher-order component (HOC) is a function that takes a component as its argument and returns a new component with extra behavior wrapped around it.',
      "A common example is withLoading(Component), which returns a new component that shows a spinner when isLoading is true, and otherwise renders the original Component with its props.",
      "HOCs let you reuse cross-cutting behavior (like loading states, permissions checks, or logging) across many components without repeating the same code in each one.",
    ],
    example: "function withLoading(Component) {\n  return function WithLoading({ isLoading, ...rest }) {\n    if (isLoading) {\n      return <p>Loading...</p>;\n    }\n    return <Component {...rest} />;\n  };\n}\n\nfunction UserList({ users }) {\n  return (\n    <ul>\n      {users.map(u => <li key={u}>{u}</li>)}\n    </ul>\n  );\n}\n\nconst UserListWithLoading = withLoading(UserList);\n\nfunction App() {\n  const [isLoading, setIsLoading] = React.useState(true);\n\n  return (\n    <div>\n      <button onClick={() => setIsLoading(!isLoading)}>Toggle loading</button>\n      <UserListWithLoading isLoading={isLoading} users={['Aria', 'Kiran', 'Maya']} />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function withBorder(Component) {\n  return function WithBorder(props) {\n    return (\n      <div style={{ border: '2px solid purple', padding: '8px' }}>\n        <Component {...props} />\n      </div>\n    );\n  };\n}\n\nfunction Message({ text }) {\n  return <p>{text}</p>;\n}\n\nconst BorderedMessage = withBorder(Message);\n\nReactDOM.createRoot(document.getElementById('root')).render(<BorderedMessage text=\"Hello from a HOC!\" />);",
  },
  {
    slug: 'portals',
    title: 'Portals',
    summary: 'Rendering a child into a different part of the DOM tree',
    explanation: [
      "ReactDOM.createPortal(child, container) renders child into a DOM node outside the normal parent-child tree, while keeping it in the same place in React's component tree (events still bubble normally).",
      "This is especially useful for things like modals or tooltips that need to visually escape a parent with overflow: hidden or a low z-index, by attaching to document.body instead.",
      'Even though the portal content lives elsewhere in the DOM, it still behaves like a normal child for things like context and event handling.',
    ],
    example: "function Modal({ onClose, children }) {\n  return ReactDOM.createPortal(\n    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n      <div style={{ background: 'white', padding: '16px', borderRadius: '8px' }}>\n        {children}\n        <button onClick={onClose}>Close</button>\n      </div>\n    </div>,\n    document.body\n  );\n}\n\nfunction App() {\n  const [open, setOpen] = React.useState(false);\n\n  return (\n    <div>\n      <button onClick={() => setOpen(true)}>Open modal</button>\n      {open && (\n        <Modal onClose={() => setOpen(false)}>\n          <p>This is rendered via a portal into document.body!</p>\n        </Modal>\n      )}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Tooltip({ text }) {\n  return ReactDOM.createPortal(\n    <div style={{ position: 'fixed', bottom: 10, right: 10, background: 'black', color: 'white', padding: '6px' }}>\n      {text}\n    </div>,\n    document.body\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <p>Main content</p>\n      <Tooltip text=\"I live in document.body\" />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'data-fetching-pattern',
    title: 'Data Fetching Pattern',
    summary: 'Simulating an async load with useEffect, useState, and loading/data/error states',
    explanation: [
      'A typical data-fetching component tracks three pieces of state: whether it is still loading, the data once it arrives, and any error that occurred.',
      "Inside useEffect, you kick off an async operation and update those state pieces when it resolves — here we use a mock wait(ms, value) Promise instead of a real network call.",
      'Showing a loading message while waiting, then the data or an error once settled, is the standard shape of almost every real-world data-fetching component.',
    ],
    example: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nfunction UserProfile() {\n  const [loading, setLoading] = React.useState(true);\n  const [data, setData] = React.useState(null);\n  const [error, setError] = React.useState(null);\n\n  React.useEffect(() => {\n    setLoading(true);\n    wait(1000, { name: 'Aria', role: 'Captain' })\n      .then(result => setData(result))\n      .catch(err => setError(err.message))\n      .finally(() => setLoading(false));\n  }, []);\n\n  if (loading) return <p>Loading user...</p>;\n  if (error) return <p>Error: {error}</p>;\n  return <p>{data.name} — {data.role}</p>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<UserProfile />);",
    starterCode: "function wait(ms, value) {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nfunction Quote() {\n  const [loading, setLoading] = React.useState(true);\n  const [quote, setQuote] = React.useState('');\n\n  React.useEffect(() => {\n    wait(800, 'Stay curious.').then(text => {\n      setQuote(text);\n      setLoading(false);\n    });\n  }, []);\n\n  return <p>{loading ? 'Loading quote...' : quote}</p>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Quote />);",
  },
  {
    slug: 'todo-list-project',
    title: 'Building a Todo List',
    summary: 'A small project combining array state, a controlled input, and list rendering',
    explanation: [
      "This project ties together several ideas at once: array state for the list, a controlled input for new entries, and .map() with keys to render the items.",
      "Adding a todo means creating a new array (with spread or concat) rather than mutating the old one, so React knows the state actually changed.",
      'Removing a todo is usually done with .filter(), creating a new array that leaves out the item that should disappear.',
    ],
    example: "function TodoApp() {\n  const [todos, setTodos] = React.useState([\n    { id: 1, text: 'Learn React' },\n    { id: 2, text: 'Build a project' },\n  ]);\n  const [text, setText] = React.useState('');\n\n  function addTodo(event) {\n    event.preventDefault();\n    if (!text.trim()) return;\n    setTodos([...todos, { id: Date.now(), text }]);\n    setText('');\n  }\n\n  function removeTodo(id) {\n    setTodos(todos.filter(todo => todo.id !== id));\n  }\n\n  return (\n    <div>\n      <form onSubmit={addTodo}>\n        <input value={text} onChange={e => setText(e.target.value)} placeholder=\"New todo\" />\n        <button type=\"submit\">Add</button>\n      </form>\n      <ul>\n        {todos.map(todo => (\n          <li key={todo.id}>\n            {todo.text} <button onClick={() => removeTodo(todo.id)}>Delete</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<TodoApp />);",
    starterCode: "function SimpleTodoApp() {\n  const [items, setItems] = React.useState(['Buy milk']);\n  const [text, setText] = React.useState('');\n\n  function addItem() {\n    if (!text.trim()) return;\n    setItems([...items, text]);\n    setText('');\n  }\n\n  return (\n    <div>\n      <input value={text} onChange={e => setText(e.target.value)} />\n      <button onClick={addItem}>Add</button>\n      <ul>\n        {items.map((item, i) => (\n          <li key={i}>{item}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SimpleTodoApp />);",
  },
  {
    slug: 'search-and-filter-list',
    title: 'Search & Filter a List',
    summary: 'Combining a controlled search input with .filter() to narrow a list',
    explanation: [
      "A search box is just a controlled input whose value drives a filter, so the list shown is recalculated every render based on the current search text.",
      "Array.prototype.filter() returns a new array containing only the items that match a condition, like name.toLowerCase().includes(query.toLowerCase()).",
      'Because filtering happens on every render from the original full list, you never lose data — you only change what is currently displayed.',
    ],
    example: "function SearchableList() {\n  const [query, setQuery] = React.useState('');\n  const fruits = ['Apple', 'Banana', 'Mango', 'Orange', 'Grape', 'Apricot'];\n\n  const filtered = fruits.filter(fruit =>\n    fruit.toLowerCase().includes(query.toLowerCase())\n  );\n\n  return (\n    <div>\n      <input\n        value={query}\n        onChange={e => setQuery(e.target.value)}\n        placeholder=\"Search fruits...\"\n      />\n      <ul>\n        {filtered.map(fruit => (\n          <li key={fruit}>{fruit}</li>\n        ))}\n      </ul>\n      {filtered.length === 0 && <p>No matches found.</p>}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SearchableList />);",
    starterCode: "function ContactSearch() {\n  const [query, setQuery] = React.useState('');\n  const contacts = ['Aria', 'Kiran', 'Maya', 'Sam'];\n\n  const filtered = contacts.filter(name =>\n    name.toLowerCase().includes(query.toLowerCase())\n  );\n\n  return (\n    <div>\n      <input value={query} onChange={e => setQuery(e.target.value)} placeholder=\"Search contacts\" />\n      <ul>\n        {filtered.map(name => <li key={name}>{name}</li>)}\n      </ul>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<ContactSearch />);",
  },
  {
    slug: 'compound-components-pattern',
    title: 'Compound Components',
    summary: 'Components designed to be used together as a family, sharing state implicitly',
    explanation: [
      "Compound components are a group of components meant to be used together, like <Tabs><Tabs.Tab/></Tabs>, where the parent manages shared state and children read it via context.",
      "Attaching sub-components as properties of the parent (Tabs.Tab = Tab) keeps related pieces organized under one namespace while still being separate components.",
      "This pattern gives the caller a clean, declarative API while hiding the coordination logic (like which tab is active) inside the parent and a shared context.",
    ],
    example: "const TabsContext = React.createContext(null);\n\nfunction Tabs({ children, defaultIndex = 0 }) {\n  const [activeIndex, setActiveIndex] = React.useState(defaultIndex);\n  return (\n    <TabsContext.Provider value={{ activeIndex, setActiveIndex }}>\n      <div>{children}</div>\n    </TabsContext.Provider>\n  );\n}\n\nfunction TabList({ children }) {\n  return <div style={{ display: 'flex', gap: '8px' }}>{children}</div>;\n}\n\nfunction Tab({ index, children }) {\n  const { activeIndex, setActiveIndex } = React.useContext(TabsContext);\n  return (\n    <button\n      style={{ fontWeight: activeIndex === index ? 'bold' : 'normal' }}\n      onClick={() => setActiveIndex(index)}\n    >\n      {children}\n    </button>\n  );\n}\n\nfunction TabPanel({ index, children }) {\n  const { activeIndex } = React.useContext(TabsContext);\n  return activeIndex === index ? <div>{children}</div> : null;\n}\n\nTabs.List = TabList;\nTabs.Tab = Tab;\nTabs.Panel = TabPanel;\n\nfunction App() {\n  return (\n    <Tabs defaultIndex={0}>\n      <Tabs.List>\n        <Tabs.Tab index={0}>Home</Tabs.Tab>\n        <Tabs.Tab index={1}>Profile</Tabs.Tab>\n      </Tabs.List>\n      <Tabs.Panel index={0}>Welcome home!</Tabs.Panel>\n      <Tabs.Panel index={1}>This is your profile.</Tabs.Panel>\n    </Tabs>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "const ToggleContext = React.createContext(null);\n\nfunction Toggle({ children }) {\n  const [on, setOn] = React.useState(false);\n  return (\n    <ToggleContext.Provider value={{ on, setOn }}>\n      {children}\n    </ToggleContext.Provider>\n  );\n}\n\nfunction ToggleButton() {\n  const { on, setOn } = React.useContext(ToggleContext);\n  return <button onClick={() => setOn(!on)}>{on ? 'ON' : 'OFF'}</button>;\n}\n\nToggle.Button = ToggleButton;\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <Toggle>\n    <Toggle.Button />\n  </Toggle>\n);",
  },
  {
    slug: 'prop-drilling-vs-context',
    title: 'Prop Drilling vs Context',
    summary: 'Refactoring a prop passed through several layers into a shared Context',
    explanation: [
      "Prop drilling happens when a value has to be passed down through several layers of components that don't actually use it themselves, just to reach a deeply nested child.",
      'Every intermediate component ends up cluttered with props it only forwards along, which makes the code harder to follow and refactor.',
      "Replacing the chain with React.createContext lets the deeply nested component read the value directly with useContext, skipping the middle layers entirely.",
    ],
    example: "// Before: prop drilling through Header and Toolbar just to reach ThemedButton\nfunction ThemedButtonDrilled({ theme }) {\n  return <button>Theme is {theme}</button>;\n}\n\nfunction ToolbarDrilled({ theme }) {\n  return <ThemedButtonDrilled theme={theme} />;\n}\n\nfunction HeaderDrilled({ theme }) {\n  return <ToolbarDrilled theme={theme} />;\n}\n\n// After: Context skips the middle layers\nconst ThemeContext = React.createContext('light');\n\nfunction ThemedButton() {\n  const theme = React.useContext(ThemeContext);\n  return <button>Theme is {theme}</button>;\n}\n\nfunction Toolbar() {\n  return <ThemedButton />;\n}\n\nfunction Header() {\n  return <Toolbar />;\n}\n\nfunction App() {\n  return (\n    <div>\n      <HeaderDrilled theme=\"dark\" />\n      <ThemeContext.Provider value=\"dark\">\n        <Header />\n      </ThemeContext.Provider>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "const UserContext = React.createContext('Guest');\n\nfunction Profile() {\n  const user = React.useContext(UserContext);\n  return <p>Logged in as {user}</p>;\n}\n\nfunction Sidebar() {\n  return <Profile />;\n}\n\nfunction Layout() {\n  return <Sidebar />;\n}\n\nfunction App() {\n  return (\n    <UserContext.Provider value=\"Aria\">\n      <Layout />\n    </UserContext.Provider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'list-reordering-pitfalls',
    title: 'List Reordering Pitfalls',
    summary: 'Why array index keys break when items are reordered, added, or removed',
    explanation: [
      "When you use the array index as a key, React assumes the item at position 0 is always 'the same item' across renders — but if items are reordered or one is removed from the middle, that assumption breaks.",
      'This can cause stale input values, mixed-up component state, or odd visual glitches, because React reuses the wrong DOM node for the wrong piece of data.',
      'Using a stable, unique id from your actual data as the key (instead of the index) lets React correctly track each item no matter how the list is reordered.',
    ],
    example: "function BadList() {\n  const [items, setItems] = React.useState([\n    { id: 1, text: 'First' },\n    { id: 2, text: 'Second' },\n    { id: 3, text: 'Third' },\n  ]);\n\n  function removeFirst() {\n    setItems(items.slice(1));\n  }\n\n  return (\n    <div>\n      <h4>Using index as key (buggy)</h4>\n      <button onClick={removeFirst}>Remove first item</button>\n      <ul>\n        {items.map((item, index) => (\n          <li key={index}>\n            {item.text} — <input defaultValue={item.text} />\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nfunction GoodList() {\n  const [items, setItems] = React.useState([\n    { id: 1, text: 'First' },\n    { id: 2, text: 'Second' },\n    { id: 3, text: 'Third' },\n  ]);\n\n  function removeFirst() {\n    setItems(items.slice(1));\n  }\n\n  return (\n    <div>\n      <h4>Using stable id as key (correct)</h4>\n      <button onClick={removeFirst}>Remove first item</button>\n      <ul>\n        {items.map(item => (\n          <li key={item.id}>\n            {item.text} — <input defaultValue={item.text} />\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <BadList />\n      <GoodList />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function NameList() {\n  const [names, setNames] = React.useState([\n    { id: 1, value: 'Aria' },\n    { id: 2, value: 'Kiran' },\n    { id: 3, value: 'Maya' },\n  ]);\n\n  function shuffle() {\n    setNames([...names].reverse());\n  }\n\n  return (\n    <div>\n      <button onClick={shuffle}>Reverse order</button>\n      <ul>\n        {names.map(name => (\n          <li key={name.id}>{name.value}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<NameList />);",
  },
]
