import type { CodingLesson } from '../languages'

export const react: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to React',
    summary: 'Building UIs out of components with JSX',
    explanation: [
      'React is a library for building user interfaces out of small, reusable pieces called components. A component is just a function that returns what should appear on screen.',
      'JSX is a syntax that lets you write HTML-like markup inside JavaScript, like <h1>Hello</h1> — it gets transformed into regular function calls behind the scenes.',
      'ReactDOM.createRoot(container).render(<App />) takes a component and draws it onto the page.',
    ],
    example: "function App() {\n  return (\n    <div>\n      <h1>Hello, React!</h1>\n      <p>This is your first component.</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function App() {\n  return <h1>Welcome to React</h1>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'jsx-basics',
    title: 'JSX Basics',
    summary: 'Mixing expressions, attributes, and tags in your markup',
    explanation: [
      'Curly braces {} let you drop any JavaScript expression straight into your JSX, like {2 + 2} or {user.name}.',
      'JSX attributes look like HTML but use camelCase and className instead of class, since class is a reserved word in JavaScript.',
      'Tags that have no children can self-close with a slash, like <img /> or <br />.',
    ],
    example: "function App() {\n  const name = 'Aria';\n  const score = 92;\n\n  return (\n    <div className=\"card\">\n      <h2>Hello, {name}!</h2>\n      <p>Your score is {score} out of 100.</p>\n      <p>Doubled: {score * 2}</p>\n      <hr />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function App() {\n  const language = 'React';\n\n  return (\n    <div className=\"box\">\n      <h2>Learning {language}</h2>\n      <p>2 + 2 = {2 + 2}</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'props',
    title: 'Props',
    summary: 'Passing data into components',
    explanation: [
      'Props are how a parent component passes data down to a child component, similar to arguments passed into a function.',
      'A component receives its props as an object: function Greeting(props) { return <p>{props.name}</p> }. You can also destructure them directly: function Greeting({ name }) { ... }.',
      'Props make components reusable — the same component can render differently depending on what data it receives.',
    ],
    example: "function Greeting({ name, role }) {\n  return (\n    <li>\n      {name} — <strong>{role}</strong>\n    </li>\n  );\n}\n\nfunction App() {\n  return (\n    <ul>\n      <Greeting name=\"Aria\" role=\"Captain\" />\n      <Greeting name=\"Kiran\" role=\"Coder\" />\n      <Greeting name=\"Maya\" role=\"Designer\" />\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Badge({ label, color }) {\n  return <span className={color}>{label}</span>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Badge label=\"New\" color=\"green\" />\n      <Badge label=\"Hot\" color=\"red\" />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'state-and-hooks',
    title: 'State & Hooks',
    summary: 'Letting components remember and update values with useState',
    explanation: [
      'State is data a component remembers between renders. The useState hook gives you a value and a function to update it: const [count, setCount] = React.useState(0).',
      'Calling the setter function (like setCount(count + 1)) updates the state and tells React to re-render the component with the new value.',
      'Because React is loaded globally here, hooks are accessed as React.useState, React.useEffect, and so on.',
    ],
    example: "function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Add one</button>\n      <button onClick={() => setCount(0)}>Reset</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
    starterCode: "function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <div>\n      <p>You clicked {count} times</p>\n      <button onClick={() => setCount(count + 1)}>Click me</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
  },
  {
    slug: 'event-handling',
    title: 'Event Handling',
    summary: 'Responding to clicks and other user actions',
    explanation: [
      'In JSX, you attach event handlers with camelCase props like onClick, onChange, or onSubmit, and pass them a function to run.',
      'Event handlers are often used together with useState to update what the component remembers in response to what the user does.',
      'Writing onClick={() => doSomething()} creates a function that only runs when the event actually happens, not while rendering.',
    ],
    example: "function LikeButton() {\n  const [likes, setLikes] = React.useState(0);\n  const [liked, setLiked] = React.useState(false);\n\n  function handleClick() {\n    setLikes(liked ? likes - 1 : likes + 1);\n    setLiked(!liked);\n  }\n\n  return (\n    <div>\n      <button onClick={handleClick}>{liked ? 'Liked!' : 'Like'}</button>\n      <p>{likes} people like this</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<LikeButton />);",
    starterCode: "function ColorPicker() {\n  const [color, setColor] = React.useState('gray');\n\n  return (\n    <div>\n      <p>Selected color: {color}</p>\n      <button onClick={() => setColor('red')}>Red</button>\n      <button onClick={() => setColor('blue')}>Blue</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<ColorPicker />);",
  },
  {
    slug: 'conditional-rendering',
    title: 'Conditional Rendering',
    summary: 'Showing different JSX depending on a condition',
    explanation: [
      'You can use a regular JavaScript if statement before the return to decide what JSX to send back.',
      'Inside JSX, the && operator shows something only when a condition is true: {isLoggedIn && <p>Welcome back!</p>}.',
      'The ternary operator condition ? a : b lets you pick between two pieces of JSX in a single expression.',
    ],
    example: "function Status({ isOnline, messages }) {\n  return (\n    <div>\n      <p>Status: {isOnline ? 'Online 🟢' : 'Offline ⚪'}</p>\n      {messages > 0 && <p>You have {messages} new messages</p>}\n      {messages === 0 && <p>No new messages</p>}\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <Status isOnline={true} messages={3} />\n      <Status isOnline={false} messages={0} />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "function Greeting({ loggedIn }) {\n  return (\n    <div>\n      {loggedIn ? <p>Welcome back!</p> : <p>Please log in.</p>}\n      {loggedIn && <button>Log out</button>}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Greeting loggedIn={true} />);",
  },
  {
    slug: 'lists-and-keys',
    title: 'Lists & Keys',
    summary: 'Rendering arrays of data with .map()',
    explanation: [
      'To render a list of items, use .map() to turn an array of data into an array of JSX elements.',
      'Each item in a rendered list needs a unique key prop, like key={item.id} — this helps React keep track of which item is which when the list changes.',
      'Keys should come from stable data (like an id), not from the array index, whenever possible.',
    ],
    example: "function TodoList() {\n  const todos = [\n    { id: 1, text: 'Learn JSX' },\n    { id: 2, text: 'Build a component' },\n    { id: 3, text: 'Use props and state' },\n  ];\n\n  return (\n    <ul>\n      {todos.map(todo => (\n        <li key={todo.id}>{todo.text}</li>\n      ))}\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<TodoList />);",
    starterCode: "function FruitList() {\n  const fruits = ['Apple', 'Banana', 'Mango'];\n\n  return (\n    <ul>\n      {fruits.map((fruit, index) => (\n        <li key={index}>{fruit}</li>\n      ))}\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<FruitList />);",
  },
  {
    slug: 'effects',
    title: 'Effects',
    summary: 'Running code in response to rendering with useEffect',
    explanation: [
      'The useEffect hook lets a component run code "on the side" — after it renders — such as logging, fetching data, or setting up a timer.',
      'React.useEffect(() => { ... }, []) with an empty array runs the effect only once, right after the component first appears.',
      'If you list values in the second argument, like [count], the effect re-runs whenever those values change.',
    ],
    example: "function Welcome() {\n  const [seconds, setSeconds] = React.useState(0);\n\n  React.useEffect(() => {\n    console.log('Welcome component mounted');\n    const timer = setInterval(() => {\n      setSeconds(s => s + 1);\n    }, 1000);\n    return () => clearInterval(timer);\n  }, []);\n\n  React.useEffect(() => {\n    console.log(`Seconds elapsed: ${seconds}`);\n  }, [seconds]);\n\n  return <p>Seconds since mount: {seconds}</p>;\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Welcome />);",
    starterCode: "function Logger() {\n  const [count, setCount] = React.useState(0);\n\n  React.useEffect(() => {\n    console.log('Logger mounted');\n  }, []);\n\n  React.useEffect(() => {\n    console.log(`Count is now ${count}`);\n  }, [count]);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Increase</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Logger />);",
  },
  {
    slug: 'forms-and-controlled-inputs',
    title: 'Forms & Controlled Inputs',
    summary: "Letting React state drive an input's value",
    explanation: [
      "A controlled input's value comes from state, not from the DOM: <input value={text} onChange={e => setText(e.target.value)} /> keeps state and the input perfectly in sync.",
      'Because state holds the current value, you can validate, transform, or react to every keystroke before it ever reaches the input.',
      "Submitting a form calls a handler on its onSubmit event; calling event.preventDefault() stops the browser's default full-page reload so React can handle the submission itself.",
    ],
    example: "function SignupForm() {\n  const [name, setName] = React.useState('');\n  const [submitted, setSubmitted] = React.useState('');\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    setSubmitted(name);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        Name:\n        <input value={name} onChange={e => setName(e.target.value)} />\n      </label>\n      <button type=\"submit\">Sign up</button>\n      {submitted && <p>Welcome, {submitted}!</p>}\n    </form>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SignupForm />);",
    starterCode: "function SearchBox() {\n  const [query, setQuery] = React.useState('');\n\n  return (\n    <div>\n      <input\n        value={query}\n        onChange={e => setQuery(e.target.value)}\n        placeholder=\"Search...\"\n      />\n      <p>You typed: {query}</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SearchBox />);",
  },
  {
    slug: 'lifting-state-and-composition',
    title: 'Lifting State Up & Composition',
    summary: 'Sharing state between components and nesting components with children',
    explanation: [
      '"Lifting state up" means moving state to the nearest shared parent of the components that need it, then passing both the value and an updater function down as props.',
      'A component can accept other JSX as a prop called children — <Card><p>Inside</p></Card> passes the paragraph to Card as props.children — which lets components wrap arbitrary content.',
      'Composition (building bigger components out of smaller ones passed as children or props) is usually more flexible than trying to make one component handle every possible case through configuration props.',
    ],
    example: "function Card({ children }) {\n  return <div className=\"card\">{children}</div>;\n}\n\nfunction TemperatureInput({ label, value, onChange }) {\n  return (\n    <label>\n      {label}: <input value={value} onChange={e => onChange(e.target.value)} />\n    </label>\n  );\n}\n\nfunction Converter() {\n  const [celsius, setCelsius] = React.useState('0');\n  const fahrenheit = (Number(celsius) * 9) / 5 + 32;\n\n  return (\n    <Card>\n      <TemperatureInput label=\"Celsius\" value={celsius} onChange={setCelsius} />\n      <p>Fahrenheit: {fahrenheit}</p>\n    </Card>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Converter />);",
    starterCode: "function Panel({ children }) {\n  return <div style={{ border: '1px solid gray', padding: '8px' }}>{children}</div>;\n}\n\nfunction NameInput({ value, onChange }) {\n  return <input value={value} onChange={e => onChange(e.target.value)} />;\n}\n\nfunction App() {\n  const [name, setName] = React.useState('');\n\n  return (\n    <Panel>\n      <NameInput value={name} onChange={setName} />\n      <p>Hello, {name || 'stranger'}!</p>\n    </Panel>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'context',
    title: 'Context & useContext',
    summary: 'Sharing a value with every component below, without passing props by hand',
    explanation: [
      'React.createContext(defaultValue) creates a Context object — a channel for sharing a value with any component underneath it in the tree, no matter how deeply nested.',
      'A <ThemeContext.Provider value={...}> wraps part of the tree and supplies the actual value; every descendant can read it.',
      "Inside any descendant, React.useContext(ThemeContext) reads the nearest Provider's value directly, skipping the need to pass it down through every component in between as a prop.",
    ],
    example: "const ThemeContext = React.createContext('light');\n\nfunction ThemedButton() {\n  const theme = React.useContext(ThemeContext);\n  return <button>Current theme: {theme}</button>;\n}\n\nfunction Toolbar() {\n  return (\n    <div>\n      <ThemedButton />\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
    starterCode: "const UserContext = React.createContext('Guest');\n\nfunction Greeting() {\n  const user = React.useContext(UserContext);\n  return <p>Hello, {user}!</p>;\n}\n\nfunction App() {\n  return (\n    <UserContext.Provider value=\"Aria\">\n      <Greeting />\n    </UserContext.Provider>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);",
  },
  {
    slug: 'custom-hooks',
    title: 'Custom Hooks',
    summary: 'Packaging reusable stateful logic into your own hook',
    explanation: [
      'A custom hook is just a regular function whose name starts with use and which calls other hooks inside it — that naming convention is how React and linters know it follows the rules of hooks.',
      "Custom hooks let you extract logic like 'track a toggled boolean' or 'track a counter' out of a component and reuse it in many components without copying code.",
      'A custom hook returns whatever is useful to its caller — often the current state plus one or more functions to update it, similar to what useState itself returns.',
    ],
    example: "function useCounter(initial = 0) {\n  const [count, setCount] = React.useState(initial);\n  const increment = () => setCount(c => c + 1);\n  const reset = () => setCount(initial);\n  return { count, increment, reset };\n}\n\nfunction Counter() {\n  const { count, increment, reset } = useCounter(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={increment}>+1</button>\n      <button onClick={reset}>Reset</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Counter />);",
    starterCode: "function useToggle(initial = false) {\n  const [value, setValue] = React.useState(initial);\n  const toggle = () => setValue(v => !v);\n  return [value, toggle];\n}\n\nfunction Light() {\n  const [isOn, toggle] = useToggle(false);\n\n  return (\n    <button onClick={toggle}>\n      {isOn ? 'Light is ON' : 'Light is OFF'}\n    </button>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Light />);",
  },
  {
    slug: 'refs-and-dom',
    title: 'Refs & useRef',
    summary: 'Reaching directly into a DOM node, or remembering a value without re-rendering',
    explanation: [
      'React.useRef(initialValue) returns a mutable ref object with a single .current property that persists across renders without causing a re-render when it changes.',
      "Passing a ref to an element's ref attribute, like <input ref={inputRef} />, gives you direct access to that real DOM node in inputRef.current — handy for focusing an input or measuring it.",
      'Unlike state, updating a ref\'s .current value does not trigger a re-render, which makes refs ideal for values you need to track but never need to show on screen, like a previous value or a timer ID.',
    ],
    example: "function FocusableInput() {\n  const inputRef = React.useRef(null);\n\n  function focusInput() {\n    inputRef.current.focus();\n  }\n\n  return (\n    <div>\n      <input ref={inputRef} placeholder=\"Click the button to focus me\" />\n      <button onClick={focusInput}>Focus the input</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<FocusableInput />);",
    starterCode: "function ClickCounter() {\n  const countRef = React.useRef(0);\n  const [display, setDisplay] = React.useState(0);\n\n  function handleClick() {\n    countRef.current += 1;\n    setDisplay(countRef.current);\n  }\n\n  return (\n    <div>\n      <p>Clicked {display} times (tracked in a ref)</p>\n      <button onClick={handleClick}>Click me</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<ClickCounter />);",
  },
  {
    slug: 'performance-and-memoization',
    title: 'Performance & Memoization',
    summary: 'Skipping unnecessary recalculations with useMemo and useCallback',
    explanation: [
      'React.useMemo(() => computeValue(), [deps]) re-runs an expensive calculation only when one of its dependencies actually changes, reusing the previous result otherwise.',
      "React.useCallback(fn, [deps]) does the same thing for functions — it returns the same function reference between renders as long as the dependencies haven't changed, which matters when that function is passed to a child component.",
      'These hooks are optimizations, not requirements — reach for them when you notice a real slowdown from expensive work or unnecessary re-renders, not on every value by default.',
    ],
    example: "function expensiveSum(n) {\n  let total = 0;\n  for (let i = 0; i <= n; i++) total += i;\n  return total;\n}\n\nfunction Calculator() {\n  const [n, setN] = React.useState(10);\n  const [theme, setTheme] = React.useState('light');\n\n  const sum = React.useMemo(() => expensiveSum(n), [n]);\n\n  return (\n    <div>\n      <p>Sum up to {n}: {sum}</p>\n      <button onClick={() => setN(n + 1)}>Increase n</button>\n      <button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>\n        Toggle theme ({theme})\n      </button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<Calculator />);",
    starterCode: "function square(n) {\n  return n * n;\n}\n\nfunction SquareCalculator() {\n  const [number, setNumber] = React.useState(4);\n  const result = React.useMemo(() => square(number), [number]);\n\n  return (\n    <div>\n      <p>{number} squared is {result}</p>\n      <button onClick={() => setNumber(number + 1)}>+1</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById('root')).render(<SquareCalculator />);",
  },
]
