import type { CodingLesson } from '../languages'

export const sql: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to SQL',
    summary: 'Talking to databases with SELECT',
    explanation: [
      'SQL (Structured Query Language) is how you create, read, update, and delete data stored in relational databases.',
      'SELECT columns FROM table; retrieves data. SELECT * FROM table; retrieves every column.',
      'Statements end with a semicolon ;. This playground runs SQLite — try creating a table and querying it.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88);\nSELECT * FROM students;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88);\nSELECT name FROM students;",
  },
  {
    slug: 'filtering',
    title: 'Filtering with WHERE',
    summary: 'Narrowing down results that match a condition',
    explanation: [
      'WHERE filters rows based on a condition: SELECT * FROM students WHERE score >= 90;.',
      'Combine conditions with AND / OR, and use comparison operators =, !=, >, <, >=, <=.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT * FROM students WHERE score >= 80;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT name FROM students WHERE score > 75;",
  },
  {
    slug: 'sorting-and-limiting',
    title: 'Sorting & Limiting',
    summary: 'Ordering results and taking only what you need',
    explanation: [
      'ORDER BY column sorts results — add DESC for descending order, ASC (the default) for ascending.',
      'LIMIT n restricts the number of rows returned — handy for "top N" style queries.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT * FROM students ORDER BY score DESC LIMIT 2;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT name FROM students ORDER BY score ASC;",
  },
  {
    slug: 'aggregates',
    title: 'Aggregate Functions',
    summary: 'Summarising data with COUNT, SUM, AVG, and GROUP BY',
    explanation: [
      'Aggregate functions compute a single value from many rows: COUNT(*), SUM(column), AVG(column), MIN(column), MAX(column).',
      'GROUP BY groups rows that share a value so you can aggregate within each group, e.g. average score per class.',
    ],
    example: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','A',88), ('Maya','B',72), ('Sam','B',81);\nSELECT class, AVG(score) AS avg_score FROM students GROUP BY class;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT COUNT(*) AS total, AVG(score) AS average FROM students;",
  },
  {
    slug: 'updating-and-deleting',
    title: 'Updating & Deleting',
    summary: 'Changing and removing existing rows',
    explanation: [
      'UPDATE table SET column = value WHERE condition; changes matching rows — always include a WHERE clause, or every row changes!',
      'DELETE FROM table WHERE condition; removes matching rows.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 60);\nUPDATE students SET score = 70 WHERE name = 'Leo';\nDELETE FROM students WHERE score < 65;\nSELECT * FROM students;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 60);\nUPDATE students SET score = score + 5 WHERE name = 'Leo';\nSELECT * FROM students;",
  },
  {
    slug: 'joins',
    title: 'Joining Tables',
    summary: 'Combining rows from related tables',
    explanation: [
      'Real data is often spread across tables. JOIN combines rows from two tables based on a related column.',
      'INNER JOIN table2 ON table1.col = table2.col returns only rows with matches in both tables.',
    ],
    example: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, subject TEXT, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo');\nINSERT INTO scores VALUES (1, 'Math', 95), (2, 'Math', 88);\nSELECT students.name, scores.subject, scores.score\nFROM students\nINNER JOIN scores ON students.id = scores.student_id;",
    starterCode: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo');\nINSERT INTO scores VALUES (1, 95), (2, 88);\nSELECT students.name, scores.score\nFROM students\nINNER JOIN scores ON students.id = scores.student_id;",
  },
  {
    slug: 'subqueries',
    title: 'Subqueries',
    summary: 'Nesting one query inside another',
    explanation: [
      'A subquery is a SELECT placed inside another query — in a WHERE clause to filter, or in a FROM clause as a temporary table.',
      'The inner query runs first, and its result is used by the outer query, e.g. WHERE score > (SELECT AVG(score) FROM students).',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT name, score FROM students\nWHERE score > (SELECT AVG(score) FROM students);",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT name FROM students\nWHERE score = (SELECT MAX(score) FROM students);",
  },
  {
    slug: 'unions',
    title: 'Combining Results with UNION',
    summary: 'Stacking the rows from two SELECT statements',
    explanation: [
      'UNION combines the results of two SELECT statements into one result set, removing duplicate rows.',
      'UNION ALL does the same but keeps duplicates — both queries must select the same number of columns with compatible types.',
    ],
    example: "CREATE TABLE current_students (name TEXT);\nCREATE TABLE alumni (name TEXT);\nINSERT INTO current_students VALUES ('Aria'), ('Leo');\nINSERT INTO alumni VALUES ('Maya'), ('Aria');\nSELECT name FROM current_students\nUNION\nSELECT name FROM alumni;",
    starterCode: "CREATE TABLE current_students (name TEXT);\nCREATE TABLE alumni (name TEXT);\nINSERT INTO current_students VALUES ('Aria'), ('Leo');\nINSERT INTO alumni VALUES ('Maya'), ('Aria');\nSELECT name FROM current_students\nUNION ALL\nSELECT name FROM alumni;",
  },
  {
    slug: 'constraints-and-keys',
    title: 'Constraints & Keys',
    summary: 'Letting the database enforce your data rules',
    explanation: [
      'PRIMARY KEY uniquely identifies each row, NOT NULL requires a value, and UNIQUE forbids duplicates in a column.',
      'FOREIGN KEY links a column to a primary key in another table, keeping related data consistent.',
    ],
    example: "CREATE TABLE students (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  email TEXT UNIQUE\n);\nCREATE TABLE scores (\n  student_id INTEGER,\n  score INTEGER,\n  FOREIGN KEY (student_id) REFERENCES students(id)\n);\nINSERT INTO students VALUES (1, 'Aria', 'aria@example.com');\nINSERT INTO scores VALUES (1, 95);\nSELECT students.name, scores.score\nFROM students\nINNER JOIN scores ON students.id = scores.student_id;",
    starterCode: "CREATE TABLE students (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  email TEXT UNIQUE\n);\nINSERT INTO students VALUES (1, 'Aria', 'aria@example.com');\nINSERT INTO students VALUES (2, 'Leo', 'leo@example.com');\nSELECT * FROM students;",
  },
  {
    slug: 'views',
    title: 'Views',
    summary: 'Saving a query as a reusable virtual table',
    explanation: [
      'CREATE VIEW name AS SELECT ...; saves a query under a name you can reuse like a table.',
      'A view does not store data itself — every time you query it, the underlying SELECT runs again with fresh results.',
    ],
    example: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','A',88), ('Maya','B',72);\nCREATE VIEW top_students AS\n  SELECT name, class, score FROM students WHERE score >= 85;\nSELECT * FROM top_students;",
    starterCode: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','A',88), ('Maya','B',72);\nCREATE VIEW class_a AS\n  SELECT name, score FROM students WHERE class = 'A';\nSELECT * FROM class_a;",
  },
  {
    slug: 'transactions',
    title: 'Transactions',
    summary: 'Grouping changes so they all succeed or all fail',
    explanation: [
      'BEGIN TRANSACTION starts a group of changes that are applied together — COMMIT saves them, ROLLBACK undoes them all.',
      'Transactions keep your data consistent: if something goes wrong partway through, ROLLBACK returns the database to where it started.',
    ],
    example: "CREATE TABLE accounts (name TEXT, balance INTEGER);\nINSERT INTO accounts VALUES ('Aria', 100), ('Leo', 50);\nBEGIN TRANSACTION;\nUPDATE accounts SET balance = balance - 20 WHERE name = 'Aria';\nUPDATE accounts SET balance = balance + 20 WHERE name = 'Leo';\nCOMMIT;\nSELECT * FROM accounts;",
    starterCode: "CREATE TABLE accounts (name TEXT, balance INTEGER);\nINSERT INTO accounts VALUES ('Aria', 100), ('Leo', 50);\nBEGIN TRANSACTION;\nUPDATE accounts SET balance = balance - 100 WHERE name = 'Aria';\nROLLBACK;\nSELECT * FROM accounts;",
  },
  {
    slug: 'string-and-date-functions',
    title: 'String & Date Functions',
    summary: 'Transforming text and working with dates in queries',
    explanation: [
      'SQLite has built-in string functions like UPPER(), LOWER(), LENGTH(), and SUBSTR(text, start, length) for reshaping text.',
      "Date functions such as date('now') and strftime('%Y', column) let you compute and format dates inside a query.",
    ],
    example: "CREATE TABLE students (name TEXT, joined TEXT);\nINSERT INTO students VALUES ('Aria', '2024-09-01'), ('Leo', '2023-01-15');\nSELECT UPPER(name) AS shout_name,\n       LENGTH(name) AS name_length,\n       SUBSTR(name, 1, 3) AS short_name,\n       strftime('%Y', joined) AS join_year\nFROM students;",
    starterCode: "CREATE TABLE students (name TEXT, joined TEXT);\nINSERT INTO students VALUES ('Aria', '2024-09-01'), ('Leo', '2023-01-15');\nSELECT LOWER(name) AS lower_name, strftime('%Y', joined) AS join_year\nFROM students;",
  },
  {
    slug: 'left-joins',
    title: 'LEFT JOIN',
    summary: 'Keeping every row from the left table, matched or not',
    explanation: [
      "The 'joins' lesson covered INNER JOIN, which only keeps rows that match in both tables. LEFT JOIN table2 ON table1.col = table2.col keeps every row from the left table no matter what, even if nothing matches on the right.",
      "When there's no match, the columns from the right table are filled in with NULL instead of the row being dropped. That makes LEFT JOIN perfect for finding gaps, like students with no scores recorded yet.",
      "SQLite supports LEFT JOIN but not RIGHT JOIN or FULL OUTER JOIN — if you need the reverse, just swap which table you list first.",
    ],
    example: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, subject TEXT, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo'), (3, 'Maya');\nINSERT INTO scores VALUES (1, 'Math', 95), (2, 'Math', 88);\nSELECT students.name, scores.subject, scores.score\nFROM students\nLEFT JOIN scores ON students.id = scores.student_id;",
    starterCode: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo'), (3, 'Maya');\nINSERT INTO scores VALUES (1, 95), (2, 88);\nSELECT students.name, scores.score\nFROM students\nLEFT JOIN scores ON students.id = scores.student_id;",
  },
  {
    slug: 'case-expressions',
    title: 'CASE Expressions',
    summary: 'Computing a conditional column inside SELECT',
    explanation: [
      'CASE lets you compute a value based on conditions, right inside a query. The pattern is CASE WHEN condition THEN value ... ELSE value END, and you can chain as many WHEN branches as you need.',
      "It's commonly used to turn raw numbers into readable labels, like turning a numeric score into a 'Pass' or 'Fail' result, or a letter grade.",
      'CASE checks each WHEN in order and uses the first one that matches, falling back to ELSE if none do — so put your most specific conditions first.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 72), ('Maya', 58);\nSELECT name, score,\n       CASE\n         WHEN score >= 90 THEN 'A'\n         WHEN score >= 70 THEN 'B'\n         ELSE 'C'\n       END AS grade\nFROM students;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 72), ('Maya', 58);\nSELECT name,\n       CASE WHEN score >= 60 THEN 'Pass' ELSE 'Fail' END AS result\nFROM students;",
  },
  {
    slug: 'self-joins',
    title: 'Self Joins',
    summary: 'Joining a table to itself',
    explanation: [
      'A self join is a regular JOIN where a table is joined to itself, useful when rows reference other rows in the same table.',
      "A classic example is an employees table with a manager_id column that points back to another employee's id — joining the table to itself matches each employee to their manager.",
      'Always give each copy of the table a different alias, like e and m, so the database knows which columns you mean.',
    ],
    example: "CREATE TABLE employees (id INTEGER, name TEXT, manager_id INTEGER);\nINSERT INTO employees VALUES (1, 'Grace', NULL), (2, 'Aria', 1), (3, 'Leo', 1);\nSELECT e.name AS employee, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;",
    starterCode: "CREATE TABLE employees (id INTEGER, name TEXT, manager_id INTEGER);\nINSERT INTO employees VALUES (1, 'Grace', NULL), (2, 'Aria', 1), (3, 'Leo', 1);\nSELECT e.name AS employee, m.name AS manager\nFROM employees e\nINNER JOIN employees m ON e.manager_id = m.id;",
  },
  {
    slug: 'having-clause',
    title: 'The HAVING Clause',
    summary: 'Filtering groups after GROUP BY',
    explanation: [
      'WHERE filters individual rows before grouping, but it cannot reference an aggregate result like COUNT(*) or AVG(score).',
      'HAVING runs after GROUP BY and filters the grouped results themselves, e.g. only keep classes with more than one student.',
      'You can use WHERE and HAVING together: WHERE narrows rows first, then GROUP BY groups them, then HAVING filters the groups.',
    ],
    example: "CREATE TABLE students (name TEXT, class TEXT);\nINSERT INTO students VALUES ('Aria','A'), ('Leo','A'), ('Maya','B');\nSELECT class, COUNT(*) AS total\nFROM students\nGROUP BY class\nHAVING COUNT(*) > 1;",
    starterCode: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','A',88), ('Maya','B',72);\nSELECT class, AVG(score) AS avg_score\nFROM students\nGROUP BY class\nHAVING AVG(score) > 80;",
  },
  {
    slug: 'distinct-keyword',
    title: 'DISTINCT',
    summary: 'Removing duplicate rows from a result',
    explanation: [
      'SELECT DISTINCT column FROM table; returns each unique value only once, dropping repeated duplicates.',
      'DISTINCT can apply to multiple columns too — it keeps unique combinations of all selected columns, not just the first one.',
    ],
    example: "CREATE TABLE students (name TEXT, class TEXT);\nINSERT INTO students VALUES ('Aria','A'), ('Leo','A'), ('Maya','B');\nSELECT DISTINCT class FROM students;",
    starterCode: "CREATE TABLE students (name TEXT, class TEXT);\nINSERT INTO students VALUES ('Aria','A'), ('Leo','A'), ('Maya','B');\nSELECT DISTINCT class FROM students;",
  },
  {
    slug: 'null-handling',
    title: 'Handling NULL',
    summary: 'Testing for missing values and filling in defaults',
    explanation: [
      "NULL means 'no value' — and = NULL never matches anything, even another NULL. Use IS NULL or IS NOT NULL instead.",
      'COALESCE(a, b, default) returns the first argument that is not NULL, which makes it handy for substituting a fallback value.',
    ],
    example: "CREATE TABLE students (name TEXT, email TEXT);\nINSERT INTO students VALUES ('Aria', 'aria@example.com'), ('Leo', NULL);\nSELECT name FROM students WHERE email IS NULL;",
    starterCode: "CREATE TABLE students (name TEXT, email TEXT);\nINSERT INTO students VALUES ('Aria', 'aria@example.com'), ('Leo', NULL);\nSELECT name, COALESCE(email, 'no email on file') AS contact\nFROM students;",
  },
  {
    slug: 'between-and-in-operators',
    title: 'BETWEEN & IN',
    summary: 'Concise alternatives to chained comparisons',
    explanation: [
      'score BETWEEN 70 AND 90 is shorthand for score >= 70 AND score <= 90 — both ends are included.',
      "class IN ('A', 'B') is shorthand for class = 'A' OR class = 'B', useful when checking against a list of values.",
    ],
    example: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','B',82), ('Maya','C',60);\nSELECT name FROM students WHERE score BETWEEN 70 AND 90;",
    starterCode: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','B',82), ('Maya','C',60);\nSELECT name FROM students WHERE class IN ('A', 'B');",
  },
  {
    slug: 'like-and-wildcards',
    title: 'LIKE & Wildcards',
    summary: 'Matching text patterns instead of exact values',
    explanation: [
      "LIKE matches text against a pattern instead of requiring an exact match — name LIKE 'A%' finds names starting with A.",
      "% matches any sequence of characters (including none), while _ matches exactly one character. '%a%' finds names containing 'a' anywhere.",
    ],
    example: "CREATE TABLE students (name TEXT);\nINSERT INTO students VALUES ('Aria'), ('Leo'), ('Amir');\nSELECT name FROM students WHERE name LIKE 'A%';",
    starterCode: "CREATE TABLE students (name TEXT);\nINSERT INTO students VALUES ('Aria'), ('Leo'), ('Amir');\nSELECT name FROM students WHERE name LIKE '%i%';",
  },
  {
    slug: 'indexes-basics',
    title: 'Indexes',
    summary: 'Speeding up lookups on a column',
    explanation: [
      "An index is like a book's index — it lets the database jump straight to matching rows instead of scanning the whole table.",
      'CREATE INDEX idx_name ON table(column); builds an index on that column, which speeds up WHERE and JOIN lookups on it.',
      "Indexes make reads faster but add a small cost to writes, since the index has to be kept up to date — they're best on columns you search or join on often.",
    ],
    example: "CREATE TABLE students (id INTEGER, name TEXT, email TEXT);\nINSERT INTO students VALUES (1, 'Aria', 'aria@example.com'), (2, 'Leo', 'leo@example.com');\nCREATE INDEX idx_students_email ON students(email);\nSELECT * FROM students WHERE email = 'leo@example.com';",
    starterCode: "CREATE TABLE students (id INTEGER, name TEXT, email TEXT);\nINSERT INTO students VALUES (1, 'Aria', 'aria@example.com'), (2, 'Leo', 'leo@example.com');\nCREATE INDEX idx_students_name ON students(name);\nSELECT * FROM students WHERE name = 'Aria';",
  },
  {
    slug: 'cte-with-clause',
    title: 'Common Table Expressions (WITH)',
    summary: 'Naming a subquery for readability and reuse',
    explanation: [
      'A common table expression (CTE) lets you name a subquery using WITH name AS (SELECT ...), then reference that name later in the statement like a temporary table.',
      'CTEs make long queries easier to read by breaking them into named steps instead of nesting subqueries inside each other.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nWITH high_scorers AS (\n  SELECT name, score FROM students WHERE score >= 85\n)\nSELECT * FROM high_scorers ORDER BY score DESC;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nWITH averages AS (\n  SELECT AVG(score) AS avg_score FROM students\n)\nSELECT name, score FROM students, averages WHERE students.score > averages.avg_score;",
  },
  {
    slug: 'window-functions-basics',
    title: 'Window Functions',
    summary: 'Ranking and computing across rows without collapsing them',
    explanation: [
      'Unlike GROUP BY, which collapses rows into one per group, a window function computes a value across a set of rows while still returning every row.',
      'ROW_NUMBER() OVER (ORDER BY score DESC) numbers each row by rank, letting you see each score alongside its position.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88), ('Maya', 72);\nSELECT name, score,\n       ROW_NUMBER() OVER (ORDER BY score DESC) AS rank\nFROM students;",
    starterCode: "CREATE TABLE students (name TEXT, class TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria','A',95), ('Leo','A',88), ('Maya','B',72);\nSELECT name, class, score,\n       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS class_rank\nFROM students;",
  },
  {
    slug: 'exists-operator',
    title: 'The EXISTS Operator',
    summary: 'Checking whether a subquery returns any rows',
    explanation: [
      'EXISTS tests whether a subquery returns at least one row, returning true or false rather than any actual data.',
      "It's often used with a correlated subquery that references the outer query, e.g. find students who have at least one recorded score.",
    ],
    example: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo');\nINSERT INTO scores VALUES (1, 95);\nSELECT name FROM students s\nWHERE EXISTS (SELECT 1 FROM scores WHERE scores.student_id = s.id);",
    starterCode: "CREATE TABLE students (id INTEGER, name TEXT);\nCREATE TABLE scores (student_id INTEGER, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria'), (2, 'Leo');\nINSERT INTO scores VALUES (1, 95);\nSELECT name FROM students s\nWHERE NOT EXISTS (SELECT 1 FROM scores WHERE scores.student_id = s.id);",
  },
  {
    slug: 'alter-table',
    title: 'ALTER TABLE',
    summary: 'Changing the structure of an existing table',
    explanation: [
      'ALTER TABLE lets you change a table after it already exists, without having to drop and recreate it.',
      'ALTER TABLE students ADD COLUMN email TEXT; adds a new column — existing rows get NULL for it until you fill it in.',
    ],
    example: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88);\nALTER TABLE students ADD COLUMN email TEXT;\nUPDATE students SET email = 'aria@example.com' WHERE name = 'Aria';\nSELECT * FROM students;",
    starterCode: "CREATE TABLE students (name TEXT, score INTEGER);\nINSERT INTO students VALUES ('Aria', 95), ('Leo', 88);\nALTER TABLE students ADD COLUMN class TEXT;\nSELECT * FROM students;",
  },
  {
    slug: 'upsert-insert-or-replace',
    title: 'Upsert: INSERT OR REPLACE',
    summary: 'Inserting a row, or updating it if it already exists',
    explanation: [
      "An 'upsert' inserts a new row, or updates the existing one if a unique or primary key already matches — saving you from checking first.",
      'SQLite supports INSERT OR REPLACE INTO table VALUES (...), which replaces any row with a conflicting key instead of erroring.',
      'SQLite also supports the more standard INSERT INTO ... ON CONFLICT(column) DO UPDATE SET ... syntax for the same idea.',
    ],
    example: "CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria', 95);\nINSERT OR REPLACE INTO students VALUES (1, 'Aria', 99);\nSELECT * FROM students;",
    starterCode: "CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, score INTEGER);\nINSERT INTO students VALUES (1, 'Aria', 95);\nINSERT INTO students (id, name, score) VALUES (1, 'Aria', 99)\nON CONFLICT(id) DO UPDATE SET score = excluded.score;\nSELECT * FROM students;",
  },
  {
    slug: 'data-types-in-sql',
    title: 'SQL Data Types',
    summary: 'Choosing the right kind of value for each column',
    explanation: [
      'SQLite columns are commonly declared as INTEGER (whole numbers), REAL (decimals), TEXT (strings), or BLOB (raw binary data).',
      "Other SQL databases add types like NUMERIC and DATE, and SQLite understands those names too — it just stores the value using one of its core types under the hood.",
      'Choosing the right type matters: it helps the database sort, compare, and validate data correctly, like sorting scores numerically instead of alphabetically.',
    ],
    example: "CREATE TABLE students (\n  name TEXT,\n  gpa REAL,\n  enrolled INTEGER,\n  joined DATE\n);\nINSERT INTO students VALUES ('Aria', 3.9, 1, '2024-09-01');\nSELECT * FROM students;",
    starterCode: "CREATE TABLE products (\n  name TEXT,\n  price REAL,\n  in_stock INTEGER\n);\nINSERT INTO products VALUES ('Notebook', 2.5, 1);\nSELECT * FROM products;",
  },
  {
    slug: 'group-by-multiple-columns',
    title: 'GROUP BY Multiple Columns',
    summary: 'Grouping by more than one column at once',
    explanation: [
      'GROUP BY can take more than one column — rows are grouped together only when all listed columns match.',
      'This lets you compute aggregates for finer-grained combinations, like the average score per class per subject instead of just per class.',
    ],
    example: "CREATE TABLE scores (class TEXT, subject TEXT, score INTEGER);\nINSERT INTO scores VALUES ('A','Math',90), ('A','Math',80), ('A','Art',70), ('B','Math',60);\nSELECT class, subject, AVG(score) AS avg_score\nFROM scores\nGROUP BY class, subject;",
    starterCode: "CREATE TABLE scores (class TEXT, subject TEXT, score INTEGER);\nINSERT INTO scores VALUES ('A','Math',90), ('A','Math',80), ('A','Art',70), ('B','Math',60);\nSELECT class, subject, COUNT(*) AS total\nFROM scores\nGROUP BY class, subject;",
  },
  {
    slug: 'cross-join',
    title: 'CROSS JOIN',
    summary: 'Pairing every row from one table with every row from another',
    explanation: [
      'CROSS JOIN pairs every row from the first table with every row from the second, producing a Cartesian product.',
      "It's useful when you genuinely need every combination, like generating all size/color pairs for a product catalog.",
      'Unlike INNER or LEFT JOIN, CROSS JOIN has no ON condition — it simply multiplies the row counts of both tables together.',
    ],
    example: "CREATE TABLE sizes (size TEXT);\nCREATE TABLE colors (color TEXT);\nINSERT INTO sizes VALUES ('S'), ('M'), ('L');\nINSERT INTO colors VALUES ('Red'), ('Blue');\nSELECT size, color FROM sizes CROSS JOIN colors;",
    starterCode: "CREATE TABLE sizes (size TEXT);\nCREATE TABLE colors (color TEXT);\nINSERT INTO sizes VALUES ('S'), ('M');\nINSERT INTO colors VALUES ('Red'), ('Blue'), ('Green');\nSELECT size, color FROM sizes CROSS JOIN colors;",
  },
  {
    slug: 'database-design-basics',
    title: 'Database Design Basics',
    summary: 'Splitting data into related tables instead of one big table',
    explanation: [
      "Cramming everything into one flat table leads to repeated data — if a student's class name changes, you'd have to update it on every single row.",
      'Splitting data into related tables (like the constraints-and-keys and joins lessons covered) keeps each fact in one place, linked by keys instead of duplicated text.',
      'This basic idea is called normalization: each table describes one kind of thing, and JOINs bring the pieces back together when you need them.',
    ],
    example: "-- Before: one flat table repeats the class name on every row\nCREATE TABLE students_flat (name TEXT, class_name TEXT, class_room TEXT);\nINSERT INTO students_flat VALUES ('Aria', 'Algebra', 'Room 101'), ('Leo', 'Algebra', 'Room 101');\n\n-- After: class info lives in its own table, linked by id\nCREATE TABLE classes (id INTEGER PRIMARY KEY, class_name TEXT, class_room TEXT);\nCREATE TABLE students (name TEXT, class_id INTEGER);\nINSERT INTO classes VALUES (1, 'Algebra', 'Room 101');\nINSERT INTO students VALUES ('Aria', 1), ('Leo', 1);\nSELECT students.name, classes.class_name, classes.class_room\nFROM students\nINNER JOIN classes ON students.class_id = classes.id;",
    starterCode: "CREATE TABLE classes (id INTEGER PRIMARY KEY, class_name TEXT, class_room TEXT);\nCREATE TABLE students (name TEXT, class_id INTEGER);\nINSERT INTO classes VALUES (1, 'Algebra', 'Room 101'), (2, 'Art', 'Room 202');\nINSERT INTO students VALUES ('Aria', 1), ('Leo', 1), ('Maya', 2);\nSELECT students.name, classes.class_name\nFROM students\nINNER JOIN classes ON students.class_id = classes.id;",
  },
]
