import type { CodingLesson } from '../languages'

export const typescript: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to TypeScript',
    summary: 'JavaScript with types attached',
    explanation: [
      'TypeScript is JavaScript with an extra layer: type annotations. You write let age: number = 12 to tell the tool what kind of value a variable should hold.',
      'These annotations help catch mistakes — like adding a number to a string by accident — before your code ever runs.',
      'Behind the scenes, the types are checked and then stripped away, leaving plain JavaScript that runs in the browser.',
    ],
    example: "let age: number = 12;\nlet name: string = 'Aria';\nlet isStudent: boolean = true;\n\nconsole.log(`${name} is ${age} years old`);\nconsole.log(`Student? ${isStudent}`);\n\nfunction add(a: number, b: number): number {\n  return a + b;\n}\n\nconsole.log(add(2, 3));",
    starterCode: "let city: string = 'Kathmandu';\nlet temperature: number = 22;\n\nconsole.log(`${city} is ${temperature} degrees today`);",
  },
  {
    slug: 'interfaces-and-types',
    title: 'Interfaces & Type Aliases',
    summary: 'Describing the shape of objects',
    explanation: [
      'An interface describes the shape an object should have: interface User { name: string; age: number }. Any object matching that shape can be treated as a User.',
      'A type alias does something similar with the type keyword: type Point = { x: number; y: number }, and can also name unions and other type combinations.',
      'You can use an interface or type alias as the type of a function parameter, so the function only accepts objects with the right shape.',
    ],
    example: "interface User {\n  name: string;\n  age: number;\n}\n\ntype Point = { x: number; y: number };\n\nfunction describeUser(user: User): string {\n  return `${user.name} is ${user.age} years old`;\n}\n\nfunction distanceFromOrigin(point: Point): number {\n  return Math.sqrt(point.x * point.x + point.y * point.y);\n}\n\nconst aria: User = { name: 'Aria', age: 12 };\nconsole.log(describeUser(aria));\nconsole.log(distanceFromOrigin({ x: 3, y: 4 }));",
    starterCode: "interface Book {\n  title: string;\n  pages: number;\n}\n\nfunction summarize(book: Book): string {\n  return `${book.title} has ${book.pages} pages`;\n}\n\nconst myBook: Book = { title: 'TypeScript Basics', pages: 120 };\nconsole.log(summarize(myBook));",
  },
  {
    slug: 'functions-and-generics',
    title: 'Functions & Generics',
    summary: 'Typing parameters, return values, and writing reusable generic functions',
    explanation: [
      'You can annotate a function\'s parameters and return type, like function greet(name: string): string, so TypeScript checks both what goes in and what comes out.',
      'Generics let a function work with many types while staying type-safe: function identity<T>(x: T): T returns whatever type it was given.',
      'The placeholder T stands in for "whatever type the caller uses" — TypeScript fills it in automatically based on the argument.',
    ],
    example: "function greet(name: string): string {\n  return `Hello, ${name}!`;\n}\n\nfunction identity<T>(value: T): T {\n  return value;\n}\n\nfunction firstItem<T>(items: T[]): T {\n  return items[0];\n}\n\nconsole.log(greet('World'));\nconsole.log(identity(42));\nconsole.log(identity('TypeScript'));\nconsole.log(firstItem([10, 20, 30]));\nconsole.log(firstItem(['a', 'b', 'c']));",
    starterCode: "function double(n: number): number {\n  return n * 2;\n}\n\nfunction wrapInArray<T>(value: T): T[] {\n  return [value];\n}\n\nconsole.log(double(21));\nconsole.log(wrapInArray('hello'));\nconsole.log(wrapInArray(99));",
  },
  {
    slug: 'classes',
    title: 'Classes',
    summary: 'Typed classes with constructor properties and access modifiers',
    explanation: [
      'A TypeScript class can declare the types of its properties, and the constructor can use access modifiers like public and private to both declare and assign properties in one step.',
      'public members can be used from outside the class, while private members can only be accessed from within the class itself.',
      'Methods on a class can have typed parameters and return types just like regular functions.',
    ],
    example: "class Animal {\n  public name: string;\n  private sound: string;\n\n  constructor(name: string, sound: string) {\n    this.name = name;\n    this.sound = sound;\n  }\n\n  speak(): string {\n    return `${this.name} says ${this.sound}`;\n  }\n}\n\nclass Dog extends Animal {\n  constructor(name: string) {\n    super(name, 'Woof');\n  }\n\n  fetch(): string {\n    return `${this.name} fetches the ball!`;\n  }\n}\n\nconst rex = new Dog('Rex');\nconsole.log(rex.speak());\nconsole.log(rex.fetch());",
    starterCode: "class Counter {\n  private count: number = 0;\n\n  increment(): number {\n    this.count += 1;\n    return this.count;\n  }\n\n  getCount(): number {\n    return this.count;\n  }\n}\n\nconst counter = new Counter();\ncounter.increment();\ncounter.increment();\nconsole.log(counter.getCount());",
  },
  {
    slug: 'enums-and-unions',
    title: 'Enums & Union Types',
    summary: 'Naming sets of related values and combining types with |',
    explanation: [
      'An enum gives friendly names to a fixed set of related values, like enum Direction { Up, Down, Left, Right }, which you can refer to as Direction.Up.',
      'A union type allows a value to be one of several specific types or literal values, like type Status = "idle" | "loading" | "done".',
      'Union types are great for representing a small, known set of possible states a value can be in.',
    ],
    example: "enum Direction {\n  Up,\n  Down,\n  Left,\n  Right,\n}\n\ntype Status = 'idle' | 'loading' | 'done';\n\nfunction describeStatus(status: Status): string {\n  if (status === 'idle') return 'Waiting to start';\n  if (status === 'loading') return 'Working on it...';\n  return 'All finished!';\n}\n\nconsole.log(Direction.Up);\nconsole.log(Direction.Left);\nconsole.log(describeStatus('loading'));\nconsole.log(describeStatus('done'));",
    starterCode: "enum Level {\n  Beginner,\n  Intermediate,\n  Advanced,\n}\n\ntype Theme = 'light' | 'dark';\n\nfunction describeTheme(theme: Theme): string {\n  return theme === 'light' ? 'Bright mode' : 'Dark mode';\n}\n\nconsole.log(Level.Intermediate);\nconsole.log(describeTheme('dark'));",
  },
  {
    slug: 'arrays-and-tuples',
    title: 'Arrays & Tuples',
    summary: 'Typed lists and fixed-shape grouped values',
    explanation: [
      'A typed array says what kind of values it holds, like number[] for a list of numbers or string[] for a list of strings.',
      'A tuple is a fixed-length array where each position has its own type, like [string, number] for a name paired with an age.',
      'Tuples are useful when you want to group a small, fixed set of related values that each have a different meaning.',
    ],
    example: "const scores: number[] = [70, 85, 92, 60];\nconst names: string[] = ['Aria', 'Kiran', 'Maya'];\n\nconst passing = scores.filter(s => s >= 70);\nconsole.log(passing);\n\nconst person: [string, number] = ['Aria', 12];\nconst [personName, personAge] = person;\nconsole.log(`${personName} is ${personAge}`);\n\nconst entries: [string, number][] = [\n  ['Aria', 92],\n  ['Kiran', 78],\n];\nfor (const [entryName, entryScore] of entries) {\n  console.log(`${entryName}: ${entryScore}`);\n}",
    starterCode: "const temperatures: number[] = [18, 22, 25, 19];\nconst average = temperatures.reduce((sum, t) => sum + t, 0) / temperatures.length;\nconsole.log(average);\n\nconst point: [number, number] = [3, 4];\nconsole.log(`x=${point[0]}, y=${point[1]}`);",
  },
  {
    slug: 'type-narrowing',
    title: 'Type Narrowing',
    summary: 'Checking a value\'s type before using it',
    explanation: [
      'When a value could be more than one type, like string | number, TypeScript lets you narrow it down using checks such as typeof.',
      'Inside an if (typeof value === "string") block, TypeScript knows the value is a string and lets you safely use string methods on it.',
      'instanceof works the same way for classes, letting you check whether an object is an instance of a particular class before treating it as one.',
    ],
    example: "type Input = string | number;\n\nfunction describe(value: Input): string {\n  if (typeof value === 'string') {\n    return `Text of length ${value.length}: \"${value}\"`;\n  }\n  return `Number doubled: ${value * 2}`;\n}\n\nclass Cat {\n  meow(): string { return 'Meow!'; }\n}\n\nclass Robot {\n  beep(): string { return 'Beep!'; }\n}\n\nfunction makeSound(thing: Cat | Robot): string {\n  if (thing instanceof Cat) {\n    return thing.meow();\n  }\n  return thing.beep();\n}\n\nconsole.log(describe('hello'));\nconsole.log(describe(21));\nconsole.log(makeSound(new Cat()));\nconsole.log(makeSound(new Robot()));",
    starterCode: "type Id = string | number;\n\nfunction formatId(id: Id): string {\n  if (typeof id === 'number') {\n    return `#${id.toFixed(0)}`;\n  }\n  return id.toUpperCase();\n}\n\nconsole.log(formatId(42));\nconsole.log(formatId('abc123'));",
  },
  {
    slug: 'optional-readonly-and-defaults',
    title: 'Optional, Readonly & Default Values',
    summary: 'Marking properties optional, locking them with readonly, and giving parameters defaults',
    explanation: [
      "Adding a ? after a property name, like nickname?: string, marks it optional — objects can omit it, and TypeScript knows it might be undefined when you read it.",
      "The readonly modifier locks a property after it's first set: readonly id: number means id can be assigned in the constructor but never reassigned afterward.",
      "Function parameters can have default values, like function greet(name: string = 'friend'), which TypeScript uses to also infer the parameter's type and let callers omit it.",
    ],
    example: "interface Profile {\n  readonly id: number;\n  name: string;\n  nickname?: string;\n}\n\nfunction describe(profile: Profile): string {\n  const label = profile.nickname ?? profile.name;\n  return `#${profile.id}: ${label}`;\n}\n\nfunction greet(name: string = 'friend'): string {\n  return `Hello, ${name}!`;\n}\n\nconst profile: Profile = { id: 1, name: 'Aria' };\nconsole.log(describe(profile));\nconsole.log(greet());\nconsole.log(greet('Kiran'));",
    starterCode: "interface Task {\n  readonly id: number;\n  title: string;\n  notes?: string;\n}\n\nfunction summarize(task: Task, fallback: string = 'No notes'): string {\n  return `${task.title}: ${task.notes ?? fallback}`;\n}\n\nconst task: Task = { id: 1, title: 'Learn TypeScript' };\nconsole.log(summarize(task));",
  },
  {
    slug: 'discriminated-unions',
    title: 'Discriminated Unions',
    summary: "Modeling a value that can be one of several known shapes",
    explanation: [
      "A discriminated union is a union of object types that all share one common, literal-valued property — often called kind or type — which identifies which shape you're looking at.",
      "Inside a switch on that shared property, TypeScript narrows the type in each case, so you can safely access the fields that only exist on that particular shape.",
      "This pattern is a clean alternative to a pile of optional properties, because it makes impossible combinations (like a circle with a width) impossible to construct.",
    ],
    example: "type Shape =\n  | { kind: 'circle'; radius: number }\n  | { kind: 'rectangle'; width: number; height: number };\n\nfunction area(shape: Shape): number {\n  switch (shape.kind) {\n    case 'circle':\n      return Math.PI * shape.radius * shape.radius;\n    case 'rectangle':\n      return shape.width * shape.height;\n  }\n}\n\nconst circle: Shape = { kind: 'circle', radius: 3 };\nconst rectangle: Shape = { kind: 'rectangle', width: 4, height: 5 };\n\nconsole.log(area(circle).toFixed(2));\nconsole.log(area(rectangle));",
    starterCode: "type Notification =\n  | { kind: 'message'; text: string }\n  | { kind: 'like'; from: string };\n\nfunction describe(note: Notification): string {\n  if (note.kind === 'message') {\n    return `New message: ${note.text}`;\n  }\n  return `${note.from} liked your post`;\n}\n\nconsole.log(describe({ kind: 'message', text: 'Hey there!' }));\nconsole.log(describe({ kind: 'like', from: 'Kiran' }));",
  },
  {
    slug: 'utility-types',
    title: 'Utility Types',
    summary: 'Building new types out of existing ones with Partial, Pick, Omit & Record',
    explanation: [
      "Partial<T> makes every property of T optional — useful for an 'update' function that only changes a few fields at a time.",
      'Pick<T, Keys> builds a smaller type with only the listed properties, while Omit<T, Keys> does the opposite, keeping everything except the listed ones.',
      'Record<Keys, ValueType> describes an object whose keys all come from a fixed list and whose values share one type, like a lookup table.',
    ],
    example: "interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nfunction updateUser(user: User, changes: Partial<User>): User {\n  return { ...user, ...changes };\n}\n\ntype UserPreview = Pick<User, 'id' | 'name'>;\n\nconst scoresByName: Record<string, number> = {\n  Aria: 95,\n  Kiran: 88,\n};\n\nconst user: User = { id: 1, name: 'Aria', email: 'aria@example.com' };\nconst updated = updateUser(user, { name: 'Aria Sharma' });\nconst preview: UserPreview = { id: updated.id, name: updated.name };\n\nconsole.log(updated);\nconsole.log(preview);\nconsole.log(scoresByName['Aria']);",
    starterCode: "interface Settings {\n  theme: string;\n  fontSize: number;\n  notifications: boolean;\n}\n\nfunction applyChanges(settings: Settings, changes: Partial<Settings>): Settings {\n  return { ...settings, ...changes };\n}\n\nconst defaults: Settings = { theme: 'light', fontSize: 14, notifications: true };\nconst next = applyChanges(defaults, { theme: 'dark' });\nconsole.log(next);",
  },
  {
    slug: 'async-await',
    title: 'Async/Await with Types',
    summary: 'Typing values that arrive later, through a Promise',
    explanation: [
      'Promise<T> describes a value of type T that will be available later — an async function that returns a number is typed as Promise<number>, even though you write return n; inside it.',
      'Inside an async function, await pauses until a Promise settles and hands you back the resolved value already unwrapped from its Promise<T> wrapper.',
      'Wrapping an await in try/catch lets you handle a rejected Promise the same way you would handle any other thrown error.',
    ],
    example: "function wait<T>(ms: number, value: T): Promise<T> {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function loadScore(name: string): Promise<number> {\n  const score = await wait(10, 92);\n  return score;\n}\n\nasync function run(): Promise<void> {\n  try {\n    console.log('loading...');\n    const score = await loadScore('Aria');\n    console.log(`Score: ${score}`);\n  } catch (error) {\n    console.log('Something went wrong');\n  }\n}\n\nrun();",
    starterCode: "function wait<T>(ms: number, value: T): Promise<T> {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function loadMessage(): Promise<string> {\n  const message = await wait(10, 'Loaded!');\n  return message;\n}\n\nasync function run(): Promise<void> {\n  const message = await loadMessage();\n  console.log(message);\n}\n\nrun();",
  },
  {
    slug: 'generic-constraints-and-keyof',
    title: 'Generic Constraints & keyof',
    summary: "Limiting what a generic can be, and looking up a type's own property names",
    explanation: [
      "Writing <T extends SomeType> constrains a generic so T must have at least the shape of SomeType — inside the function, TypeScript then knows it's safe to use those properties.",
      'keyof T produces a union of all the property names of T as string literal types, so keyof User might be \'id\' | \'name\' | \'email\'.',
      "Combining both, function getProp<T, K extends keyof T>(obj: T, key: K): T[K] can fetch any property by name while keeping the exact return type — try passing a key that doesn't exist and TypeScript will catch it.",
    ],
    example: "interface HasLength {\n  length: number;\n}\n\nfunction longest<T extends HasLength>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}\n\nfunction getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst user = { id: 1, name: 'Aria', email: 'aria@example.com' };\n\nconsole.log(longest('hello', 'hi'));\nconsole.log(longest([1, 2, 3], [1]));\nconsole.log(getProp(user, 'name'));\nconsole.log(getProp(user, 'id'));",
    starterCode: "interface HasId {\n  id: number;\n}\n\nfunction printId<T extends HasId>(item: T): void {\n  console.log(`ID: ${item.id}`);\n}\n\nfunction getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst book = { id: 7, title: 'TypeScript Basics' };\nprintId(book);\nconsole.log(getProp(book, 'title'));",
  },
  {
    slug: 'type-assertions-and-unknown',
    title: 'Type Assertions & unknown',
    summary: 'Telling TypeScript "trust me" — carefully — and handling values of unknown shape',
    explanation: [
      'unknown is a safe alternative to any: a value typed unknown could be anything, so TypeScript forces you to check or narrow it before using it for anything specific.',
      "A type assertion, written value as Type, tells the compiler 'I know more than you do here' without changing the value at runtime — use it sparingly, since an incorrect assertion will compile but fail later.",
      "The safest way to go from unknown to a specific type is still a runtime check, like typeof or an 'in' check, rather than reaching straight for as.",
    ],
    example: "function parseConfig(json: string): unknown {\n  return JSON.parse(json);\n}\n\nfunction readPort(config: unknown): number {\n  if (typeof config === 'object' && config !== null && 'port' in config) {\n    return (config as { port: number }).port;\n  }\n  return 3000;\n}\n\nconst raw = parseConfig('{\"port\": 8080}');\nconsole.log(readPort(raw));\nconsole.log(readPort({}));\n\nconst value: unknown = 'hello';\nconst length = (value as string).length;\nconsole.log(length);",
    starterCode: "function readName(data: unknown): string {\n  if (typeof data === 'object' && data !== null && 'name' in data) {\n    return (data as { name: string }).name;\n  }\n  return 'Unknown';\n}\n\nconsole.log(readName({ name: 'Aria' }));\nconsole.log(readName(42));",
  },
  {
    slug: 'error-handling',
    title: 'Typed Error Handling',
    summary: 'Catching errors safely and creating your own Error subclasses',
    explanation: [
      'In a catch block, the caught value is typed unknown (not Error), because JavaScript lets you throw anything — checking instanceof Error before reading .message keeps things type-safe.',
      "You can define your own error type by extending Error: class ValidationError extends Error { ... } — instances still work with instanceof and carry a normal .message.",
      "Typing a function's possible failure explicitly, even just through a custom error class, helps callers know what to expect and catch precisely.",
    ],
    example: "class ValidationError extends Error {\n  constructor(message: string) {\n    super(message);\n    this.name = 'ValidationError';\n  }\n}\n\nfunction parsePositive(value: string): number {\n  const n = Number(value);\n  if (Number.isNaN(n) || n <= 0) {\n    throw new ValidationError(`\"${value}\" is not a positive number`);\n  }\n  return n;\n}\n\nfor (const input of ['12', 'abc', '-5']) {\n  try {\n    console.log(`Parsed: ${parsePositive(input)}`);\n  } catch (error) {\n    if (error instanceof ValidationError) {\n      console.log(`Validation failed: ${error.message}`);\n    } else if (error instanceof Error) {\n      console.log(`Unexpected error: ${error.message}`);\n    }\n  }\n}",
    starterCode: "class NotFoundError extends Error {\n  constructor(message: string) {\n    super(message);\n    this.name = 'NotFoundError';\n  }\n}\n\nfunction findUser(id: number): string {\n  if (id !== 1) {\n    throw new NotFoundError(`User ${id} was not found`);\n  }\n  return 'Aria';\n}\n\ntry {\n  console.log(findUser(2));\n} catch (error) {\n  if (error instanceof NotFoundError) {\n    console.log(`Error: ${error.message}`);\n  }\n}",
  },
  {
    slug: 'type-inference',
    title: 'Type Inference',
    summary: 'Letting TypeScript figure out types on its own',
    explanation: [
      'TypeScript can often infer a type from the value you assign, so let age = 12 already knows age is a number without writing : number yourself.',
      'Inference works for variables, return types, and even array contents, but it stops at function parameters — those need explicit annotations because TypeScript has no initial value to look at.',
      'Hovering over a variable in an editor shows you the inferred type, which is a great way to check what TypeScript decided.',
    ],
    example: "let age = 12;\nlet name = 'Aria';\nlet scores = [70, 85, 92];\n\nfunction double(n: number) {\n  return n * 2;\n}\n\nconst doubled = scores.map(double);\n\nconsole.log(typeof age, typeof name);\nconsole.log(doubled);\n\nfunction makeGreeting(person: string) {\n  return `Hello, ${person}!`;\n}\n\nconst greeting = makeGreeting(name);\nconsole.log(greeting);",
    starterCode: "let city = 'Kathmandu';\nlet population = 1500000;\n\nfunction describe(place: string, count: number) {\n  return `${place} has about ${count} people`;\n}\n\nconsole.log(describe(city, population));",
  },
  {
    slug: 'literal-types',
    title: 'Literal Types',
    summary: 'Treating specific values as their own exact types',
    explanation: [
      'A literal type narrows a type down to one exact value, like type Yes = true, instead of allowing any boolean.',
      'Literal types are most useful combined into a union, like type Direction = "up" | "down" | "left" | "right", which only allows those exact strings.',
      'Assigning anything outside the listed values is a compile error, which makes literal unions a lightweight way to model a fixed set of choices.',
    ],
    example: "type Direction = 'up' | 'down' | 'left' | 'right';\ntype DiceRoll = 1 | 2 | 3 | 4 | 5 | 6;\n\nfunction move(direction: Direction): string {\n  return `Moving ${direction}`;\n}\n\nfunction rollDescription(roll: DiceRoll): string {\n  return roll === 6 ? 'Jackpot!' : `You rolled a ${roll}`;\n}\n\nconsole.log(move('up'));\nconsole.log(rollDescription(6));\nconsole.log(rollDescription(3));",
    starterCode: "type Size = 'small' | 'medium' | 'large';\n\nfunction priceFor(size: Size): number {\n  if (size === 'small') return 3;\n  if (size === 'medium') return 4;\n  return 5;\n}\n\nconsole.log(priceFor('medium'));\nconsole.log(priceFor('large'));",
  },
  {
    slug: 'mapped-types',
    title: 'Mapped Types',
    summary: 'Building a new type by transforming every property of another',
    explanation: [
      'A mapped type loops over the keys of an existing type and produces a new type from them, like type Flags<T> = { [K in keyof T]: boolean }.',
      'Inside the brackets, K in keyof T means "for every property name K found in T", and whatever comes after the colon describes the new value type for each one.',
      'Mapped types are how built-in helpers like Partial and Readonly are implemented, so writing your own is a great way to understand them.',
    ],
    example: "interface Profile {\n  name: string;\n  age: number;\n  active: boolean;\n}\n\ntype Flags<T> = {\n  [K in keyof T]: boolean;\n};\n\ntype ReadonlyVersion<T> = {\n  readonly [K in keyof T]: T[K];\n};\n\nconst touched: Flags<Profile> = {\n  name: true,\n  age: false,\n  active: true,\n};\n\nconst locked: ReadonlyVersion<Profile> = { name: 'Aria', age: 12, active: true };\n\nconsole.log(touched);\nconsole.log(locked.name);",
    starterCode: "interface Settings {\n  theme: string;\n  volume: number;\n}\n\ntype Enabled<T> = {\n  [K in keyof T]: boolean;\n};\n\nconst enabledFields: Enabled<Settings> = {\n  theme: true,\n  volume: false,\n};\n\nconsole.log(enabledFields);",
  },
  {
    slug: 'conditional-types',
    title: 'Conditional Types',
    summary: 'Choosing a type based on a condition, at the type level',
    explanation: [
      'A conditional type picks between two types using syntax that mirrors a ternary: T extends U ? X : Y means "if T is assignable to U, use X, otherwise use Y".',
      'These checks happen entirely while TypeScript is checking your code — there is no runtime cost, since it is all decided before the JavaScript even runs.',
      'Conditional types are often combined with generics, letting a type change shape depending on what it is given.',
    ],
    example: "type IsString<T> = T extends string ? 'yes' : 'no';\n\ntype A = IsString<string>;\ntype B = IsString<number>;\n\ntype ElementType<T> = T extends (infer U)[] ? U : T;\n\ntype Item = ElementType<number[]>;\n\nconst a: A = 'yes';\nconst b: B = 'no';\nconst item: Item = 42;\n\nconsole.log(a, b, item);",
    starterCode: "type IsArray<T> = T extends unknown[] ? true : false;\n\nconst result1: IsArray<string[]> = true;\nconst result2: IsArray<number> = false;\n\nconsole.log(result1, result2);",
  },
  {
    slug: 'template-literal-types',
    title: 'Template Literal Types',
    summary: 'Building string types out of patterns and other types',
    explanation: [
      'Template literal types use the same backtick syntax as template literals, but at the type level, like type EventName = `on${string}`.',
      'You can combine them with literal unions to generate every combination automatically, such as `${"red" | "blue"}-shirt` producing "red-shirt" | "blue-shirt".',
      'Built-in helpers like Capitalize<T> can be used inside a template literal type to transform the casing of part of the string.',
    ],
    example: "type Color = 'red' | 'blue';\ntype Shirt = `${Color}-shirt`;\n\ntype EventName = `on${Capitalize<'click' | 'hover'>}`;\n\ntype HexChannel = `#${number}`;\n\nconst shirt: Shirt = 'red-shirt';\nconst event: EventName = 'onClick';\nconst hex: HexChannel = `#${255}` as HexChannel;\n\nconsole.log(shirt, event, hex);",
    starterCode: "type Direction = 'left' | 'right';\ntype Action = `move-${Direction}`;\n\nconst action: Action = 'move-left';\nconsole.log(action);",
  },
  {
    slug: 'abstract-classes',
    title: 'Abstract Classes',
    summary: 'A base class that cannot be instantiated directly',
    explanation: [
      'An abstract class, declared with the abstract keyword, defines shared structure for subclasses but can never be created with new directly.',
      'An abstract method has no body in the base class — it only declares a signature that every subclass is required to implement.',
      'This is useful when several related classes should share some behavior but each must provide its own version of one specific method.',
    ],
    example: "abstract class Shape {\n  abstract area(): number;\n\n  describe(): string {\n    return `This shape has an area of ${this.area().toFixed(2)}`;\n  }\n}\n\nclass Circle extends Shape {\n  constructor(private radius: number) {\n    super();\n  }\n\n  area(): number {\n    return Math.PI * this.radius * this.radius;\n  }\n}\n\nclass Square extends Shape {\n  constructor(private side: number) {\n    super();\n  }\n\n  area(): number {\n    return this.side * this.side;\n  }\n}\n\nconst shapes: Shape[] = [new Circle(2), new Square(3)];\nfor (const shape of shapes) {\n  console.log(shape.describe());\n}",
    starterCode: "abstract class Animal {\n  abstract speak(): string;\n\n  greet(): string {\n    return `This animal says: ${this.speak()}`;\n  }\n}\n\nclass Dog extends Animal {\n  speak(): string {\n    return 'Woof';\n  }\n}\n\nconst dog = new Dog();\nconsole.log(dog.greet());",
  },
  {
    slug: 'access-modifiers-and-parameter-properties',
    title: 'Access Modifiers & Parameter Properties',
    summary: 'Controlling visibility of class members, with a shorthand for declaring them',
    explanation: [
      'public members (the default) can be used from anywhere, private members can only be accessed inside the class, and protected members can be used inside the class and its subclasses.',
      'Writing an access modifier directly in front of a constructor parameter, like constructor(private name: string), is a shortcut that both declares the property and assigns it in one step.',
      'protected is handy when a subclass needs access to a field that outside code should not be able to touch.',
    ],
    example: "class Account {\n  protected balance: number;\n\n  constructor(private owner: string, startingBalance: number) {\n    this.balance = startingBalance;\n  }\n\n  describe(): string {\n    return `${this.owner}'s balance: $${this.balance}`;\n  }\n}\n\nclass SavingsAccount extends Account {\n  addInterest(rate: number): void {\n    this.balance += this.balance * rate;\n  }\n}\n\nconst account = new SavingsAccount('Aria', 100);\naccount.addInterest(0.1);\nconsole.log(account.describe());",
    starterCode: "class Point {\n  constructor(private x: number, private y: number) {}\n\n  toString(): string {\n    return `(${this.x}, ${this.y})`;\n  }\n}\n\nconst p = new Point(3, 4);\nconsole.log(p.toString());",
  },
  {
    slug: 'index-signatures',
    title: 'Index Signatures',
    summary: 'Typing objects whose keys are not known ahead of time',
    explanation: [
      'An index signature like { [key: string]: number } describes an object that can have any number of string keys, as long as every value is a number.',
      'This is useful for dictionary-like objects, such as a lookup table of scores by name, where you cannot list every possible key in advance.',
      'You can still mix in known properties alongside an index signature, as long as those properties are compatible with the signature\'s value type.',
    ],
    example: "interface ScoreBoard {\n  [playerName: string]: number;\n}\n\nconst scores: ScoreBoard = {\n  Aria: 92,\n  Kiran: 78,\n};\n\nscores.Maya = 88;\n\nfor (const name in scores) {\n  console.log(`${name}: ${scores[name]}`);\n}\n\nfunction totalScore(board: ScoreBoard): number {\n  return Object.values(board).reduce((sum, s) => sum + s, 0);\n}\n\nconsole.log(totalScore(scores));",
    starterCode: "interface Inventory {\n  [item: string]: number;\n}\n\nconst stock: Inventory = {\n  apples: 10,\n  bananas: 5,\n};\n\nstock.cherries = 20;\nconsole.log(stock);",
  },
  {
    slug: 'function-overloads',
    title: 'Function Overloads',
    summary: 'Describing multiple ways a function can be called',
    explanation: [
      'Function overloads let you write several call signatures for the same function, describing different combinations of argument types and matching return types.',
      'You write the overload signatures first, then a single implementation signature below them that must be general enough to handle every overload.',
      'Callers only see the overload signatures, so TypeScript picks the most specific match and gives you a precisely typed result.',
    ],
    example: "function makeId(value: string): string;\nfunction makeId(value: number): string;\nfunction makeId(value: string | number): string {\n  return `id-${value}`;\n}\n\nconsole.log(makeId('aria'));\nconsole.log(makeId(42));\n\nfunction firstElement(arr: string[]): string;\nfunction firstElement(arr: number[]): number;\nfunction firstElement(arr: any[]): any {\n  return arr[0];\n}\n\nconsole.log(firstElement(['a', 'b']));\nconsole.log(firstElement([1, 2, 3]));",
    starterCode: "function combine(a: string, b: string): string;\nfunction combine(a: number, b: number): number;\nfunction combine(a: any, b: any): any {\n  return a + b;\n}\n\nconsole.log(combine('Hello, ', 'world!'));\nconsole.log(combine(2, 3));",
  },
  {
    slug: 'never-and-void',
    title: 'never & void',
    summary: 'The type for "returns nothing" versus the type for "never finishes"',
    explanation: [
      'void describes a function that completes normally but does not return a meaningful value, like a function that only calls console.log.',
      'never describes a function that never successfully returns at all — either it always throws an error or it loops forever.',
      'TypeScript can use never to check exhaustiveness: if every case of a union has been handled, the leftover type in an unreachable branch is never.',
    ],
    example: "function logMessage(message: string): void {\n  console.log(message);\n}\n\nfunction fail(reason: string): never {\n  throw new Error(reason);\n}\n\ntype Shape = { kind: 'circle' } | { kind: 'square' };\n\nfunction describe(shape: Shape): string {\n  switch (shape.kind) {\n    case 'circle':\n      return 'A circle';\n    case 'square':\n      return 'A square';\n    default:\n      const exhaustiveCheck: never = shape;\n      return exhaustiveCheck;\n  }\n}\n\nlogMessage('Starting...');\nconsole.log(describe({ kind: 'circle' }));\ntry {\n  fail('Something went wrong');\n} catch (e) {\n  if (e instanceof Error) console.log(e.message);\n}",
    starterCode: "function warn(message: string): void {\n  console.log(`Warning: ${message}`);\n}\n\nfunction throwError(message: string): never {\n  throw new Error(message);\n}\n\nwarn('Low battery');\ntry {\n  throwError('Out of battery');\n} catch (e) {\n  if (e instanceof Error) console.log(e.message);\n}",
  },
  {
    slug: 'labeled-and-optional-tuples',
    title: 'Labeled & Optional Tuple Elements',
    summary: 'Giving tuple positions names and making some of them optional',
    explanation: [
      'Tuple elements can have labels purely for readability, like [name: string, age: number], which shows up in editor hints without changing how the tuple behaves.',
      'Adding a ? after a labeled element, like [name: string, age?: number], makes that position optional, so the tuple can be shorter and still be valid.',
      'Optional tuple elements must come after the required ones, just like optional function parameters.',
    ],
    example: "type Person = [name: string, age?: number];\n\nfunction describe(person: Person): string {\n  const [name, age] = person;\n  return age !== undefined ? `${name} is ${age}` : `${name} (age unknown)`;\n}\n\nconst withAge: Person = ['Aria', 12];\nconst withoutAge: Person = ['Kiran'];\n\nconsole.log(describe(withAge));\nconsole.log(describe(withoutAge));",
    starterCode: "type Coordinate = [x: number, y: number, z?: number];\n\nfunction describePoint(point: Coordinate): string {\n  const [x, y, z] = point;\n  return z !== undefined ? `(${x}, ${y}, ${z})` : `(${x}, ${y})`;\n}\n\nconsole.log(describePoint([1, 2]));\nconsole.log(describePoint([1, 2, 3]));",
  },
  {
    slug: 'satisfies-operator',
    title: 'The satisfies Operator',
    summary: 'Checking a value against a type without widening its inferred type',
    explanation: [
      'The satisfies operator checks that a value matches a given type, just like a type annotation would, but it keeps the more specific type TypeScript inferred from the value itself.',
      'This means value satisfies SomeType still lets you access the exact literal keys and values afterward, instead of widening everything to the general shape.',
      'It is especially useful for objects like color palettes or config maps, where you want validation but also want to keep precise autocomplete on the result.',
    ],
    example: "type Colors = Record<string, string>;\n\nconst palette = {\n  red: '#ff0000',\n  green: '#00ff00',\n} satisfies Colors;\n\n// Because of satisfies, palette.red is known to exist with its exact key:\nconsole.log(palette.red);\nconsole.log(palette.green);\n\nconst widened: Colors = { red: '#ff0000', green: '#00ff00' };\n// widened.red still works, but TypeScript no longer remembers the exact keys as literals.\nconsole.log(widened.red);",
    starterCode: "type Config = Record<string, number>;\n\nconst settings = {\n  volume: 80,\n  brightness: 50,\n} satisfies Config;\n\nconsole.log(settings.volume);\nconsole.log(settings.brightness);",
  },
  {
    slug: 'custom-type-guards',
    title: 'Custom Type Guards',
    summary: 'Writing your own functions that narrow a type',
    explanation: [
      'A custom type guard is a function whose return type is written as x is SomeType, like function isString(x: unknown): x is string.',
      'When you call that function inside an if statement, TypeScript narrows the checked value to SomeType for the rest of that block, just like it does with typeof.',
      'Custom type guards are especially useful for checking complex shapes, like distinguishing between several object types in a union.',
    ],
    example: "function isString(x: unknown): x is string {\n  return typeof x === 'string';\n}\n\ninterface Cat { meow(): string; }\ninterface Robot { beep(): string; }\n\nfunction isCat(x: Cat | Robot): x is Cat {\n  return 'meow' in x;\n}\n\nfunction makeSound(thing: Cat | Robot): string {\n  if (isCat(thing)) {\n    return thing.meow();\n  }\n  return thing.beep();\n}\n\nconst values: unknown[] = ['hello', 42, 'world'];\nfor (const v of values) {\n  if (isString(v)) {\n    console.log(v.toUpperCase());\n  }\n}\n\nconsole.log(makeSound({ meow: () => 'Meow!' }));",
    starterCode: "function isNumber(x: unknown): x is number {\n  return typeof x === 'number';\n}\n\nconst values: unknown[] = [1, 'two', 3];\nfor (const v of values) {\n  if (isNumber(v)) {\n    console.log(v * 2);\n  }\n}",
  },
  {
    slug: 'const-assertions',
    title: 'const Assertions',
    summary: 'Freezing a value\'s type at its most specific, literal form',
    explanation: [
      'Adding as const after a value tells TypeScript to infer the narrowest possible type instead of the usual widened one — a string becomes its exact literal type, not just string.',
      'On an array, as const also makes it a readonly tuple instead of a mutable array, so its length and element types are locked in.',
      'as const is often combined with keyof and typeof to derive a union type directly from a list of allowed values, avoiding having to repeat them.',
    ],
    example: "const direction = 'up' as const;\n// direction has type 'up', not string\n\nconst point = [3, 4] as const;\n// point has type readonly [3, 4]\n\nconst directions = ['up', 'down', 'left', 'right'] as const;\ntype Direction = typeof directions[number];\n\nfunction move(dir: Direction): string {\n  return `Moving ${dir}`;\n}\n\nconsole.log(direction);\nconsole.log(point[0], point[1]);\nconsole.log(move('left'));",
    starterCode: "const sizes = ['small', 'medium', 'large'] as const;\ntype Size = typeof sizes[number];\n\nfunction describeSize(size: Size): string {\n  return `Size: ${size}`;\n}\n\nconsole.log(describeSize('medium'));",
  },
  {
    slug: 'intersection-types',
    title: 'Intersection Types',
    summary: 'Combining multiple types into one with &',
    explanation: [
      'An intersection type combines two or more types into one that must satisfy all of them at once, written with &, like type Both = A & B.',
      'When combining two object types, the result has every property from both — a value must have all the fields of A and all the fields of B to qualify.',
      'Intersections are useful for mixing in shared traits, like adding a Timestamped shape onto several different record types.',
    ],
    example: "interface Named {\n  name: string;\n}\n\ninterface Aged {\n  age: number;\n}\n\ntype Person = Named & Aged;\n\nconst person: Person = { name: 'Aria', age: 12 };\n\nfunction introduce(p: Person): string {\n  return `${p.name} is ${p.age} years old`;\n}\n\nconsole.log(introduce(person));\n\ninterface Timestamped {\n  createdAt: string;\n}\n\ntype LoggedPerson = Person & Timestamped;\nconst entry: LoggedPerson = { name: 'Kiran', age: 15, createdAt: '2024-01-01' };\nconsole.log(entry);",
    starterCode: "interface HasId {\n  id: number;\n}\n\ninterface HasTitle {\n  title: string;\n}\n\ntype Article = HasId & HasTitle;\n\nconst article: Article = { id: 1, title: 'Learning TypeScript' };\nconsole.log(article);",
  },
  {
    slug: 'numeric-and-string-enums',
    title: 'Numeric & String Enums',
    summary: 'Comparing auto-numbered enums with explicit string enums',
    explanation: [
      'A plain enum without assigned values, like enum Level { Low, Medium, High }, automatically numbers its members starting at 0, so Level.Low is 0 and Level.Medium is 1.',
      'A string enum assigns an explicit string to every member, like enum Level { Low = "LOW", Medium = "MEDIUM" }, so the runtime value is always a readable string instead of a number.',
      'String enums are often clearer in logs and debugging, since printing Level.Low shows "LOW" instead of an unhelpful 0.',
    ],
    example: "enum NumericLevel {\n  Low,\n  Medium,\n  High,\n}\n\nenum StringLevel {\n  Low = 'LOW',\n  Medium = 'MEDIUM',\n  High = 'HIGH',\n}\n\nconsole.log(NumericLevel.Low, NumericLevel.Medium, NumericLevel.High);\nconsole.log(StringLevel.Low, StringLevel.Medium, StringLevel.High);\n\nfunction describe(level: StringLevel): string {\n  return `Level is ${level}`;\n}\n\nconsole.log(describe(StringLevel.High));",
    starterCode: "enum Status {\n  Pending = 'PENDING',\n  Active = 'ACTIVE',\n  Done = 'DONE',\n}\n\nfunction describeStatus(status: Status): string {\n  return `Current status: ${status}`;\n}\n\nconsole.log(describeStatus(Status.Active));",
  },
]
