import type { CodingLesson } from '../languages'

export const typescript: CodingLesson[] = [
  {
    slug: 'introduction',
    title: 'Introduction to TypeScript',
    summary: 'JavaScript with types attached',
    explanation: [
      'TypeScript is JavaScript with an extra layer: type annotations. You write let age: number = 12 to tell the tool what kind of value a variable should hold.',
      'These annotations help catch mistakes — like adding a number to a string by accident — before your code ever runs.',
      'Behind the scenes, the types are checked and then stripped away, leaving plain JavaScript that runs in the browser.',
    ],
    example: "let age: number = 12;\nlet name: string = 'Aria';\nlet isStudent: boolean = true;\n\nconsole.log(`${name} is ${age} years old`);\nconsole.log(`Student? ${isStudent}`);\n\nfunction add(a: number, b: number): number {\n  return a + b;\n}\n\nconsole.log(add(2, 3));",
    starterCode: "let city: string = 'Kathmandu';\nlet temperature: number = 22;\n\nconsole.log(`${city} is ${temperature} degrees today`);",
  },
  {
    slug: 'interfaces-and-types',
    title: 'Interfaces & Type Aliases',
    summary: 'Describing the shape of objects',
    explanation: [
      'An interface describes the shape an object should have: interface User { name: string; age: number }. Any object matching that shape can be treated as a User.',
      'A type alias does something similar with the type keyword: type Point = { x: number; y: number }, and can also name unions and other type combinations.',
      'You can use an interface or type alias as the type of a function parameter, so the function only accepts objects with the right shape.',
    ],
    example: "interface User {\n  name: string;\n  age: number;\n}\n\ntype Point = { x: number; y: number };\n\nfunction describeUser(user: User): string {\n  return `${user.name} is ${user.age} years old`;\n}\n\nfunction distanceFromOrigin(point: Point): number {\n  return Math.sqrt(point.x * point.x + point.y * point.y);\n}\n\nconst aria: User = { name: 'Aria', age: 12 };\nconsole.log(describeUser(aria));\nconsole.log(distanceFromOrigin({ x: 3, y: 4 }));",
    starterCode: "interface Book {\n  title: string;\n  pages: number;\n}\n\nfunction summarize(book: Book): string {\n  return `${book.title} has ${book.pages} pages`;\n}\n\nconst myBook: Book = { title: 'TypeScript Basics', pages: 120 };\nconsole.log(summarize(myBook));",
  },
  {
    slug: 'functions-and-generics',
    title: 'Functions & Generics',
    summary: 'Typing parameters, return values, and writing reusable generic functions',
    explanation: [
      'You can annotate a function\'s parameters and return type, like function greet(name: string): string, so TypeScript checks both what goes in and what comes out.',
      'Generics let a function work with many types while staying type-safe: function identity<T>(x: T): T returns whatever type it was given.',
      'The placeholder T stands in for "whatever type the caller uses" — TypeScript fills it in automatically based on the argument.',
    ],
    example: "function greet(name: string): string {\n  return `Hello, ${name}!`;\n}\n\nfunction identity<T>(value: T): T {\n  return value;\n}\n\nfunction firstItem<T>(items: T[]): T {\n  return items[0];\n}\n\nconsole.log(greet('World'));\nconsole.log(identity(42));\nconsole.log(identity('TypeScript'));\nconsole.log(firstItem([10, 20, 30]));\nconsole.log(firstItem(['a', 'b', 'c']));",
    starterCode: "function double(n: number): number {\n  return n * 2;\n}\n\nfunction wrapInArray<T>(value: T): T[] {\n  return [value];\n}\n\nconsole.log(double(21));\nconsole.log(wrapInArray('hello'));\nconsole.log(wrapInArray(99));",
  },
  {
    slug: 'classes',
    title: 'Classes',
    summary: 'Typed classes with constructor properties and access modifiers',
    explanation: [
      'A TypeScript class can declare the types of its properties, and the constructor can use access modifiers like public and private to both declare and assign properties in one step.',
      'public members can be used from outside the class, while private members can only be accessed from within the class itself.',
      'Methods on a class can have typed parameters and return types just like regular functions.',
    ],
    example: "class Animal {\n  public name: string;\n  private sound: string;\n\n  constructor(name: string, sound: string) {\n    this.name = name;\n    this.sound = sound;\n  }\n\n  speak(): string {\n    return `${this.name} says ${this.sound}`;\n  }\n}\n\nclass Dog extends Animal {\n  constructor(name: string) {\n    super(name, 'Woof');\n  }\n\n  fetch(): string {\n    return `${this.name} fetches the ball!`;\n  }\n}\n\nconst rex = new Dog('Rex');\nconsole.log(rex.speak());\nconsole.log(rex.fetch());",
    starterCode: "class Counter {\n  private count: number = 0;\n\n  increment(): number {\n    this.count += 1;\n    return this.count;\n  }\n\n  getCount(): number {\n    return this.count;\n  }\n}\n\nconst counter = new Counter();\ncounter.increment();\ncounter.increment();\nconsole.log(counter.getCount());",
  },
  {
    slug: 'enums-and-unions',
    title: 'Enums & Union Types',
    summary: 'Naming sets of related values and combining types with |',
    explanation: [
      'An enum gives friendly names to a fixed set of related values, like enum Direction { Up, Down, Left, Right }, which you can refer to as Direction.Up.',
      'A union type allows a value to be one of several specific types or literal values, like type Status = "idle" | "loading" | "done".',
      'Union types are great for representing a small, known set of possible states a value can be in.',
    ],
    example: "enum Direction {\n  Up,\n  Down,\n  Left,\n  Right,\n}\n\ntype Status = 'idle' | 'loading' | 'done';\n\nfunction describeStatus(status: Status): string {\n  if (status === 'idle') return 'Waiting to start';\n  if (status === 'loading') return 'Working on it...';\n  return 'All finished!';\n}\n\nconsole.log(Direction.Up);\nconsole.log(Direction.Left);\nconsole.log(describeStatus('loading'));\nconsole.log(describeStatus('done'));",
    starterCode: "enum Level {\n  Beginner,\n  Intermediate,\n  Advanced,\n}\n\ntype Theme = 'light' | 'dark';\n\nfunction describeTheme(theme: Theme): string {\n  return theme === 'light' ? 'Bright mode' : 'Dark mode';\n}\n\nconsole.log(Level.Intermediate);\nconsole.log(describeTheme('dark'));",
  },
  {
    slug: 'arrays-and-tuples',
    title: 'Arrays & Tuples',
    summary: 'Typed lists and fixed-shape grouped values',
    explanation: [
      'A typed array says what kind of values it holds, like number[] for a list of numbers or string[] for a list of strings.',
      'A tuple is a fixed-length array where each position has its own type, like [string, number] for a name paired with an age.',
      'Tuples are useful when you want to group a small, fixed set of related values that each have a different meaning.',
    ],
    example: "const scores: number[] = [70, 85, 92, 60];\nconst names: string[] = ['Aria', 'Kiran', 'Maya'];\n\nconst passing = scores.filter(s => s >= 70);\nconsole.log(passing);\n\nconst person: [string, number] = ['Aria', 12];\nconst [personName, personAge] = person;\nconsole.log(`${personName} is ${personAge}`);\n\nconst entries: [string, number][] = [\n  ['Aria', 92],\n  ['Kiran', 78],\n];\nfor (const [entryName, entryScore] of entries) {\n  console.log(`${entryName}: ${entryScore}`);\n}",
    starterCode: "const temperatures: number[] = [18, 22, 25, 19];\nconst average = temperatures.reduce((sum, t) => sum + t, 0) / temperatures.length;\nconsole.log(average);\n\nconst point: [number, number] = [3, 4];\nconsole.log(`x=${point[0]}, y=${point[1]}`);",
  },
  {
    slug: 'type-narrowing',
    title: 'Type Narrowing',
    summary: 'Checking a value\'s type before using it',
    explanation: [
      'When a value could be more than one type, like string | number, TypeScript lets you narrow it down using checks such as typeof.',
      'Inside an if (typeof value === "string") block, TypeScript knows the value is a string and lets you safely use string methods on it.',
      'instanceof works the same way for classes, letting you check whether an object is an instance of a particular class before treating it as one.',
    ],
    example: "type Input = string | number;\n\nfunction describe(value: Input): string {\n  if (typeof value === 'string') {\n    return `Text of length ${value.length}: \"${value}\"`;\n  }\n  return `Number doubled: ${value * 2}`;\n}\n\nclass Cat {\n  meow(): string { return 'Meow!'; }\n}\n\nclass Robot {\n  beep(): string { return 'Beep!'; }\n}\n\nfunction makeSound(thing: Cat | Robot): string {\n  if (thing instanceof Cat) {\n    return thing.meow();\n  }\n  return thing.beep();\n}\n\nconsole.log(describe('hello'));\nconsole.log(describe(21));\nconsole.log(makeSound(new Cat()));\nconsole.log(makeSound(new Robot()));",
    starterCode: "type Id = string | number;\n\nfunction formatId(id: Id): string {\n  if (typeof id === 'number') {\n    return `#${id.toFixed(0)}`;\n  }\n  return id.toUpperCase();\n}\n\nconsole.log(formatId(42));\nconsole.log(formatId('abc123'));",
  },
  {
    slug: 'optional-readonly-and-defaults',
    title: 'Optional, Readonly & Default Values',
    summary: 'Marking properties optional, locking them with readonly, and giving parameters defaults',
    explanation: [
      "Adding a ? after a property name, like nickname?: string, marks it optional — objects can omit it, and TypeScript knows it might be undefined when you read it.",
      "The readonly modifier locks a property after it's first set: readonly id: number means id can be assigned in the constructor but never reassigned afterward.",
      "Function parameters can have default values, like function greet(name: string = 'friend'), which TypeScript uses to also infer the parameter's type and let callers omit it.",
    ],
    example: "interface Profile {\n  readonly id: number;\n  name: string;\n  nickname?: string;\n}\n\nfunction describe(profile: Profile): string {\n  const label = profile.nickname ?? profile.name;\n  return `#${profile.id}: ${label}`;\n}\n\nfunction greet(name: string = 'friend'): string {\n  return `Hello, ${name}!`;\n}\n\nconst profile: Profile = { id: 1, name: 'Aria' };\nconsole.log(describe(profile));\nconsole.log(greet());\nconsole.log(greet('Kiran'));",
    starterCode: "interface Task {\n  readonly id: number;\n  title: string;\n  notes?: string;\n}\n\nfunction summarize(task: Task, fallback: string = 'No notes'): string {\n  return `${task.title}: ${task.notes ?? fallback}`;\n}\n\nconst task: Task = { id: 1, title: 'Learn TypeScript' };\nconsole.log(summarize(task));",
  },
  {
    slug: 'discriminated-unions',
    title: 'Discriminated Unions',
    summary: "Modeling a value that can be one of several known shapes",
    explanation: [
      "A discriminated union is a union of object types that all share one common, literal-valued property — often called kind or type — which identifies which shape you're looking at.",
      "Inside a switch on that shared property, TypeScript narrows the type in each case, so you can safely access the fields that only exist on that particular shape.",
      "This pattern is a clean alternative to a pile of optional properties, because it makes impossible combinations (like a circle with a width) impossible to construct.",
    ],
    example: "type Shape =\n  | { kind: 'circle'; radius: number }\n  | { kind: 'rectangle'; width: number; height: number };\n\nfunction area(shape: Shape): number {\n  switch (shape.kind) {\n    case 'circle':\n      return Math.PI * shape.radius * shape.radius;\n    case 'rectangle':\n      return shape.width * shape.height;\n  }\n}\n\nconst circle: Shape = { kind: 'circle', radius: 3 };\nconst rectangle: Shape = { kind: 'rectangle', width: 4, height: 5 };\n\nconsole.log(area(circle).toFixed(2));\nconsole.log(area(rectangle));",
    starterCode: "type Notification =\n  | { kind: 'message'; text: string }\n  | { kind: 'like'; from: string };\n\nfunction describe(note: Notification): string {\n  if (note.kind === 'message') {\n    return `New message: ${note.text}`;\n  }\n  return `${note.from} liked your post`;\n}\n\nconsole.log(describe({ kind: 'message', text: 'Hey there!' }));\nconsole.log(describe({ kind: 'like', from: 'Kiran' }));",
  },
  {
    slug: 'utility-types',
    title: 'Utility Types',
    summary: 'Building new types out of existing ones with Partial, Pick, Omit & Record',
    explanation: [
      "Partial<T> makes every property of T optional — useful for an 'update' function that only changes a few fields at a time.",
      'Pick<T, Keys> builds a smaller type with only the listed properties, while Omit<T, Keys> does the opposite, keeping everything except the listed ones.',
      'Record<Keys, ValueType> describes an object whose keys all come from a fixed list and whose values share one type, like a lookup table.',
    ],
    example: "interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nfunction updateUser(user: User, changes: Partial<User>): User {\n  return { ...user, ...changes };\n}\n\ntype UserPreview = Pick<User, 'id' | 'name'>;\n\nconst scoresByName: Record<string, number> = {\n  Aria: 95,\n  Kiran: 88,\n};\n\nconst user: User = { id: 1, name: 'Aria', email: 'aria@example.com' };\nconst updated = updateUser(user, { name: 'Aria Sharma' });\nconst preview: UserPreview = { id: updated.id, name: updated.name };\n\nconsole.log(updated);\nconsole.log(preview);\nconsole.log(scoresByName['Aria']);",
    starterCode: "interface Settings {\n  theme: string;\n  fontSize: number;\n  notifications: boolean;\n}\n\nfunction applyChanges(settings: Settings, changes: Partial<Settings>): Settings {\n  return { ...settings, ...changes };\n}\n\nconst defaults: Settings = { theme: 'light', fontSize: 14, notifications: true };\nconst next = applyChanges(defaults, { theme: 'dark' });\nconsole.log(next);",
  },
  {
    slug: 'async-await',
    title: 'Async/Await with Types',
    summary: 'Typing values that arrive later, through a Promise',
    explanation: [
      'Promise<T> describes a value of type T that will be available later — an async function that returns a number is typed as Promise<number>, even though you write return n; inside it.',
      'Inside an async function, await pauses until a Promise settles and hands you back the resolved value already unwrapped from its Promise<T> wrapper.',
      'Wrapping an await in try/catch lets you handle a rejected Promise the same way you would handle any other thrown error.',
    ],
    example: "function wait<T>(ms: number, value: T): Promise<T> {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function loadScore(name: string): Promise<number> {\n  const score = await wait(10, 92);\n  return score;\n}\n\nasync function run(): Promise<void> {\n  try {\n    console.log('loading...');\n    const score = await loadScore('Aria');\n    console.log(`Score: ${score}`);\n  } catch (error) {\n    console.log('Something went wrong');\n  }\n}\n\nrun();",
    starterCode: "function wait<T>(ms: number, value: T): Promise<T> {\n  return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\nasync function loadMessage(): Promise<string> {\n  const message = await wait(10, 'Loaded!');\n  return message;\n}\n\nasync function run(): Promise<void> {\n  const message = await loadMessage();\n  console.log(message);\n}\n\nrun();",
  },
  {
    slug: 'generic-constraints-and-keyof',
    title: 'Generic Constraints & keyof',
    summary: "Limiting what a generic can be, and looking up a type's own property names",
    explanation: [
      "Writing <T extends SomeType> constrains a generic so T must have at least the shape of SomeType — inside the function, TypeScript then knows it's safe to use those properties.",
      'keyof T produces a union of all the property names of T as string literal types, so keyof User might be \'id\' | \'name\' | \'email\'.',
      "Combining both, function getProp<T, K extends keyof T>(obj: T, key: K): T[K] can fetch any property by name while keeping the exact return type — try passing a key that doesn't exist and TypeScript will catch it.",
    ],
    example: "interface HasLength {\n  length: number;\n}\n\nfunction longest<T extends HasLength>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}\n\nfunction getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst user = { id: 1, name: 'Aria', email: 'aria@example.com' };\n\nconsole.log(longest('hello', 'hi'));\nconsole.log(longest([1, 2, 3], [1]));\nconsole.log(getProp(user, 'name'));\nconsole.log(getProp(user, 'id'));",
    starterCode: "interface HasId {\n  id: number;\n}\n\nfunction printId<T extends HasId>(item: T): void {\n  console.log(`ID: ${item.id}`);\n}\n\nfunction getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst book = { id: 7, title: 'TypeScript Basics' };\nprintId(book);\nconsole.log(getProp(book, 'title'));",
  },
  {
    slug: 'type-assertions-and-unknown',
    title: 'Type Assertions & unknown',
    summary: 'Telling TypeScript "trust me" — carefully — and handling values of unknown shape',
    explanation: [
      'unknown is a safe alternative to any: a value typed unknown could be anything, so TypeScript forces you to check or narrow it before using it for anything specific.',
      "A type assertion, written value as Type, tells the compiler 'I know more than you do here' without changing the value at runtime — use it sparingly, since an incorrect assertion will compile but fail later.",
      "The safest way to go from unknown to a specific type is still a runtime check, like typeof or an 'in' check, rather than reaching straight for as.",
    ],
    example: "function parseConfig(json: string): unknown {\n  return JSON.parse(json);\n}\n\nfunction readPort(config: unknown): number {\n  if (typeof config === 'object' && config !== null && 'port' in config) {\n    return (config as { port: number }).port;\n  }\n  return 3000;\n}\n\nconst raw = parseConfig('{\"port\": 8080}');\nconsole.log(readPort(raw));\nconsole.log(readPort({}));\n\nconst value: unknown = 'hello';\nconst length = (value as string).length;\nconsole.log(length);",
    starterCode: "function readName(data: unknown): string {\n  if (typeof data === 'object' && data !== null && 'name' in data) {\n    return (data as { name: string }).name;\n  }\n  return 'Unknown';\n}\n\nconsole.log(readName({ name: 'Aria' }));\nconsole.log(readName(42));",
  },
  {
    slug: 'error-handling',
    title: 'Typed Error Handling',
    summary: 'Catching errors safely and creating your own Error subclasses',
    explanation: [
      'In a catch block, the caught value is typed unknown (not Error), because JavaScript lets you throw anything — checking instanceof Error before reading .message keeps things type-safe.',
      "You can define your own error type by extending Error: class ValidationError extends Error { ... } — instances still work with instanceof and carry a normal .message.",
      "Typing a function's possible failure explicitly, even just through a custom error class, helps callers know what to expect and catch precisely.",
    ],
    example: "class ValidationError extends Error {\n  constructor(message: string) {\n    super(message);\n    this.name = 'ValidationError';\n  }\n}\n\nfunction parsePositive(value: string): number {\n  const n = Number(value);\n  if (Number.isNaN(n) || n <= 0) {\n    throw new ValidationError(`\"${value}\" is not a positive number`);\n  }\n  return n;\n}\n\nfor (const input of ['12', 'abc', '-5']) {\n  try {\n    console.log(`Parsed: ${parsePositive(input)}`);\n  } catch (error) {\n    if (error instanceof ValidationError) {\n      console.log(`Validation failed: ${error.message}`);\n    } else if (error instanceof Error) {\n      console.log(`Unexpected error: ${error.message}`);\n    }\n  }\n}",
    starterCode: "class NotFoundError extends Error {\n  constructor(message: string) {\n    super(message);\n    this.name = 'NotFoundError';\n  }\n}\n\nfunction findUser(id: number): string {\n  if (id !== 1) {\n    throw new NotFoundError(`User ${id} was not found`);\n  }\n  return 'Aria';\n}\n\ntry {\n  console.log(findUser(2));\n} catch (error) {\n  if (error instanceof NotFoundError) {\n    console.log(`Error: ${error.message}`);\n  }\n}",
  },
]
