import type { CTQuestion } from '../types'

export const abstraction: CTQuestion[] = [
  {
    slug: 'abstraction-1',
    question: 'What does "abstraction" mean in computational thinking?',
    options: [
      'Breaking a big problem into smaller pieces',
      'Hiding unnecessary details and focusing only on what matters for the problem',
      'Writing code as fast as possible',
      'Finding patterns between similar problems',
    ],
    correctIndex: 1,
    explanation: 'Abstraction means stripping away details that are not important right now so you can focus on the parts of a problem that actually matter.',
  },
  {
    slug: 'abstraction-2',
    question: 'A subway map is a great example of abstraction because it:',
    options: [
      'Shows every building and street in the city',
      'Is drawn to an exact geographic scale',
      'Leaves out real geography and shows only stations and how lines connect',
      'Includes traffic and weather information',
    ],
    correctIndex: 2,
    explanation: 'Subway maps abstract away real-world distances and curves, keeping only the information riders need: stations, lines, and connections.',
  },
  {
    slug: 'abstraction-3',
    question: 'A TV remote control is an example of abstraction because the user:',
    options: [
      'Has to understand the circuits inside the TV',
      'Can press "volume up" without knowing how the speaker electronics work',
      'Must rewire the TV to change channels',
      'Needs to write code to turn the TV on',
    ],
    correctIndex: 1,
    explanation: 'The remote hides the complicated electronics and just gives the user simple buttons, which is exactly what abstraction does.',
  },
  {
    slug: 'abstraction-4',
    question: 'In programming, why are functions considered a form of abstraction?',
    options: [
      'They make programs run faster automatically',
      'They let you use a named block of code without needing to know how it works inside',
      'They always require fewer lines of code than loops',
      'They prevent any bugs from occurring',
    ],
    correctIndex: 1,
    explanation: 'A function lets you call something like calculateTotal() and get a result without having to think about every line of logic hidden inside it.',
  },
  {
    slug: 'abstraction-5',
    question: 'A recipe card that says "saute the onions until golden" is using abstraction because it:',
    options: [
      'Lists the exact chemical reactions happening in the pan',
      'Explains the history of the dish',
      'Leaves out low-level details like exact stirring motions and heat transfer physics',
      'Tells you the price of each ingredient',
    ],
    correctIndex: 2,
    explanation: 'The recipe gives just enough detail for a cook to follow the step, hiding unnecessary physical and chemical detail that is not needed to cook the dish.',
  },
  {
    slug: 'abstraction-6',
    question: 'What is the main difference between abstraction and decomposition?',
    options: [
      'They are exactly the same thing with different names',
      'Decomposition breaks a problem into smaller parts, while abstraction hides irrelevant detail to focus on what matters',
      'Abstraction is only used in math, decomposition only in computer science',
      'Decomposition is for hardware and abstraction is for software',
    ],
    correctIndex: 1,
    explanation: 'Decomposition is about splitting a problem into manageable pieces, whereas abstraction is about ignoring details that are not relevant to the task at hand.',
  },
  {
    slug: 'abstraction-7',
    question: 'A variable like "score" in a program is a form of abstraction because it:',
    options: [
      'Represents a value without requiring the programmer to track its exact memory address',
      'Always stores the number zero',
      'Must be renamed every time the program runs',
      'Is only used for decoration in the code',
    ],
    correctIndex: 0,
    explanation: 'Variables abstract away the low-level details of memory storage, letting programmers think in terms of meaningful names like "score" instead of memory addresses.',
  },
  {
    slug: 'abstraction-8',
    question: 'When you use a weather app, abstraction lets you see "Rainy, 18°C" without needing to know:',
    options: [
      'What city you are in',
      'The complex satellite data and atmospheric models behind the forecast',
      'What day it is',
      'Whether the app has a search bar',
    ],
    correctIndex: 1,
    explanation: 'The app abstracts away enormous amounts of scientific data and calculations, presenting only the simple result you actually need.',
  },
  {
    slug: 'abstraction-9',
    question: 'An API (Application Programming Interface) is useful because it:',
    options: [
      'Forces every programmer to use the same programming language',
      'Lets other programs use a service through a simple set of commands, without seeing the internal code',
      'Deletes unnecessary files from your computer',
      'Is only used for designing video games',
    ],
    correctIndex: 1,
    explanation: 'An API exposes a clean, simple way to interact with a system while hiding the complicated implementation behind it, which is abstraction in action.',
  },
  {
    slug: 'abstraction-10',
    question: 'Why is choosing the right "level of abstraction" sometimes tricky?',
    options: [
      'Because there is only ever one correct level for any problem',
      'Because too much detail can overwhelm you, but too little detail can hide information you actually need',
      'Because computers cannot handle abstract ideas',
      'Because abstraction always makes problems harder to solve',
    ],
    correctIndex: 1,
    explanation: 'Good abstraction is a balance: include enough detail to solve the problem correctly, but not so much that it becomes confusing or overwhelming.',
  },
  {
    slug: 'abstraction-11',
    question: 'A car dashboard shows speed, fuel level, and warning lights instead of raw engine sensor data because:',
    options: [
      'Raw sensor data would be more useful to drivers',
      'The dashboard abstracts complex sensor readings into simple information drivers can act on',
      'Cars do not actually have sensors',
      'It is cheaper to build dashboards with no information at all',
    ],
    correctIndex: 1,
    explanation: 'The dashboard hides the complex sensor and engine data, presenting only the simplified information a driver needs to make decisions.',
  },
  {
    slug: 'abstraction-12',
    question: 'A programmer is designing a function called isOldEnoughToVote(age). What makes this a good abstraction?',
    options: [
      'It exposes the exact line of code that compares numbers so other programmers must rewrite it',
      'It hides the comparison logic inside and lets other code simply ask a clear yes-or-no question',
      'It requires the caller to know the legal voting age in every country',
      'It only works for one specific age value',
    ],
    correctIndex: 1,
    explanation: 'A well-named function abstracts the comparison logic away, so anyone using it only needs to understand the question being asked, not how it is answered.',
  },
  {
    slug: 'abstraction-13',
    question: 'Which scenario shows abstraction at the WRONG level, making a tool less useful?',
    options: [
      'A subway map showing only stations and connecting lines',
      'A thermostat showing the room temperature instead of raw circuit voltages',
      'A children\'s coding app that requires kids to write machine code to move a sprite',
      'A calculator app that shows the result of a calculation, not the chip-level math',
    ],
    correctIndex: 2,
    explanation: 'Forcing beginners to use machine code is the wrong level of abstraction for the audience, since it exposes far more low-level detail than they need to learn the concept.',
  },
  {
    slug: 'abstraction-14',
    question: 'A simple weather icon (a sun, a cloud, a raindrop) is a useful abstraction because it:',
    options: [
      'Shows exact humidity and wind speed numbers',
      'Replaces complicated atmospheric data with one quick visual that tells you what to expect',
      'Requires a meteorology degree to understand',
      'Changes depending on which phone you own',
    ],
    correctIndex: 1,
    explanation: 'The icon abstracts away complex weather data into a single, instantly recognizable symbol so anyone can glance at it and know what to expect.',
  },
  {
    slug: 'abstraction-15',
    question: 'In a video game, the minimap in the corner of the screen is an abstraction of the world because it:',
    options: [
      'Shows every blade of grass and texture in full detail',
      'Replaces the detailed 3D world with simple dots and shapes representing players and locations',
      'Is exactly the same view as the main game screen',
      'Only appears after you finish the game',
    ],
    correctIndex: 1,
    explanation: 'A minimap strips away visual detail like textures and lighting, keeping only the positions and layout information a player needs to navigate.',
  },
  {
    slug: 'abstraction-16',
    question: 'A school timetable that just says "Math, Room 204, 9:00" is an abstraction because it:',
    options: [
      'Includes the full lesson plan and every topic the teacher will cover',
      'Leaves out details like the teacher\'s lesson notes and seating chart, showing only what a student needs to find the right class',
      'Lists the GPS coordinates of the school',
      'Shows the grades of every student in the class',
    ],
    correctIndex: 1,
    explanation: 'The timetable hides unnecessary planning details and shows only the essential information a student needs: subject, location, and time.',
  },
  {
    slug: 'abstraction-17',
    question: 'A musical chord symbol like "Cmaj7" written above sheet music is an abstraction because it:',
    options: [
      'Tells a musician which notes to play without spelling out the exact finger positions or sound waves involved',
      'Forces every musician to play the chord identically with no creativity',
      'Describes the history of the song',
      'Is only understood by professional composers',
    ],
    correctIndex: 0,
    explanation: 'The chord symbol abstracts away the physics of sound and exact playing technique, giving musicians a compact label that represents a set of notes.',
  },
  {
    slug: 'abstraction-18',
    question: 'The button panel inside an elevator (just floor numbers and "door open/close") is an abstraction because it hides:',
    options: [
      'The names of the people riding the elevator',
      'The motors, cables, and control systems that actually move the elevator car',
      'The number of floors in the building',
      'The weight limit of the elevator',
    ],
    correctIndex: 1,
    explanation: 'Riders only need to choose a floor and open or close the doors; the panel abstracts away the mechanical and electrical systems doing the real work.',
  },
  {
    slug: 'abstraction-19',
    question: 'Why is naming a variable totalPrice better abstraction than naming it x?',
    options: [
      'totalPrice runs faster in the computer than x',
      'totalPrice communicates the meaning of the value, letting other programmers understand its purpose without studying every line of code',
      'x is not allowed in most programming languages',
      'Variable names have no effect on understanding code',
    ],
    correctIndex: 1,
    explanation: 'A meaningful name is a small act of abstraction: it lets readers grasp what a value represents without tracing through the whole program.',
  },
  {
    slug: 'abstraction-20',
    question: 'In object-oriented programming, a class called Car that has methods like drive() and brake() is a good abstraction because it:',
    options: [
      'Models the real-world idea of a car using relevant actions, while hiding the internal code that calculates engine forces and physics',
      'Requires the programmer to simulate every nut and bolt of a real car',
      'Can only be used to build racing games',
      'Stores the exact weight of every car ever manufactured',
    ],
    correctIndex: 0,
    explanation: 'The Car class abstracts a real-world object into relevant behaviors like driving and braking, hiding the messy physics calculations happening underneath.',
  },
  {
    slug: 'abstraction-21',
    question: 'A ride-hailing app shows "Driver arriving in 4 minutes" instead of raw GPS coordinates and traffic algorithm output. This is abstraction because it:',
    options: [
      'Removes all useful information from the user',
      'Translates complex location and traffic data into one simple, actionable piece of information',
      'Means the app does not use GPS at all',
      'Only works when there is no traffic',
    ],
    correctIndex: 1,
    explanation: 'The app abstracts away complicated calculations and raw data, surfacing just the one number a rider actually cares about.',
  },
  {
    slug: 'abstraction-22',
    question: 'Two different city maps of the same city, one for drivers (roads and parking) and one for hikers (trails and parks), show that abstraction:',
    options: [
      'Always produces exactly one correct version of any map',
      'Can highlight different relevant details depending on who is using it and why',
      'Is impossible when two maps describe the same place',
      'Means one of the maps must be factually wrong',
    ],
    correctIndex: 1,
    explanation: 'The same real-world place can be abstracted in different valid ways, since what counts as "relevant detail" depends on the needs of the person using it.',
  },
  {
    slug: 'abstraction-23',
    question: 'A flight-booking website lets you pick seats by clicking icons on a simple cabin diagram instead of reading raw seating database records. This is abstraction because it:',
    options: [
      'Hides irrelevant database structure and lets the user interact with a simple, visual representation instead',
      'Means the airline has no database at all',
      'Forces users to know SQL to book a flight',
      'Shows the exact server code that handles bookings',
    ],
    correctIndex: 0,
    explanation: 'The seat diagram is a friendly abstraction layer over a complex backend database, so travelers can make choices without touching the raw data.',
  },
  {
    slug: 'abstraction-24',
    question: 'A new app feature hides ALL settings from users, even ones they frequently need to change, leaving only an on/off switch. What problem does this show?',
    options: [
      'This is a perfect abstraction with no downsides',
      'Over-abstraction: too much useful detail and control has been hidden, frustrating users who need it',
      'Abstraction is impossible in app design',
      'The app now requires more programming knowledge to use',
    ],
    correctIndex: 1,
    explanation: 'Abstraction can go too far: if you hide details that people genuinely need to do their task, the abstraction becomes a hindrance rather than a help.',
  },
  {
    slug: 'abstraction-25',
    question: 'A thermostat app that just says "Comfortable" instead of showing the temperature in degrees is comparing two abstractions of the same system. Which statement is true?',
    options: [
      'Both abstractions are equally good in every situation, regardless of what the user needs to do',
      'The simpler "Comfortable" label might hide information a user needs, like exact degrees, if they want precise control',
      'Showing the temperature in degrees is never useful',
      'There can only ever be one valid abstraction for a thermostat',
    ],
    correctIndex: 1,
    explanation: 'Different abstractions trade off detail differently; a vague label is friendlier for quick glances, but a precise reading is better when exact control matters, showing there is no single "best" abstraction for every case.',
  },
  {
    slug: 'abstraction-26',
    question: 'A GPS navigation app tells you to "turn left in 200 meters" instead of describing every curve, pothole, and lane marking on the road. This is abstraction because it:',
    options: [
      'Removes the need for roads to exist',
      'Reduces the overwhelming complexity of the real road network into the one instruction a driver needs right now',
      'Means the app does not actually know the road layout',
      'Only works on highways, never in cities',
    ],
    correctIndex: 1,
    explanation: 'The app processes huge amounts of map data behind the scenes but abstracts it into a single simple instruction, hiding details the driver does not need at that moment.',
  },
  {
    slug: 'abstraction-27',
    question: 'A thermostat lets you set a target temperature without knowing how the refrigerant cycle, compressor, or coils work. Why is this a good abstraction for most homeowners?',
    options: [
      'Because refrigeration is not actually complicated',
      'Because the homeowner only needs to control comfort, not perform the mechanical engineering of cooling',
      'Because thermostats never break and never need understanding',
      'Because showing refrigerant pressure would make the thermostat cheaper to build',
    ],
    correctIndex: 1,
    explanation: 'The thermostat hides the complex refrigeration engineering and exposes only the one control that matters to a homeowner: the desired temperature.',
  },
  {
    slug: 'abstraction-28',
    question: 'A piano key produces a musical note when pressed. The player does not need to think about sound-wave frequencies or string vibration physics. This is an example of abstraction because:',
    options: [
      'Pianos do not actually rely on physics',
      'The instrument design hides the physics of sound, letting the player focus on rhythm and melody instead',
      'Sound waves are simulated by software inside the piano',
      'Only electric pianos involve any physics at all',
    ],
    correctIndex: 1,
    explanation: 'The mechanical design of the piano abstracts away wave physics, so a musician can focus on playing music rather than calculating frequencies.',
  },
  {
    slug: 'abstraction-29',
    question: 'An IKEA-style furniture instruction manual uses simple line drawings of a person and arrows instead of detailed engineering blueprints. Why is this the right abstraction level for its audience?',
    options: [
      'Because customers building furniture need clear, simple steps, not manufacturing tolerances or material stress calculations',
      'Because blueprints are illegal to include in manuals',
      'Because line drawings are always more accurate than blueprints',
      'Because customers are expected to redesign the furniture themselves',
    ],
    correctIndex: 0,
    explanation: 'The manual is aimed at someone assembling furniture at home, so it abstracts away manufacturing-level detail and keeps only the steps needed to put the pieces together.',
  },
  {
    slug: 'abstraction-30',
    question: 'In a spreadsheet, typing =SUM(A1:A10) into a cell is a form of abstraction because it:',
    options: [
      'Requires you to manually add each of the ten numbers yourself first',
      'Lets you get a total without writing out the individual addition steps the spreadsheet performs internally',
      'Deletes the data in cells A1 through A10',
      'Only works if the numbers are typed in a specific font',
    ],
    correctIndex: 1,
    explanation: 'The SUM formula hides the step-by-step addition happening behind the scenes, letting you simply ask for a total by name.',
  },
  {
    slug: 'abstraction-31',
    question: 'Think about three people looking at the same car: a driver, a mechanic, and an engineer who designed the engine. Why do they each use a different level of abstraction?',
    options: [
      'Because only one of them is allowed to be correct about how the car works',
      'Because each person needs a different amount of detail to do their own job well',
      'Because cars work differently depending on who is looking at them',
      'Because mechanics and engineers are not allowed to drive',
    ],
    correctIndex: 1,
    explanation: 'The driver just needs to know how to operate the controls, the mechanic needs to understand repairable systems, and the engineer needs deep technical detail — each is a valid abstraction for a different purpose.',
  },
  {
    slug: 'abstraction-32',
    question: 'A library catalog search shows a book\'s title, author, and shelf location, but not the exact words printed on every page. This is useful abstraction because it:',
    options: [
      'Gives searchers exactly the information they need to find a book, without overwhelming them with its full contents',
      'Means the library does not actually own the full books',
      'Prevents anyone from ever reading the book',
      'Is only useful for picture books',
    ],
    correctIndex: 0,
    explanation: 'The catalog abstracts each book down to a few key facts that help someone locate it, hiding the irrelevant detail of the book\'s full text.',
  },
  {
    slug: 'abstraction-33',
    question: 'A children\'s science book describes the water cycle as "water goes up as vapor, forms clouds, then falls as rain" without mentioning molecular bonds or atmospheric pressure equations. Is this good abstraction?',
    options: [
      'No, because every science explanation must include every known scientific detail',
      'Yes, because it matches the right level of detail for a young audience trying to grasp the basic idea',
      'No, because children cannot understand any science at all',
      'Yes, but only if pictures are added to the explanation',
    ],
    correctIndex: 1,
    explanation: 'Good abstraction means matching the detail to the audience; a simplified water cycle is appropriate for young learners, even though scientists use far more detailed models.',
  },
  {
    slug: 'abstraction-34',
    question: 'A delivery tracking page shows "Out for delivery" instead of the truck\'s exact GPS coordinates and the driver\'s turn-by-turn route. A user who wants to know precisely when to expect the package might find this abstraction:',
    options: [
      'Perfectly detailed for every possible need',
      'Too vague for their specific goal, even though it is fine for casual checking',
      'Impossible to create with current technology',
      'The only way delivery tracking could ever work',
    ],
    correctIndex: 1,
    explanation: 'This shows that choosing an abstraction level always involves a trade-off: a status label is convenient for quick checks but may hide detail that some users genuinely need.',
  },
  {
    slug: 'abstraction-35',
    question: 'A programming language\'s "print" or "console.log" command lets you display text on screen without writing the low-level instructions that control pixels and the display hardware. This is abstraction because it:',
    options: [
      'Means the computer screen does not use pixels',
      'Provides a simple command that hides the complex hardware-level work of rendering characters on a screen',
      'Only works on very old computers',
      'Requires you to know the screen\'s resolution in advance',
    ],
    correctIndex: 1,
    explanation: 'A print command abstracts away the complicated process of turning text into pixels on a display, letting programmers focus on what to show rather than how it appears.',
  },
  {
    slug: 'abstraction-36',
    question: 'A flowchart used to plan a school project shows boxes like "Research topic" and "Write draft" without detailing every sentence that will be written. Why is this an appropriate abstraction for planning?',
    options: [
      'Because flowcharts can never include any detail at all',
      'Because at the planning stage, the overall steps matter more than the exact wording, which can be figured out later',
      'Because writing drafts is not actually part of doing a project',
      'Because flowcharts are only used by professional software engineers',
    ],
    correctIndex: 1,
    explanation: 'During planning, a useful abstraction focuses on the major steps needed, deliberately leaving out fine details that are better decided once you reach that step.',
  },
  {
    slug: 'abstraction-37',
    question: 'A teacher explaining computers to two different classes uses "a computer is like a very fast, very obedient helper that follows instructions" for young students, but discusses CPUs, RAM, and binary logic for older students. What does this show about abstraction?',
    options: [
      'That one of the two explanations must be factually wrong',
      'That the same underlying topic can be abstracted at different levels depending on what the audience is ready to understand',
      'That computers work differently depending on who is being taught',
      'That only the technical explanation can ever be considered correct',
    ],
    correctIndex: 1,
    explanation: 'Both explanations are valid abstractions of the same truth, chosen at a level of detail that matches what each audience can usefully absorb.',
  },
  {
    slug: 'abstraction-38',
    question: 'A new employee is learning a company\'s software and is given a one-page "quick start" guide instead of the full 200-page technical manual on day one. Which best explains why this is good abstraction?',
    options: [
      'The full manual contains incorrect information that the quick guide fixes',
      'The quick guide matches what a beginner needs right now, while the full manual remains available for when deeper detail is actually required',
      'New employees are not allowed to read the full manual ever',
      'Quick guides always replace manuals permanently in every situation',
    ],
    correctIndex: 1,
    explanation: 'Good abstraction adapts to the task and the learner\'s current needs; a simple starting guide avoids overwhelming a beginner while the detailed manual stays available for later, more advanced needs.',
  },
]
