import type { CTQuestion } from '../types'

export const abstraction: CTQuestion[] = [
  {
    slug: 'abstraction-1',
    question: 'What does "abstraction" mean in computational thinking?',
    options: [
      'Breaking a big problem into smaller pieces',
      'Hiding unnecessary details and focusing only on what matters for the problem',
      'Writing code as fast as possible',
      'Finding patterns between similar problems',
    ],
    correctIndex: 1,
    explanation: 'Abstraction means stripping away details that are not important right now so you can focus on the parts of a problem that actually matter.',
  },
  {
    slug: 'abstraction-2',
    question: 'A subway map is a great example of abstraction because it:',
    options: [
      'Shows every building and street in the city',
      'Is drawn to an exact geographic scale',
      'Leaves out real geography and shows only stations and how lines connect',
      'Includes traffic and weather information',
    ],
    correctIndex: 2,
    explanation: 'Subway maps abstract away real-world distances and curves, keeping only the information riders need: stations, lines, and connections.',
  },
  {
    slug: 'abstraction-3',
    question: 'A TV remote control is an example of abstraction because the user:',
    options: [
      'Has to understand the circuits inside the TV',
      'Can press "volume up" without knowing how the speaker electronics work',
      'Must rewire the TV to change channels',
      'Needs to write code to turn the TV on',
    ],
    correctIndex: 1,
    explanation: 'The remote hides the complicated electronics and just gives the user simple buttons, which is exactly what abstraction does.',
  },
  {
    slug: 'abstraction-4',
    question: 'In programming, why are functions considered a form of abstraction?',
    options: [
      'They make programs run faster automatically',
      'They let you use a named block of code without needing to know how it works inside',
      'They always require fewer lines of code than loops',
      'They prevent any bugs from occurring',
    ],
    correctIndex: 1,
    explanation: 'A function lets you call something like calculateTotal() and get a result without having to think about every line of logic hidden inside it.',
  },
  {
    slug: 'abstraction-5',
    question: 'A recipe card that says "saute the onions until golden" is using abstraction because it:',
    options: [
      'Lists the exact chemical reactions happening in the pan',
      'Explains the history of the dish',
      'Leaves out low-level details like exact stirring motions and heat transfer physics',
      'Tells you the price of each ingredient',
    ],
    correctIndex: 2,
    explanation: 'The recipe gives just enough detail for a cook to follow the step, hiding unnecessary physical and chemical detail that is not needed to cook the dish.',
  },
  {
    slug: 'abstraction-6',
    question: 'What is the main difference between abstraction and decomposition?',
    options: [
      'They are exactly the same thing with different names',
      'Decomposition breaks a problem into smaller parts, while abstraction hides irrelevant detail to focus on what matters',
      'Abstraction is only used in math, decomposition only in computer science',
      'Decomposition is for hardware and abstraction is for software',
    ],
    correctIndex: 1,
    explanation: 'Decomposition is about splitting a problem into manageable pieces, whereas abstraction is about ignoring details that are not relevant to the task at hand.',
  },
  {
    slug: 'abstraction-7',
    question: 'A variable like "score" in a program is a form of abstraction because it:',
    options: [
      'Represents a value without requiring the programmer to track its exact memory address',
      'Always stores the number zero',
      'Must be renamed every time the program runs',
      'Is only used for decoration in the code',
    ],
    correctIndex: 0,
    explanation: 'Variables abstract away the low-level details of memory storage, letting programmers think in terms of meaningful names like "score" instead of memory addresses.',
  },
  {
    slug: 'abstraction-8',
    question: 'When you use a weather app, abstraction lets you see "Rainy, 18°C" without needing to know:',
    options: [
      'What city you are in',
      'The complex satellite data and atmospheric models behind the forecast',
      'What day it is',
      'Whether the app has a search bar',
    ],
    correctIndex: 1,
    explanation: 'The app abstracts away enormous amounts of scientific data and calculations, presenting only the simple result you actually need.',
  },
  {
    slug: 'abstraction-9',
    question: 'An API (Application Programming Interface) is useful because it:',
    options: [
      'Forces every programmer to use the same programming language',
      'Lets other programs use a service through a simple set of commands, without seeing the internal code',
      'Deletes unnecessary files from your computer',
      'Is only used for designing video games',
    ],
    correctIndex: 1,
    explanation: 'An API exposes a clean, simple way to interact with a system while hiding the complicated implementation behind it, which is abstraction in action.',
  },
  {
    slug: 'abstraction-10',
    question: 'Why is choosing the right "level of abstraction" sometimes tricky?',
    options: [
      'Because there is only ever one correct level for any problem',
      'Because too much detail can overwhelm you, but too little detail can hide information you actually need',
      'Because computers cannot handle abstract ideas',
      'Because abstraction always makes problems harder to solve',
    ],
    correctIndex: 1,
    explanation: 'Good abstraction is a balance: include enough detail to solve the problem correctly, but not so much that it becomes confusing or overwhelming.',
  },
  {
    slug: 'abstraction-11',
    question: 'A car dashboard shows speed, fuel level, and warning lights instead of raw engine sensor data because:',
    options: [
      'Raw sensor data would be more useful to drivers',
      'The dashboard abstracts complex sensor readings into simple information drivers can act on',
      'Cars do not actually have sensors',
      'It is cheaper to build dashboards with no information at all',
    ],
    correctIndex: 1,
    explanation: 'The dashboard hides the complex sensor and engine data, presenting only the simplified information a driver needs to make decisions.',
  },
  {
    slug: 'abstraction-12',
    question: 'A programmer is designing a function called isOldEnoughToVote(age). What makes this a good abstraction?',
    options: [
      'It exposes the exact line of code that compares numbers so other programmers must rewrite it',
      'It hides the comparison logic inside and lets other code simply ask a clear yes-or-no question',
      'It requires the caller to know the legal voting age in every country',
      'It only works for one specific age value',
    ],
    correctIndex: 1,
    explanation: 'A well-named function abstracts the comparison logic away, so anyone using it only needs to understand the question being asked, not how it is answered.',
  },
  {
    slug: 'abstraction-13',
    question: 'Which scenario shows abstraction at the WRONG level, making a tool less useful?',
    options: [
      'A subway map showing only stations and connecting lines',
      'A thermostat showing the room temperature instead of raw circuit voltages',
      'A children\'s coding app that requires kids to write machine code to move a sprite',
      'A calculator app that shows the result of a calculation, not the chip-level math',
    ],
    correctIndex: 2,
    explanation: 'Forcing beginners to use machine code is the wrong level of abstraction for the audience, since it exposes far more low-level detail than they need to learn the concept.',
  },
]
