import type { CTQuestion } from '../types'

export const abstraction: CTQuestion[] = [
  {
    slug: 'abstraction-1',
    question: 'What does "abstraction" mean in computational thinking?',
    options: [
      'Breaking a big problem into smaller pieces',
      'Hiding unnecessary details and focusing only on what matters for the problem',
      'Writing code as fast as possible',
      'Finding patterns between similar problems',
    ],
    correctIndex: 1,
    explanation: 'Abstraction means stripping away details that are not important right now so you can focus on the parts of a problem that actually matter.',
  },
  {
    slug: 'abstraction-2',
    question: 'A subway map is a great example of abstraction because it:',
    options: [
      'Shows every building and street in the city',
      'Is drawn to an exact geographic scale',
      'Leaves out real geography and shows only stations and how lines connect',
      'Includes traffic and weather information',
    ],
    correctIndex: 2,
    explanation: 'Subway maps abstract away real-world distances and curves, keeping only the information riders need: stations, lines, and connections.',
  },
  {
    slug: 'abstraction-3',
    question: 'A TV remote control is an example of abstraction because the user:',
    options: [
      'Has to understand the circuits inside the TV',
      'Can press "volume up" without knowing how the speaker electronics work',
      'Must rewire the TV to change channels',
      'Needs to write code to turn the TV on',
    ],
    correctIndex: 1,
    explanation: 'The remote hides the complicated electronics and just gives the user simple buttons, which is exactly what abstraction does.',
  },
  {
    slug: 'abstraction-4',
    question: 'In programming, why are functions considered a form of abstraction?',
    options: [
      'They make programs run faster automatically',
      'They let you use a named block of code without needing to know how it works inside',
      'They always require fewer lines of code than loops',
      'They prevent any bugs from occurring',
    ],
    correctIndex: 1,
    explanation: 'A function lets you call something like calculateTotal() and get a result without having to think about every line of logic hidden inside it.',
  },
  {
    slug: 'abstraction-5',
    question: 'A recipe card that says "saute the onions until golden" is using abstraction because it:',
    options: [
      'Lists the exact chemical reactions happening in the pan',
      'Explains the history of the dish',
      'Leaves out low-level details like exact stirring motions and heat transfer physics',
      'Tells you the price of each ingredient',
    ],
    correctIndex: 2,
    explanation: 'The recipe gives just enough detail for a cook to follow the step, hiding unnecessary physical and chemical detail that is not needed to cook the dish.',
  },
  {
    slug: 'abstraction-6',
    question: 'What is the main difference between abstraction and decomposition?',
    options: [
      'They are exactly the same thing with different names',
      'Decomposition breaks a problem into smaller parts, while abstraction hides irrelevant detail to focus on what matters',
      'Abstraction is only used in math, decomposition only in computer science',
      'Decomposition is for hardware and abstraction is for software',
    ],
    correctIndex: 1,
    explanation: 'Decomposition is about splitting a problem into manageable pieces, whereas abstraction is about ignoring details that are not relevant to the task at hand.',
  },
  {
    slug: 'abstraction-7',
    question: 'A variable like "score" in a program is a form of abstraction because it:',
    options: [
      'Represents a value without requiring the programmer to track its exact memory address',
      'Always stores the number zero',
      'Must be renamed every time the program runs',
      'Is only used for decoration in the code',
    ],
    correctIndex: 0,
    explanation: 'Variables abstract away the low-level details of memory storage, letting programmers think in terms of meaningful names like "score" instead of memory addresses.',
  },
  {
    slug: 'abstraction-8',
    question: 'When you use a weather app, abstraction lets you see "Rainy, 18°C" without needing to know:',
    options: [
      'What city you are in',
      'The complex satellite data and atmospheric models behind the forecast',
      'What day it is',
      'Whether the app has a search bar',
    ],
    correctIndex: 1,
    explanation: 'The app abstracts away enormous amounts of scientific data and calculations, presenting only the simple result you actually need.',
  },
  {
    slug: 'abstraction-9',
    question: 'An API (Application Programming Interface) is useful because it:',
    options: [
      'Forces every programmer to use the same programming language',
      'Lets other programs use a service through a simple set of commands, without seeing the internal code',
      'Deletes unnecessary files from your computer',
      'Is only used for designing video games',
    ],
    correctIndex: 1,
    explanation: 'An API exposes a clean, simple way to interact with a system while hiding the complicated implementation behind it, which is abstraction in action.',
  },
  {
    slug: 'abstraction-10',
    question: 'Why is choosing the right "level of abstraction" sometimes tricky?',
    options: [
      'Because there is only ever one correct level for any problem',
      'Because too much detail can overwhelm you, but too little detail can hide information you actually need',
      'Because computers cannot handle abstract ideas',
      'Because abstraction always makes problems harder to solve',
    ],
    correctIndex: 1,
    explanation: 'Good abstraction is a balance: include enough detail to solve the problem correctly, but not so much that it becomes confusing or overwhelming.',
  },
  {
    slug: 'abstraction-11',
    question: 'A car dashboard shows speed, fuel level, and warning lights instead of raw engine sensor data because:',
    options: [
      'Raw sensor data would be more useful to drivers',
      'The dashboard abstracts complex sensor readings into simple information drivers can act on',
      'Cars do not actually have sensors',
      'It is cheaper to build dashboards with no information at all',
    ],
    correctIndex: 1,
    explanation: 'The dashboard hides the complex sensor and engine data, presenting only the simplified information a driver needs to make decisions.',
  },
  {
    slug: 'abstraction-12',
    question: 'A programmer is designing a function called isOldEnoughToVote(age). What makes this a good abstraction?',
    options: [
      'It exposes the exact line of code that compares numbers so other programmers must rewrite it',
      'It hides the comparison logic inside and lets other code simply ask a clear yes-or-no question',
      'It requires the caller to know the legal voting age in every country',
      'It only works for one specific age value',
    ],
    correctIndex: 1,
    explanation: 'A well-named function abstracts the comparison logic away, so anyone using it only needs to understand the question being asked, not how it is answered.',
  },
  {
    slug: 'abstraction-13',
    question: 'Which scenario shows abstraction at the WRONG level, making a tool less useful?',
    options: [
      'A subway map showing only stations and connecting lines',
      'A thermostat showing the room temperature instead of raw circuit voltages',
      'A children\'s coding app that requires kids to write machine code to move a sprite',
      'A calculator app that shows the result of a calculation, not the chip-level math',
    ],
    correctIndex: 2,
    explanation: 'Forcing beginners to use machine code is the wrong level of abstraction for the audience, since it exposes far more low-level detail than they need to learn the concept.',
  },
  {
    slug: 'abstraction-14',
    question: 'A simple weather icon (a sun, a cloud, a raindrop) is a useful abstraction because it:',
    options: [
      'Shows exact humidity and wind speed numbers',
      'Replaces complicated atmospheric data with one quick visual that tells you what to expect',
      'Requires a meteorology degree to understand',
      'Changes depending on which phone you own',
    ],
    correctIndex: 1,
    explanation: 'The icon abstracts away complex weather data into a single, instantly recognizable symbol so anyone can glance at it and know what to expect.',
  },
  {
    slug: 'abstraction-15',
    question: 'In a video game, the minimap in the corner of the screen is an abstraction of the world because it:',
    options: [
      'Shows every blade of grass and texture in full detail',
      'Replaces the detailed 3D world with simple dots and shapes representing players and locations',
      'Is exactly the same view as the main game screen',
      'Only appears after you finish the game',
    ],
    correctIndex: 1,
    explanation: 'A minimap strips away visual detail like textures and lighting, keeping only the positions and layout information a player needs to navigate.',
  },
  {
    slug: 'abstraction-16',
    question: 'A school timetable that just says "Math, Room 204, 9:00" is an abstraction because it:',
    options: [
      'Includes the full lesson plan and every topic the teacher will cover',
      'Leaves out details like the teacher\'s lesson notes and seating chart, showing only what a student needs to find the right class',
      'Lists the GPS coordinates of the school',
      'Shows the grades of every student in the class',
    ],
    correctIndex: 1,
    explanation: 'The timetable hides unnecessary planning details and shows only the essential information a student needs: subject, location, and time.',
  },
  {
    slug: 'abstraction-17',
    question: 'A musical chord symbol like "Cmaj7" written above sheet music is an abstraction because it:',
    options: [
      'Tells a musician which notes to play without spelling out the exact finger positions or sound waves involved',
      'Forces every musician to play the chord identically with no creativity',
      'Describes the history of the song',
      'Is only understood by professional composers',
    ],
    correctIndex: 0,
    explanation: 'The chord symbol abstracts away the physics of sound and exact playing technique, giving musicians a compact label that represents a set of notes.',
  },
  {
    slug: 'abstraction-18',
    question: 'The button panel inside an elevator (just floor numbers and "door open/close") is an abstraction because it hides:',
    options: [
      'The names of the people riding the elevator',
      'The motors, cables, and control systems that actually move the elevator car',
      'The number of floors in the building',
      'The weight limit of the elevator',
    ],
    correctIndex: 1,
    explanation: 'Riders only need to choose a floor and open or close the doors; the panel abstracts away the mechanical and electrical systems doing the real work.',
  },
  {
    slug: 'abstraction-19',
    question: 'Why is naming a variable totalPrice better abstraction than naming it x?',
    options: [
      'totalPrice runs faster in the computer than x',
      'totalPrice communicates the meaning of the value, letting other programmers understand its purpose without studying every line of code',
      'x is not allowed in most programming languages',
      'Variable names have no effect on understanding code',
    ],
    correctIndex: 1,
    explanation: 'A meaningful name is a small act of abstraction: it lets readers grasp what a value represents without tracing through the whole program.',
  },
  {
    slug: 'abstraction-20',
    question: 'In object-oriented programming, a class called Car that has methods like drive() and brake() is a good abstraction because it:',
    options: [
      'Models the real-world idea of a car using relevant actions, while hiding the internal code that calculates engine forces and physics',
      'Requires the programmer to simulate every nut and bolt of a real car',
      'Can only be used to build racing games',
      'Stores the exact weight of every car ever manufactured',
    ],
    correctIndex: 0,
    explanation: 'The Car class abstracts a real-world object into relevant behaviors like driving and braking, hiding the messy physics calculations happening underneath.',
  },
  {
    slug: 'abstraction-21',
    question: 'A ride-hailing app shows "Driver arriving in 4 minutes" instead of raw GPS coordinates and traffic algorithm output. This is abstraction because it:',
    options: [
      'Removes all useful information from the user',
      'Translates complex location and traffic data into one simple, actionable piece of information',
      'Means the app does not use GPS at all',
      'Only works when there is no traffic',
    ],
    correctIndex: 1,
    explanation: 'The app abstracts away complicated calculations and raw data, surfacing just the one number a rider actually cares about.',
  },
  {
    slug: 'abstraction-22',
    question: 'Two different city maps of the same city, one for drivers (roads and parking) and one for hikers (trails and parks), show that abstraction:',
    options: [
      'Always produces exactly one correct version of any map',
      'Can highlight different relevant details depending on who is using it and why',
      'Is impossible when two maps describe the same place',
      'Means one of the maps must be factually wrong',
    ],
    correctIndex: 1,
    explanation: 'The same real-world place can be abstracted in different valid ways, since what counts as "relevant detail" depends on the needs of the person using it.',
  },
  {
    slug: 'abstraction-23',
    question: 'A flight-booking website lets you pick seats by clicking icons on a simple cabin diagram instead of reading raw seating database records. This is abstraction because it:',
    options: [
      'Hides irrelevant database structure and lets the user interact with a simple, visual representation instead',
      'Means the airline has no database at all',
      'Forces users to know SQL to book a flight',
      'Shows the exact server code that handles bookings',
    ],
    correctIndex: 0,
    explanation: 'The seat diagram is a friendly abstraction layer over a complex backend database, so travelers can make choices without touching the raw data.',
  },
  {
    slug: 'abstraction-24',
    question: 'A new app feature hides ALL settings from users, even ones they frequently need to change, leaving only an on/off switch. What problem does this show?',
    options: [
      'This is a perfect abstraction with no downsides',
      'Over-abstraction: too much useful detail and control has been hidden, frustrating users who need it',
      'Abstraction is impossible in app design',
      'The app now requires more programming knowledge to use',
    ],
    correctIndex: 1,
    explanation: 'Abstraction can go too far: if you hide details that people genuinely need to do their task, the abstraction becomes a hindrance rather than a help.',
  },
  {
    slug: 'abstraction-25',
    question: 'A thermostat app that just says "Comfortable" instead of showing the temperature in degrees is comparing two abstractions of the same system. Which statement is true?',
    options: [
      'Both abstractions are equally good in every situation, regardless of what the user needs to do',
      'The simpler "Comfortable" label might hide information a user needs, like exact degrees, if they want precise control',
      'Showing the temperature in degrees is never useful',
      'There can only ever be one valid abstraction for a thermostat',
    ],
    correctIndex: 1,
    explanation: 'Different abstractions trade off detail differently; a vague label is friendlier for quick glances, but a precise reading is better when exact control matters, showing there is no single "best" abstraction for every case.',
  },
]
