import type { CTQuestion } from '../types'

export const debugging: CTQuestion[] = [
  {
    slug: 'debugging-1',
    question: 'What does "debugging" mean in computational thinking?',
    options: [
      'Writing a plan or set of instructions for the first time',
      'Finding and fixing errors in a set of instructions or a plan',
      'Making a plan run as fast as possible',
      'Copying a successful plan from someone else',
    ],
    correctIndex: 1,
    explanation: 'Debugging is the process of locating why something is not working as expected and correcting it, not writing or speeding up the plan.',
  },
  {
    slug: 'debugging-2',
    question: 'You are debugging a multi-step plan that fails at some point. What is usually the most effective first move?',
    options: [
      'Rewrite the entire plan from scratch',
      'Trace through the steps one at a time to see where the result first goes wrong',
      'Assume the last step is broken and only fix that one',
      'Ignore the failure and run the plan again hoping it works',
    ],
    correctIndex: 1,
    explanation: 'Tracing step by step lets you pinpoint exactly where the actual outcome diverges from the expected one, which narrows down the source of the error.',
  },
  {
    slug: 'debugging-3',
    question: 'What does it mean to "isolate" a problem when debugging?',
    options: [
      'Deleting every step except the very first one',
      'Separating out the smallest part of the plan that still produces the error, to test it on its own',
      'Working on the problem completely alone, without help',
      'Running the whole plan many times in a row',
    ],
    correctIndex: 1,
    explanation: 'Isolating means narrowing the system down to the smallest piece that still reproduces the bug, which makes the cause much easier to identify.',
  },
  {
    slug: 'debugging-4',
    question: 'A recipe says: "Step 1: Preheat the oven. Step 2: Bake the cake for 30 minutes. Step 3: Mix the batter. Step 4: Pour batter into a pan." Why will this recipe fail?',
    options: [
      'The oven temperature is too high',
      'The steps are in the wrong order — baking happens before the batter is even made',
      'There are too many steps',
      'The recipe is missing an ingredient',
    ],
    correctIndex: 1,
    explanation: 'Step 2 tells you to bake before the batter is mixed and poured in Steps 3 and 4, so the order of steps is the logical error, not the ingredients or temperature.',
  },
  {
    slug: 'debugging-5',
    question: 'What is "rubber duck debugging"?',
    options: [
      'Explaining your plan out loud, step by step, to a person or object, to spot mistakes as you talk through them',
      'Testing a plan with rubber duck toys as test data',
      'A method where you let someone else fix all your mistakes',
      'A way to make plans more colorful and fun',
    ],
    correctIndex: 0,
    explanation: 'Rubber duck debugging gets its name from explaining your logic out loud to an inanimate object (like a rubber duck); the act of explaining often reveals the flaw yourself.',
  },
  {
    slug: 'debugging-6',
    question: 'Why is "checking your assumptions" an important debugging strategy?',
    options: [
      'Assumptions are always correct, so checking them wastes time',
      'A plan can look logically correct but fail because one of your starting assumptions about the situation was wrong',
      'It lets you skip testing the plan entirely',
      'It only matters for very long plans',
    ],
    correctIndex: 1,
    explanation: 'Many bugs happen not because the steps are wrong, but because a hidden assumption (like "the input will always be a positive number") turns out to be false.',
  },
  {
    slug: 'debugging-7',
    question: 'Why is it usually a bad debugging strategy to immediately blame the computer (or tool) for a wrong result?',
    options: [
      'Computers are never the cause of any problem',
      'It is rude to blame machines',
      'Most errors come from mistakes in the instructions or logic given to the computer, so blaming the tool first skips the real investigation',
      'Blaming the computer makes the bug fix itself',
    ],
    correctIndex: 2,
    explanation: 'Computers and tools follow instructions exactly as given, so an unexpected result is far more often caused by a flaw in the plan or logic than by the tool itself, and assuming otherwise stops you from looking in the right place.',
  },
  {
    slug: 'debugging-8',
    question: 'Why is it valuable to find a way to make a bug happen the same way every time (reproduce it consistently)?',
    options: [
      'It makes the bug look more impressive to others',
      'It guarantees the bug will never happen again on its own',
      'A consistently reproducible bug lets you test one change at a time and clearly see whether that change actually fixed the problem',
      'It is not valuable; random, unpredictable bugs are easier to fix',
    ],
    correctIndex: 2,
    explanation: 'If you can trigger a bug reliably, you can experiment with fixes and know for certain whether each change worked, instead of guessing based on a problem that only sometimes appears.',
  },
  {
    slug: 'debugging-9',
    question: 'A set of directions says: "1. Walk to the corner. 2. Turn left at the bakery. 3. Walk straight for 2 blocks. 4. Turn left at the bakery again. 5. The library is on your right." A friend follows these directions but ends up back near the bakery instead of at the library. What is the most likely logical error?',
    options: [
      'There is no bakery in the area',
      'Step 4 repeats the same landmark as step 2, which likely should reference a different, later landmark instead',
      'The friend cannot walk in a straight line',
      'The library does not exist',
    ],
    correctIndex: 1,
    explanation: 'Reusing "turn left at the bakery" in step 4 sends the walker back toward the same spot as step 2, suggesting that step should have referenced a new landmark further along the route.',
  },
  {
    slug: 'debugging-10',
    question: 'When debugging, why is it useful to compare what you expected to happen with what actually happened at each step?',
    options: [
      'It is not useful; only the final result matters',
      'Comparing expected versus actual results at each step shows you exactly where the plan first starts behaving incorrectly',
      'It only works if the plan has just one step',
      'It guarantees you will never make another mistake',
    ],
    correctIndex: 1,
    explanation: 'Checking expectations against actual outcomes at each step reveals the precise point where things diverge, which is usually where the bug lives.',
  },
  {
    slug: 'debugging-11',
    question: 'A plan for watering a garden says: "If it rained today, water the plants. If it did not rain today, do not water the plants." The gardener finds the plants are dying from too little water during a dry month. What is the actual logical flaw?',
    options: [
      'The condition is backwards — plants need water when it has NOT rained, not when it has',
      'The plan has too many steps',
      'The plants were planted in the wrong season',
      'There is no flaw; the gardener is not following the plan',
    ],
    correctIndex: 0,
    explanation: 'The rule waters plants only on rainy days and skips watering on dry days, which is the opposite of what plants actually need, so the condition itself is logically reversed.',
  },
  {
    slug: 'debugging-12',
    question: 'You changed one step in a plan to try to fix a bug, and the bug seems gone. What should you do before concluding the fix worked?',
    options: [
      'Immediately move on to a completely different part of the plan',
      'Delete your notes about the original bug',
      'Test the plan multiple times, including the situation that originally caused the bug, to make sure it is truly fixed and nothing else broke',
      'Assume it is fixed because it worked once',
    ],
    correctIndex: 2,
    explanation: 'A single successful run is not strong evidence; retesting the original failing scenario (and other cases) confirms the fix is real and did not introduce new problems.',
  },
  {
    slug: 'debugging-13',
    question: 'Why is breaking a large, confusing plan into smaller sections a helpful debugging approach?',
    options: [
      'Smaller sections are easier to check individually, making it simpler to find which exact section contains the error',
      'It makes the plan longer and harder to follow',
      'It guarantees the plan has no bugs',
      'It removes the need to test the plan at all',
    ],
    correctIndex: 0,
    explanation: 'Breaking a plan into smaller, testable sections lets you check each piece on its own, so the section causing the error becomes much easier to identify.',
  },
]
