import type { CTQuestion } from '../types'

export const debugging: CTQuestion[] = [
  {
    slug: 'debugging-1',
    question: 'What does "debugging" mean in computational thinking?',
    options: [
      'Writing a plan or set of instructions for the first time',
      'Finding and fixing errors in a set of instructions or a plan',
      'Making a plan run as fast as possible',
      'Copying a successful plan from someone else',
    ],
    correctIndex: 1,
    explanation: 'Debugging is the process of locating why something is not working as expected and correcting it, not writing or speeding up the plan.',
  },
  {
    slug: 'debugging-2',
    question: 'You are debugging a multi-step plan that fails at some point. What is usually the most effective first move?',
    options: [
      'Rewrite the entire plan from scratch',
      'Trace through the steps one at a time to see where the result first goes wrong',
      'Assume the last step is broken and only fix that one',
      'Ignore the failure and run the plan again hoping it works',
    ],
    correctIndex: 1,
    explanation: 'Tracing step by step lets you pinpoint exactly where the actual outcome diverges from the expected one, which narrows down the source of the error.',
  },
  {
    slug: 'debugging-3',
    question: 'What does it mean to "isolate" a problem when debugging?',
    options: [
      'Deleting every step except the very first one',
      'Separating out the smallest part of the plan that still produces the error, to test it on its own',
      'Working on the problem completely alone, without help',
      'Running the whole plan many times in a row',
    ],
    correctIndex: 1,
    explanation: 'Isolating means narrowing the system down to the smallest piece that still reproduces the bug, which makes the cause much easier to identify.',
  },
  {
    slug: 'debugging-4',
    question: 'A recipe says: "Step 1: Preheat the oven. Step 2: Bake the cake for 30 minutes. Step 3: Mix the batter. Step 4: Pour batter into a pan." Why will this recipe fail?',
    options: [
      'The oven temperature is too high',
      'The steps are in the wrong order — baking happens before the batter is even made',
      'There are too many steps',
      'The recipe is missing an ingredient',
    ],
    correctIndex: 1,
    explanation: 'Step 2 tells you to bake before the batter is mixed and poured in Steps 3 and 4, so the order of steps is the logical error, not the ingredients or temperature.',
  },
  {
    slug: 'debugging-5',
    question: 'What is "rubber duck debugging"?',
    options: [
      'Explaining your plan out loud, step by step, to a person or object, to spot mistakes as you talk through them',
      'Testing a plan with rubber duck toys as test data',
      'A method where you let someone else fix all your mistakes',
      'A way to make plans more colorful and fun',
    ],
    correctIndex: 0,
    explanation: 'Rubber duck debugging gets its name from explaining your logic out loud to an inanimate object (like a rubber duck); the act of explaining often reveals the flaw yourself.',
  },
  {
    slug: 'debugging-6',
    question: 'Why is "checking your assumptions" an important debugging strategy?',
    options: [
      'Assumptions are always correct, so checking them wastes time',
      'A plan can look logically correct but fail because one of your starting assumptions about the situation was wrong',
      'It lets you skip testing the plan entirely',
      'It only matters for very long plans',
    ],
    correctIndex: 1,
    explanation: 'Many bugs happen not because the steps are wrong, but because a hidden assumption (like "the input will always be a positive number") turns out to be false.',
  },
  {
    slug: 'debugging-7',
    question: 'Why is it usually a bad debugging strategy to immediately blame the computer (or tool) for a wrong result?',
    options: [
      'Computers are never the cause of any problem',
      'It is rude to blame machines',
      'Most errors come from mistakes in the instructions or logic given to the computer, so blaming the tool first skips the real investigation',
      'Blaming the computer makes the bug fix itself',
    ],
    correctIndex: 2,
    explanation: 'Computers and tools follow instructions exactly as given, so an unexpected result is far more often caused by a flaw in the plan or logic than by the tool itself, and assuming otherwise stops you from looking in the right place.',
  },
  {
    slug: 'debugging-8',
    question: 'Why is it valuable to find a way to make a bug happen the same way every time (reproduce it consistently)?',
    options: [
      'It makes the bug look more impressive to others',
      'It guarantees the bug will never happen again on its own',
      'A consistently reproducible bug lets you test one change at a time and clearly see whether that change actually fixed the problem',
      'It is not valuable; random, unpredictable bugs are easier to fix',
    ],
    correctIndex: 2,
    explanation: 'If you can trigger a bug reliably, you can experiment with fixes and know for certain whether each change worked, instead of guessing based on a problem that only sometimes appears.',
  },
  {
    slug: 'debugging-9',
    question: 'A set of directions says: "1. Walk to the corner. 2. Turn left at the bakery. 3. Walk straight for 2 blocks. 4. Turn left at the bakery again. 5. The library is on your right." A friend follows these directions but ends up back near the bakery instead of at the library. What is the most likely logical error?',
    options: [
      'There is no bakery in the area',
      'Step 4 repeats the same landmark as step 2, which likely should reference a different, later landmark instead',
      'The friend cannot walk in a straight line',
      'The library does not exist',
    ],
    correctIndex: 1,
    explanation: 'Reusing "turn left at the bakery" in step 4 sends the walker back toward the same spot as step 2, suggesting that step should have referenced a new landmark further along the route.',
  },
  {
    slug: 'debugging-10',
    question: 'When debugging, why is it useful to compare what you expected to happen with what actually happened at each step?',
    options: [
      'It is not useful; only the final result matters',
      'Comparing expected versus actual results at each step shows you exactly where the plan first starts behaving incorrectly',
      'It only works if the plan has just one step',
      'It guarantees you will never make another mistake',
    ],
    correctIndex: 1,
    explanation: 'Checking expectations against actual outcomes at each step reveals the precise point where things diverge, which is usually where the bug lives.',
  },
  {
    slug: 'debugging-11',
    question: 'A plan for watering a garden says: "If it rained today, water the plants. If it did not rain today, do not water the plants." The gardener finds the plants are dying from too little water during a dry month. What is the actual logical flaw?',
    options: [
      'The condition is backwards — plants need water when it has NOT rained, not when it has',
      'The plan has too many steps',
      'The plants were planted in the wrong season',
      'There is no flaw; the gardener is not following the plan',
    ],
    correctIndex: 0,
    explanation: 'The rule waters plants only on rainy days and skips watering on dry days, which is the opposite of what plants actually need, so the condition itself is logically reversed.',
  },
  {
    slug: 'debugging-12',
    question: 'You changed one step in a plan to try to fix a bug, and the bug seems gone. What should you do before concluding the fix worked?',
    options: [
      'Immediately move on to a completely different part of the plan',
      'Delete your notes about the original bug',
      'Test the plan multiple times, including the situation that originally caused the bug, to make sure it is truly fixed and nothing else broke',
      'Assume it is fixed because it worked once',
    ],
    correctIndex: 2,
    explanation: 'A single successful run is not strong evidence; retesting the original failing scenario (and other cases) confirms the fix is real and did not introduce new problems.',
  },
  {
    slug: 'debugging-13',
    question: 'Why is breaking a large, confusing plan into smaller sections a helpful debugging approach?',
    options: [
      'Smaller sections are easier to check individually, making it simpler to find which exact section contains the error',
      'It makes the plan longer and harder to follow',
      'It guarantees the plan has no bugs',
      'It removes the need to test the plan at all',
    ],
    correctIndex: 0,
    explanation: 'Breaking a plan into smaller, testable sections lets you check each piece on its own, so the section causing the error becomes much easier to identify.',
  },
  {
    slug: 'debugging-14',
    question: 'What is "binary search debugging"?',
    options: [
      'Checking every single step from the very first one to the very last one, in order, one by one',
      'Repeatedly testing the midpoint of the remaining suspect steps to cut the number of possible error locations in half each time',
      'Guessing randomly which step is broken until you happen to find it',
      'Rewriting every step using only the numbers 0 and 1',
    ],
    correctIndex: 1,
    explanation: 'Binary search debugging means testing roughly the middle of the steps you still suspect, then throwing away the half that worked correctly, which finds the faulty step much faster than checking one by one.',
  },
  {
    slug: 'debugging-15',
    question: 'A weekly chore chart says: "Monday: laundry. Tuesday: laundry. Wednesday: dishes. Thursday: dishes. Friday: dishes. Saturday: dishes. Sunday: dishes." The family runs out of clean clothes by Thursday. What is the actual problem with the plan?',
    options: [
      'Laundry is scheduled far too rarely compared to how often clothes are needed, while dishes are scheduled far more often than needed',
      'There are too many days in the week',
      'Dishes should never be washed on weekends',
      'The chart is missing a day for vacuuming',
    ],
    correctIndex: 0,
    explanation: 'The chart allocates only 2 days to laundry but 5 days to dishes, an imbalance that does not match how often each chore actually needs doing, which is why laundry runs out first.',
  },
  {
    slug: 'debugging-16',
    question: 'Why should you change only ONE thing at a time when trying to fix a bug, instead of changing several steps at once?',
    options: [
      'Changing many things at once is always faster and just as reliable',
      'If multiple things change together and the result improves, you cannot tell which change actually fixed the problem',
      'Plans are only allowed to be edited one time total',
      'It has no real benefit; it is just a tradition',
    ],
    correctIndex: 1,
    explanation: 'When several changes happen at once, you lose the ability to tell which one mattered, so you might keep a useless change or miss what truly fixed the bug.',
  },
  {
    slug: 'debugging-17',
    question: 'What is the difference between a "symptom" and a "root cause" when debugging?',
    options: [
      'A symptom is the visible problem you notice, while the root cause is the deeper reason that actually produced that problem',
      'They mean exactly the same thing and can be used interchangeably',
      'A root cause only exists in medicine, not in plans or instructions',
      'A symptom is always more important to fix than the root cause',
    ],
    correctIndex: 0,
    explanation: 'The symptom is what you observe going wrong (like "the cake is burnt"), while the root cause is the underlying reason (like "the oven temperature step was wrong"); fixing only the symptom often leaves the real problem in place.',
  },
  {
    slug: 'debugging-18',
    question: 'A student keeps closing and reopening an app every time it freezes, and says the app is "fixed" because it works again afterward. Why might this not actually be a fix?',
    options: [
      'Restarting always permanently fixes every problem',
      'The freeze may still happen again later, because restarting only clears the immediate symptom without addressing whatever inside the app actually caused the freeze',
      'Apps can never freeze more than once',
      'It is impossible to know if an app is really fixed',
    ],
    correctIndex: 1,
    explanation: 'Restarting can temporarily clear a frozen state without ever finding or correcting the underlying issue, so the same root cause is likely to trigger the freeze again later.',
  },
  {
    slug: 'debugging-19',
    question: 'Why is it important to test "edge cases" — like an empty list, a zero, or the very first or last item — when debugging a plan?',
    options: [
      'Edge cases never actually occur in real use, so testing them is optional',
      'Plans often work fine on typical, middle-of-the-road inputs but break on unusual extreme inputs that were not considered when the plan was designed',
      'Testing edge cases is only necessary for plans involving numbers',
      'Edge cases are easier to test than normal cases, so they should be tested first and nothing else',
    ],
    correctIndex: 1,
    explanation: 'Many bugs hide in unusual situations the planner did not think about, like an empty input or a boundary value, so deliberately testing those cases catches errors that normal testing would miss.',
  },
  {
    slug: 'debugging-20',
    question: 'A vending machine error message reads: "Error: insufficient balance for selected item." A student says, "I don\'t understand all of this, so I\'ll just ignore it and keep pressing buttons." What is the better debugging approach?',
    options: [
      'Read the message carefully even without fully understanding every word, since it is already telling you the actual problem: not enough money was inserted',
      'Shake the machine until it gives the snack anyway',
      'Assume the message is meaningless and unrelated to the actual issue',
      'Wait for someone else to read it for you before doing anything',
    ],
    correctIndex: 0,
    explanation: 'Even a partly confusing error message often names the real problem directly; here it states the balance is insufficient, which immediately points to the fix (insert more money) without needing to understand every word.',
  },
  {
    slug: 'debugging-21',
    question: 'A morning routine plan says: "1. Wake up. 2. Get dressed. 3. Take a shower. 4. Eat breakfast. 5. Brush teeth." A student follows it exactly and ends up putting on clothes, then showering in them. What is the logical error?',
    options: [
      'Showering is listed before getting dressed, so the order should be swapped',
      'Getting dressed (step 2) happens before showering (step 3), so clothes get wet; dressing should come after the shower',
      'Breakfast should come before waking up',
      'There is no error; the student simply showered incorrectly',
    ],
    correctIndex: 1,
    explanation: 'Because step 2 puts clothes on before step 3 showers, the routine forces the student to shower while dressed; swapping the order of those two steps fixes the plan.',
  },
  {
    slug: 'debugging-22',
    question: 'You are debugging a long plan and have already confirmed that steps 1 through 6 produce the correct result. The final output is still wrong. Where should you focus your search next?',
    options: [
      'Back at step 1, since the earliest steps are always the most suspicious',
      'On the steps after step 6, since everything up through step 6 has already been verified to work correctly',
      'Randomly anywhere in the plan, since location does not matter once something is wrong',
      'Nowhere; if early steps work, the plan must be entirely correct',
    ],
    correctIndex: 1,
    explanation: 'Once a range of steps has been verified correct, the bug must be located in the unverified remainder of the plan, so narrowing the search there is the most efficient next move.',
  },
  {
    slug: 'debugging-23',
    question: 'Why is keeping a written log of what you changed and what result each change produced a good debugging habit?',
    options: [
      'It guarantees you will find the bug within five minutes',
      'It lets you track which changes already failed so you do not waste time repeating them, and helps you see patterns across attempts',
      'It is only useful for very short plans with one or two steps',
      'It replaces the need to actually test anything',
    ],
    correctIndex: 1,
    explanation: 'A log of attempted changes and their outcomes prevents you from retrying the same failed fix and can reveal patterns that point toward the real cause.',
  },
  {
    slug: 'debugging-24',
    question: 'A thermostat rule says: "If the room temperature is above 70 degrees, turn the heater on. Otherwise, turn the heater off." The room keeps getting too hot. What is the logical flaw?',
    options: [
      'The comparison is backwards — the heater should turn ON when it is too cold (below a threshold), not when it is already warm',
      'The thermostat is broken and cannot be fixed by changing the rule',
      'Heaters should never be controlled by rules',
      'The number 70 is too small to ever matter',
    ],
    correctIndex: 0,
    explanation: 'This rule turns the heater on exactly when the room is already warm, making it hotter still; the condition should instead turn the heater on when the temperature is too low, not too high.',
  },
  {
    slug: 'debugging-25',
    question: 'After fixing one bug in a plan, you run the whole plan again from start to finish, not just the part you changed. Why is this a good idea?',
    options: [
      'It is unnecessary busywork that wastes time',
      'A fix to one part can sometimes accidentally change behavior elsewhere, so re-checking the full plan helps catch any new problems the fix may have introduced',
      'Running the whole plan again always finds a second unrelated bug',
      'It is only needed if the first bug was very serious',
    ],
    correctIndex: 1,
    explanation: 'Changing one part of a plan can have unexpected ripple effects on other parts, so retesting the entire plan helps confirm the fix did not quietly break something else.',
  },
  {
    slug: 'debugging-26',
    question: 'Two students both have a plan that fails on the same step. Student A says, "It\'s just broken, I give up trying to understand why." Student B asks, "What did I expect this step to do, and what did it actually do instead?" Whose approach is more likely to lead to an actual fix?',
    options: [
      'Student A, because giving up avoids wasted effort',
      'Student B, because comparing the expected behavior to the actual behavior is how you identify the specific mismatch causing the failure',
      'Neither approach matters; bugs fix themselves over time',
      'Student A, because broken steps can never be repaired',
    ],
    correctIndex: 1,
    explanation: 'Pinpointing the gap between what you expected a step to do and what it actually did is the core move of debugging; giving up without investigating guarantees the bug stays unfixed.',
  },
]
