import type { CTQuestion } from '../types'

export const debugging: CTQuestion[] = [
  {
    slug: 'debugging-1',
    question: 'What does "debugging" mean in computational thinking?',
    options: [
      'Writing a plan or set of instructions for the first time',
      'Finding and fixing errors in a set of instructions or a plan',
      'Making a plan run as fast as possible',
      'Copying a successful plan from someone else',
    ],
    correctIndex: 1,
    explanation: 'Debugging is the process of locating why something is not working as expected and correcting it, not writing or speeding up the plan.',
  },
  {
    slug: 'debugging-2',
    question: 'You are debugging a multi-step plan that fails at some point. What is usually the most effective first move?',
    options: [
      'Rewrite the entire plan from scratch',
      'Trace through the steps one at a time to see where the result first goes wrong',
      'Assume the last step is broken and only fix that one',
      'Ignore the failure and run the plan again hoping it works',
    ],
    correctIndex: 1,
    explanation: 'Tracing step by step lets you pinpoint exactly where the actual outcome diverges from the expected one, which narrows down the source of the error.',
  },
  {
    slug: 'debugging-3',
    question: 'What does it mean to "isolate" a problem when debugging?',
    options: [
      'Deleting every step except the very first one',
      'Separating out the smallest part of the plan that still produces the error, to test it on its own',
      'Working on the problem completely alone, without help',
      'Running the whole plan many times in a row',
    ],
    correctIndex: 1,
    explanation: 'Isolating means narrowing the system down to the smallest piece that still reproduces the bug, which makes the cause much easier to identify.',
  },
  {
    slug: 'debugging-4',
    question: 'A recipe says: "Step 1: Preheat the oven. Step 2: Bake the cake for 30 minutes. Step 3: Mix the batter. Step 4: Pour batter into a pan." Why will this recipe fail?',
    options: [
      'The oven temperature is too high',
      'The steps are in the wrong order — baking happens before the batter is even made',
      'There are too many steps',
      'The recipe is missing an ingredient',
    ],
    correctIndex: 1,
    explanation: 'Step 2 tells you to bake before the batter is mixed and poured in Steps 3 and 4, so the order of steps is the logical error, not the ingredients or temperature.',
  },
  {
    slug: 'debugging-5',
    question: 'What is "rubber duck debugging"?',
    options: [
      'Explaining your plan out loud, step by step, to a person or object, to spot mistakes as you talk through them',
      'Testing a plan with rubber duck toys as test data',
      'A method where you let someone else fix all your mistakes',
      'A way to make plans more colorful and fun',
    ],
    correctIndex: 0,
    explanation: 'Rubber duck debugging gets its name from explaining your logic out loud to an inanimate object (like a rubber duck); the act of explaining often reveals the flaw yourself.',
  },
  {
    slug: 'debugging-6',
    question: 'Why is "checking your assumptions" an important debugging strategy?',
    options: [
      'Assumptions are always correct, so checking them wastes time',
      'A plan can look logically correct but fail because one of your starting assumptions about the situation was wrong',
      'It lets you skip testing the plan entirely',
      'It only matters for very long plans',
    ],
    correctIndex: 1,
    explanation: 'Many bugs happen not because the steps are wrong, but because a hidden assumption (like "the input will always be a positive number") turns out to be false.',
  },
  {
    slug: 'debugging-7',
    question: 'Why is it usually a bad debugging strategy to immediately blame the computer (or tool) for a wrong result?',
    options: [
      'Computers are never the cause of any problem',
      'It is rude to blame machines',
      'Most errors come from mistakes in the instructions or logic given to the computer, so blaming the tool first skips the real investigation',
      'Blaming the computer makes the bug fix itself',
    ],
    correctIndex: 2,
    explanation: 'Computers and tools follow instructions exactly as given, so an unexpected result is far more often caused by a flaw in the plan or logic than by the tool itself, and assuming otherwise stops you from looking in the right place.',
  },
  {
    slug: 'debugging-8',
    question: 'Why is it valuable to find a way to make a bug happen the same way every time (reproduce it consistently)?',
    options: [
      'It makes the bug look more impressive to others',
      'It guarantees the bug will never happen again on its own',
      'A consistently reproducible bug lets you test one change at a time and clearly see whether that change actually fixed the problem',
      'It is not valuable; random, unpredictable bugs are easier to fix',
    ],
    correctIndex: 2,
    explanation: 'If you can trigger a bug reliably, you can experiment with fixes and know for certain whether each change worked, instead of guessing based on a problem that only sometimes appears.',
  },
  {
    slug: 'debugging-9',
    question: 'A set of directions says: "1. Walk to the corner. 2. Turn left at the bakery. 3. Walk straight for 2 blocks. 4. Turn left at the bakery again. 5. The library is on your right." A friend follows these directions but ends up back near the bakery instead of at the library. What is the most likely logical error?',
    options: [
      'There is no bakery in the area',
      'Step 4 repeats the same landmark as step 2, which likely should reference a different, later landmark instead',
      'The friend cannot walk in a straight line',
      'The library does not exist',
    ],
    correctIndex: 1,
    explanation: 'Reusing "turn left at the bakery" in step 4 sends the walker back toward the same spot as step 2, suggesting that step should have referenced a new landmark further along the route.',
  },
  {
    slug: 'debugging-10',
    question: 'When debugging, why is it useful to compare what you expected to happen with what actually happened at each step?',
    options: [
      'It is not useful; only the final result matters',
      'Comparing expected versus actual results at each step shows you exactly where the plan first starts behaving incorrectly',
      'It only works if the plan has just one step',
      'It guarantees you will never make another mistake',
    ],
    correctIndex: 1,
    explanation: 'Checking expectations against actual outcomes at each step reveals the precise point where things diverge, which is usually where the bug lives.',
  },
  {
    slug: 'debugging-11',
    question: 'A plan for watering a garden says: "If it rained today, water the plants. If it did not rain today, do not water the plants." The gardener finds the plants are dying from too little water during a dry month. What is the actual logical flaw?',
    options: [
      'The condition is backwards — plants need water when it has NOT rained, not when it has',
      'The plan has too many steps',
      'The plants were planted in the wrong season',
      'There is no flaw; the gardener is not following the plan',
    ],
    correctIndex: 0,
    explanation: 'The rule waters plants only on rainy days and skips watering on dry days, which is the opposite of what plants actually need, so the condition itself is logically reversed.',
  },
  {
    slug: 'debugging-12',
    question: 'You changed one step in a plan to try to fix a bug, and the bug seems gone. What should you do before concluding the fix worked?',
    options: [
      'Immediately move on to a completely different part of the plan',
      'Delete your notes about the original bug',
      'Test the plan multiple times, including the situation that originally caused the bug, to make sure it is truly fixed and nothing else broke',
      'Assume it is fixed because it worked once',
    ],
    correctIndex: 2,
    explanation: 'A single successful run is not strong evidence; retesting the original failing scenario (and other cases) confirms the fix is real and did not introduce new problems.',
  },
  {
    slug: 'debugging-13',
    question: 'Why is breaking a large, confusing plan into smaller sections a helpful debugging approach?',
    options: [
      'Smaller sections are easier to check individually, making it simpler to find which exact section contains the error',
      'It makes the plan longer and harder to follow',
      'It guarantees the plan has no bugs',
      'It removes the need to test the plan at all',
    ],
    correctIndex: 0,
    explanation: 'Breaking a plan into smaller, testable sections lets you check each piece on its own, so the section causing the error becomes much easier to identify.',
  },
  {
    slug: 'debugging-14',
    question: 'What is "binary search debugging"?',
    options: [
      'Checking every single step from the very first one to the very last one, in order, one by one',
      'Repeatedly testing the midpoint of the remaining suspect steps to cut the number of possible error locations in half each time',
      'Guessing randomly which step is broken until you happen to find it',
      'Rewriting every step using only the numbers 0 and 1',
    ],
    correctIndex: 1,
    explanation: 'Binary search debugging means testing roughly the middle of the steps you still suspect, then throwing away the half that worked correctly, which finds the faulty step much faster than checking one by one.',
  },
  {
    slug: 'debugging-15',
    question: 'A weekly chore chart says: "Monday: laundry. Tuesday: laundry. Wednesday: dishes. Thursday: dishes. Friday: dishes. Saturday: dishes. Sunday: dishes." The family runs out of clean clothes by Thursday. What is the actual problem with the plan?',
    options: [
      'Laundry is scheduled far too rarely compared to how often clothes are needed, while dishes are scheduled far more often than needed',
      'There are too many days in the week',
      'Dishes should never be washed on weekends',
      'The chart is missing a day for vacuuming',
    ],
    correctIndex: 0,
    explanation: 'The chart allocates only 2 days to laundry but 5 days to dishes, an imbalance that does not match how often each chore actually needs doing, which is why laundry runs out first.',
  },
  {
    slug: 'debugging-16',
    question: 'Why should you change only ONE thing at a time when trying to fix a bug, instead of changing several steps at once?',
    options: [
      'Changing many things at once is always faster and just as reliable',
      'If multiple things change together and the result improves, you cannot tell which change actually fixed the problem',
      'Plans are only allowed to be edited one time total',
      'It has no real benefit; it is just a tradition',
    ],
    correctIndex: 1,
    explanation: 'When several changes happen at once, you lose the ability to tell which one mattered, so you might keep a useless change or miss what truly fixed the bug.',
  },
  {
    slug: 'debugging-17',
    question: 'What is the difference between a "symptom" and a "root cause" when debugging?',
    options: [
      'A symptom is the visible problem you notice, while the root cause is the deeper reason that actually produced that problem',
      'They mean exactly the same thing and can be used interchangeably',
      'A root cause only exists in medicine, not in plans or instructions',
      'A symptom is always more important to fix than the root cause',
    ],
    correctIndex: 0,
    explanation: 'The symptom is what you observe going wrong (like "the cake is burnt"), while the root cause is the underlying reason (like "the oven temperature step was wrong"); fixing only the symptom often leaves the real problem in place.',
  },
  {
    slug: 'debugging-18',
    question: 'A student keeps closing and reopening an app every time it freezes, and says the app is "fixed" because it works again afterward. Why might this not actually be a fix?',
    options: [
      'Restarting always permanently fixes every problem',
      'The freeze may still happen again later, because restarting only clears the immediate symptom without addressing whatever inside the app actually caused the freeze',
      'Apps can never freeze more than once',
      'It is impossible to know if an app is really fixed',
    ],
    correctIndex: 1,
    explanation: 'Restarting can temporarily clear a frozen state without ever finding or correcting the underlying issue, so the same root cause is likely to trigger the freeze again later.',
  },
  {
    slug: 'debugging-19',
    question: 'Why is it important to test "edge cases" — like an empty list, a zero, or the very first or last item — when debugging a plan?',
    options: [
      'Edge cases never actually occur in real use, so testing them is optional',
      'Plans often work fine on typical, middle-of-the-road inputs but break on unusual extreme inputs that were not considered when the plan was designed',
      'Testing edge cases is only necessary for plans involving numbers',
      'Edge cases are easier to test than normal cases, so they should be tested first and nothing else',
    ],
    correctIndex: 1,
    explanation: 'Many bugs hide in unusual situations the planner did not think about, like an empty input or a boundary value, so deliberately testing those cases catches errors that normal testing would miss.',
  },
  {
    slug: 'debugging-20',
    question: 'A vending machine error message reads: "Error: insufficient balance for selected item." A student says, "I don\'t understand all of this, so I\'ll just ignore it and keep pressing buttons." What is the better debugging approach?',
    options: [
      'Read the message carefully even without fully understanding every word, since it is already telling you the actual problem: not enough money was inserted',
      'Shake the machine until it gives the snack anyway',
      'Assume the message is meaningless and unrelated to the actual issue',
      'Wait for someone else to read it for you before doing anything',
    ],
    correctIndex: 0,
    explanation: 'Even a partly confusing error message often names the real problem directly; here it states the balance is insufficient, which immediately points to the fix (insert more money) without needing to understand every word.',
  },
  {
    slug: 'debugging-21',
    question: 'A morning routine plan says: "1. Wake up. 2. Get dressed. 3. Take a shower. 4. Eat breakfast. 5. Brush teeth." A student follows it exactly and ends up putting on clothes, then showering in them. What is the logical error?',
    options: [
      'Showering is listed before getting dressed, so the order should be swapped',
      'Getting dressed (step 2) happens before showering (step 3), so clothes get wet; dressing should come after the shower',
      'Breakfast should come before waking up',
      'There is no error; the student simply showered incorrectly',
    ],
    correctIndex: 1,
    explanation: 'Because step 2 puts clothes on before step 3 showers, the routine forces the student to shower while dressed; swapping the order of those two steps fixes the plan.',
  },
  {
    slug: 'debugging-22',
    question: 'You are debugging a long plan and have already confirmed that steps 1 through 6 produce the correct result. The final output is still wrong. Where should you focus your search next?',
    options: [
      'Back at step 1, since the earliest steps are always the most suspicious',
      'On the steps after step 6, since everything up through step 6 has already been verified to work correctly',
      'Randomly anywhere in the plan, since location does not matter once something is wrong',
      'Nowhere; if early steps work, the plan must be entirely correct',
    ],
    correctIndex: 1,
    explanation: 'Once a range of steps has been verified correct, the bug must be located in the unverified remainder of the plan, so narrowing the search there is the most efficient next move.',
  },
  {
    slug: 'debugging-23',
    question: 'Why is keeping a written log of what you changed and what result each change produced a good debugging habit?',
    options: [
      'It guarantees you will find the bug within five minutes',
      'It lets you track which changes already failed so you do not waste time repeating them, and helps you see patterns across attempts',
      'It is only useful for very short plans with one or two steps',
      'It replaces the need to actually test anything',
    ],
    correctIndex: 1,
    explanation: 'A log of attempted changes and their outcomes prevents you from retrying the same failed fix and can reveal patterns that point toward the real cause.',
  },
  {
    slug: 'debugging-24',
    question: 'A thermostat rule says: "If the room temperature is above 70 degrees, turn the heater on. Otherwise, turn the heater off." The room keeps getting too hot. What is the logical flaw?',
    options: [
      'The comparison is backwards — the heater should turn ON when it is too cold (below a threshold), not when it is already warm',
      'The thermostat is broken and cannot be fixed by changing the rule',
      'Heaters should never be controlled by rules',
      'The number 70 is too small to ever matter',
    ],
    correctIndex: 0,
    explanation: 'This rule turns the heater on exactly when the room is already warm, making it hotter still; the condition should instead turn the heater on when the temperature is too low, not too high.',
  },
  {
    slug: 'debugging-25',
    question: 'After fixing one bug in a plan, you run the whole plan again from start to finish, not just the part you changed. Why is this a good idea?',
    options: [
      'It is unnecessary busywork that wastes time',
      'A fix to one part can sometimes accidentally change behavior elsewhere, so re-checking the full plan helps catch any new problems the fix may have introduced',
      'Running the whole plan again always finds a second unrelated bug',
      'It is only needed if the first bug was very serious',
    ],
    correctIndex: 1,
    explanation: 'Changing one part of a plan can have unexpected ripple effects on other parts, so retesting the entire plan helps confirm the fix did not quietly break something else.',
  },
  {
    slug: 'debugging-26',
    question: 'Two students both have a plan that fails on the same step. Student A says, "It\'s just broken, I give up trying to understand why." Student B asks, "What did I expect this step to do, and what did it actually do instead?" Whose approach is more likely to lead to an actual fix?',
    options: [
      'Student A, because giving up avoids wasted effort',
      'Student B, because comparing the expected behavior to the actual behavior is how you identify the specific mismatch causing the failure',
      'Neither approach matters; bugs fix themselves over time',
      'Student A, because broken steps can never be repaired',
    ],
    correctIndex: 1,
    explanation: 'Pinpointing the gap between what you expected a step to do and what it actually did is the core move of debugging; giving up without investigating guarantees the bug stays unfixed.',
  },
  {
    slug: 'debugging-27',
    question: 'A school bus schedule says: "1. Pick up students on Maple St. 2. Drive to the school. 3. Pick up students on Oak St. 4. Drop students off at school." Parents on Oak St complain their kids arrive at school twice as late as expected. What is the logical error?',
    options: [
      'Step 3 happens after the bus has already driven to the school in step 2, so Oak St students get picked up too late and the bus must backtrack',
      'There are not enough students on the bus',
      'Maple St should not be on the route at all',
      'The bus is driving too slowly between stops',
    ],
    correctIndex: 0,
    explanation: 'Because the route drives to the school before picking up the Oak St students, the bus has to double back, which is the actual cause of the delay, not speed or the number of riders.',
  },
  {
    slug: 'debugging-28',
    question: 'A board game rule sheet says: "Roll the die. If you roll a 6, move forward 6 spaces and roll again. If you roll a 6, move forward 6 spaces and roll again." Players notice this rule is printed twice and wonder if that is a bug. What is the best way to check whether the duplicate line actually causes a problem?',
    options: [
      'Assume duplicate text is always harmless and move on without checking',
      'Read what each duplicate line actually does: since both copies say the exact same thing, the duplication is just repeated text, not a logic error, so it is worth confirming no second action was intended before ignoring it',
      'Delete both copies of the rule immediately without reading them',
      'Add a third copy of the rule to see if three copies behave differently',
    ],
    correctIndex: 1,
    explanation: 'Before dismissing or deleting something that looks odd, you should check what it actually says and does; here the duplicate lines are identical, so they do not change the game logic, but confirming that is part of debugging.',
  },
  {
    slug: 'debugging-29',
    question: 'A study plan says: "Study math for 1 hour. Study science for 1 hour. Take the math test. Study English for 1 hour." A student fails the science test the next day. What is the most likely logical flaw?',
    options: [
      'The plan never schedules any time to study for the science test at all before it happens',
      'One hour is too long to study any subject',
      'Math should always be studied last',
      'The student needs to study English for two hours instead of one',
    ],
    correctIndex: 0,
    explanation: 'The plan studies science but the science test itself is never mentioned or prepared for at the right time, so missing or mistiming that step is the real gap, similar to leaving a needed action out of a plan entirely.',
  },
  {
    slug: 'debugging-30',
    question: 'A delivery route plan says: "Deliver package A to House 1. Deliver package B to House 2. Deliver package C to House 1." House 1 ends up with two different packages and House 2\'s resident says theirs never arrived... but it turns out package B was correctly delivered. What does this scenario best illustrate about debugging?',
    options: [
      'That all complaints about a plan are always accurate and require a fix',
      'That you should verify a reported problem actually happened before changing the plan, since acting on an unconfirmed report can lead you to "fix" something that was not actually broken',
      'That delivery plans can never be trusted',
      'That House 1 should be removed from the route entirely',
    ],
    correctIndex: 1,
    explanation: 'Good debugging includes confirming whether a reported failure is real before making changes; here the report about package B turned out to be wrong, so chasing it would have wasted effort on a non-bug.',
  },
  {
    slug: 'debugging-31',
    question: 'You are debugging a plan with 100 steps. Checking each step individually takes about the same amount of time. Which approach will most reliably find the single broken step using the fewest checks?',
    options: [
      'Check step 1, then step 2, then step 3, continuing in order until you happen to reach the broken one',
      'Test around the middle of the steps, determine which half still contains the error, and keep repeating that narrowing process on the remaining half',
      'Check the last step first and then never check any other step',
      'Check steps in a random order with no plan for which to try next',
    ],
    correctIndex: 1,
    explanation: 'Repeatedly testing the midpoint of the remaining suspect range and discarding the half that works correctly narrows down the search much faster than checking steps one by one or randomly.',
  },
  {
    slug: 'debugging-32',
    question: 'A student fixes a typo in step 3 of a plan, and afterward notices the plan now also produces a correct result in step 9 that had been wrong before. The student assumes the step 3 fix must have somehow caused the step 9 improvement. What is the danger in that assumption?',
    options: [
      'There is no danger; anything that happens after a fix must be caused by it',
      'Two things happening around the same time does not prove one caused the other; step 9 might have been fixed by something else entirely, or might not really be fixed at all',
      'The student should immediately undo the step 3 fix since it is clearly unrelated',
      'Step 9 can never be affected by step 3 under any circumstances',
    ],
    correctIndex: 1,
    explanation: 'This is a correlation-versus-causation trap: just because step 9 changed around the same time as the step 3 fix does not prove the fix caused it, so the connection needs to be tested directly, not assumed.',
  },
  {
    slug: 'debugging-33',
    question: 'After applying a fix, a plan works correctly on the next 3 attempts. Which follow-up best confirms the fix is genuinely reliable rather than just lucky?',
    options: [
      'Stop testing immediately, since 3 successes in a row always proves a permanent fix',
      'Re-run the original failing scenario several more times, including any unusual or edge-case inputs that caused trouble before, to see if it ever fails again',
      'Test a completely unrelated plan instead, since this one already passed three times',
      'Assume the fix worked because no one has complained yet',
    ],
    correctIndex: 1,
    explanation: 'A few successful runs can sometimes happen by chance or by avoiding the exact conditions that triggered the original bug, so deliberately retesting the failing scenario and edge cases gives much stronger evidence the fix truly works.',
  },
  {
    slug: 'debugging-34',
    question: 'A garden sprinkler timer is changed, and a neighbor says the grass "looks a little greener" the very next morning. The owner concludes the new timer setting fixed the watering problem for good. What is the most important thing missing from this conclusion?',
    options: [
      'Nothing is missing; one morning of slightly greener grass is enough proof',
      'Grass color can change for many reasons (like recent weather), so one quick, vague observation does not reliably confirm the timer change was the actual cause; the result needs more careful, repeated checking over time',
      'The neighbor must be lying about the grass color',
      'The timer change could not possibly affect the grass at all',
    ],
    correctIndex: 1,
    explanation: 'A single subjective observation shortly after a change is weak evidence, since other factors (like rain) could explain it; confirming a real fix requires more consistent, deliberate observation over time.',
  },
  {
    slug: 'debugging-35',
    question: 'A treasure hunt clue list says: "Clue 1 leads to the oak tree. Clue 2 leads to the fountain. Clue 4 leads to the gate." A player gets stuck after Clue 2 because there is no Clue 3. What kind of bug is this?',
    options: [
      'A missing step in the sequence, where the plan jumps from one numbered step straight to a later one without including what comes in between',
      'A step that is repeated too many times',
      'A step where two actions contradict each other',
      'A step that uses the wrong unit of measurement',
    ],
    correctIndex: 0,
    explanation: 'Jumping from Clue 2 directly to Clue 4 leaves a gap where Clue 3 should be, which is a missing-step bug rather than a contradiction, repetition, or measurement issue.',
  },
  {
    slug: 'debugging-36',
    question: 'A class is split into two groups to debug the same broken plan independently, without talking to each other first. Why can this be a useful debugging strategy?',
    options: [
      'It wastes effort because only one group is ever allowed to be right',
      'Each group might notice different clues or test different parts first, and comparing their independent findings afterward can reveal the bug faster or confirm it more confidently than one group working alone',
      'It guarantees both groups will make the exact same mistake',
      'It is never useful, since debugging must always be done by exactly one person',
    ],
    correctIndex: 1,
    explanation: 'Independent investigation can surface different angles on the same problem, and comparing notes afterward often narrows down the true cause faster than relying on a single line of investigation.',
  },
  {
    slug: 'debugging-37',
    question: 'A printed instruction sheet for assembling a shelf says: "Step 5: Attach panel A to panel B using the long screws." There are no long screws in the box, only short ones. What is the best first debugging action?',
    options: [
      'Throw away the instructions and guess how to build the shelf without them',
      'Force the short screws to work no matter what, even if they do not fit properly',
      'Stop and check whether the box is missing parts, the instructions listed the wrong screw type, or you are looking at the wrong step, rather than guessing which one it is',
      'Assume the shelf cannot be built and return it without checking anything',
    ],
    correctIndex: 2,
    explanation: 'When actual results do not match expectations, the first move is to investigate which assumption is wrong (missing hardware, wrong instructions, or misread step) instead of jumping straight to forcing a fix or giving up.',
  },
  {
    slug: 'debugging-38',
    question: 'A plan to brush a dog says: "1. Get the brush. 2. Brush the dog\'s fur. 3. Get the dog." Someone follows it exactly and cannot complete step 2 because the dog is not there yet. What kind of logical error is this, and what is the fix?',
    options: [
      'It is a contradiction error, and the fix is to remove step 2 entirely',
      'It is a step-ordering error, since step 3 (getting the dog) must happen before step 2 (brushing it); swapping steps 2 and 3 fixes the plan',
      'It is a missing-step error, and the fix is to add a fourth step',
      'There is no error; the dog simply needs to be trained better',
    ],
    correctIndex: 1,
    explanation: 'You cannot brush a dog that has not been retrieved yet, so the steps are simply out of order; moving "get the dog" before "brush the dog" resolves the issue without needing to add or remove any step.',
  },
]
