import type { CTQuestion } from '../types'

export const logicalReasoning: CTQuestion[] = [
  {
    slug: 'logical-reasoning-1',
    question: 'A is true and B is false. What is A AND B?',
    options: ['True', 'False', 'Unknown', 'Both true and false'],
    correctIndex: 1,
    explanation: 'AND only gives true when both sides are true. Since B is false, A AND B is false.',
  },
  {
    slug: 'logical-reasoning-2',
    question: 'A is true and B is false. What is A OR B?',
    options: ['True', 'False', 'Unknown', 'Neither'],
    correctIndex: 0,
    explanation: 'OR gives true when at least one side is true. Since A is true, A OR B is true.',
  },
  {
    slug: 'logical-reasoning-3',
    question: 'If A is false, what is NOT A?',
    options: ['False', 'True', 'A', 'Unknown'],
    correctIndex: 1,
    explanation: 'NOT flips the value, so NOT false becomes true.',
  },
  {
    slug: 'logical-reasoning-4',
    question: 'Rule: "If it is raining, then I bring an umbrella." It is not raining. What can we conclude?',
    options: [
      'I bring an umbrella',
      'I do not bring an umbrella',
      'We cannot be sure whether I bring an umbrella',
      'It must be sunny',
    ],
    correctIndex: 2,
    explanation: 'The rule only tells us what happens when it IS raining. When it is not raining, the rule says nothing, so we cannot be certain either way.',
  },
  {
    slug: 'logical-reasoning-5',
    question: 'Rule: "If a shape is a square, then it has 4 sides." A shape has 4 sides. Can we conclude it is a square?',
    options: [
      'Yes, it must be a square',
      'No, having 4 sides does not guarantee it is a square',
      'Yes, because all 4-sided shapes are squares',
      'The rule is false',
    ],
    correctIndex: 1,
    explanation: 'The rule only says squares have 4 sides, not that every 4-sided shape is a square. A rectangle also has 4 sides but is not a square.',
  },
  {
    slug: 'logical-reasoning-6',
    question: 'Rule: "If you finish your homework, then you can watch TV." Sam did not watch TV. What can we conclude?',
    options: [
      'Sam finished homework',
      'Sam did not finish homework',
      'Sam did not finish homework, OR Sam chose not to watch TV anyway',
      'The rule is broken',
    ],
    correctIndex: 2,
    explanation: 'The rule guarantees TV time if homework is done, but it does not stop Sam from skipping TV anyway, so not watching TV does not prove the homework was unfinished.',
  },
  {
    slug: 'logical-reasoning-7',
    question: 'Three friends: Amy, Ben, and Cara each like a different fruit: apple, banana, or cherry. Amy does not like apple. Ben likes banana. What does Amy like?',
    options: ['Apple', 'Banana', 'Cherry', 'Cannot be determined'],
    correctIndex: 2,
    explanation: 'Ben already has banana, and Amy does not like apple, so by elimination Amy must like cherry.',
  },
  {
    slug: 'logical-reasoning-8',
    question: 'In a row of 3 lockers (1, 2, 3), the red locker is not in position 1. The blue locker is in position 2. What must be true about the red locker?',
    options: ['It is in position 1', 'It is in position 2', 'It is in position 3', 'It could be in position 1 or 3'],
    correctIndex: 2,
    explanation: 'The red locker cannot be in position 1 (given) or position 2 (taken by blue), so it must be in position 3.',
  },
  {
    slug: 'logical-reasoning-9',
    question: 'A truth table shows AND for two inputs. Which row gives a true result?',
    options: [
      'Input1 = false, Input2 = true',
      'Input1 = false, Input2 = false',
      'Input1 = true, Input2 = true',
      'Input1 = true, Input2 = false',
    ],
    correctIndex: 2,
    explanation: 'AND is only true when both inputs are true, so the row with true and true is the only one that gives a true result.',
  },
  {
    slug: 'logical-reasoning-10',
    question: 'What is NOT (true AND false)?',
    options: ['True', 'False', 'Unknown', 'NOT true'],
    correctIndex: 0,
    explanation: 'true AND false is false, and NOT false is true.',
  },
  {
    slug: 'logical-reasoning-11',
    question: 'A game lets you enter the bonus room if (you have the key OR you know the secret code) AND you are not banned. You have the key and you are not banned. Can you enter?',
    options: [
      'Yes, you can enter',
      'No, you also need the secret code',
      'No, having the key does not count',
      'Cannot be determined',
    ],
    correctIndex: 0,
    explanation: 'Having the key alone makes the OR part true, and since you are not banned, both parts of the AND are satisfied, so you can enter.',
  },
  {
    slug: 'logical-reasoning-12',
    question: 'Four kids — Dev, Mia, Sam, and Lee — sit in a line. Mia sits immediately to the left of Sam. Dev sits at the far left end. Lee sits at the far right end. What is the order from left to right?',
    options: ['Dev, Mia, Sam, Lee', 'Mia, Sam, Dev, Lee', 'Dev, Sam, Mia, Lee', 'Lee, Mia, Sam, Dev'],
    correctIndex: 0,
    explanation: 'Dev must be first and Lee must be last, leaving Mia and Sam for the two middle spots; since Mia is immediately left of Sam, the order is Dev, Mia, Sam, Lee.',
  },
  {
    slug: 'logical-reasoning-13',
    question: 'A vending machine dispenses a snack only if (coin inserted AND button pressed) is true, OR if the free-sample switch is on. The free-sample switch is off, a coin was inserted, but no button was pressed. Will a snack come out?',
    options: [
      'Yes, because a coin was inserted',
      'No, because the AND condition fails and the OR condition is also false',
      'Yes, because the OR makes it true regardless',
      'Cannot be determined without more information',
    ],
    correctIndex: 1,
    explanation: 'Coin AND button requires both to be true, but the button was not pressed, so that part is false; the free-sample switch is also off, so the whole OR expression is false and no snack dispenses.',
  },
]
