import type { CTQuestion } from '../types'

export const logicalReasoning: CTQuestion[] = [
  {
    slug: 'logical-reasoning-1',
    question: 'A is true and B is false. What is A AND B?',
    options: ['True', 'False', 'Unknown', 'Both true and false'],
    correctIndex: 1,
    explanation: 'AND only gives true when both sides are true. Since B is false, A AND B is false.',
  },
  {
    slug: 'logical-reasoning-2',
    question: 'A is true and B is false. What is A OR B?',
    options: ['True', 'False', 'Unknown', 'Neither'],
    correctIndex: 0,
    explanation: 'OR gives true when at least one side is true. Since A is true, A OR B is true.',
  },
  {
    slug: 'logical-reasoning-3',
    question: 'If A is false, what is NOT A?',
    options: ['False', 'True', 'A', 'Unknown'],
    correctIndex: 1,
    explanation: 'NOT flips the value, so NOT false becomes true.',
  },
  {
    slug: 'logical-reasoning-4',
    question: 'Rule: "If it is raining, then I bring an umbrella." It is not raining. What can we conclude?',
    options: [
      'I bring an umbrella',
      'I do not bring an umbrella',
      'We cannot be sure whether I bring an umbrella',
      'It must be sunny',
    ],
    correctIndex: 2,
    explanation: 'The rule only tells us what happens when it IS raining. When it is not raining, the rule says nothing, so we cannot be certain either way.',
  },
  {
    slug: 'logical-reasoning-5',
    question: 'Rule: "If a shape is a square, then it has 4 sides." A shape has 4 sides. Can we conclude it is a square?',
    options: [
      'Yes, it must be a square',
      'No, having 4 sides does not guarantee it is a square',
      'Yes, because all 4-sided shapes are squares',
      'The rule is false',
    ],
    correctIndex: 1,
    explanation: 'The rule only says squares have 4 sides, not that every 4-sided shape is a square. A rectangle also has 4 sides but is not a square.',
  },
  {
    slug: 'logical-reasoning-6',
    question: 'Rule: "If you finish your homework, then you can watch TV." Sam did not watch TV. What can we conclude?',
    options: [
      'Sam finished homework',
      'Sam did not finish homework',
      'Sam did not finish homework, OR Sam chose not to watch TV anyway',
      'The rule is broken',
    ],
    correctIndex: 2,
    explanation: 'The rule guarantees TV time if homework is done, but it does not stop Sam from skipping TV anyway, so not watching TV does not prove the homework was unfinished.',
  },
  {
    slug: 'logical-reasoning-7',
    question: 'Three friends: Amy, Ben, and Cara each like a different fruit: apple, banana, or cherry. Amy does not like apple. Ben likes banana. What does Amy like?',
    options: ['Apple', 'Banana', 'Cherry', 'Cannot be determined'],
    correctIndex: 2,
    explanation: 'Ben already has banana, and Amy does not like apple, so by elimination Amy must like cherry.',
  },
  {
    slug: 'logical-reasoning-8',
    question: 'In a row of 3 lockers (1, 2, 3), the red locker is not in position 1. The blue locker is in position 2. What must be true about the red locker?',
    options: ['It is in position 1', 'It is in position 2', 'It is in position 3', 'It could be in position 1 or 3'],
    correctIndex: 2,
    explanation: 'The red locker cannot be in position 1 (given) or position 2 (taken by blue), so it must be in position 3.',
  },
  {
    slug: 'logical-reasoning-9',
    question: 'A truth table shows AND for two inputs. Which row gives a true result?',
    options: [
      'Input1 = false, Input2 = true',
      'Input1 = false, Input2 = false',
      'Input1 = true, Input2 = true',
      'Input1 = true, Input2 = false',
    ],
    correctIndex: 2,
    explanation: 'AND is only true when both inputs are true, so the row with true and true is the only one that gives a true result.',
  },
  {
    slug: 'logical-reasoning-10',
    question: 'What is NOT (true AND false)?',
    options: ['True', 'False', 'Unknown', 'NOT true'],
    correctIndex: 0,
    explanation: 'true AND false is false, and NOT false is true.',
  },
  {
    slug: 'logical-reasoning-11',
    question: 'A game lets you enter the bonus room if (you have the key OR you know the secret code) AND you are not banned. You have the key and you are not banned. Can you enter?',
    options: [
      'Yes, you can enter',
      'No, you also need the secret code',
      'No, having the key does not count',
      'Cannot be determined',
    ],
    correctIndex: 0,
    explanation: 'Having the key alone makes the OR part true, and since you are not banned, both parts of the AND are satisfied, so you can enter.',
  },
  {
    slug: 'logical-reasoning-12',
    question: 'Four kids — Dev, Mia, Sam, and Lee — sit in a line. Mia sits immediately to the left of Sam. Dev sits at the far left end. Lee sits at the far right end. What is the order from left to right?',
    options: ['Dev, Mia, Sam, Lee', 'Mia, Sam, Dev, Lee', 'Dev, Sam, Mia, Lee', 'Lee, Mia, Sam, Dev'],
    correctIndex: 0,
    explanation: 'Dev must be first and Lee must be last, leaving Mia and Sam for the two middle spots; since Mia is immediately left of Sam, the order is Dev, Mia, Sam, Lee.',
  },
  {
    slug: 'logical-reasoning-13',
    question: 'A vending machine dispenses a snack only if (coin inserted AND button pressed) is true, OR if the free-sample switch is on. The free-sample switch is off, a coin was inserted, but no button was pressed. Will a snack come out?',
    options: [
      'Yes, because a coin was inserted',
      'No, because the AND condition fails and the OR condition is also false',
      'Yes, because the OR makes it true regardless',
      'Cannot be determined without more information',
    ],
    correctIndex: 1,
    explanation: 'Coin AND button requires both to be true, but the button was not pressed, so that part is false; the free-sample switch is also off, so the whole OR expression is false and no snack dispenses.',
  },
  {
    slug: 'logical-reasoning-14',
    question: 'P is false and Q is false. What is P OR Q?',
    options: ['True', 'False', 'Unknown', 'P'],
    correctIndex: 1,
    explanation: 'OR is only false when both sides are false, and here both P and Q are false, so P OR Q is false.',
  },
  {
    slug: 'logical-reasoning-15',
    question: 'X is true. What is X AND (NOT X)?',
    options: ['True', 'False', 'Unknown', 'X'],
    correctIndex: 1,
    explanation: 'NOT X is false when X is true, and true AND false is false, so the expression is always false no matter what X is.',
  },
  {
    slug: 'logical-reasoning-16',
    question: 'What is NOT (false OR false)?',
    options: ['True', 'False', 'Unknown', 'NOT false'],
    correctIndex: 0,
    explanation: 'false OR false is false, and flipping false with NOT gives true.',
  },
  {
    slug: 'logical-reasoning-17',
    question: 'Rule: "If a number is divisible by 4, then it is even." A number is even. Can we conclude it is divisible by 4?',
    options: [
      'Yes, all even numbers are divisible by 4',
      'No, being even does not guarantee divisibility by 4',
      'Yes, because the rule works both ways',
      'The rule must be false',
    ],
    correctIndex: 1,
    explanation: 'The rule only goes one direction: divisible by 4 implies even. A number like 6 is even but not divisible by 4, so the reverse is not guaranteed.',
  },
  {
    slug: 'logical-reasoning-18',
    question: 'Rule: "If you are a member, then you get a discount." Maria did not get a discount. What can we conclude?',
    options: [
      'Maria is a member',
      'Maria is not a member',
      'Maria might still be a member',
      'The rule is wrong',
    ],
    correctIndex: 1,
    explanation: 'This is valid logic: if membership always leads to a discount, then no discount means Maria cannot be a member, otherwise the rule would have been broken.',
  },
  {
    slug: 'logical-reasoning-19',
    question: 'Rule: "If the alarm is armed, then the light blinks." The light is blinking. What can we conclude?',
    options: [
      'The alarm is definitely armed',
      'The alarm is definitely not armed',
      'We cannot be sure the alarm is armed just from the blinking light',
      'The rule must be broken',
    ],
    correctIndex: 2,
    explanation: 'This is the flawed "affirming the consequent" pattern: the rule says armed leads to blinking, but something else could also make the light blink, so blinking alone does not prove the alarm is armed.',
  },
  {
    slug: 'logical-reasoning-20',
    question: 'Four runners — Jo, Kim, Lee, and Max — finish a race in 1st through 4th place with no ties. Jo finishes before Kim. Lee finishes last. Max finishes 1st. What is the finishing order?',
    options: ['Max, Jo, Kim, Lee', 'Jo, Max, Kim, Lee', 'Max, Kim, Jo, Lee', 'Max, Jo, Lee, Kim'],
    correctIndex: 0,
    explanation: 'Max is 1st and Lee is 4th, leaving 2nd and 3rd for Jo and Kim; since Jo finishes before Kim, the order is Max, Jo, Kim, Lee.',
  },
  {
    slug: 'logical-reasoning-21',
    question: 'Three boxes are labeled A, B, and C. Only one box contains a prize. The prize is not in box A. The prize is not in box C. Where is the prize?',
    options: ['Box A', 'Box B', 'Box C', 'Cannot be determined'],
    correctIndex: 1,
    explanation: 'Since the prize is not in A and not in C, by elimination it must be in box B.',
  },
  {
    slug: 'logical-reasoning-22',
    question: 'A truth table shows OR for two inputs. Which row gives a false result?',
    options: [
      'Input1 = false, Input2 = false',
      'Input1 = true, Input2 = false',
      'Input1 = false, Input2 = true',
      'Input1 = true, Input2 = true',
    ],
    correctIndex: 0,
    explanation: 'OR is false only when both inputs are false, so the row with false and false is the one that gives a false result.',
  },
  {
    slug: 'logical-reasoning-23',
    question: 'A streaming app lets you watch a show if (you have a subscription OR it is a free preview) AND your device is supported. You have no subscription, it is not a free preview, but your device is supported. Can you watch the show?',
    options: [
      'Yes, because your device is supported',
      'No, because the OR part is false, so the whole condition fails',
      'Yes, because at least one condition is true',
      'Cannot be determined',
    ],
    correctIndex: 1,
    explanation: 'Without a subscription and without a free preview, the OR part is false; even though the device is supported, AND needs both parts true, so you cannot watch.',
  },
  {
    slug: 'logical-reasoning-24',
    question: 'Five friends sit in a row of 5 seats numbered 1 to 5. Nina sits exactly in the middle seat. Omar sits immediately to the right of Nina. Priya sits in seat 1. Quinn sits immediately to the left of Nina. Who sits in seat 5?',
    options: ['Omar', 'Priya', 'Quinn', 'The fifth friend, not yet placed'],
    correctIndex: 3,
    explanation: 'Nina is in seat 3, Quinn is in seat 2, Omar is in seat 4, and Priya is in seat 1, leaving seat 5 for the fifth friend whose seat was never fixed by any clue.',
  },
  {
    slug: 'logical-reasoning-25',
    question: 'Rule 1: "If it is a weekday, the library opens at 9am." Rule 2: "If the library opens at 9am, the morning class can use it." Today is a weekday. What can we conclude?',
    options: [
      'The morning class can use the library today',
      'The library is closed today',
      'The morning class cannot use the library',
      'Nothing can be concluded',
    ],
    correctIndex: 0,
    explanation: 'Chaining the two rules: weekday means the library opens at 9am, and opening at 9am means the morning class can use it, so the class can use the library today.',
  },
  {
    slug: 'logical-reasoning-26',
    question: 'A robot moves forward only if (the path is clear AND battery is above 10%) OR (override switch is on). The path is clear, the battery is at 5%, and the override switch is off. Does the robot move forward?',
    options: [
      'Yes, because the path is clear',
      'No, because both the AND condition and the OR condition fail',
      'Yes, because the override switch does not matter',
      'Cannot be determined without more information',
    ],
    correctIndex: 1,
    explanation: 'The AND needs both a clear path and battery above 10%, but the battery is only at 5%, so that part fails; the override switch is also off, so the whole expression is false and the robot does not move.',
  },
]
