import type { CTQuestion } from '../types'

export const patternRecognition: CTQuestion[] = [
  {
    slug: 'pattern-recognition-1',
    question: 'What number comes next in this sequence? 2, 4, 8, 16, ...',
    options: ['18', '24', '32', '20'],
    correctIndex: 2,
    explanation: 'Each number is double the one before it, so the pattern is multiply by 2: 16 x 2 = 32.',
  },
  {
    slug: 'pattern-recognition-2',
    question: 'What number comes next? 1, 1, 2, 3, 5, 8, ...',
    options: ['11', '12', '13', '10'],
    correctIndex: 2,
    explanation: 'This is the Fibonacci pattern, where each number is the sum of the two before it: 5 + 8 = 13.',
  },
  {
    slug: 'pattern-recognition-3',
    question: 'A row of shapes goes: circle, square, circle, square, circle, ... What shape comes next?',
    options: ['Circle', 'Square', 'Triangle', 'It is impossible to know'],
    correctIndex: 1,
    explanation: 'The shapes alternate in a repeating two-step pattern, so after circle comes square again.',
  },
  {
    slug: 'pattern-recognition-4',
    question: 'A wallpaper design repeats one motif of a star, a moon, and a sun, over and over in that order. If the wallpaper starts with a star, what is the 8th motif?',
    options: ['Star', 'Moon', 'Sun', 'Star and moon together'],
    correctIndex: 1,
    explanation: 'The pattern repeats every 3 motifs (star, moon, sun). Position 8 mod 3 = 2, which lines up with the second item in the cycle: moon.',
  },
  {
    slug: 'pattern-recognition-5',
    question: 'What number comes next? 100, 90, 80, 70, ...',
    options: ['65', '60', '50', '55'],
    correctIndex: 1,
    explanation: 'The pattern subtracts 10 each time, so 70 - 10 = 60.',
  },
  {
    slug: 'pattern-recognition-6',
    question: 'Every morning you brush your teeth, eat breakfast, and pack your bag in the same order before school. Recognizing this as a pattern is most useful because it lets you...',
    options: [
      'Forget the steps since they happen automatically',
      'Predict and plan your morning routine more efficiently',
      'Avoid eating breakfast on busy days',
      'Change the order randomly each day for fun',
    ],
    correctIndex: 1,
    explanation: 'Spotting the repeated structure in your routine lets you predict what comes next and plan your time well, which is the core benefit of pattern recognition.',
  },
  {
    slug: 'pattern-recognition-7',
    question: 'A program prints "Hello" five times using five separate print statements written one after another. What pattern should a programmer notice here?',
    options: [
      'The code uses too many different variable names',
      'The same instruction is being repeated, which is a sign a loop could replace it',
      'The program will crash because of repeated text',
      'There is no pattern since the text never changes',
    ],
    correctIndex: 1,
    explanation: 'Repeating the exact same instruction multiple times is a classic pattern that signals the code could be simplified using a loop instead of copy-pasting lines.',
  },
  {
    slug: 'pattern-recognition-8',
    question: 'In a spreadsheet of daily temperatures, you notice the values go up every day for a week, then drop sharply on the weekend, repeating this pattern every week. What is this an example of?',
    options: [
      'A coding error in the spreadsheet',
      'A trend or pattern in the data that could help predict future temperatures',
      'Random numbers with no meaning',
      'A sign the spreadsheet needs to be deleted',
    ],
    correctIndex: 1,
    explanation: 'Noticing the same weekly rise-and-drop pattern in data is exactly how pattern recognition helps you make predictions about what is likely to happen next.',
  },
  {
    slug: 'pattern-recognition-9',
    question: 'What number comes next? 3, 6, 9, 12, ...',
    options: ['13', '14', '15', '16'],
    correctIndex: 2,
    explanation: 'The pattern adds 3 each time, so 12 + 3 = 15.',
  },
  {
    slug: 'pattern-recognition-10',
    question: 'A tiled floor has a row of tiles colored: red, red, blue, red, red, blue, red, red, blue. What is the repeating unit of this pattern?',
    options: ['red, blue', 'red, red, blue', 'blue, red, red', 'red, blue, red'],
    correctIndex: 1,
    explanation: 'The smallest group of tiles that repeats over and over is "red, red, blue," which then starts again from the beginning.',
  },
  {
    slug: 'pattern-recognition-11',
    question: 'Why is pattern recognition considered an important part of computational thinking, especially before writing code?',
    options: [
      'It lets you skip testing your program',
      'It helps you notice similarities between problems so you can reuse or adapt known solutions',
      'It guarantees your code will never have bugs',
      'It replaces the need to break a problem into smaller parts',
    ],
    correctIndex: 1,
    explanation: 'Recognizing patterns lets you see that a new problem is similar to one you have solved before, so you can reuse or adapt an existing solution instead of starting from scratch.',
  },
  {
    slug: 'pattern-recognition-12',
    question: 'A student notices that three different math problems all involve doubling a starting number a set number of times. Why does spotting this shared pattern matter when writing a program to solve them?',
    options: [
      'It means the problems are unrelated and need totally different code',
      'It means one general piece of code, like a loop that doubles a value, can likely solve all three problems',
      'It means the program must use a different language for each problem',
      'It means pattern recognition only applies to shapes, not numbers',
    ],
    correctIndex: 1,
    explanation: 'When several problems share the same underlying structure, a single flexible solution, such as a loop, can often be reused for all of them instead of writing separate code each time.',
  },
  {
    slug: 'pattern-recognition-13',
    question: 'What number comes next? 1, 4, 9, 16, 25, ...',
    options: ['30', '36', '34', '32'],
    correctIndex: 1,
    explanation: 'These are square numbers (1x1, 2x2, 3x3, 4x4, 5x5), so the next one is 6x6 = 36.',
  },
]
