import type { CTQuestion } from '../types'

export const patternRecognition: CTQuestion[] = [
  {
    slug: 'pattern-recognition-1',
    question: 'What number comes next in this sequence? 2, 4, 8, 16, ...',
    options: ['18', '24', '32', '20'],
    correctIndex: 2,
    explanation: 'Each number is double the one before it, so the pattern is multiply by 2: 16 x 2 = 32.',
  },
  {
    slug: 'pattern-recognition-2',
    question: 'What number comes next? 1, 1, 2, 3, 5, 8, ...',
    options: ['11', '12', '13', '10'],
    correctIndex: 2,
    explanation: 'This is the Fibonacci pattern, where each number is the sum of the two before it: 5 + 8 = 13.',
  },
  {
    slug: 'pattern-recognition-3',
    question: 'A row of shapes goes: circle, square, circle, square, circle, ... What shape comes next?',
    options: ['Circle', 'Square', 'Triangle', 'It is impossible to know'],
    correctIndex: 1,
    explanation: 'The shapes alternate in a repeating two-step pattern, so after circle comes square again.',
  },
  {
    slug: 'pattern-recognition-4',
    question: 'A wallpaper design repeats one motif of a star, a moon, and a sun, over and over in that order. If the wallpaper starts with a star, what is the 8th motif?',
    options: ['Star', 'Moon', 'Sun', 'Star and moon together'],
    correctIndex: 1,
    explanation: 'The pattern repeats every 3 motifs (star, moon, sun). Position 8 mod 3 = 2, which lines up with the second item in the cycle: moon.',
  },
  {
    slug: 'pattern-recognition-5',
    question: 'What number comes next? 100, 90, 80, 70, ...',
    options: ['65', '60', '50', '55'],
    correctIndex: 1,
    explanation: 'The pattern subtracts 10 each time, so 70 - 10 = 60.',
  },
  {
    slug: 'pattern-recognition-6',
    question: 'Every morning you brush your teeth, eat breakfast, and pack your bag in the same order before school. Recognizing this as a pattern is most useful because it lets you...',
    options: [
      'Forget the steps since they happen automatically',
      'Predict and plan your morning routine more efficiently',
      'Avoid eating breakfast on busy days',
      'Change the order randomly each day for fun',
    ],
    correctIndex: 1,
    explanation: 'Spotting the repeated structure in your routine lets you predict what comes next and plan your time well, which is the core benefit of pattern recognition.',
  },
  {
    slug: 'pattern-recognition-7',
    question: 'A program prints "Hello" five times using five separate print statements written one after another. What pattern should a programmer notice here?',
    options: [
      'The code uses too many different variable names',
      'The same instruction is being repeated, which is a sign a loop could replace it',
      'The program will crash because of repeated text',
      'There is no pattern since the text never changes',
    ],
    correctIndex: 1,
    explanation: 'Repeating the exact same instruction multiple times is a classic pattern that signals the code could be simplified using a loop instead of copy-pasting lines.',
  },
  {
    slug: 'pattern-recognition-8',
    question: 'In a spreadsheet of daily temperatures, you notice the values go up every day for a week, then drop sharply on the weekend, repeating this pattern every week. What is this an example of?',
    options: [
      'A coding error in the spreadsheet',
      'A trend or pattern in the data that could help predict future temperatures',
      'Random numbers with no meaning',
      'A sign the spreadsheet needs to be deleted',
    ],
    correctIndex: 1,
    explanation: 'Noticing the same weekly rise-and-drop pattern in data is exactly how pattern recognition helps you make predictions about what is likely to happen next.',
  },
  {
    slug: 'pattern-recognition-9',
    question: 'What number comes next? 3, 6, 9, 12, ...',
    options: ['13', '14', '15', '16'],
    correctIndex: 2,
    explanation: 'The pattern adds 3 each time, so 12 + 3 = 15.',
  },
  {
    slug: 'pattern-recognition-10',
    question: 'A tiled floor has a row of tiles colored: red, red, blue, red, red, blue, red, red, blue. What is the repeating unit of this pattern?',
    options: ['red, blue', 'red, red, blue', 'blue, red, red', 'red, blue, red'],
    correctIndex: 1,
    explanation: 'The smallest group of tiles that repeats over and over is "red, red, blue," which then starts again from the beginning.',
  },
  {
    slug: 'pattern-recognition-11',
    question: 'Why is pattern recognition considered an important part of computational thinking, especially before writing code?',
    options: [
      'It lets you skip testing your program',
      'It helps you notice similarities between problems so you can reuse or adapt known solutions',
      'It guarantees your code will never have bugs',
      'It replaces the need to break a problem into smaller parts',
    ],
    correctIndex: 1,
    explanation: 'Recognizing patterns lets you see that a new problem is similar to one you have solved before, so you can reuse or adapt an existing solution instead of starting from scratch.',
  },
  {
    slug: 'pattern-recognition-12',
    question: 'A student notices that three different math problems all involve doubling a starting number a set number of times. Why does spotting this shared pattern matter when writing a program to solve them?',
    options: [
      'It means the problems are unrelated and need totally different code',
      'It means one general piece of code, like a loop that doubles a value, can likely solve all three problems',
      'It means the program must use a different language for each problem',
      'It means pattern recognition only applies to shapes, not numbers',
    ],
    correctIndex: 1,
    explanation: 'When several problems share the same underlying structure, a single flexible solution, such as a loop, can often be reused for all of them instead of writing separate code each time.',
  },
  {
    slug: 'pattern-recognition-13',
    question: 'What number comes next? 1, 4, 9, 16, 25, ...',
    options: ['30', '36', '34', '32'],
    correctIndex: 1,
    explanation: 'These are square numbers (1x1, 2x2, 3x3, 4x4, 5x5), so the next one is 6x6 = 36.',
  },
  {
    slug: 'pattern-recognition-14',
    question: 'What number comes next? 5, 15, 45, 135, ...',
    options: ['270', '405', '180', '540'],
    correctIndex: 1,
    explanation: 'Each number is multiplied by 3 to get the next one, so 135 x 3 = 405.',
  },
  {
    slug: 'pattern-recognition-15',
    question: 'What number comes next? 10, 13, 9, 12, 8, ...',
    options: ['5', '11', '4', '7'],
    correctIndex: 1,
    explanation: 'The pattern alternates between adding 3 and subtracting 4: 10+3=13, 13-4=9, 9+3=12, 12-4=8, so the next step is 8+3=11.',
  },
  {
    slug: 'pattern-recognition-16',
    question: 'What number comes next in this list of prime numbers? 2, 3, 5, 7, 11, ...',
    options: ['12', '13', '14', '15'],
    correctIndex: 1,
    explanation: 'Each number can only be divided evenly by 1 and itself. After 11, the next number with no other factors is 13.',
  },
  {
    slug: 'pattern-recognition-17',
    question: 'What number comes next? 1, 3, 6, 10, 15, ...',
    options: ['18', '20', '21', '22'],
    correctIndex: 2,
    explanation: 'These are triangular numbers, where each term adds one more than the previous gap was increased by (1, +2, +3, +4, +5), so 15 + 6 = 21.',
  },
  {
    slug: 'pattern-recognition-18',
    question: 'What number comes next? 1, 8, 27, 64, ...',
    options: ['100', '125', '81', '128'],
    correctIndex: 1,
    explanation: 'These are cube numbers (1x1x1, 2x2x2, 3x3x3, 4x4x4), so the next one is 5x5x5 = 125.',
  },
  {
    slug: 'pattern-recognition-19',
    question: 'A row of shapes shows: triangle, triangle, circle, square, triangle, triangle, circle, square, triangle, triangle, circle, ... What comes next?',
    options: ['Triangle', 'Circle', 'Square', 'Star'],
    correctIndex: 2,
    explanation: 'The repeating unit is "triangle, triangle, circle, square," so right after circle the unit always finishes with square.',
  },
  {
    slug: 'pattern-recognition-20',
    question: 'A necklace is being strung with beads in this color order: blue, yellow, yellow, blue, yellow, yellow, blue, yellow, yellow, blue, ... What is the smallest repeating unit?',
    options: ['blue, yellow', 'yellow, yellow, blue', 'blue, yellow, yellow', 'blue, blue, yellow'],
    correctIndex: 2,
    explanation: 'Reading from the start, the sequence "blue, yellow, yellow" repeats over and over to build the whole necklace.',
  },
  {
    slug: 'pattern-recognition-21',
    question: 'A bus arrives at your stop at 8:00, 8:15, 8:30, and 8:45 every weekday morning, but on Saturdays it only runs once at 9:00. Why is it important to notice the Saturday exception in this pattern?',
    options: [
      'Exceptions should always be ignored so the pattern stays simple',
      'Recognizing the exception lets you correctly predict the schedule on weekends instead of assuming it always repeats the weekday pattern',
      'It means there is no real pattern to the bus schedule at all',
      'It means the bus never runs on Saturdays',
    ],
    correctIndex: 1,
    explanation: 'A good pattern spotter notices both the regular rule and its exceptions, since assuming the weekday pattern applies on Saturday would lead to a wrong prediction.',
  },
  {
    slug: 'pattern-recognition-22',
    question: 'A weather app shows that every time ice cream sales went up last summer, the local pool also got more crowded. Someone says "selling ice cream makes the pool more crowded." What is the better explanation?',
    options: [
      'The claim is correct because the two events always matched',
      'Both ice cream sales and pool crowds likely increase together because of a third factor, hot weather, rather than one causing the other',
      'Ice cream sales control how many people decide to swim',
      'There is no relationship between the two at all, even though they rise together',
    ],
    correctIndex: 1,
    explanation: 'Two patterns rising together does not prove one causes the other; here a shared cause, hot weather, likely explains both trends, which is an important distinction when reading data.',
  },
  {
    slug: 'pattern-recognition-23',
    question: 'A programmer looks at three functions in their code and notices each one takes a list, checks every item one at a time, and adds up a total. What is the most useful pattern to recognize here?',
    options: [
      'The functions are too long and should be deleted',
      'All three functions follow the same "loop through items and accumulate a result" structure, so they could share one reusable function',
      'The functions must be written in different programming languages',
      'Lists cannot be used more than once in a program',
    ],
    correctIndex: 1,
    explanation: 'Spotting that several functions share the same underlying loop-and-accumulate structure means a programmer can write one general, reusable function instead of three similar ones.',
  },
  {
    slug: 'pattern-recognition-24',
    question: 'In a table of student quiz scores, you notice that every score ending in the same number of practice problems completed also tends to be higher, except for one student who practiced a lot but scored low because they were sick on quiz day. What should you do with that one unusual case?',
    options: [
      'Delete that score so the pattern looks perfect',
      'Recognize it as an exception with its own explanation, while still trusting the overall pattern for most students',
      'Conclude that practicing never helps anyone',
      'Assume the data must be completely wrong and start over',
    ],
    correctIndex: 1,
    explanation: 'A reliable pattern can still have a reasonable exception; understanding why the outlier happened lets you keep using the overall trend without being misled by one unusual case.',
  },
  {
    slug: 'pattern-recognition-25',
    question: 'A traffic light cycles through red, yellow, green, yellow, red, yellow, green, yellow, ... in that order. If the light just turned green, what color will it show two changes from now?',
    options: ['Red', 'Yellow', 'Green', 'It depends on the time of day'],
    correctIndex: 0,
    explanation: 'After green comes yellow, and after that yellow comes red, so two changes after green lands on red.',
  },
  {
    slug: 'pattern-recognition-26',
    question: 'Two students both noticed that their phone battery drops faster on days they play games. One student says this proves games are the only reason batteries drain. What is a better way to think about this pattern?',
    options: [
      'Accept the claim immediately since the pattern appeared twice',
      'Consider that other factors, like screen brightness or weak signal, could also explain faster battery drain before blaming only one cause',
      'Stop using the phone entirely to avoid the pattern',
      'Ignore the pattern since two data points can never mean anything',
    ],
    correctIndex: 1,
    explanation: 'Noticing a pattern is a good start, but a careful thinker checks for other possible causes before assuming the first noticeable factor is the only explanation.',
  },
  {
    slug: 'pattern-recognition-27',
    question: 'What number comes next? 0, 3, 8, 15, 24, ...',
    options: ['30', '32', '35', '33'],
    correctIndex: 2,
    explanation: 'Each term is a square number minus 1 (1x1-1, 2x2-1, 3x3-1, 4x4-1, 5x5-1), so the next term is 6x6-1 = 35.',
  },
  {
    slug: 'pattern-recognition-28',
    question: 'What number comes next? 1, 2, 6, 24, 120, ...',
    options: ['240', '600', '720', '840'],
    correctIndex: 2,
    explanation: 'Each term is a factorial (1!, 2!, 3!, 4!, 5!), where you multiply by one more number each time, so the next term is 6! = 720.',
  },
  {
    slug: 'pattern-recognition-29',
    question: 'What number comes next? 2, 5, 7, 12, 19, 31, ...',
    options: ['38', '43', '50', '45'],
    correctIndex: 2,
    explanation: 'Just like Fibonacci, each number is the sum of the two before it, so 19 + 31 = 50.',
  },
  {
    slug: 'pattern-recognition-30',
    question: 'What number comes next? 1, 3, 9, 27, 81, ...',
    options: ['162', '216', '243', '729'],
    correctIndex: 2,
    explanation: 'Each number is multiplied by 3 to get the next one, so 81 x 3 = 243.',
  },
  {
    slug: 'pattern-recognition-31',
    question: 'What number comes next? 2, 9, 7, 14, 12, 19, ...',
    options: ['17', '21', '24', '15'],
    correctIndex: 0,
    explanation: 'The pattern alternates adding 7 and subtracting 2: 2+7=9, 9-2=7, 7+7=14, 14-2=12, 12+7=19, so the next step is 19-2=17.',
  },
  {
    slug: 'pattern-recognition-32',
    question: 'A wall is decorated with a repeating strip of shapes: square, triangle, triangle, square, triangle, triangle, square, triangle, triangle, square, ... What is the smallest repeating unit?',
    options: ['square, triangle', 'triangle, triangle, square', 'square, triangle, triangle', 'triangle, square, square'],
    correctIndex: 2,
    explanation: 'Starting from the first shape, the group "square, triangle, triangle" repeats over and over to build the whole strip.',
  },
  {
    slug: 'pattern-recognition-33',
    question: 'A row of arrows points: up, up, right, down, up, up, right, down, up, up, right, ... What direction comes next?',
    options: ['Up', 'Right', 'Down', 'Left'],
    correctIndex: 2,
    explanation: 'The repeating unit is "up, up, right, down," so right after the third arrow (right) the unit always finishes with down.',
  },
  {
    slug: 'pattern-recognition-34',
    question: 'In a music playlist, every third song is always a slow ballad, while the other two songs are upbeat. If song 1 and song 2 are upbeat, what kind of song is number 9?',
    options: ['Upbeat', 'Ballad', 'It could be either', 'There is not enough information'],
    correctIndex: 1,
    explanation: 'Since every third song is a ballad, you can check that 9 divided by 3 has no remainder, meaning song 9 lines up with the ballad position in the repeating cycle.',
  },
  {
    slug: 'pattern-recognition-35',
    question: 'A coder reviews two different programs and notices both repeatedly check "is this number bigger than the biggest one seen so far," updating a stored value when it is. What pattern have they spotted?',
    options: [
      'Both programs have the same bug and will crash',
      'Both programs follow the common "track a running maximum" pattern, which could be written as one reusable function',
      'The programs must be checking text instead of numbers',
      'This is not a real pattern since the numbers being checked are different',
    ],
    correctIndex: 1,
    explanation: 'Recognizing that two programs use the same "keep track of the largest value seen so far" structure means that logic could be pulled out into one reusable function instead of being written twice.',
  },
  {
    slug: 'pattern-recognition-36',
    question: 'A spreadsheet of monthly app downloads shows numbers that go up every month for almost a year, but one month suddenly drops to almost zero due to a server outage that prevented downloads. How should you treat that one month when describing the overall pattern?',
    options: [
      'Ignore the rest of the data and conclude downloads are always falling',
      'Treat that month as an explainable exception caused by the outage, while still describing the rest of the year as a growing trend',
      'Delete every month of data because one value looks unusual',
      'Assume the spreadsheet formulas are broken and stop tracking downloads',
    ],
    correctIndex: 1,
    explanation: 'A single explainable dip does not erase an otherwise clear growth trend; good pattern recognition separates a real exception from the overall pattern in the rest of the data.',
  },
  {
    slug: 'pattern-recognition-37',
    question: 'For three weeks in a row, a student wore a red shirt on the same day they got a high quiz score. They conclude the red shirt causes good grades. What is the strongest flaw in this reasoning?',
    options: [
      'Three weeks is already enough data to prove causation',
      'A short coincidence between two events does not show that one causes the other, especially with so few observations and no clear mechanism connecting them',
      'Quiz scores can never be affected by anything a student wears',
      'The student should immediately stop wearing red shirts forever',
    ],
    correctIndex: 1,
    explanation: 'Noticing a repeated coincidence is the first step of pattern recognition, but a careful thinker checks whether there is a real connection rather than assuming a small, unrelated pattern is the cause.',
  },
  {
    slug: 'pattern-recognition-38',
    question: 'What number comes next? 4, 8, 12, 16, 20, ...',
    options: ['22', '23', '24', '26'],
    correctIndex: 2,
    explanation: 'The pattern adds 4 each time, so 20 + 4 = 24.',
  },
  {
    slug: 'pattern-recognition-39',
    question: 'A teacher lists test scores in the order they were graded: 88, 91, 94, 97, 60, 100, 103. One number clearly breaks the steady "add 3" pattern the rest of the list follows. Which number is the exception?',
    options: ['94', '97', '60', '100'],
    correctIndex: 2,
    explanation: 'Every other number increases by exactly 3 (88, 91, 94, 97, then would be 100, 103), so 60 is the value that breaks the expected pattern, likely a typo or different scale.',
  },
]
